mdn/yari

client/src/App.js
client/src/ingredients/attributes.js
client/src/ingredients/examples.js
client/src/ingredients/interactive-example.js

Thanks for the updates today, it made it much less painful to get things running.
I know essentially nothing about React, so I'm probably doing some awful things here, but I wanted to get the code from https://github.com/mdn/stumptown-experiment/pull/33 running in your environment, and that's what this PR does.
Specifically it does a couple of things:
* I replaced a lot of `DocumentFromRecipe`: partly because I think the way it was doing prose sections was wrong (you don't just stick together all the prose sections, you have to interleave them with other sections like interactive examples), and partly because I wanted a way to have a bit of separation between this function and the renderers, so it's fairly simple to add new renderers. And I didn't want them all in the same source file.
* …

Add some renderers

---

client/src/App.js

Update prose renderers for the new JSON structure in which prose titles are explicitly represented indepently of the content. Also the new structure consistently uses underscores to separate words in identifiers.

Update prose renderers for the new JSON structure

---

cli/index.js

I just wanted to try out the [latest stumptown](https://github.com/mdn/stumptown-experiment/commit/fdd943e96307b64ff6b32cbe98133f33012aea86). Seems to work. 
Generating the static HTML for *all* pages is breaking on something else now. So I snook in a slight improvement to that by catching the error, `console.error` some important details, then rethrow the error. Now when you run `make deployment-build` you get this:
```
Rendering HTML failed!
uri=/docs/Web/HTML/Element/abbr
filePath=../stumptown/packaged/html/elements/abbr.json
/Users/peterbe/dev/MOZILLA/MDN/mdn2/cli/dist/webpack:/.ent/src/ingredients/attributes.js:21
{attributes.map(attribute => {
^
TypeError: Cannot read property 'map' of null
at map (/Users/peterbe/dev/MOZILLA/MDN/mdn2/cli/dist/webpack:/.ent/src/ingredients/attributes. …
```

Upgrade stumptown

---

client/src/ingredients/attributes.js

This PR adds a preamble to the Attributes section of the rendered page. It adds a slightly different one depending on whether there are element-specific attributes or only the global attributes.
I've manually tested its output with the `abbr` and `video` pages.
Since I'm super-unfamiliar with React there are probably much better ways of expressing this.

Add a preamble to the Attributes section

---

client/src/mdn.scss

This PR adds a border and width setting to the output iframe used for live samples. Without it, the video examples look OK but other examples look terrible:
******

Style live sample output iframe

---

cli/index.js
client/src/App.js

For https://github.com/mdn/sprints/issues/1638, I need to be able to suppress headings for short descriptions and overview, and this seems to make us confront the split between recipes in stumptown and the way MDN wants to render pages.
In this PR I'm doing this by hardcoding the set of things to include in the renderer itself. I think you suggested this in conversation yesterday, @peterbe , and it seems somewhat in line with especially @ddbeck 's https://github.com/mdn/stumptown-experiment/issues/48#issuecomment-498992233.
I like this better: it's smaller, simpler, more explicit. Although we would want a way some time to represent the fact that HTML elements are only one of the page types we know how to render.
What do you think?

Remove the renderer's dependency on recipes.

---

.travis.yml
README.md
scripts/ci-client.sh

You can't argue with the results :)
First of all, we're not done with Travis. We'd want to run a linter across all apps (client, server, cli). We also want to run the `make deployment-build` which produces fully working `.html` which we should test that they work and can be opened with `curl` or something. 
I'm not sure I'm doing the matrix stuff right. Would love some feedback here. There's a `before_install` portion *before* the matrix but I think it runs that once per every step in the matix. I'd rather just do the stuff, currently in `before_install` once BEFORE all the matrix sections. 
I'm happy to land this early and iterate. I just want to get the wheels rolling. 
Also, if we [dockerize everything](https://github.com/peterbe/mdn2/issues/23) all of these Travis DSL tricks will …

more travis

---

.travis.yml
client/src/ingredients/examples.js

This isn't very deeply thought out but I think it might help a little. 
With this change, you can render out .html files for every single "html" element. Nifty!
As of this change http://localhost:3000/docs/Web/HTML/Element/aside now works and `make deployment-build` also works.

be lenient with example titles' presence

---

client/public/index.html

Lighthouse complained about this:
I just copied it verbatim from developer.mozilla.org

meta description

---

Makefile
README.md
cli/index.js

Fixes #76
This, I hope, greatly simplifies things. Now the `cli` works so that if no special file or folder is specified, it just defaults to `../stumptown/packaged`. 
This...
```
cd cli
yarn run run
```
...is exactly the same as...
```
cd cli
yarn run run ../stumptown/packaged
```
But you can always ignore the defaults and control it entirely manually like this:
```
cd cli
yarn run run ~/stumptown-content/packaged/html/reference/elements/dialog.json
yarn run run ~/stumptown-content/packaged/html/reference/elements/
```
By default, the root of the content is `../stumptown` and that's what `$STUMPTOWN_CONTENT_ROOT` becomes if you don't set the env var. 
This...
```
cd cli
STUMPTOWN_CONTENT_ROOT=/path/to/stumptown-content yarn run run
```
...is exactly the same as...
```
cd cli
yarn run run …
```

stumptown-content can be anywhere

---

cli/index.js
cli/package.json
cli/syntax-highlighter.js
cli/syntax-highlighter.test.js
cli/yarn.lock
client/package.json
client/src/index.scss
client/src/ingredients/examples.js
client/src/mdn.scss
client/yarn.lock

The results speak for themselves:
*Inline code snippets*
*Examples*
If you look closely you'll notice that their styling is slightly different. At least the font-size seems to differ between Examples and snippets in prose. 
This is the first time I've broken out something from `cli/index.js` into its own file. Now I need to figure out how to change the Webpack config so I can run `jest` tests against a *transpiled* version of `syntax-highligher.js`. I.e. it used to just be: `cli/index.js` which Webpack turned into `dist/cli.js`. What I want is:
* index.js
* src/cli.js
* src/syntaxt-highlighter.js
* src/syntaxt-highlighter.test.js
To be turned into equivalent files in `dist/`. 
Might just ignore that for now.

Syntax highlighting

---

client/src/document.js
client/src/mdn.scss

This should make the sidebar look a bit more like the production site. Originally i was going to check the depth before either rendering the "leaflets" or just another leaf, but found that at the depth of the content when it gets to that point it should always use the `details` tags if a content array is present. I couldn't find an example on the prod site that nested further than this.

Sidebar adjustments

---

client/src/search.scss

Addresses #117 although the original issue reported there is no longer present.
---
In both Firefox (69.0.1) and Chrome (Chromium 77.0.3865.75), if I have a page with a very long file name (example below), the URI part of search result will overflow
Applying [`overflow-wrap: break-word;`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap), solves this issue.

Make part of URI in BreadcrumbURI able to wrap

---

client/src/app.js
client/src/homepage.js

Stumptown-content updated the `mdn_url` everywhere to include the locale. I figured it would be best to stay as up-to-date with that as we can so i provided small changes to allow the renderer to use the new `mdn_url`.

Upgrade to stumptown-content 464d89e9b5

---

client/src/document.js

stumptown-content now supports `short_title`. This PR uses them inside `<details>` elements in the sidebar, if they exist, falling back to `title` if they don't.

Use short titles (where present) in sidebar leaflets

---

cli/index.js
client/src/document.js

I do wonder if this was a premature optimization waste-of-time kinda thing. 
The point is that this is an example of where the renderer takes a stance about what it gets from the packaged content. 
The only reason this stuff matters is because we render everything as a web APP. React needs to know the state (aka. the input) so it can produce its own virtual DOM. So if it needs to internall re-render it needs to have all these bits and pieces. So what we're shipping is not just the HTML but also the state (as it was sent to `renderToString` in the `cli`) serialized into the HTML. 
But being deliberate about what gets serialized we can save gobs of bytes. :)

remove what's not needed from related_content

---

cli/render.js

Fixes #104
At the rendered html, now the scripts (which already have `defer` attribute) are put at the end of `<head>` instead of end of `<body>`.
Example of html output:
Question: should the `documentData` be moved to head too?

Move scripts from body to head

---

client/src/document.js
client/src/ingredients/examples.js

Fixes #137 
This will allow example sections to render properly. Fixes https://github.com/mdn/stumptown-renderer/issues/137 and partially satisfies https://github.com/mdn/stumptown-renderer/issues/157

Render example sections

---

client/src/document.js
client/src/ingredients/link-list.js
client/src/mdn.scss

This will allow link list sections to render properly. Partially satisfies https://github.com/mdn/stumptown-renderer/issues/157
Might style this differently, but i think because it's important to support all the sections in the current version of stumptown-content I wanted to get a functional piece in there for this type of section. Any feedback on this is much appreciated.

Render Link Lists

---

.travis.yml
README.md
package.json

The `yarn build-content` script is going out of fashion. All it does is converts stumptown's packaged json into the necessary .json that the React client needs. It's only really needed one time and we already get it from `yarn build`.

simplify deployment build in CI

---

README.md

Fixes #164
Add subsections to the building section and add documentation for building a specific content file.

Document building of a specific file

---

cli/index.js
client/src/document.js

Fixes #155
This one was tricky. Promises and async/await is fine until you actually need to really care and do something sane with the possible exceptions. Errors thrown deep inside `client/src/*.js` in some React component is totally something that's going to happen from time to time as we're making mistakes. What matters here is that we deal with it properly in the `cli`. What also matters here is that if *any* error happens, it should break the build. I.e. the `cli` should fail with a non-zero exit code. 
Here's the output of running this patch:
```
▶ CLI_BUILD_HTML=true yarn workspace cli start
<snipped to save space>
Rendering HTML failed!
uri=/en-US/docs/Web/HTML
filePath=/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/stumptown/packaged/html/HTML.json
Error: No idea how to handle …
```

'yarn deployment-build' isn't exiting early

---

cli/index.js
client/src/search.js

Fix #148
This PR will store the titles.json files in their respective locale, and the search component will set the correct localStorage key along with fetch the correct titles depending on the locale in the path.
Also fixed how it was "Starting a fresh new file" every time.

Support locale for titles

---

cli/syntax-highlighter.js

Fix #174
Not sure if this is the direction to take here, but it works. Highlights the `example` sections properly.

Highlight Example Syntax

---

cli/index.js
cli/package.json
yarn.lock

[`glob`](https://www.npmjs.com/package/glob) is slow but I'm not sure it matters.
But I did find that using `glob` to scan a directory with 5,000 files took almost a whole second. 
This'll matter if when stumptown-renderer might process all tens of thousands of ported temporary docs from Kuma.

don't use glob

---

client/src/ingredients/browser-compatibility-table/error-boundary.js
client/src/ingredients/browser-compatibility-table/error-boundary.test.js
client/src/ingredients/browser-compatibility-table/index.js
client/src/ingredients/browser-compatibility-table/index.test.js

Fixes #144 
Per discussion there, finally settled for error boundary only for the Browser Compatibility Table ingredient.
The light red color comes from [react-error-overlay](https://github.com/facebook/create-react-app/tree/master/packages/react-error-overlay)

Implement error boundary for Browser Compatibility ingredient

---

.travis.yml
scripts/ci-yarn-lockfile-check.sh

Had to add a config param to skip install. Also removed the before_install `yarn` as that happens by default for all jobs anyways.

Don't run install for lockfile-check job

---

client/src/document.js
client/src/ingredients/link-lists.js

This PR updates the renderer so it knows how to render JS class pages, which contain lists of methods.
It also updates the `stumptown` submodule to one that actually contains some content for one of these things, and its subpages. So you should see it at http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt.

Add renderer support for JS; update stumptown submodule with JS content

---

cli/index.js
client/src/fuzzy-search.js
client/src/search.js
client/src/search.test.js

Flexsearch with popularity basic

---

cli/browser-compatibility-table.js
cli/index.js
client/src/ingredients/browser-compatibility-table/bcd.scss
client/src/ingredients/browser-compatibility-table/rows.js

Fixes #243 
This mutates the `mdn_url` for browser-compatibility sections and allows you to navigate to the docs linked in the BCD table.

BCD Table Links

---

cli/index.js
cli/package.json
cli/webpack.config.js
yarn.lock

Part of #139
This isn't a solution to #139 but it's definitely a big improvement. I admitted ran out of time/steam but this little improvement is actually a decent improvement. 
I injected a little 
```javascript
if (Math.random() > 0.9) throw new Error("crap");
```
in the `cli/index.js` and now this happens:
```
▶ yarn build && node dist/main.js
yarn run v1.19.1
$ webpack --config webpack.config.js --mode=development
Hash: cfa37a868aa75c15323e
Version: webpack 4.41.2
Time: 2921ms
Built at: 11/19/2019 3:47:21 PM
Asset      Size  Chunks                   Chunk Names
main.js  6.04 MiB    main  [emitted]        main
main.js.map  84 bytes    main  [emitted] [dev]  main
Entrypoint main = main.js main.js.map
[../client/src/app.js] .ent/src/app.js 1.25 KiB {main} [built] …
```

Better stacktraces for the cli

---

package.json

This actually works great! 
Would you mind thinking about how to incorporate this into [your cli commad work](https://github.com/mdn/stumptown-renderer/pull/261)
What's neat about this is that you can now healthy run:
```
▶ export STUMPTOWN_CONTENT_ROOT=~/stumptown-content
▶ yarn build && yarn start
```
and it runs `npm run build-json` for the right stumptown-content and it watches the right files and stuff.

break up builds

---

.prettierignore
cli/index.js
ssr/index.js

Fixes #235
Based on https://github.com/mdn/stumptown-renderer/pull/259#pullrequestreview-325419683, I added `--no-progress-bar` option.
It's more useful to display either progress bar or each built file, but not both.
But if `--quiet` is passed, we should disable both.

Add --no-progress-bar option

---

scripts/end-to-end-test.js
server/index.js
ssr/index.js

Fixes #289 
This way, every file written to disk by the ssr is always in lowercase.
When you use the dev server on `localhost:5000` it won't even notice if you're on macOS or Windows, so I added a little rewrite rule to the express app there to lowercase all requests before they become file lookups. 
We could do more, like redirecting to the correctly spelled case,  but it can wait till some other day.

lowercase everything everywhere

---

README.md
package.json

This fixes the problem of the lockfile not being correctly updated after adding a dependency, by running yarn before committing. On my machine this makes committing ~1s slower (if there's no update to the lockfile required).

Run yarn as a pre-commit hook to ensure up-to-date lockfile

---

client/src/document.js
client/src/mdn.scss
ssr/index.js

This updates the renderer so it can render the JS sidebar discussed in https://github.com/mdn/stumptown-content/issues/302 and implemented on the content side in https://github.com/mdn/stumptown-content/pull/313.
Changes:
* tell stumptown-renderer what to do about `class_constructor` ingredients. This is not related to the sidebar change itself, but is needed for us to render JS class pages at all.
* update the sidebar rendering code. Before this change it expect a sidebar to contain only three levels. But the JS sidebar can and does include more levels than that, so this change should support arbitrary levels. Of course nesting too deep would make the sidebar unusable, but I think the author of the sidebar should have the responsibility of avoiding that.
* update the sidebar styling: …

Render JS sidebar

---

content/package.json
content/scripts/constants.js
content/scripts/importer.js

@peterbe I decided to make this a PR.
* additional slug exclusion prefixes
* additional archive prefixes
* extend archive check to parent slug for translations
* remove locale from metadata
* replace parent with translationof in metadata for translations
* fix import script in content/package.json

update "node content import" command

---

content/scripts/utils.js

Missed that when I reviewed it originally 🙈 
The slashes in the slug DB columns are always forward. Whereas `path.sep` is backwards on Windows, which is why I ended up with basically no hierarchy in my content fs.
I think we should just always split on forward slashes, so here's that change.

Split slugs on slashes instead of OS path separators

---

content/scripts/importer.js

This PR does the following:
- improves the detection of archived content/redirects
- adds localized slug prefixes to the list of slug prefixes that should be archived
- determines the set of all redirects that ultimately redirect to a page that should be archived
- ensures that `translation_of` is always set to the slug of a real document and never the slug of a redirect
- ensures that redirects are always to their final destination, skipping all intermediate redirects, so for example, if the actual redirects are A-->B, B-->C, and C-->D, the final redirects will be A-->D, B-->D, and C-->D.
NOTE: This is meant to replace https://github.com/mdn/stumptown-renderer/pull/398.

better archived content, "translation_of" values, and redirects

---

client/src/document.js
server/index.js

Fixes #450
@Gregoor @escattone I'm pretty sure this change is sane. It's easy to test. 
That whole `getRedirectUrl()` function is pretty ugly anyway and I might refactor it into the builder instead of having it exclusively in the `server`. 
Review if you have the headspace.

Redirects don't work in local development

---

content/scripts/build.js

Otherwise `C:\something` becomes `C\something` on Windows, which doesn't work. I think we're only interested in using `sanitizeFilenames` for slugs aka `mdn_url`s anyway

Only sanitize mdn_url in content/build

---

content/scripts/build.js

Fixes #466
I like this solution because it's brutally simple. If a single dependency package has changed since you last started `yari`, it means that saved `content/_all-titles.json` file is considered out-of-date. But this is the worst-case scenario. Any other more important change that can have an effect on `this.allTitles` should immediately be considered. In that case, the worst case is you have to wait a bunch of seconds. 
Good caching is one that is predictable and tightly controlled. It's better than aggressive and potentially confusing caching. 
Also, this new strategy matches exactly how the caching works on building the `index.html` (and `index.json`) files. So now they are treated exactly the same. If you don't touch and `.js` files and re-start the Node programs, the caching …

invalidate _all-titles.json

---

content/scripts/build.js
content/scripts/importer.js

Here's how I tested it...
First I made sure I had this in my `.env` file:
```
BUILD_ROOT=content/files
BUILD_ARCHIVE_ROOT=archivecontent/files
```
Then I ran `node content import --start-clean`
Check the contents of `archivecontent/files/de/codeschnipsel/index.html` and `content/files/en-us/games/anatomy/index.html`
Then `yarn clean && yarn prebuild` 
Then `node content build -l de --no-progressbar` (because I didn't want to wait for en-US)
Start the file server `nf start`
and then lastly visit http://localhost:5000/de/docs/DragDrop/Drag_and_Drop/ and http://localhost:5000/de/docs/Codeschnipsel/
(fun fact, note that the language switcheroo works fine for the built archive content too!)

already rendered archive content

---

client/src/search.js
client/src/search.test.js

Fixes #493
Now there's at least *some* feedback that the search is being initialized. 
Sorry for the terrible screencast. 
But what you're seeing is the input's placeholder between the first focus and until the XHR has finished downloading the `/en-US/titles.json`

Search placeholder text should come from state

---

client/src/search.test.js

Less `container` and more `getBy...` testing which is how Kent wanted it to be done.

use getByPlaceholderText to test search widget

---

client/package.json
client/src/app.js
client/src/app.test.js
client/src/document/index.js
client/src/document/ingredients/browser-compatibility-table/error-boundary.test.js
client/src/document/ingredients/browser-compatibility-table/index.test.js
client/src/document/ingredients/browser-compatibility-table/rows.js
client/src/document/ingredients/link-lists.js
client/src/document/languages.js
client/src/document/spy.js
client/src/homepage.js
client/src/index.js
client/src/routing.js
client/src/search.js
client/src/search.scss
client/src/search.test.js
client/src/setupTests.js
ssr/index.js
ssr/package.json
yarn.lock

Fixes #357
`yarn workspace client build` ...
**before:**
```
File sizes after gzip:
54.95 KB  build/static/js/2.b527d6f2.chunk.js
10.59 KB  build/static/js/main.f7b85584.chunk.js
5.05 KB   build/static/css/main.e800292a.chunk.css
772 B     build/static/js/runtime-main.cea588d5.js
532 B     build/static/css/2.3a14348e.chunk.css
```
**after:**
```
File sizes after gzip:
53.69 KB  build/static/js/2.0189310b.chunk.js
10.65 KB  build/static/js/main.35b80476.chunk.js
5.05 KB   build/static/css/main.e800292a.chunk.css
772 B     build/static/js/runtime-main.cea588d5.js
532 B     build/static/css/2.3a14348e.chunk.css
```
So, a 1.5KB smaller? But it's not unexpected. As [mentioned in this comment](https://github.com/mdn/stumptown-renderer/issues/357#issuecomment-605731056), the huge bundle size …

React router v6

---

ssr/package.json

The way we should distinguish between `production` and `development` in the React and the SSR code is that *all* SSR should be `production` and the only time it's `development` is when you use `yarn start` and open that `http://localhost:3000`. 
As of this change, any generated `client/build/$locale/**/*.html` is created with `process.env.NODE_ENV==='production'`. It actually doesn't make the build a whole lot faster. 
From **31.4 docs/s** to **33.8 docs/s**. But every little helps and the best of all is that the the generated `index.html` files should not have been made with anything that depended on `process.env.NODE_ENV==='development'`.

faster rendering by reading index.html once

---

ssr/syntax-highlighter.js

It's not a huge win but the `fixSyntaxHighlighting()` function is pretty important in terms of performance and I saw a low hanging fruit. 
Before (`master`): **31.4 docs/sec**
After (this branch): **33.1 docs/sec**
Also, the important difference was that `.filter()` which uses `section.value.content.includes("</pre>")` to quickly bail in (roughly) 4 out of 5 cases. 
The mess with `getPrismPluginName` was just to move it to module-level so I can use memoization for repeated calls. It's actually not used that much but will be when you use `stumptown-content`. I can take it out if you find it annoying. All I did was move it outside the `fixSyntaxHighlighting` and introduced a module-level `Map` which I use as memoization cache.

Optimization in fixsyntaxhighlighting

---

client/src/mdn.scss

hidden like mdn

---

content/index.js
content/scripts/build.js
content/scripts/constants.js
docs/envvars.md

Fixes #562
Ahhh That's much better. Now I can run `node content build ...` over and over between small changes without having to wait for the `_all-titles.json` to be regenerated every time. 
Caching is hard but maybe we should have a worker that starts when the file is out of date and goes and fixes it in the background. But that would be vastly overcomplicated and never foolproof. 
Note that I started a new file called `docs/envvars.md` which only has this new one. If/when you merge this I'll promise to make a follow-up to describe all the other interesting and important env vars. 
By the way, our README is vastly out of date because it's very stumptown'y.

ability to ignore cache invalidation of content/_all-titles.json

---

.gitignore

As of [the `ejs` upgrade](https://github.com/mdn/stumptown-renderer/pull/551) it now creates a executable inside the `kumascript` workspace. 
Without this, you get a new file after a fresh `yarn install`

ignore more

---

client/src/document/index.tsx

Fixes #559
Here's how I tested it:
```diff
diff --git a/server/index.js b/server/index.js
index 0e2475b..204d8a6 100644
--- a/server/index.js
+++ b/server/index.js
@@ -174,6 +174,10 @@ app.get("/*", async (req, res) => {
// Check that it even makes sense!
if (specificFolder) {
+      if (Math.random() > 0.5) {
+        return res.status(500).send("No bueno");
+      }
const t0 = performance.now();
try {
const built = await getOrCreateBuilder().start({
```
Then `yarn clean && yarn start` and I click around until an error happens. Looks like this:
And going to a page like http://localhost:3000/en-US/docs/Web/HTML/Element/audioXXX should still be the usual no-match error:

500 errors in server look like 404s in client

---

client/src/document/index.scss
client/src/document/index.tsx
client/src/document/spy.tsx

Fixes #486
On `master`
```
File sizes after gzip:
53.68 KB  build/static/js/2.71854ddc.chunk.js
10.65 KB  build/static/js/main.1ef91198.chunk.js
5.09 KB   build/static/css/main.26b1250e.chunk.css
772 B     build/static/js/runtime-main.cea588d5.js
532 B     build/static/css/2.3a14348e.chunk.css
```
On this branch:
```
File sizes after gzip:
53.41 KB (-275 B)  build/static/js/2.ec8ee9a2.chunk.js
10.68 KB (+31 B)   build/static/js/main.44a539d3.chunk.js
5.08 KB (-18 B)    build/static/css/main.29f476ed.chunk.css
1.46 KB (+725 B)   build/static/js/runtime-main.45594010.js
1.03 KB            build/static/js/3.876b0feb.chunk.js
532 B              build/static/css/2.3a14348e.chunk.css
180 B              build/static/css/3.23cdc1f6.chunk.css
```

Make DocumentSpy lazy loaded

---

content/scripts/build.js

This line dates back to the very beginning of yari coming into life. 
But a lots of empty tags are a reality with Kuma HTML as it creates the right margins that you're used to seeing. This is not a great place to fix that. 
In fact, after we have completely migrated MySQL into git and shut down the Wiki, we can go in and do a mass edit of all the `index.html` sources and remove all `span.alllinks` directly in the source. For now, let's just get rid of them in the post-processing.

only remove 'span.alllinks'

---

content/scripts/build.js

Fixes #593
Given that this is ultimately a problem with the cli parameters, I wonder if we should instead just show the one line ("No folders found to process!") in red without the stack trace.

handle foldersearch with nothing better

---

content/scripts/utils.js

Fixes #609
Now it becomes...
```
▶ ls content/files/en-us/web/css/_doublecolon_-ms-fill/
index.html       index.yaml       wikihistory.json
```
and 
```
▶ ls client/build/en-us/docs/web/css/_doublecolon_-ms-fill
_index.hash         _preferred-name.txt index.html          index.json
```

double colon directories

---

client/src/document/flaws.tsx
content/scripts/build.js

Fixes #595
To test
1. `yarn clean && yarn start`
2. Go to http://localhost:3000/en-us/docs/web/css/background#_flaws
3. Hover over all the orange links "Formal syntax" section.

Broken links checking needs to be smarter about anchor links

---

server/index.js

Fixes #597
To test:
1. `yarn start` and `node content build -l en-us -f learn`
1. Go to http://localhost:3000/en-US/_flaws?flaws=macros&sort_by=flaws
It now sorts by the number of `macros` errors.

Sorting by # flaws should take filtering into account

---

content/scripts/build.js

Fixes #554
Steps to test:
1. `yarn clean && yarn prebuild && ls -l client/build`
2. `node content build -l en-us -f glossary -l fr -l sv-SE`
3. `ls -l client/build` (note only the mentioned locales got built)
4. `less client/build/sv-se/titles.json` look at the case of the keys
5. `less client/build/sitemaps/fr/sitemap.xml` look at the case of the URLs within

titles.json and sitemap urls

---

content/scripts/build.js

This PR fixes the largest contributor to the build performance degradation (the build times were roughly doubling). The problems were within `getCurrentGitBranch()`:
- Most importantly, it was never caching the successful result of `git branch --show-current`.
- It was also never detecting the error case where the `git branch --show-current` completes without a `child_process` error (`spawned.error` is _falsy_), but with a `git branch` error (`spawned.status` is _truthy_) which was my case since I was using an older version of `git` that didn't support `--show-current` for the `git branch` command. Also, when an error occurs I don't think we should keep trying to run the child-process command on every single call to `processFolder`, but instead just cache the `fallback`.
There seems to be …

fix build performance issue

---

content/scripts/constants.js
content/scripts/importer.js

Fixes #573
Run `node content import --start-clean` and then:
```
▶ cat  content/files/en-us/_redirects.txt | rg Trash
```
Note the empty output. It used to be lots and lots of lines.

Trash Trash?

---

content/scripts/document.js
content/scripts/importer.js

```
▶ ls -l archivecontent/files/en-us/mozilla/projects/spidermonkey/jsapi_reference/js_defineownproperty/
total 392
-rw-r--r--  1 peterbe  staff  189694 May 28 06:46 index.html
-rw-r--r--  1 peterbe  staff    2238 May 28 06:46 raw.html
-rw-r--r--  1 peterbe  staff     203 May 28 06:46 wikihistory.json
```
```
▶ cat archivecontent/files/en-us/xul/attribute/onunload/index.html | head -n 13
---
title: onunload
slug: XUL/Attribute/onunload
summary: >-
Specifies a set of scripts to execute when the browser window is closed by the
user. This code is used by some programmers to annoyingly pop up alert boxes
preventing the users from leaving the page.
tags:
- JavaScript
---
<div class="noinclude"><span class="breadcrumbs xulRefAttr_breadcrumbs">« <a href="/en-US/docs/XUL/XUL_Reference">XUL …
```

include raw html in archivecontent

---

content/scripts/build.js

Fixes #677
Steps to test:
1. `yarn clean && yarn start`
2. Create a brand new folder: `mkdir content/files/en-us/somethingnew`
3. Save a new `index.html` in it. E.g.:
```
---
slug: Brandspankingnew
title: Brand spanking new
summary: BLa bla
---
<p>Hi!</p>
```
4. Save file. 
5. Go to http://localhost:3000 and expect to find it in the search and be able to go to it. 
Second Steps to test:
1. `yarn clean && yarn start`
2. Find an existing `index.html`. Eg. `emacs content/files/en-us/glossary/jpeg/index.html`
3. Change the `slug` to something new. 
Now, what we **could** do is be really smart. 
When a `processFolder()` is called from the watcher, it could check if this was a new slug but we can loop over all the values in `this.allTitles` to see if this file was already in there but had a …

cope with new slugs created

---

content/scripts/importer.js

Fixes #500
To review this, note first that some of the functions got so hairy and confusing (I'm not going to say complicated!) that I wrote tiny little unit tests. So look for the `test_getRedirectURL` and `test_postProcessRedirectURL` and they all pass. So if the assertions in there are good, perhaps "assume" the code is fine. 
Also, let's go back to some of the comments I made throughout https://github.com/mdn/stumptown-renderer/issues/500 Let's prove that they are solved:
```
▶ cat content/files/en-us/_redirects.txt | rg moz-locale-dir
/en-US/docs/-moz-locale-dir(ltr)	/en-US/docs/Web/CSS/:-moz-locale-dir(ltr)
/en-US/docs/-moz-locale-dir(rtl)	/en-US/docs/Web/CSS/:-moz-locale-dir(rtl)
/en-US/docs/CSS/:-moz-locale-dir(ltr)	/en-US/docs/Web/CSS/:-moz-locale-dir(ltr) …
```

Low-hanging fruit fixes on bad redirects in dumper

---

README.md

I also removed the sentence prompting people to check out Procfile/package.json, as that seems more dev-relevant than anything else.

Add links to git, node & yarn to README

---

server/index.js

Fixes #781
@tobinmori If you can do the Quickstart but instead download this branch, I think it would be review enough :)
```
git clone https://github.com/peterbe/yari.git
cd yari
git checkout 781-server-and-default-build-root
yarn 
yarn start
open http://localhost:3000/en-US/docs/Web/HTML/Element/audio
```

server and default build root

---

testing/.env
testing/content/files/en-us/learn/css/css_layout/introduction/flex/index.html
testing/content/files/en-us/learn/css/css_layout/introduction/flex/stuff/index.html
testing/content/files/en-us/learn/css/css_layout/introduction/flex/stuff/wikihistory.json
testing/content/files/en-us/learn/css/css_layout/introduction/flex/wikihistory.json
testing/content/files/en-us/learn/css/css_layout/introduction/grid/index.html
testing/content/files/en-us/learn/css/css_layout/introduction/grid/stuff/index.html
testing/content/files/en-us/learn/css/css_layout/introduction/grid/stuff/wikihistory.json
testing/content/files/en-us/learn/css/css_layout/introduction/grid/wikihistory.json
testing/content/files/en-us/learn/css/css_layout/introduction/index.html
testing/content/files/en-us/learn/css/css_layout/introduction/wikihistory.json
testing/tests/headless.test.js

Fixes #698 
This PR adds the core tests for macro rendering as well as the building of live samples. The focus here is **not** on testing the breadth of macros that exist, but rather on testing these core aspects of rendering/live-sample-building:
- that recursion that can occur when rendering documents that depend on other documents, i.e. the rendering of one document may first require the rendering of one or more "prerequisite" documents, which in turn may require the rendering of their prerequisites and so on
- that prerequisite documents must be fully rendered before being incorporated into the document that is including them (via the `Page` or `IncludeSubnav` macro)
- that live samples can be included from a document different from the document they're being embedded within
- that …

add basic tests for kumascript rendering

---

content/scripts/importer.js

Fixes #798
Here's how I tested it:
1. `rm -fr archivedcontent`
2. `node content import`
3. `ls -l archivecontent/files/en-us/mozilla/projects/spidermonkey/jsapi_reference/js_defineownproperty/`
4. `cat archivecontent/files/en-us/xul/attribute/onunload/index.html | head -n 13`
5. `cat archivecontent/files/en-us/mozilla/projects/spidermonkey/jsapi_reference/js_defineownproperty/raw.html | head -n 6`

Importer should write raw.html as well

---

client/src/search.tsx

Fixes #621
To test:
1. Go to a page on http://localhost:3000
2. Press <kbd>?</kbd> to focus on the search input. 
3. Press <kbd>Esc</kbd>
Note that it only works if you have nothing typed into the field which is deliberate.

Double-escape inside search widget should blur input

---

client/src/search.tsx

Fixes #809
Sigh. What a rabbit hole. More fuel to the argument of jumping onto the [`downshift` bandwagon](https://github.com/mdn/yari/pull/814). 
The reason the `<input>` has a `onBlur` is because if you start typing something and then realize, "Nah! I don't want to search I want to scroll down or click this link". It's not nice to have to force the user to hide the displayed search results (by clearing the input field). Amazon.com does this. Go to https://www.amazon.com/ and start typing something in the search and then click somewhere outside the search results but not on a link. That blurs the search and hides the displayed results but it doesn't clear the input. 
But what happens is that when it triggers, that blur kills the DOM element that has a `onClick` on it. That's why the …

wait longer for search result click

---

client/src/document/toolbar/edit-actions.tsx
client/src/document/toolbar/index.tsx

This moves the "Create new document" link to be to the right of the document actions
fix #834

Move create document link

---

client/src/document/toolbar/flaws.tsx
content/scripts/build.js
testing/content/files/en-us/web/brokenlinks/index.html
testing/tests/index.test.js

Fixes #849 
[The issue](https://github.com/mdn/yari/issues/849) suggest using: http://localhost:3000/en-US/docs/Web/HTML/Element/a#_flaws which now looks like this:
But also, a good way to test is to:
1. `yarn start:functional`
2. Go to http://localhost:3000/en-US/docs/Web/BrokenLinks#_flaws

suggestions for broken links with hash fragments

---

kumascript/macros/htmlattrxref.ejs
kumascript/src/api/web.js
kumascript/src/render.js
testing/tests/index.test.js

Fixes #756 
This PR adds a `data-flaw-id` attribute to each `<a>` tag created by `web.smartLink()` when it detects and creates a non-fatal flaw related to the link, and the value of the `data-flaw-id` attribute maps to the value of the `id` attribute of the flaw created. Only non-fatal flaws will have `id` attributes, and the values of the `id` attributes will be unique per document only.
While writing tests, I found a bug within `kumascript/macros/htmlattrxref.ejs`, which I also fixed within this PR.

unique-per-doc ID maps non-fatal error to DOM

---

client/src/document/toolbar/watcher.scss
client/src/document/toolbar/watcher.tsx

The jumpiness is a little distracting when switching between documents

Prevent toolbar relayouting

---

.gitignore
client/src/user-context.tsx
docs/proxying.md
server/constants.js
server/fake-v1-api.js
server/index.js
server/package.json
yarn.lock

I'm really please with how this turned out. Now it's working really well. 
You can't fake the Kuma (Django) `sessionid` cookies so if you really want to use the real `docker-compose` and MySQL/Django stuff you really do need to set `HOST=localhost.org` and use http://localhost.org:3000 but it really works. 
What's exciting is the ability to fake any JSON response. This can become really powerful because it means you can hack on this like Subscriptions, User Account, etc. all without having to start `docker-compose` or even needing an internet connection. Hopefully, the documentation I wrote is clear enough so I won't repeat how to test this PR. 
So why `express-http-proxy` and not `http-proxy-middleware` in CRA's Webpack? 
Because, this way ALL proxying is always going through to …

proxy kuma

---

kumascript/package.json
yarn.lock

Fixes #895 
This is something I missed doing in some earlier PR, sorry! Generated this PR using:
```
yarn workspace kumascript remove lru-cache
```

remove lru-cache dependency from kumascript workspace

---

content/scripts/build.js

Before:
After:
I don't think we need to know how many milliseconds it took, in finer granularity than milliseconds.

use integers for msLong()

---

client/src/header/index.tsx
ssr/webpack.config.js

Fixes #882
It works!
I found out about it on [this blog post](https://www.pluralsight.com/guides/how-to-load-svg-with-react-and-webpack) and it made sense. But there are choices and I didn't know how `create-react-app` does it but I noticed that you get `./node_modules/@svgr/webpack/` which gets put there by `create-react-app`:
```
▶ yarn why @svgr/webpack
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "@svgr/webpack"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@svgr/webpack@4.3.3"
info Reasons this module exists
- "_project_#client#react-scripts" depends on it
- Hoisted from "_project_#client#react-scripts#@svgr#webpack"
info Disk size without dependencies: "28KB"
info Disk size with unique dependencies: …
```

use @svgr/webpack for inline svgs in ssr

---

content/scripts/build.js
content/scripts/matches-in-text.js
testing/content/files/en-us/web/fixable_flaws/index.html
testing/tests/index.test.js

Part of #680
To test, ...one way:
1. `yarn clean && yarn start:functional`
2. `ENV_FILE=testing/.env node content build -f brokenlinks --fix-flaws --fix-flaws-dry-run` 
3. Enjoy the output or remove the `--fix-flaws-dry-run`, add `--no-cache`, followed by `git diff testing/content/files/en-us/web/brokenlinks/index.html` and `git checkout testing/content/files/en-us/web/brokenlinks/index.html`
Another way to test is to use some real content. E.g. 
1. `yarn clean && yarn prebuild`
2. `node content build -l en-us -f web/html/element --fix-flaws --fix-flaws-dry-run --no-progressbar`
The output of that is pretty extreme. But it works.

automatically fix broken_links flaws

---

content/scripts/build.js
testing/content/files/en-us/web/brokenlinks/index.html
testing/tests/index.test.js

Fixes #898
To test, go to http://localhost:3000/en-US/docs/Web/HTML/Element/a#_flaws 
Without this patch you'd see what you see in the screenshot in the issue. 
Now you should see:
The `broken_links` checking will have two branches where it comes up with a suggestion
1. If the link is a redirect
2. If the link is in `this.allTitles` but under the wrong case. 
In both cases, when it makes the suggestion it needs to not forget the old fragment. 
What tripped me was that the links mentioned in the issue were actually perfectly fine. They were typed perfectly but ended up in the flaws because they had hash fragments on them. 
But when I was in there poking and debugging I noticed the other problem where the flaw might be that the case is wrong and if that was the case the hash fragment was …

Broken links flaws confused on some anchors

---

client/src/document/toolbar/flaws.scss
client/src/document/toolbar/flaws.tsx

Part of #772
It's so ugly but it works.
It's so confusing that you're worrying about this page here but when you click the lines it opens something else and that surprises. This alert will give some attention to that. 
Does "In prerequisite macro" mean anything beyond the core team who actually works on the KS renderer :)

alert about macro flaws from other pages

---

client/src/header/search.tsx
client/src/search.tsx

I mean, it kinda works
I just don't know what I'm doing with the styles. 
Also, even if we can get the search results to appear underneath the search widget correctly aligned, I don't think we're quite done because I think the search results should probably tie in better with the search input field. 
I don't think it's a must that the search results fit perfectly (e.g. the width of the widget matches the width of the input field). But it would be nice if the gap between wasn't too large. 
I'm asking for a review from you @Gregoor in hope that you know what the problem is but I'd love to get @schalkneethling to take a look in case you know what the problem is.

new searchwidget inside kumastyles

---

client/src/search.scss
client/src/search.tsx

Fixes #910
It's not amazing but I think it's an improvement. 
To test:
1. `yarn clean && yarn start`
2. Go to http://localhost:3000 and hover over the search at least once to it gets built
3. Refresh the page and DON'T focus on mouse hover over the search input
4. `cd client/build/en-us` and `echo "CORRUPTED JSON" >> titles.json`
5. Now focus the search input in the browser

display initialize search error instead of throwing

---

content/scripts/build.js
content/scripts/document.js
kumascript/macros/LiveSampleURL.ejs
kumascript/src/api/wiki.js
kumascript/src/errors.js
kumascript/src/info.js
kumascript/tests/macros/EmbedLiveSample.test.js
kumascript/tests/macros/LiveSampleURL.test.js
kumascript/tests/macros/dekiscript-page.test.js
testing/content/files/en-us/web/foo/index.html
testing/content/files/en-us/web/fubar/index.html
testing/tests/index.test.js

Fixes #915 and #930 
This PR took longer than expected because of all of the options I explored. In the end, for flaw de-duplication, I decided to go with a simpler approach (but less elegant because it doesn't prevent duplicates, it just removes them) because the more elegant approach would complicate @Gregoor 's planned refactor.
With this PR, every macro flaw returned from `renderMacrosAndBuildLiveSamples()` or `renderMacros()` is ensured to have the correct:
- `filepath`
- `line` -- adjusted to account for the front-matter of its corresponding file
- `sourceContext` -- i.e., its line numbers have also been adjusted to account for the front-matter of its corresponding file
I've also added some new tests.
Here are some screenshots of …

better flaws (fixes #915 and #930)

---

testing/content/files/en-us/web/fubar/index.html
testing/tests/index.test.js

@peterbe noticed that I had typo'ed a `<dic>` tag that of course should have been a `<div>` tag.

fix <dic> tag that should be <div> tag

---

testing/tests/search.test.js

Part of #920
I only today noticed that my TS integration in VSCode tells me that there's nothing to `await` when you use `expect(page.url())` because it doesn't report a promise. It makes sense because it's [not available in expect-puppeteer](https://github.com/smooth-code/jest-puppeteer/issues/365). 
The bad thing about this fix is that's a bit weird. Hopefully, my code comment can alleviate some of that.

check that the url has changed later

---

server/middlewares.js

I just realized that I must've still had that line commented out when I tested your PR. I think we don't want that line there, at least samples aren't even working for me in local mode without it.
What we do ultimately want our static server to do (and also our lambda at edge) is rewrite urls to foldernames, but that shouldn't be live sample requests, should it?

no slugToFolder transform for live sample request

---

client/src/document/index.tsx

Fixes #972
First of all, to test, go to http://localhost:3000/en-US/docs/Web/CSS/CSS_Reference and it should automatically redirect to http://localhost:3000/en-US/docs/Web/CSS/Reference
Lemme justify why there are no tests.
We currently have no test suite for the dev environment. But it's going to come, but even then I'm not sure it's worth testing. 
The only way, in production, you can end up on a URL that redirects is **if you click** on a link that would redirect. E.g. 
```html
<a href="/en-US/docs/Web/OldName">
```
If you had gone directly to `https://developer.mozilla.org/en-US/docs/Web/OldName` (with `curl` for example) our S3 website would have an S3 entry for this because it comes from the deployer uploading an S3 key for every entry in `_redirects.txt`. So it would never start …

redirect when using localhost:3000

---

build/cli.js

It adds line noise but I like that it's exclusively outside and only ever relevant in the CLI usage. 
Also, I didn't want to get fancy with `chalk` and `ms` for formatting because then it would complicate what doesn't need to be complicated at this point.

cli output about rate of building documents

---

import/cli.js

Without this you don't get a stacktrace when the import fails.

import improvements

---

client/src/document/toolbar/edit-actions.tsx

Fixes #697
I like that the toolbar looks like crap because it gives @schalkneethling a clear canvas to work with (when time allows).

"View on MDN" in Toolbar

---

.gitignore
kumascript/macros/WebExtAllExamples.ejs
kumascript/macros/WebExtExamples.ejs
kumascript/package.json
kumascript/src/api/mdn.js
yarn.lock

Fixes #951 
This PR is a possible approach to resolving #951. The recent inclusion of the `/en-US/docs/mozilla/add-ons/webextensions` tree of documents re-introduced the need for the `WebExtExamples` and `WebExtAllExamples` macros, both of which make a network call to get https://raw.githubusercontent.com/mdn/webextensions-examples/master/examples.json. The philosophy of this PR is to keep the `kumascript` rendering details as hidden as possible from the rest of the build process.

make web-ext-examples macros work again

---

server/index.js

Prior to this, if anything goes wrong deep inside `buildDocumentFromURL` the server just hangs and doesn't return anything. (Until you force `nodemon` to restart it)
And you get a warning that it's an unhandled rejection. Now you get
```
4:14:33 PM server.1    |  Error in buildDocumentFromURL(/en-us/docs/web/html/element/audio) Error: Oh crap!
4:14:33 PM server.1    |      at buildDocument (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:109:9)
4:14:33 PM server.1    |      at async buildDocumentFromURL (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:236:11)
4:14:33 PM server.1    |      at async /Users/peterbe/dev/MOZILLA/MDN/yari/server/index.js:148:16
```
for example.

Crash server more gracefully

---

server/fake-v1-api.js

Fixes #1035
To test,
1. First start with `master` (or any branch that is not *this* branch)
2. Add `SERVER_FAKE_V1_API=true` and `REACT_APP_KUMA_HOST=localhost.org:8000` in your `.env`
3. `yarn start`
4. View a page.
It should complain that you haven't created a folder called `fake-v1-api` in the yari root. Or rather, without this branch it'll complain about that folder not existing outside of the `yari` project root.

Use of fake v1 API fails

---

content/document.js

Fixes #1047
The way to test it is:
```
yarn prepare-build
BUILD_FILES=$(git diff master... '--diff-filter=AM' --name-only | rg index.html) yarn build
```
This is basically what [get-diff-action](https://github.com/mdn/yari/blob/b72c7d77a76a2cf1dc239abc209dbf7fdf504ccf/.github/workflows/pr-build.yml#L26-L31) does for us in the CI.

unbreak PR Build CI workflow

---

build/flaws.js
kumascript/macros/Compat.ejs
kumascript/tests/macros/Compat.test.js
testing/content/files/en-us/_wikihistory.json
testing/content/files/en-us/web/badbcdqueries/index.html
testing/tests/index.test.js

Fixes #1011
I'm not super in love with how it looks but I think it works much better than nothing. 
*Test content*
*Real content deliberately messed up*

highlight bad bcd queries better

---

client/src/document/ingredients/prose.tsx

Fixes #1004
See https://github.com/mdn/yari/issues/1004#issuecomment-673632588
These are the kind of mistakes we're likely to make when we rush things. But that's the world we're (currently) living in.

fix in string interpolation

---

ssr/render.js

This paves the way for starting the server before the client has been built. Basically, it used to be that simply importing (`require('./ssr/dist/main')`) would trigger this `fs.readFileSync`. But you actually don't need to until you need to start properly SSR render a document.

lazy load build HTML

---

client/src/document/index.tsx
content/document.js
content/files/en-us/glossary/happyness/index.html
kumascript/index.js
server/document-watch.worker.js
server/index.js

Fixes #1037
Now, instead you get an error message which is a lot easier to comprehend:
```
error while building documents: Error: From URL /en-US/docs/Glossary/Happiness no folder on disk could be found. Tried to find a folder called en-us/glossary/happiness
at /Users/peterbe/dev/MOZILLA/MDN/yari/kumascript/index.js:20:11
at Object.render (/Users/peterbe/dev/MOZILLA/MDN/yari/content/utils.js:54:19)
at buildDocument (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:101:50)
at buildDocuments (/Users/peterbe/dev/MOZILLA/MDN/yari/build/cli.js:59:65)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
It doesn't solved the problem but at least the error isn't so cryptic.

Deal with unresolved Document.findByURL urls

---

build/flaws.js
testing/content/files/en-us/web/brokenlinks_repeats/index.html
testing/tests/index.test.js

It *used* to be:
1. Loop over every `<a href="...">`
2. For each unique `href`, find all matches and add each match to `doc.flaws.broken_links`
So if you have
```
<a href="foo">One</a>
<a href="foo">Two</a>
<a href="foo">Three</a>
```
It would analyze `foo` once and add it 3 times. But the 2nd and 3rd wouldn't get its own unique `id`. 
So you'd end up with this rendered:
```html
<a href="foo" data-flaw="link1">One</a>
<a href="foo">Two</a>
<a href="foo">Three</a>
```
*Now* it's like this instead:
1. Loop over every `<a href="...">`
2. For every `href`, find *its* match
The rendered output will now become:
```html
<a href="foo" data-flaw="link1">One</a>
<a href="foo" data-flaw="link2">Two</a>
<a href="foo" data-flaw="link3">Three</a>
```

fix broken_links flaws when repeated

---

.github/workflows/pr-build.yml
.github/workflows/production-build.yml
kumascript/index.js
kumascript/macros/LiveSampleURL.ejs
kumascript/src/constants.js

Fixes #977
Now if you start from scratch the live sample iframes work when you spin up http://localhost:3000
It's obviously wrong for shipping but that's why the better value is set into the GHA workflows so those files become ready for shipping out.

LIVE_SAMPLES_BASE_URL is clunky for most people

---

content/constants.js
import/README.md

Part of #1095
I need this to be able to use the dumper to write to folders outside the `yari` folder.

allow CONTENT_ARCHIVE_ROOT to not have to be relative

---

build/search-index.js
content/document.js
content/index.js
content/popularities.js
content/redirect.js
server/flaws.js

Part of #1095
Without these changes, you can't run `cd import && CONTENT_ROOT=/some/path ARCHIVE_CONTENT_ROOT=/some/other node cli.js` because it tries to open the `popularities.json` simply be importing the module. Same with the `_redirects.txt` files.

make redirects and popularities loading lazy

---

build/bcd-urls.js
build/check-images.js
build/document-utils.js
build/flaws.js
build/page-title.js
content/document.js
kumascript/src/info.js
server/document-watch.worker.js

Fixes #1292
The use of `fields` was meant when you only needed some of the metadata. E.g.
```javascript
Document.findByURL("/en-US/docs/Web/API/Index".toLowerCase()), { metadata: true }).metadata.title;
```
But when you needed the body or the raw content you were supposed to omit the fields param:
```javascript
Document.findByURL("/en-US/docs/Web/API/Index".toLowerCase())).rawHTML;
Document.findByURL("/en-US/docs/Web/API/Index".toLowerCase())).rawContent;
```
But it's no point. The `read()` function didn't do any less. It still read the whole `index.html` file and the front-matter parsing.

Refactor use of `read(... , {metadata: true})`

---

package.json

This is needed so you can run `yarn filecheck` from the Content repo.

move caporal and tempy

---

.github/workflows/auto-merge.yml
.github/workflows/npm-publish.yml
.github/workflows/testing.yml

Fixes #1291
Now, a PR doesn't always have to be about merging into `master`. For example, I make a PR against your PR, the CI workflows will run there too. 
The exception is the `auto-merge.yml` which only ever makes sense when it's against the `master`. 
If this is "abused" in the future, we can revisit. Although I find that unlikely.

run CI indpendent of branch name

---

server/index.js

Fixes #1228
Actually, not much is needed here. If your `EDITOR` isn't set, the `openEditor` (which depends on `env-editor`) does a pretty good job of throwing a nice error. 
And in the Toolbar you get a pretty decent experience. Better than it just hanging. 
At least enough to give you some guidance that something's wrong.

500 error if process.env.EDITOR isn't set

---

server/index.js

Fixes #1264
This is admittedly serving the `yarn start` inside Content as a fallback if something goes wrong. 
But you can use it in yari too. For example, if you have a typo in your `.env`:
```
▶ yarn start:server
yarn run v1.22.4
$ node server
/Users/peterbe/dev/MOZILLA/MDN/content/fileXXXs does not exist!
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
It also gives you a nice warning when you do `yarn dev` since the `server` part will "crash".
If all goes well, it will print:
```
▶ yarn start:server
yarn run v1.22.4
$ node server
CONTENT_ROOT: ../content/files (absolute path: /Users/peterbe/dev/MOZILLA/MDN/content/files)
Listening on port 5000
```

Display the CONTENT_ROOT when starting the server

---

deployer/src/deployer/upload.py

The reason it's bad to use newlines characters in log lines is that it can cause problems with log files when it's written to by multiple threads. 
Also, without this change it would fill up 3 lines for every 1 error.

log errors shouldn't have newlines in them

---

.github/workflows/production-build.yml

I created a new AWS IAM user for the deployer, as well as its associated IAM policies for S3 and Lamabda. They work!

use latest deployer aws credentials

---

import/import.js

In Yari, when building a page, it replaces any `<div class="bc-data" id="...">` with its own React based BCD table. 
In doing so, it discards everything that was in there already. So it's a waste to have it in the rendered HTML anyway. 
If you do this, you save a total of 238MB when you sum the bytes from all the tables HTML. 
After this change, the `translated-content` repo is now only 1.3GB. Seem worth doing.

strip all div.bc-data tables when dumping rendered HTML

---

client/src/header/language-menu.tsx

Part of #1320
When on an English page:
If you focus it:
The most contentious thing to discuss is: What if you stumble in on http://localhost:5000/ja/docs/Web/HTML/Element/option and you can't read Japanese. 
You might attempt to look for the word "English" somewhere on the page. But you won't find it because it's not there until you focus the `<select>`:
**Is that a problem?**
The other thing is, **is this widget accessible?** There's no submit button (hidden or displayed) after the select. Instead, I'm relying on a `<select onChange={...}>` event handler.

simplified language selector

---

client/src/document/ingredients/browser-compatibility-table/index.tsx

Fixes #1344
It started as a joke in my head with the phrase "See something? Say something." but that could be misinterpreted for a lingo that belongs in the dark world of counter-terrorism. Truth is, I wanted to make sure it's different from what it used to say because what it used to say was fine but many people have given up home on that link since it would only take you to the home page. 
So please take your time and think about the ideal link display/text. 
Another option is to make it louder graphically. We can start with using bold or italic or just a larger font size. Perhaps, with the help of @schalkneethling we can make it stand out in other ways. 
Another option is to display it under the table where it's already kinda crowded and mess with all the legends. 
On MDN...
When you …

link to BCD GitHub new-issue

---

client/src/document/toolbar/index.tsx
client/src/homepage/hooks.tsx
client/src/homepage/index.tsx
client/src/homepage/viewed-documents.scss
client/src/homepage/viewed-documents.tsx

This is a kinda rushed job but I quite like it and it's something I've been wanting for myself. If you like it, let's keep it. 
Note that all this code is lazy-loaded in the client only so none of it will bloat the JS/CSS bundle we ship to production.

recently viewed documents on the home page

---

deployer/aws-lambda/content-origin-request/index.js

Fixes #1363 
This change has already been uploaded to the `dev` environment. https://main.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Thunderbird/contributors.txt works now.

update lambda to handle contributors.txt

---

kumascript/src/info.js

Fixes #1377
Here's how I tested it:
1. In `content/files/en-us/mdn/kitchensink/index.html` there exists this: `{{domxref("HTMLElement")}}`
2. Confirm that that's a perfectly healthy document: `files/en-us/web/api/htmlelement/index.html`
3. Edit `files/en-us/_redirects.txt` and add: `echo '/en-US/docs/Web/API/HTMLElement /en-US/docs/Web/API/window/window' >> files/en-us/_redirects.txt`
4. [View the kitchensink](http://localhost:3000/en-US/docs/MDN/Kitchensink) and find the mention of "DOM Interface" and the link that follows. 
That link becomes (on `master`):
```html
<a href="/en-US/docs/Web/API/Window/window" data-flaw-src="{{domxref(&quot;HTMLElement&quot;)}}"><code>HTMLElement</code></a>
```
With the code in this branch:
```html
<a …
```

prefer documents on disk over redirects

---

.github/workflows/production-build.yml
deployer/aws-lambda/content-origin-request/index.js
deployer/src/deployer/upload.py

Fixes #1371 
Fixes #1365 
This also temporarily fixes the `BUILD_LIVE_SAMPLES_BASE_URL` for the `production-build` GHA workflow. Since we're temporarily deploying to `mdn-content-dev`, we need to build with `export BUILD_LIVE_SAMPLES_BASE_URL=` or else the live-samples won't work.
The Lambda function defined here has already been published (version 48) and configured to work with our dev CF instance. I also did a full build of the latest `mdn/content` (using `export BUILD_LIVE_SAMPLES_BASE_URL=`) and deployed to `mdn-content-dev` with the `ryan` prefix:
- https://ryan.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/align-content (scroll down to the live sample)
- https://ryan.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/align-content/ (redirects)
- …

better s3 keys and lambda function

---

build/document-extractor.js
build/index.js
client/src/document/ingredients/browser-compatibility-table/index.tsx
client/src/document/ingredients/prose.tsx
client/src/document/ingredients/utils.tsx

Fixes #1322
Some interesting pages to try it on:
* http://localhost:3000/en-US/docs/Web/API/MediaSessionActionDetails - uses the `{{page}}` macro to embed sections from another document. 
* http://localhost:3000/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs - so many BCD tables
* http://localhost:3000/en-us/docs/Web/API/Web_Authentication_API - Lots of BCD tables but no `<h2>` for each

"Browser compatibility" isn't a clickable permalink header

---

filecheck/cli.js
import/cli.js
package.json
redirects/cli.js
yarn.lock

Fixes #1388
Sneakily killing two birds with one stone here: 
* Fixing  #1388 (now `yarn redirects --help` does exit 0)
* Upgrading from caporal 1.x to 2.x

"yarn redirects --help" will exit non-zero

---

testing/tests/headless.test.js

Because [it happened](https://github.com/mdn/yari/runs/1211695379?check_suite_focus=true).
I'm not sure if going from 500ms to 1,500ms actually would have saved the bacon that time, but this definitely will reduce the probability a bit.

longer default timeout on headless testing

---

kumascript/index.js
kumascript/src/live-sample.js

Fixes #1397
This fixes the problem. Now
http://localhost:3000/en-US/docs/Web/API/FocusEvent and http://localhost:3000/en-US/docs/Web/API/HTMLDataListElement work. 
I'm just not entirely sure this was the right fix. Seems a bit hacky.

InheritanceDiagram to produce live samples

---

build/syntax-highlight.js

Fixes #1281
Now, we're doing what Prism does when it runs in the browser. It too, looks for any `<pre>` extracts its text, runs Prism itself and then wraps it by putting it all in a `<code>` element first. 
But what Prism also does is that they copy the languge class-name into the code. E.g. 
```html
<pre class="language-js">function</pre>
```
becomes:
```html
<pre class="language-js"><code class="language-js"><span class="keyword">function</span></code></pre>
```
whereas here in Yari, I ignore that.

Code examples should be wrapped in a code element

---

content/document.js

Fixes #758
Now, if you've created a folder with a space in it you'll notice it as soon as you type `yarn start`. Mine says:
```
5:06:54 PM server.1     |  Error while adding document /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/glossary/not allowed/index.html to index: Error: Folder contains whitespace which is not allowed.
5:06:54 PM server.1     |      at Object.read (/Users/peterbe/dev/MOZILLA/MDN/yari/content/document.js:154:11)
5:06:54 PM server.1     |      at postDocumentInfo (/Users/peterbe/dev/MOZILLA/MDN/yari/server/document-watch.worker.js:18:31)
5:06:54 PM server.1     |      at FSWatcher.<anonymous> (/Users/peterbe/dev/MOZILLA/MDN/yari/server/document-watch.worker.js:61:3)
5:06:54 PM server.1     |      at FSWatcher.emit (events.js:314:20)
5:06:54 PM server.1     | …
```

disallow content folders with whitespace

---

build/cli.js
ssr/render.js

Fixes #1403
Now, view-source:http://localhost:5000/en-US/docs/MDN/Kitchensink/ will contain `<meta name="robots" content="noindex, nofollow">`
And the sitemaps.xml.gz won't list it either.

Exclude Kitchensink from indexing

---

build/flaws.js

Fixes #1412
I opened http://localhost:3000/en-US/docs/Learn/Server-side/First_steps/Client-Server_overview#_flaws
and it complained about 2 external images. Both images's names had uppercase characters and whitespace (URL encoded).
Now, when you press the "Fix fixable flaws" button and then check what it did to $CONTENT_ROOT, you'll find:
```
▶ git status
On branch main
Your branch is up to date with 'origin/main'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   files/en-us/learn/server-side/first_steps/client-server_overview/index.html
Untracked files:
(use "git add <file>..." to include in what will be committed) …
```

Download of fixable flaw images should be lowercased

---

build/cli.js

Noticed this while working on the AWS infrastructure.

fix name of main sitemap file

---

build/flaws.js
build/index.js

Fixes #1409
First of all, the diff looks huge but it's just unfortunate from the refactoring. 
It used to be this, all in one big function:
```javascript
function injectFlaws() {
if (options.flawLevels.get("broken_links") !== FLAW_LEVELS.IGNORE) {
...
}
if (options.flawLevels.get("bad_bcd_queries") !== FLAW_LEVELS.IGNORE) {
...
}
}
```
And, apart from the actual important fixes, my refactoring was to break it into smaller functions:
```javascript
function injectFlaws() {
injectBrokenLinksFlaws(options.flawLevels.get("broken_links"), ...);
injectBadBCDQueriesFlaws(options.flawLevels.get("bad_bcd_queries"), ...);
}
```
and within those broken-out functions, I made it return early if `level === FLAW_LEVELS.IGNORE`.
Hence the diff looking so large.

refactor flaw injection

---

deployer/src/deployer/constants.py

Now, files will be cached in the CDN for 24h instead of 60m. By default.

more aggressive S3 key caching

---

build/constants.js
build/flaws.js
build/index.js
client/src/document/toolbar/flaws.tsx
client/src/document/types.tsx
client/src/flaw-utils.js
testing/content/files/en-us/learn/some_code/index.html
testing/content/files/en-us/web/fixable_flaws/pre_with_html/index.html
testing/tests/destructive.test.js
testing/tests/index.test.js

~This PR is a draft because it builds [on top of this refactoring PR](https://github.com/mdn/yari/pull/1410). That's why, at the time of writing, the diff looks huge.~
---------------
Fixes #1404
This got a bit more involved than I had hoped. 
Nevertheless, we have [over 200 documents](https://gist.github.com/peterbe/291c10e81976433f15aac6b2fad864fe) whose Kuma-HTML source is the Prism escaped HTML inside the `<pre>` tag rather than just the code itself. So some way, we have to tackle that. 
To test this, find one of the pages in https://gist.github.com/peterbe/291c10e81976433f15aac6b2fad864fe and view it on localhost:3000. 
It should pop up as a flaw and it should say it's fixable. E.g.
When you press the "Fix fixable flaw" the page should render perfectly the same as before. 
But when …

<pre> tags with html flaws

---

build/document-utils.js

I noticed that if you look carefully at how that `while` loop works, for every document we ultimately end up doing:
```javascript
const parentDoc = Document.findByURL('/en-US/docs');
// and 
const parentDoc = Document.findByURL('/en-US');
```
That will never yield anything. Thankfully, the `Document.findByURL` is backed by `Document.read` which is memoized (in production) but it's still a waste if this fix is so easy. 
A good page to test it on that has a deep breadcrumb trail is: http://localhost:3000/en-US/docs/Games/Techniques/3D_on_the_web/Building_up_a_basic_demo_with_PlayCanvas/editor
Part of #1458

optimize breadcrumb data lookups

---

kumascript/macros/Index.ejs

Fixes #1468
The page to test it on is http://localhost:3000/en-US/docs/WebAssembly/Index which makes it easy to see the before-and-after with `master`. 
Also, I think *this* will be easier to review once https://github.com/mdn/yari/pull/1469 is merged (and this branch is updated).

Exclude pages called Index in the Index macro

---

content/document.js

Fixes #1383
This is my backward way of reviewing https://github.com/mdn/yari/pull/1449
My first instinct was that it's weird that a *folder* has a hash in it. It's not weird that a URL has a hash in it.
I think it makes sense for the call of `Document.findByURL('/en-us/docs/foo#bar')` but that's also the only time it makes sense. In your PR, you replaced every `read()` with `readWithHash` which felt like a solution to a problem that didn't exist. 
Also, there's a breakage of logic here:
```javascript
const doc = read(folder);
if (hash) {
doc.url = `${doc.url}#${hash}`;
```
because `read(folder)` can return `undefined`. See: https://github.com/mdn/yari/blob/ed215461b28b24607160074113964cfd4855ae67/content/document.js#L150-L151
In my hack, I only reattach the `hash` back if the `read()` did …

make findByURL smarter with hashes

---

.github/workflows/performance.yml
package.json
server/static.js

Fixes #274
Moved from https://github.com/mdn/yari/pull/1487
Because I need to run it from the `mdn` repo otherwise the `LHCI_GITHUB_APP_TOKEN` can't be used.

Run Lighthouse in CI

---

build/flaws.js
testing/content/files/en-us/web/brokenlinks/without_locale_prefix/index.html
testing/tests/index.test.js

Fixes #1460
Fixes #1458
I think the new tests speak for themselves :)

assume /en-US/ on /docs links that might be broken

---

kumascript/macros/NonStandardBadge.ejs
kumascript/tests/macros/ListGroups.test.js
kumascript/tests/macros/apiref.test.js

Fixes #1519 
@schalkneethling As part of fixing the unit tests, I noticed that the `NonStandardBadge.ejs` macro uses the `experimental` CSS class, but I suspect that should be something else. I changed it to use `nonStandard` instead (which my kumascript unit test changes assume as well), but let me know if that's incorrect.

fix ks unit tests for mdn-fiori branch

---

.github/workflows/production-build.yml
deployer/src/deployer/upload.py

Fixes #1529
At the moment, we only use the `client/build/index.html` in the `ssr` component to generate the HTML for each and every document. 
Some day, aka. Yari 2, we're going not just (server-side) generate documents but also other single-page-apps (aka. skeletons) such as the home page, site-search, sign-up, etc. That day, we'll use, just like the server-side rendering of documents, the `client/build/index.html` as the template to generate files like `client/build/en-us/index.html` or `client/build/en-us/search/index.html`. But once the index.html "template file" has been used up, there's no point keep it or ever letting it get into S3.

how to treat the root index.html file

---

.github/workflows/production-build.yml
deployer/src/deployer/main.py
deployer/src/deployer/whatsdeployed.py

Fixes #1527
This creates an S3 key `_whatsdeployed/code.json` and `_whatsdeployed/content.json` based on the git sha of `mdn/yari` and `mdn/content` respectively. 
Next is to go to https://whatsdeployed.io and generate the right URLs and share them somehow. Like we're doing in the README.md on kuma. 
However, we're not in production yet! But we'll have a dev URL at least and Whatsdeployed supports (and encourages) that you have multiple environments that compare against.

Support Whatsdeployed

---

deployer/src/deployer/upload.py

Fixes #1569 
It's amazing that neither of us caught this earlier, but when we modified our deployer uploads as well as our Lambda@Edge function to stop using `index.html`, we forgot to do the same for redirects.
This code has already been used to upload to both https://main.content.dev.mdn.mozit.cloud and https://yari.stage.mdn.mozit.cloud, and it works.
Try https://main.content.dev.mdn.mozit.cloud/en-US/docs/SVG. It now correctly redirects to https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG.

fix deployer upload of redirects

---

client/src/document/on-github.tsx

Fixes #1556
To test, go to a page like http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll and scroll down to the "Report a problem with this content on GitHub" link and click it. Compare with screenshot in issue.

Headers have whitespace in front of them in issue template

---

content/document.js
content/utils.js

fixes #1574 
- git toplevel as cwd for git commands
- check if parent slug exists when moving content

fix path issues in tool

---

client/src/document/index.scss
client/src/document/index.tsx

Part of #1587
I'm not falling in love with how it looks but it certainly works and it's certainly a huge deal better than what we had before at a pretty cheap cost. 
Here's a screencast where I use Chrome and the "Fast 3G" network speed:

A better loading screen for client-side navigation transitions

---

kumascript/src/api/util.js

Fixes #1585
This is how they describe doing the `.map` in the documentation: https://cheerio.js.org/
How we joined the array of strings is up to us. It's not clear if kuma is using `\n` or ` ` but I think a newline feels more solid.

stich live samples together with whitespace

---

kumascript/src/info.js
kumascript/src/render.js

Fixes #1570
I started down the rabbit hole of using `renderMacros()` instead and constructing the environment from within there in the `getPage`. We'd have to track back in every macro where the `.summary` is used and turn that into an async call. 
Also, I got myself into a circular require loop in Node. 
The basic solution (presented here in this PR) seems to work wonderfully on all the pages I tested on. 
The index pages, that use these kinds of macros, are not a high priority itself. 
Suppose that we could figure out how to make a full KS macro render, it still leaves us at risk of going into an infinite loop akin to the chicken-and-egg problem. 
I seem to be able to build EVERYTHING now with `Cheerio`. I edited a couple of corrupt and broken ones on wiki.developer.mozilla.org so …

fake ks macros in regex summaries

---

client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
client/src/document/ingredients/browser-compatibility-table/index.tsx
client/src/document/ingredients/browser-compatibility-table/utils.ts

Fixes #1611
To test, look at the BCD table on http://localhost:3000/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_compatibility_for_manifest.json and compare with https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_compatibility_for_manifest.json
Apart from the styling, it should have the same rows and same stuff in the first column.

list BCD sub-rows

---

.github/dependabot.yml

No issue. This is a bit experimental (but most likely harmless) and uncertain. 
The author of our wonderful [`action-dependabot-auto-merge`](https://github.com/ahmadnassri/action-dependabot-auto-merge) now [claims he's found a solution](https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/31#issuecomment-718779806) to the problem that sometimes Dependabot generates PRs that don't have a "from version" in the title which means the auto-merge workflow can't work. 
It's kinda hard to test this, but let's try if having this means that we cease to get Dependabot PRs (on Actions) that lack the from-version in the title. If this works now, let's do it for `npm` too.

force dependabot commit messages

---

build/flaws.js
build/index.js
docs/cli-tool.md
testing/tests/destructive.test.js
tool/cli.js

- add flaws check to validate
- add flaws command

Add flaws check / fix to cli

---

package.json
yarn.lock

Let CRA take care of managing Jest as a dependency.
fix #1659

do not manually manage jest dependency

---

client/src/document/index.tsx
client/src/document/organisms/sidebar/index.scss
client/src/document/organisms/toc/index.scss
client/src/document/organisms/toc/index.tsx
client/src/stories/organisms/page-header.stories.js

Reduce the font-size of the sidebar and toc:
1. It is too large
2. It bleeds too much into the content and makes the UI feel cluttered
fix #1605

fix: toc and sidebar font size

---

client/src/ui/molecules/titlebar/index.scss

Wrap long titles on mobile.
fix #1674

fix: wrap long titles on mobile

---

client/src/document/ingredients/browser-compatibility-table/headers.tsx
client/src/document/ingredients/browser-compatibility-table/index.tsx
kumascript/macros/Compat.ejs
kumascript/tests/macros/Compat.test.js

Fixes #1676
What happened was that [`safari` was added to the list of `webextension-desktop`](https://github.com/mdn/kumascript/commit/56bb32e064b62252d6e7a069960724abef631366). 
The original PR was here: https://github.com/mdn/kumascript/pull/1396
I don't know exactly when we forked Compat.ejs into Yari, but clearly this is a case of a macro that was edit since *after* the fork point.

Safari column missing in Yari

---

client/src/document/ingredients/browser-compatibility-table/headers.tsx

Fixes #1595
Proof that it works:

correct BCD platform icons

---

.github/workflows/dev-build.yml
.github/workflows/prod-build.yml
.github/workflows/stage-build.yml
docs/deployments.md

Part of #1713
@escattone I'm starting to get writers-block. I can't think of anything else to include now. 
I wanted to jot down some key points in that markdown documentation file, but I deliberately tried to be brief to not overcommit to too many technical details. 
I quite like the look of this! It's never pretty to have to see all those little bash tricks repeated so heavily, but I quite like the idea that you can put on your Stage environment hat and work exclusively on that without having to worry about breaking something in prod or dev, for example.

Different deployment strategies for prod, stage, and dev

---

client/src/search.tsx
testing/tests/search.test.js

Fixes #1696
Much better!
Also, I cheekily added some more end-to-end headless tests to the search that finds (and not finds) things by fuzzy-search.

Don't say "Nothing found" when you haven't typed anything

---

kumascript/macros/B2GOnlyHeader2.ejs
kumascript/macros/CompatibilityTable.ejs
kumascript/macros/DeprecatedGeneric.ejs
kumascript/macros/Draft.ejs
kumascript/macros/LegacyAddonsNotice.ejs
kumascript/macros/Non-standardGeneric.ejs
kumascript/macros/NoteStart.ejs
kumascript/macros/ObsoleteGeneric.ejs
kumascript/macros/SeeCompatTable.ejs
kumascript/macros/SimpleBanner.ejs
kumascript/macros/gecko_minversion_note.ejs
kumascript/macros/jsOverrides.ejs
kumascript/macros/jsapi_minversion_header.ejs
kumascript/macros/minversionGeneric.ejs
kumascript/macros/secureContextGeneric.ejs
kumascript/macros/unimplementedGeneric.ejs
kumascript/macros/warning.ejs
kumascript/src/info.js
kumascript/tests/macros/Deprecated.test.js
kumascript/tests/macros/Draft.test.js

Update kumascript macros in preparation for the changes from minimalist release 0.2.6
Test page: http://localhost.org:3000/en-US/docs/Web/API/Window/applicationCache
- /yari/kumascript/macros/B2GOnlyHeader2.ejs
- /yari/kumascript/macros/Draft.ejs
- /yari/kumascript/macros/gecko_minversion_note.ejs
- /yari/kumascript/macros/jsOverrides.ejs
- /yari/kumascript/macros/LegacyAddonsNotice.ejs
- /yari/kumascript/macros/NoteStart.ejs
- /yari/kumascript/macros/SimpleBanner.ejs
- /yari/kumascript/macros/warning.ejs
part of #1133

fix: note cards

---

client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
client/src/document/ingredients/browser-compatibility-table/index.tsx
client/src/document/ingredients/browser-compatibility-table/utils.ts

Fixes #1668
I believe all of these are now matching in parity. Or, are they? My head is a spinning from all the tabs and stuff:
1. http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Browser_compatibility and https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Browser_compatibility
2. http://localhost:5000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat/#Browser_compatibility and https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat#Browser_compatibility
3. http://localhost:5000/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_compatibility_for_manifest.json and https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_compatibility_for_manife …

BCD table doesn't list main feature

---

.github/workflows/dev-build.yml
.github/workflows/prod-build.yml
.github/workflows/stage-build.yml

I'll be honest, I started reading the error messages and the documentation and I just got half lost and half bored. 
The lines that broke are these: https://github.com/mdn/yari/blob/12e461062567ab8e0db6e4c659e1ba562a2b0572/.github/workflows/dev-build.yml#L93-L94
So I went to [their repo](https://github.com/dschep/install-poetry-action) to see if there are any issues/PRs. 
But then I see that repo is archived and it recommends to use: [`snok/install-poetry`](https://github.com/snok/install-poetry) instead. 
So I changed to that and suddenly, [it can now build set up `poetry` again](https://github.com/mdn/yari/runs/1414185250?check_suite_focus=true).

unbreak poetry install in GHA

---

.github/workflows/testing.yml
deployer/README.md
deployer/src/deployer/constants.py
deployer/src/deployer/main.py

Following the directions on https://github.com/snok/install-poetry#testing
The problem was that when I did https://github.com/mdn/yari/pull/1755 I forgot to fix the `testing.yml` too. But we didn't notice because the `get-diff-action` prevented anything to even attempt to run there. 
What's cool now is that we're now caching the whole `virtualenv` it creates (cached by the `deployer/poetry.lock` file). So not just caching the HTTP downloads that `poetry` would have to done to PyPI but the whole `deployer/.venv` directory. Here's an example of that awesomeness:
**1s to install all the Python code**
I also desperately made some irrelevant edits to some files just to trigger changes between commits, to bypass the `get-diff-action` stuff. Sorry.

unbreak 'deployer' test suite

---

libs/constants/index.js
libs/fundamental-redirects/index.js
testing/tests/redirects.test.js

Part of #1345
Here's how I tested it manually:
```javascript
const { resolveFundamental } = require("./libs/fundamental-redirects");
console.log(resolveFundamental("/en/docs/Foo/bar"));
console.log(resolveFundamental("/En_uS/docs/Foo/bar"));
console.log(resolveFundamental("/pt/docs/Foo/bar"));
console.log(resolveFundamental("/fr-FR/docs/Foo/bar"));
console.log('-');
console.log(resolveFundamental("/en-US/docs/Foo/bar"));
console.log(resolveFundamental("/en-us/docs/Foo/bar"));
```
Outputs:
```
{ url: '/en-US/docs/Foo/bar', status: 301 }
{ url: '/en-US/docs/Foo/bar', status: 301 }
{ url: '/pt-PT/docs/Foo/bar', status: 301 }
{ url: '/fr/docs/Foo/bar', status: 301 }
-
{}
{}
```
So the key here is that there is exactly 1 single Map object we need to maintain to control all legacy locale …

cope with old locale prefixes

---

client/src/document/ingredients/browser-compatibility-table/atoms/_bc-supports.scss

Use orange and red variants from color palette for BCD table instead of custom red and orange
@mdn/core-yari-dev merging this as it is a super simple change.
fix #1683

fix: bcd: use colors from color palette

---

build/index.js
testing/content/files/en-us/web/donttranslatethese/index.html
testing/tests/index.test.js

Part of #1795
I still think we should, someday in 2021, go in and do a mass edit of all ~400 files. 
Also, there's something rather strange about the display now. 
The fact that in the red warning box you have 
```
[ICON] [HEADING]
[text]
```
whereas on the yellow one, it's 
```
[ICON]
[HEADING]
[text]
```

add .notecard on div.warning divs

---

.gitignore
package.json
yarn.lock

CRA manages the version and updates for `babel-loader` so we should not.
fix #1847

deps: remove babel-loader

---

.stylelintrc.json
client/src/ui/molecules/breadcrumbs/index.scss

Use `highlight-link-state` for the `:active` state of breadcrumb links
fix #1594

fix: use highlighted link state for breadcrumb active

---

client/src/document/index.scss

Use `columns` to display indexes in a multi column layout
fix #1609

fix: indexes lacks multi column display

---

client/src/document/ingredients/browser-compatibility-table/atoms/_bc-legend.scss
client/src/document/ingredients/browser-compatibility-table/legend.tsx

Fix browser compat table legend layout across viewports
fix #1612

fix: browser-compat legend layout

---

client/src/ui/molecules/titlebar/index.scss

Switch from `break-all` to using `break-word` for the titlebar
fix #1869

fix: use break-wor for titlebar

---

client/tsconfig.json
package.json
yarn.lock

Switch to using just sass as a dependency without the addition of `node-sass`
The `tsconfig` change was made by react-scripts:
```
The following changes are being made to your tsconfig.json file:
- compilerOptions.jsx must be react-jsx (to support the new JSX transform in React 17)
```
fix #1871

deps: remove node-sass

---

client/src/document/ingredients/browser-compatibility-table/atoms/_bc-table.scss
client/src/document/ingredients/browser-compatibility-table/feature-row.tsx

All text in the row headers is now displayed without using any text decoration.
When a user hovers over an entry that is a link
1. The little pointer icon will show and,
2. The background color of the cell will change
fix #1610
fix #1694

fix: underlining for links in row headers not clean

---

kumascript/macros/HTMLRefTable.ejs

I searched the content repo and the only file that uses `HTMLRefTable` is:
files/en-us/web/html/element/index.html
None of those uses the optional second parameter that will show badges. As such,
I opted to simply remove that option and the related code.
fix #1581

fix: htmlreftable depends on hard coded image

---

README.md

Updated instructions to make it more obvious to point to files directory inside content repo
I had trouble to get started running this repo. I don't think it's very clear to point to the files folder inside the clone of the content repo. I think this change will help people get started quicker.

Update instructions for `CONTENT_ROOT` in README.md

---

build/cli.js
build/index.js
ssr/render.js

Fixes #1603
I know this is very hard to test but I know it works. 
You need to have the `translated-content` repo, which only I have on my laptop 🙃. But you can generate one with the importer. 
Or, we can just land this and see how it goes once we enable the translated content in the stage builds. 
Basically, what it does is almost exactly what Kuma does. 
When I open view-source:http://localhost:5000/en-US/docs/Web/HTML/Element/a/ I get: https://gist.github.com/peterbe/f0dd4e116f163e2cda59c3f871ac0adc (pretty printed)
Note that it uses 
```html
<link
rel="alternate"
title="&lt;a&gt;"
href="https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/a"
hreflang="zh"
/>
```
for the "Chinese" alternate URL. 
But because the document is available in Traditional Chinese too, it does include: …

rel=alternate links

---

client/src/document/index.scss
client/src/ui/organisms/header/index.scss

Add a fixed banner on archived content pages.
fix #1312

fix: archived content banner

---

client/src/ui/molecules/breadcrumbs/index.scss

fix: Vertically align the > with the anchors

---

client/src/document/index.scss

The inline readonly badge needs a slightly darker background color when used in general article content.
fix #1883

fix: readonly badge background color

---

build/index.js

Part of #7647
This doesn't entirely solve the problem. 
Perhaps once we're in Yari proper we can do some relatively fancy grep and search-and-replace everywhere. That day, we can revert this PR.

scrub all links to www_fxsitecompat_com

---

build/document-extractor.js
build/index.js
testing/content/files/en-us/web/foo/index.html

convert div.warning to div.notecard

---

client/src/ui/molecules/breadcrumbs/index.scss

fix: active state of breadcrumb items to remove background color from >

---

client/src/ui/molecules/search/index.scss

Prevent long titles from extending beyond the search result drop-down container
fix #1680

fix: overflow items in search results dropdown

---

.github/workflows/npm-publish.yml
tool/cli.js

I knew the new git history stuff would come to bite us. I don't think we've fully perfected how we're going to store the git log history which we dig up from the `git clone` to a file on disk. Anyway. One battle at a time. 
What's happening in https://github.com/mdn/yari/runs/1488979842?check_suite_focus=true for example is that the `yarn prepare-build` command is failing hard because there is no `CONTENT_ROOT` set in the NPM publishing Workflow. 
You can simulate this error easily by doing:
```
cd /tmp
git clone git@github.com:mdn/yari.git && cd yari
yarn --frozen-lockfile
yarn prepare-build
```
And you just run:
```
export CONTENT_ROOT=testing/content/files
```
and try `yarn prepare-build` again, it solves world hunger. 
It's a bit weird that `yarn prepare-build` does so much but it's …

unbreak npm publishing

---

client/src/document/index.tsx
client/src/document/types.tsx
client/src/ui/molecules/language-menu/index.tsx
testing/.env
testing/tests/headless.test.js
testing/tests/index.test.js
testing/translated-content/files/fr/web/foo/index.html

Fixes #1914
Clearly, we failed ourselves here by not having test coverage. 
So I took the time to introduce a test that tests the translated content. At least at an absolute minimal. 
It literally tests what I described in the issue but it's all automated with headless testing.

Language drop-down is broken

---

.github/workflows/dev-build.yml
.github/workflows/stage-build.yml
build/constants.js
docs/envvars.md
ssr/render.js
testing/tests/index.test.js

robots 'noindex, nofollow' set on every document

---

ssr/render.js

Fixes #1954
It seems that for mobile sometimes you need the Zilla Slab Regular. But mobile is only 15%. 
As of this change, we cover most users and the preloading-in-vain problem goes away.

only preload the Bold woff2 font

---

.gitignore

Looks like during a rebase `.gitignore` got extra lines showing the diff of two branches `<<<<<<< HEAD`, `=======`, `>>>>>>> master`. These probably should be removed.

Fixup .gitignore after PR #1573

---

client/.storybook/preview.scss
client/src/app.tsx
client/src/stories/grid/reference-page-grid.stories.mdx
client/src/stories/organisms/page-header.stories.js

Change the `reference-page` class name to `document-page`
fix #1998

fix: change reference-page to document-page

---

client/src/document/organisms/sidebar/index.scss

Bump down the size of the links and icons in sidebar
fix #1919

fix: bump down font size of related topics links

---

client/src/ui/organisms/footer/index.tsx

Add `aria-label` to ensure social links in footer have discernable names
fix #1978

fix: social links in footer lack discernable names

---

build/git-history.js

Fixes #1990
Here's how I tested this. I created a folder that was symlinked to the real location of where I keep the content/files. 
E.g.
```
▶ ls -l ~/Downloads/ | rg content
lrwxr-xr-x  1 peterbe  staff         16 Dec  7 10:17 content -> /tmp/mdn/content
▶ export CONTENT_ROOT=/Users/peterbe/Downloads/content/files
```
But for sanity, I had to delete the previous disk-based cache of git histories which is in my (real) temp directory. 
```
▶ rm -fr /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/yari-git-history.json
```
Now:
```
▶ node tool/cli.js gather-git-history --verbose
Wrote 'en-us' 11,408 paths into /Users/peterbe/Downloads/content/files/en-us/_githistory.json
Saved 11,408 paths into /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/yari-git-history.json
```

git-history rather fails on symlink CONTENT_ROOT

---

client/src/ui/molecules/language-menu/index.tsx
deployer/aws-lambda/content-origin-request/index.js
deployer/aws-lambda/content-origin-request/package.json
deployer/aws-lambda/content-origin-request/yarn.lock
libs/constants/index.js
libs/get-locale/index.js
libs/get-locale/package.json
package.json
server/index.js
server/middlewares.js
testing/tests/developing.test.js
yarn.lock

Part of #1889
(The reason I'm not saying "Fixes" is because I don't want the issue to close until we've upgraded and tested the new Lambda function on stage)
This is quite a big and complex PR so I'm hoping for a review from both of you gentlemen. 
To test this, you need to build some translated content. I use:
```
export CONTENT_ROOT=/Users/peterbe/dev/MOZILLA/MDN/yari/testing/content/files
export CONTENT_TRANSLATED_ROOT=testing/translated-content/files
yarn build && yarn start
```
Now you should be able to go to http://localhost:5000/en-US/docs/Web/Foo and note the little language drop-down and you should be able to change to French. Once you've done that, check your browser's cookies. 
Now if you go to http://localhost:5000/ it should redirect to http://localhost:5000/fr/
And if you go …

set a cookie when changing language

---

client/src/app.tsx
client/src/page-not-found/index.tsx

Fixes #2007
First of all, switching from `<Link to>` to `<a href>` within the `PageNotFound` component solves the problem of it might not scroll to the top when you click it. This can equally be solved with [scroll restoration](https://reactrouter.com/web/guides/scroll-restoration) but I suspect it needs a little bit more work. 
Secondly, I appreciate that it's hard to test this now! But when we enable the auto-complete search widget, a click on a search result there will mutate the page and want to try to load a document. 
Complicated challenges like this is another feather in the hat of abandoning client-side navigation for the production site. :)

link to English equivalent from 404 page

---

.github/workflows/prod-build.yml
.github/workflows/stage-build.yml

Fixes #2036
Wow what a timesink!! Turns out you can't use
```
contains(github.event.inputs.translated_content || env.DEFAULT_TRANSLATED_CONTENT, 'true')
```
because it becomes falsy if `github.event.inputs.translated_content` *and* `env.DEFAULT_TRANSLATED_CONTENT` is set. Or something. 
This PR might look small and neat but I went through 10+ commits and equally many builds to test this carefully. 
Now, we should be getting the best of both worlds:
1. If it's a `cron` schedule, the default env vars rule the decision. 
2. If it's a manual trigger, the inputs decide. That means it's possible to type in `false` and have it NOT build the translated content.
3. The inputs, if you use that, get *their* default from the env vars. 
Yikes! That got complicated.

Make it possible to control translated-content from manual builds

---

deployer/src/deployer/upload.py

Fixes #2037
The S3 key to check, once this has landed and made it into the next build is: https://s3.console.aws.amazon.com/s3/object/mdn-content-stage?region=us-west-2&prefix=main/en-us/_spas/404.html
But it reminds me, if we don't delete that key from S3 before the next build, our uploader might think the file hasn't changed (only its metadata is different)
So as a reminder ourselves, we need to go back and check that it get set correctly. Or we delete the S3 key right before a build finishes.

404 page should not cache

---

build/resolve-bcd.js
client/src/document/lazy-bcd-table.tsx

Fixes #2020
@ddbeck I can't request a review from you. I added you with `Write` permission to the repo but perhaps it's pending you invitation acceptance. Or perhaps some caching going on in the PR UI. Anyway...
@schalkneethling Can you please review the appears and can you also sanity test my PR. If you open `lazy-bcd-table.tsx` you'll see that there are 3 individual chances of NOT displaying the full BCD table but instead displaying an "error message". 
Can you please have a think about some better styling we can use. Perhaps there's something from minimalist or from the `ui` folder that I can use?
@ddbeck Can you sanity check the implementation and perhaps reflect on the "word smithing" of the error message it self. Here's what it looks like:
It crashes hard [in …

BCD table crashes shouldn't break the page

---

client/src/document/index.scss

Ensure that on desktop viewports the top element in the article lines up with the heading of the "Jump to section" component.
- https://developer.allizom.org/en-US/docs/Web/JavaScript/About_JavaScript
- https://developer.allizom.org/en-US/docs/Web/API/DeviceMotionEventAcceleration
Note: A lot of pages start with two empty `div` element. Not sure why CKEditor did that but, that is something we will have to clean up post-launch. Those are not a problem visually. Sometimes though, like the two pages linked below, it starts with a `div` that wraps an empty paragraph tag. That is a problem visually as paragraphs have a bottom margin. This again is something we will have to live with until the source is cleaned up.
- https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Object …

fix: top alignment of article with toc

---

client/src/document/index.scss

Update the style for inline optional badges to give them a darker shade of grey
fix #1936

fix: update style for inline optional badge

---

client/src/document/organisms/toc/index.scss

Update the border color for the TOC button on mobile.
Part of #1918

fix: consistent border color

---

libs/fundamental-redirects/index.js
testing/integration/headless/map_301.py
testing/tests/redirects.test.js

Kuma supports to just replace the matching parts, yari should too.
```
curl -I  https://developer.allizom.org/en-US/Learn/JavaScript/First_steps → /en-US/docs/Learn/JavaScript
curl -I  https://developer.mozilla.org/en-US/Learn/JavaScript/First_steps → /en-US/docs/Learn/JavaScript/First_steps
```

fix redirects for prefixes

---

kumascript/macros/SpecData.json

Adds the spec for https://github.com/mdn/content/pull/187

Add EXT_texture_norm16 spec

---

client/src/document/toolbar/flaws.tsx

Part of #1541
Basically removed all the use of `<small>` and replaced it with `<span>`. Most of them were my fault in the first place, but now I think it's often just weird to show many of them as small as if they're unimportant. We should use `<small>` (or `font-size` related techniques) to indicate that some piece of information is "less important" and shouldn't distract from the main message.

don't use <small> when there's plenty of space

---

build/index.js
kumascript/src/render.js
kumascript/tests/render.test.js

Fixes #2169
Fixes #2168
Here's what you'd see in `localhost:3000` if you accidentally introduce something to the raw (KS) HTML that can't even be parsed:
It's not gorgeous but it's sufficiently informative and that's what matters. 
This is what you'd see if you use `yarn build` (which is what we use the PR Build in CI on the mdn/content repo):
```
▶ yarn build /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/index.html
$ cross-env NODE_ENV=production node build/cli.js /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/index.html
Building SPAs...
Wrote /Users/peterbe/dev/MOZILLA/MDN/yari/client/build/en-us/_spas/404.html
Building Documents...
Building roots: [ '/Users/peterbe/dev/MOZILLA/MDN/content/files' ]
Error: …
```

Unexpected build errors in CI doesn't reveal which file caused it

---

build/cli.js
build/flaws.js
build/utils.js

Fixes #2164
How I tested it was that I grepped around for a page that has external images and when viewing it with the toolbar it should say "Fix fixable flaws". If you look at the `stdout` it should say something like:
```
12:49:13 PM server.1    |  Raw image size: 33.5 KB Compressed: 13.6 KB
12:49:13 PM server.1    |  Downloaded https://mdn.mozillademos.org/files/11403/matrix-composition.jpg to /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/webgl_api/matrix_math_for_the_web/matrix-composition.jpg
12:49:13 PM server.1    |  Fixed (image4) image https://mdn.mozillademos.org/files/11403/matrix-composition.jpg to matrix-composition.jpg
```
And if the file was already small, it should say something like:
```
12:46:05 PM server.1    |  Raw image size: 38.5 KB
12:46:05 PM server.1 …
```

Downloading images (fixable flaws) should also compress

---

.github/workflows/testing.yml
client/src/constants.ts
client/src/document/lazy-bcd-table.tsx
kumascript/tests/macros/EmbedInteractiveExample.test.js
kumascript/tests/macros/EmbedLiveSample.test.js
kumascript/tests/macros/jsxref.test.js
testing/scripts/lint-check.sh

In https://github.com/mdn/yari/pull/2157 @nschonni discovered a bug in that our prettier and eslint checks never correctly broke the CI, when it should. I'm just "cherry-picking" that diff from until we figure out all the hard discussions around yarn packaging and more advanced eslint config.

bark on eslint and prettier checks in CI

---

content/document.js

Fixes #2171
Once this goes into `master` it's going to break the cron jobs that build. But we can now already go and fix it in `mdn/content` so *this* PR can be merged without breaking things. 
Here's how I tested it by the way:
```
BUILD_FOLDERSEARCH=web/api/paintworklet yarn build
```

crash early on zero width space characters in folder names

---

deployer/src/deployer/upload.py

Fixes #350
I tested it by building the whole site and then running `poetry run upload ../client/build` but before I did that I had it just print to a file what it WOULD have done. It worked :)

deployer sets wrong URL on external URL redirects

---

deployer/src/deployer/speedcurve.py

The default `backoff_factor` is 0. That means the `Retry` mechanism will immediately retry `total` times. The default for `total` is 10 from my skimming of `lib/python3.8/site-packages/urllib3/util/retry.py`. 
The formula for `backoff_factor` is documented follows:
```
:param float backoff_factor:
A backoff factor to apply between attempts after the second try
(most errors are resolved immediately by a second try without a
delay). urllib3 will sleep for::
{backoff factor} * (2 ** ({number of total retries} - 1))
seconds. If the backoff_factor is 0.1, then :func:`.sleep` will sleep
for [0.0s, 0.2s, 0.4s, ...] between retries. It will never be longer
than :attr:`Retry.BACKOFF_MAX`.
By default, backoff is disabled (set to 0).
```
In this PR, I set it to 0.3. With 10 retries it means:
```
>>> …
```

much longer backoff factor for speedcurve pings

---

build/sitemaps.js

Fixes #2199
Running
```
BUILD_FOLDERSEARCH=web/html/element/v yarn build
```
Produces
```
▶ cat client/build/sitemap.xml
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap><loc>https://developer.mozilla.org/sitemaps/ca/sitemap.xml.gz</loc><lastmod>2020-12-18</lastmod></sitemap>
<sitemap><loc>https://developer.mozilla.org/sitemaps/de/sitemap.xml.gz</loc><lastmod>2020-12-18</lastmod></sitemap>
<sitemap><loc>https://developer.mozilla.org/sitemaps/fr/sitemap.xml.gz</loc><lastmod>2020-12-18</lastmod></sitemap>
<sitemap><loc>https://developer.mozilla.org/sitemaps/ja/sitemap.xml.gz</loc><lastmod>2020-12-18</lastmod></sitemap>
<sitemap><loc>https://developer.mozilla.org/sitemaps/ko/sitemap.xml.gz</loc><lastmod>2020-12-18</lastmod></si …
```

fix /sitemaps.xml

---

kumascript/macros/GroupData.json

The API was renamed to [Barcode_Detection_API](https://developer.mozilla.org/en-US/docs/Web/API/Barcode_Detection_API). There is a redirect from *Barcode Detector API* but it isn't working in all cases.
When this goes in I can go back and fix up the new name for the macro. That's easy now we're in github

GroupData - update Barcode Detection API

---

client/public/index.html
client/src/document/index.tsx

Fixes #2054
Before:
After:
Print stylesheets is a matter of "how long is a rope?". There's probably, even more, we could do. But printing isn't a huge priority so it doesn't yet deserve a huge investment. 
Here are a couple of cheap fixes that, I believe, carry a lot of punch. I haven't actually printed them out on actual paper but I've been using the PDF print which is potentially what a lot of people will use when they "print".

make printing documents suck a bit less

---

client/src/document/ingredients/browser-compatibility-table/index.tsx

This changes the compat table's issue link to mention "compatibility" explicitly, in the hopes of reducing confusion about what the link covers.
Fixes #2183.

Revise compat table issue reporting link

---

.github/workflows/dev-build.yml
.github/workflows/developing.yml
.github/workflows/npm-publish.yml
.github/workflows/performance.yml
.github/workflows/prod-build.yml
.github/workflows/stage-build.yml
.github/workflows/testing.yml

Don't feel strongly about this, but it has the benefit of allowing cross-OS building by allowing the action to set/export as required.
You can see the calculated values in the collapsed section of the steps like https://github.com/mdn/yari/pull/2167/checks?check_run_id=1565822944#step:9:8, so a bunch of the `echo` statements could be removed.
Didn't dig into a way to do the conditional assignments of variables like:
```bash
if [ ${{ github.event.inputs.archived_content }} == "true" ]; then
echo "Will build mdn/archived-content too"
export CONTENT_ARCHIVED_ROOT=$(pwd)/mdn/archived-content/files
else
echo "Will NOT build mdn/archived-content too"
fi
```

chore: Hoist env variables in GitHub Actions

---

build/flaws.js
filecheck/checker.js
server/index.js

Fixes #2262
Thanks for these fixes I was able to make https://github.com/mdn/content/pull/584
It uncovered two problems. First, if you download a `foo.PNG` file, it couldn't find the right `imagemin` plugin. 
But also, requesting `curl -I http://localhost:5000/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose/mongodb_atlas_-_createcluster.jpg` failed because the server was only aware of `.jpeg` file extensions.

Cope with .PNG file extension

---

kumascript/macros/WebExtAPISidebar.ejs

E.g. display `create()` for page devtools.panel.create()
Fix #2189
---
Quoting from my first comment on #2189:
> I tried to make a PR but changing the `WebExtAPISidebar.ejs` didn’t seem to affect the rendered page. I noticed that `nodemon` didn’t listen for ejs files but even after relaunching `yarn dev` it still gave me the wrong results.
I tried again and it still doesn’t work. When using `yarn start`, and I try to visit the `devtools.panels` page, I get a “`Error: 404 on /en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.panels/create/index.json: Page not found`”. The only way I get to make yari work is to launch `yarn start` in my local clone of `mdn/content` first, which I believe builds file with its own version of yari. `yarn build` also failed: …

Use last part of the title page in WebExtAPISidebar

---

build/check-images.js
build/flaws.js

Part of #1103
This takes care of the first 2 checkboxes on https://github.com/mdn/yari/issues/1103
Using this patch, I was able to create:
* https://github.com/mdn/content/pull/933
* https://github.com/mdn/content/pull/934
...simply by pressing the "Fix fixable flaws" button.

make weird actually external images fixable

---

kumascript/macros/MDNSidebar.ejs
kumascript/tests/macros/mdnsidebar.test.js

...so that it no longer shows outdated and broken links
This is really just a temporary fix, and we'll probably want to improve this further at a later date.
@escattone how would we go about testing KumaScript updates at this point? That's not particularly clear anymore, after the move.

fixing up the MDNSidebar... 

---

kumascript/macros/Interwiki.ejs

This change makes the `Interwiki` macro construct the path value for wiki URLs by replacing any spaces in the article title with underscores, and uppercasing the first letter of the path.
Otherwise, without this change, the macro constructs wiki URLs that contain spaces — which results in MDN having more than 100 URLs with spaces; and because the URL spec disallows spaces in URLs, all the MDN articles with those space-containing URLs are invalid.
Moreover, given a URL with spaces, MediaWiki anyway redirects that to the corresponding URL which has the spaces replaced by underscores. So this change also prevents an unnecessary/wasteful redirect.
Further, given a URL with a path that begins with a lowercase letter, MediaWiki redirects that to the corresponding URL which has the first letter …

Make Interwiki macro replace spaces & uppercase first letter of path

---

kumascript/macros/SVGRef.ejs

This commit fixes a bug in the `SVGRef` macro, by changing part of the `SVGRef` macro source to use the same code as the corresponding part in the `HTMLRef` macro source.
Without this change, the macro can cause broken hyperlinks to be generated.
---
See the **Related Topics** sidebar at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/desc. If you View Source or inspect the DOM, you’ll find this:
```html
<a href="/en-US/docs/Web/SVG/Element/title — the SVG accessible name element"><code>&lt;title — the SVG accessible name element&gt;</code></a>
```

Fix linkifying bug in SVGRef macro

---

client/src/document/index.tsx
client/src/document/ingredients/utils.tsx
client/src/document/organisms/toc/index.tsx
testing/tests/headless.test.js

This actually works. Try going to 
http://localhost:5000/en-US/docs/Web/HTML/Element/video#Browser_Compatibility

lowercase all anchor IDs and recover if not lowercase

---

kumascript/src/live-sample.js

This change fixes a bug that makes Yari fail to find a given ID for a sample-containing section when LiveSampleLink is used, but not when EmbedLiveSample is used.
Related: https://github.com/mdn/content/issues/657

Fix bug causing LiveSampleLink ID search to fail

---

.github/workflows/pr-docs.yml
.github/workflows/testing.yml

This way, GitHub Actions doesn't even need to start a container if that `on.pull_request.paths` don't match. 
And it doesn't hurt to run `markdownlint-cli` on every single `docs/**/*.md` file we have because there are so few.

break out CI workflows (docs)

---

kumascript/macros/InterfaceData.json

I'm working on documenting a bunch of missing CSSRule interface pages. This PR adds the data to InterfaceData.

Adding the missing CSSRule interfaces

---

kumascript/macros/TemplateLink.ejs
kumascript/tests/macros/TemplateLink.test.js

The generated links were still pointing to the old kuma repo, so I've updated the base URL to point correctly to the macros directory inside the yari repo.
I also tweaked the explanatory wording a bit.

fixing the templatelink macro, as it was pointing links to the wrong place

---

client/src/app.tsx
client/src/constants.ts
client/src/document/index.tsx
client/src/ga-context.tsx
docs/envvars.md
ssr/render.js

Fixes #2355
**How to test this...**
Best way to test this is to use `localhost:5000` which is a whole lot more realistic than using `localhost:3000` because, this way, the initial HTML is always server-side rendered (on-the-fly by Express instead of statically built in S3). 
But to be able to even do that add the following to your `.env` first:
```
BUILD_GOOGLE_ANALYTICS_ACCOUNT=UA-00000000-0
BUILD_GOOGLE_ANALYTICS_DEBUG=true
```
Use a browser that doesn't block or "mess" with Google Analytics so that you know that it's not tracking protection refusing things. I use my stable Chrome. 
Load a page like: http://localhost:5000/en-US/docs/Web/HTML/Element/video
Open the web console, and what you should see is something like this:
Things to observe:
* It doesn't set `dimension19`
* The …

trigger GA pageview send event

---

kumascript/macros/SpecData.json

CSS Text Level 3 and CSS Box Model Level 3 have both gone to CR: https://www.w3.org/blog/CSS/ this PR updates SpecData

two specs to CR

---

kumascript/macros/anch.ejs

Fixes #2383.
When being rendered, the header IDs are converted to lowercase, whereas the [anchor macro] does not convert its argument to lowercase. This causes in-page links to be broken on pages that pass IDs containing capital letters to the anchor macro. This commit fixes it by converting the argument of the anchor macro to lowercase, with the help of [string.toLower function].
[anchor macro]: kumascript/macros/anch.ejs
[string.toLower function]: kumascript/src/api/string.js

Fix broken links to in-page sections (#2383)

---

kumascript/macros/CSS_Ref.ejs

This change makes the CSS_Ref macro by default also output features marked as status:experimental.
Otherwise, without this change, CSS_Ref by default only output features marked as status:standard.
Related: https://github.com/mdn/content/issues/903
Related: https://github.com/mdn/sprints/issues/2068

Make CSS_Ref by default include experimental too

---

server/index.js

This change fixes a problem that causes Yari to crash for requests to `/*/contributors.txt` routes. The existing code expects a call to `await buildDocument(document)` to return an array. when in fact it returns an object.
Without this change, requests for `/*/contributors.txt` routes cause Yari to crash with this log output:
```
node_modules/@mdn/yari/server/index.js:102
const [builtDocument] = await buildDocument(document);
^
TypeError: (intermediate value) is not iterable
at node_modules/@mdn/yari/server/index.js:102:27
```

Fix handling for /*/contributors.txt routes

---

kumascript/macros/JsSidebar.ejs

In the german JS Sidebar the link for Memory Management is linked to a non existent page leading to a 404 page not found.
But there actually exists a german page for this and it is correctly linked in the content of other pages.
The page is called "Speicherverwaltung"
Here's the link to the german page: https://developer.mozilla.org/de/docs/Web/JavaScript/Speicherverwaltung

Add correct german page for Memory Management

---

kumascript/macros/EmbedYouTube.ejs

Fixes #2245
Fixes #2246
This kills two issues with one stone. Sorry, but I think it's justifiable. 
Also, I noticed that the `intrinstic-wrapper` and `intrinsic-container` doesn't do anything. Neither of those terms can be found in use anywhere in `yari` or in `mdn-minimalist`. 
There are quite a few pages that use `EmbedYouTube` but I randomly picked some and checked and it works fine.

update youtube embed code

---

client/src/ui/molecules/breadcrumbs/index.scss

Fixes #2260
This fixes the main issue of the chevron icon being cutoff. But for it to be perfect, some review and maybe another media query might remedy the "too small" icon viewport ranges.

Fix chevron icon being cutoff on smaller viewports

---

client/public/index.html
client/src/index.tsx

Fixes #2353
Fixes #2367
Fixes #1547
Fixes #2344
This way, it works in Firefox 58, IE11, MS Edge 80 to name a few. 
I opted for a polyfill because it's only 19KB (gzipped, 83KB uncompressed) and it makes the nav work. 
What was curious was that for Firefox 58, it wasn't enough to download the `es6` polyfill, but when I explicitly added `Array.protoype.flat` to it, it started to work. 
Now the top nav works, i.e. clicking to open "Technologies" and the BCD table works. 
I did get some errors with the BCD table and the interactive examples in IE11 but not enough to care.

 make it work in old browsers

---

kumascript/macros/LearnSidebar.ejs

The page linked to is https://developer.mozilla.org/en-US/docs/Learn/How_to_contribute
I've removed this page from the content, and want to remove the corresponding link to it from the learn sidebar.
This page was ineffective, hardly ever looked at, and out of date.

removing contribute link from learn sidebar

---

.github/workflows/pr-kumascript.yml
.github/workflows/testing.yml

Similar to https://github.com/mdn/yari/pull/2361
This way, there's a dedicated CI workflow exclusively for any changes within the kumascript sub-folder but only if there are changes there (or if packages are upgraded). 
This simplifies things.

refactor kumascript testing workflow

---

build/cli.js
build/document-extractor.js

Fixes #2308
How to test this:
```
yarn prepare-build
BUILD_FOLDERSEARCH=web/css yarn build 
cat client/build/en-us/docs/web/css/writing-mode/bcd.json | jq
```
The bug only shows itself when the builder comes across the same object from `@mdn/browser-compat-data`. Whoever is the first object that touched the object would mutate it too destructively so when the next page builds, it would lack information. 
For the record, the serialized and dumped `bcd.json` becomes about 113KB if you don't disregard that chunk of data. If you do the exclusion serialization it becomes about 5KB. So there's value in the optimization.

Browser release dates not being shown

---

client/src/flaws/index.tsx

Display human-friendly flaw names on the dashboard in "Breakdown by type" table.
E.g., instead of `bad_bcd_links` show "Bad BCD Links".
<details>
<summary>Images</summary>
</details>

On Flaws dashboard, humanize flaw names

---

client/src/document/ingredients/browser-compatibility-table/index.tsx
client/src/document/ingredients/browser-compatibility-table/legend.tsx

Fixes #2444
My fault, when I [worked on PR #1681](https://github.com/mdn/yari/pull/1681) I didn't realize that the legend is dependent on the function that I needed to refactor. 
This PR just makes sure the logic used to list features is the same for the legend as it is for the guts of the main table.

always show legends

---

kumascript/macros/SpecData.json
kumascript/tests/macros/specdata.test.js

1.1 published version is marked as a "NOTE", added versions to the names

fix: ARIA practices entries in SpecData

---

content/document.js
package.json
yarn.lock

The "safe*" methods no longer are prefixed https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md
Fixes #2315

feat: Bump js-yaml to v4

---

kumascript/src/api/util.js
testing/content/files/en-us/web/embeddable/index.html
testing/tests/index.test.js

Fixes #2488
Using the `testing/content/files` as the `CONTENT_ROOT`:

EmbedLiveSample fails if the ID gets changed from the text

---

deployer/src/deployer/search/__init__.py

With this change, I can, in my `kuma` branche search the ES index for non-en-us content and be able to distinguish between actually archived and not actually archived.

be smarter about indexing 'archived' in ES

---

kumascript/macros/CSSSyntax.ejs

Fixes #2096
You can test on http://localhost:3000/en-US/docs/Web/CSS/::-webkit-scrollbar#_flaws
I ran this on all of `web/css/` and it stumbled across 14 of these.

flaw when CSSSyntax macro finds nothing in mdn-data

---

client/src/document/index.scss
kumascript/src/api/web.js
kumascript/tests/index.test.js
testing/tests/index.test.js

Change the class name used for links to pages that do not yet exist from `new` to `page-not-created` and add relevant styling.
fix #2065

fix: add style for links to pages that do not yet exists

---

kumascript/macros/Interwiki.ejs

Only ran across this in one doc in mdn/content for `glossary/node.js`, but it seemed better to allow `Wikipedia` in addition to other possible incorrect casing. Figured there may be others in the translated or archived content

fix: Allow uppercase names for InterWiki

---

package.json
yarn.lock

Following some warnings around webpack when doing the yarn install in the content repo, I went through each of the dependencies and pushed them down if the were only referenced in tests or webpack build files.
Following your principle in https://github.com/mdn/yari/blob/master/docs/npm-packaging.md#as-slim-as-possible

chore: Remove unreferenced dependencies

---

filecheck/checker.js

Fixes #2562
You can test it against some of the files in https://github.com/mdn/content/pull/1368
Or just navigate to a page that has an external image and whose folder the page is in has the `()` characters in the name.

imagemin on filepaths with brackets

---

client/src/document/organisms/toc/index.tsx

Part of #1747
All this does is that it closes the "Jump to section" if you click on any of its links. 
You still get z-index overlay problem. But, this is an incremental improvement. 
I wish the "Jump to section" thing was more like a modal window. That any click outside it should close it.

close "Jump to section" on click

---

client/src/document/ingredients/browser-compatibility-table/atoms/_bc-history.scss
client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
client/src/document/ingredients/browser-compatibility-table/index.tsx
client/src/document/lazy-bcd-table.tsx

Fixes #2163
Now it looks like this:
The old `Compat.ejs` used to rely on `L10n-CompatTable.json` to get some of it strings. When Gregor rewrote how the BCD table works (in React with TypeScript) instead of relying on that file, he just copied the English strings over directly into the TypeScript code. Clearly, I missed one. The one that this PR fixes. It was subtle. 
I think the original intent was to move away from having these `.json` files fo chrome localization that Kumascript used and move to something more modern/sane such as `react-fluent`. Either way, the reason it was never fully implemented was because at the time the BCD table was ported to React, we didn't know what was going to happen with localization. So, instead of just waiting (forever) for a firm decision on that, we …

Compat tables aren't rendering prefixes

---

client/src/document/ingredients/browser-compatibility-table/atoms/_bc-history.scss

Updates the padding for the notes inside BCD tables
note: @peterbe

fix: padding on notes in bcd table

---

client/src/ui/organisms/header/index.scss

Fix stacking order of TOC drop-down and main menu on mobile to ensure the main menu covers the TOC if both are expanded at the same time.
fix #1747

fix: stacking order of main menu and toc

---

package.json
yarn.lock

The others seemed to still be keeping an older version range from being used

chore: Remove unneeded yarn resolution

---

tool/cli.js

When I was reviewing https://github.com/mdn/yari/pull/2545 I stumbled into a bug. That's fine, but to see the full traceback I needed to go into "verbose" mode. I thought I could just add `-v` but that didn't do anything. 
If I had used `--verbose` it worked and I would get the stacktrace printed out. 
As of this change, it's now the same effect to type:
```
yarn tool fix-redirects -v
```
...as:
```
yarn tool fix-redirects --verbose
```

support -v in tools/cli

---

package.json
yarn.lock

Still meets react-script dep of `eslint "^7.11.0"`, but fixes warnings
for other ESLint plugins

chore: Add missing ESLint peerDep

---

build/cli.js
content/document.js

It's not OK to have diff markers in the content

---

kumascript/macros/secureContextGeneric.ejs

The current link within the securecontext macro directs to #Browser_compatibility when the id is in fact lowercase. 
Example: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API#Secure_context

Update securecontext macro: Fix link to browser compatibility

---

build/flaws.js
testing/content/files/en-us/web/not_lowercase_anchors/index.html
testing/tests/index.test.js

Fixes #2524
Basically, anything like:
```
<a href="#Foo">
<a href="/en-US/docs/Web#Capital">
```
is now considered a flaw. They're always fixable. 
Most easily seen on http://localhost:3000/en-US/docs/web/not_lowercase_anchors#_flaws

not lowercase anchor links is a flaw

---

.github/dependabot.yml

Related docs https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#ignore

chore: Ignore ESLint/Webpack dependabots

---

build/flaws.js

Fixes #2659
Fixes #2643
The time it took me to tinker with the problem in https://github.com/mdn/content/pull/1587 was enough to have a bunch of code that is worth keeping. 
Now, it will download the image with the **correct file extension** independent of the URL. 
But also, there's an interesting chance here to validate the image before downloading it. If it's not going to work, it's good to elevate that explicitly. This will prevent you from thinking the fixable flaw thing worked, just to eventually fail in the PR CI. 
I copied the HTML from the above-mentioned PR and confirmed that it's a fixable flaw:
(pun intended that I used the `Glossary/PNG` page)
After running the fixable flaws:

Download external images with the extension that it really is

---

.eslintrc.js
build/git-history.js
kumascript/src/api/wiki.js
kumascript/tests/macros/Compat.test.js
kumascript/tests/macros/jsxref.test.js

Recently during a review @peterbe mentioned that MDN avoids multi-variable declarations. (I was not aware of this at the time.) This PR adds [`one-var`](https://eslint.org/docs/rules/one-var) Eslint rule to enforce this convention.
For example, instead of this:
```
let a, b;
```
contributors should write this:
```
let a;
let b;
```
This rule is automatically fixable by Eslint, so it will never cause trouble even for the most novice contributors.
I created this PR just by adding a line to `.eslintrc.js` and running Eslint with `--fix`. Eslint did the rest automatically!

Chore: add eslint one-var rule

---

content/redirect.js

- fixes: `yarn tool test-redirects '/en-US/docs/%3cimg%3e'`
- and switches to first resolve fundamental then _redirects.txt

resolve like prod

---

libs/fundamental-redirects/index.js
testing/tests/redirects.test.js

Part of #2697
@fiji-flo I'm not sure what I'm doing with the fundamental redirects. This is my first ever attempt in there. 
But I'm not looking for perfection here. There are no active links (except those 2 in the obscure Firefox 3.5 release docs) to these so if we get some not perfectly, I'm not that bothered. 
But being able to not have to S3 upload 1,246 redirects every day feels like a win for the planet.

Make Core_JavaScript_1.5 a fundamental redirect

---

kumascript/macros/InterfaceData.json
kumascript/macros/SpecData.json

Adds: https://wicg.github.io/element-timing and the inheritance data for the `PerformanceElementTiming` interface.

Adding Element Timing spec

---

deployer/src/deployer/main.py
deployer/src/deployer/search/__init__.py
deployer/src/deployer/search/models.py

Fixes #7752
Basically, now http://localhost.org:8000/en-US/search?q=Array+foreach works as expected. And I wrote a little CLI debugging tool to better understand how the token filters end up. For example:
```
▶ DEPLOYER_ELASTICSEARCH_URL=localhost:9200 poetry run deployer search-analyze  'Array.prototype.forEach'
token         'array.prototype.foreach'
start_offset  0
end_offset    23
type          '<ALPHANUM>'
position      0
token         'array'
start_offset  0
end_offset    5
type          '<ALPHANUM>'
position      0
token         'prototype'
start_offset  6
end_offset    15
type          '<ALPHANUM>'
position      1
token         'foreach'
start_offset  16
end_offset    23
type          '<ALPHANUM>'
position      2
```
This now means it'll break up that into:
- …

bad es indexing when with dots

---

.editorconfig

Copied from original version in mdn/content and added Python config

chore: Add EditorConfig for whitespace

---

ssr/render.js

use ...args, not arguments

---

client/src/document/ingredients/browser-compatibility-table/atoms/_bc-icons.scss

Fixes #2630
Brings 6px down to 5px for `margin-left` and introduces a `margin-right` of 4px. This seems to provide a much more centered alignment when the star icon wraps to the next line in bc tables, while maintaining space between value and icon when side-by-side.

Update margins for star-icon in bc tables to provide better alignment

---

Procfile.dev
package.json
ssr/render.js
ssr/webpack.config.js
yarn.lock

**UPDATE**
I've sneakily added something that makes sense now. This way, as part of running `yarn dev` it will also start `yarn watch:ssr` and I've added `ssr/dist/` to the list of things that `nodeman` watches over for doing Express restarts. 
The net effect is simply; you make a change in `ssr/index.js` or `ssr/render.js` and now the effect takes place simply by reloading the browsers at localhost:5000. Before, it used to be that you kill it and run `yarn dev` all over again for every little change to the `ssr/*.js` files. 
Before:
After:
This also removes the need for the `CleanWebpackPlugin` plugin because there's virtually no chance of that directory filling up with junk.

optimize the ssr bundling

---

build/cli.js
build/index.js

Fixes #2766
At first I realized I just need to move those lines `document.noIndexing = ...` so that they appear any time *before* the `renderDocHTML()` which does the actual React SSR part. But then I realized that the stuff in `buildDocuments()` is basically just a wrapper around `buildDocument()` but with the act of writing files to disk. 
By moving it inside the `buildDocument()` function instead, it means that this stuff works when testing from the server. 
Now view-source:http://localhost:5000/en-us/docs/mdn/kitchensink works as expected.

noIndexing should be reflected in robots meta tag

---

build/document-extractor.js
testing/archived-content/files/en-us/busted_bcd_rendering/index.html
testing/archived-content/files/en-us/busted_bcd_rendering/wikihistory.json

Fixes #2785
Now http://localhost:3000/ar/docs/web/api/navigator.battery works. It didn't before. This is just the first one that would trip it up. Nothing special about that page. 
The fix took a lot longer than it might appear when looking at the PR diff. 
All of this would have entirely been impossible to even happen if we had proper typing in JS. If we had return types on the functions, something like TS would have caught this immediately. :(
Mixed emotions about that. 
I'm confident this unbreaks the complete builds. I'll add an end-to-end test that makes sure that section of the document extractor gets walked. The tests don't need to assert much but it would be nice to include a fixture page that would have at least broken in CI when I worked on https://github.com/mdn/yari/pull/2752

Error in section types in translated-content

---

client/src/ui/molecules/breadcrumbs/index.scss

Part of #2791
I suspect it happened because we're not running `stylelint` in Yari. Only in mdn-minimalist.

remove @include highlighted-link-state()

---

kumascript/tests/macros/utils.js

Changed behaviour to match comment block. Since it's for testing the "first" result might be enough and just suppressed though

fix: ESlint no-unreachable-loop

---

server/document-watch.worker.js

Fixes #2733
Fixes #2732
@hamishwillee If you have the time, do you think you can test this?
You'd have to have a git checkout of this branch of mine of the `yari` repo. You can't test this from the `mdn/content` repo yet. 
I don't have access to Windows to test, but I'm fairly confident it will work. But your functional test-blessing would be great.

glob in Windows breaks document-watch

---

build/flaws.js
build/index.js
client/src/document/toolbar/flaws.tsx
testing/content/files/en-us/web/fixable_flaws/deprecated_macros/index.html
testing/tests/destructive.test.js
testing/tests/index.test.js

MacroDeprecatedError should be fixable

---

kumascript/macros/EmbedLiveSample.ejs
kumascript/tests/macros/EmbedLiveSample.test.js

Fixes #2683
This depends on https://github.com/mdn/mdn-minimalist/pull/479
To test this PR in Yari you can simply open `node_modules/@mdn/minimalist/sass/atoms/_examples.scss` and remove the `height` line and visit a bunch of pages that used `EmbedLiveSample`. I think they all look sane now.

min height in EmbedLiveSample iframes

---

testing/tests/sitesearch.test.js

The sitesearch headless tests are fragile as they depend on the timing of the lazy-loaded assets. 
As soon as the [site-search PR](https://github.com/mdn/yari/pull/1473) had been merged, it [failed in CI on `master`](https://github.com/mdn/yari/runs/1863028438?check_suite_focus=true)
This PR fixes the only places where it too prematurely checks that the page URL had changed.

force a slight wait after site-search form submission

---

client/src/document/organisms/toc/index.tsx

Reword the heading from "Jump to section" to "Table of contents"
fix #2874

fix: change jump to section to table of contents

---

deployer/src/deployer/constants.py
deployer/src/deployer/main.py

Fixes #2879
Note that, thankfully, this doesn't even touch the `upload.py` code. Just a matter of that list `content_roots`. I tested it like this:
```
poetry run deployer upload ../client/build --no-progressbar --content-root=/Users/peterbe/dev/MOZILLA/MDN/content/files --content-translated-root=/Users/peterbe/dev/MOZILLA/MDN/translated-content/files --content-archived-root=/Users/peterbe/dev/MOZILLA/MDN/archived-content/files | tee /tmp/output.log
```
But before I ran it I replaced the `bucket_manager.client.upload_file(...` and `bucket_manager.client.put_object(...` with a temporary `pass` just so I can pretend that I actually uploaded. 
The summary said:
```
Total uploaded redirects: 43,989
```
On a regular [Prod build](https://github.com/mdn/yari/runs/1867543782?check_suite_focus=true …

Deploy redirects from the archived content

---

client/src/page-not-found/fallback-link.tsx
client/src/page-not-found/index.tsx

Part of #2877
You can trigger that stuff by opening http://localhost:5000/sv-SE/_404/Web/JavaScript/Guide/Introduction which will 
trigger a lazy-load chunk. 
All I really did was to extract a bunch of code from the `index.tsx` and put it into `fallback-link.tsx`. Then, I also refactored some `React` imports so it's using `React. useEffect(` instead of `useEffect`.

make page-not-found more lazy loading

---

deployer/aws-lambda/content-origin-response/index.js

Part of #2884
This partially addresses #2884, but needs to be added to the proper Cloudfront (CF) behaviors on `dev` and `prod` to fully address #2884. It has already been added to the CF behaviors on `stage` for testing (and the `stage` CF cache has been invalidated).

restore some security-related headers

---

kumascript/macros/SpecData.json

Cascading and Inheritance is now a W3C Recommendation: https://www.w3.org/TR/2021/REC-css-cascade-3-20210211/
Updating specdata.

CSS Cascading and inheritance to REC

---

deployer/src/deployer/upload.py

I failed to test https://github.com/mdn/yari/pull/2914/files because my OS doesn't get it wrong, unlike the Ubuntu we use in GHA.

unbreak font content-type hack

---

kumascript/macros/jsxref.ejs

In the [`Expressions and operators`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators) page, the [`new.target`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target) and [`import.meta`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta) references aren't linked properly due to the escaped dot in the URL not getting unescaped
This PR fixes the linking issue by trying to unescape the URI before sending it to `web.smartLink`

Fix: Decode string before using it

---

client/src/document/ingredients/browser-compatibility-table/feature-row.tsx

Follow-up to https://github.com/mdn/yari/pull/2892 which will make this problem more visible but you can already see it here:
https://developer.mozilla.org/en-US/docs/Web/API/Window/customElements
If you expand, you find historic support and these have removal versions and should appear red. They don't currently. 
I believe the function calls the wrong data.
Here's how it should look like:

Fix compat data used for determining cell color in notes

---

docs/npm-packaging.md

Found one more change related to the switch from `master` to `main`.

fix yari link to use main branch

---

README.md

The `Listen` repository has moved all its wiki content to the readme file. 
This PR updates the link from wiki page to the related section in readme

Fix broken link to the wiki of Listen repository

---

client/src/ga-context.tsx

This was a leftover from the days when we [added Google Analytics to yari](https://github.com/mdn/yari/commit/369a95e0d8bd845642eb3d8f0ee5c4b44bb13b7d).
If someone really needs to debug this, they can add it in the day they're hacking on it.

remove ga.send() debugging

---

build/index.js
server/document-watch.worker.js
server/index.js
testing/archived-content/files/en-us/xul/index.html

Fixes #2976
Suppose that you mess with the slug and change it to something that doesn't match its folder name. 
For example, I edited the `content/files/mdn/kitchensink/index.html` front-matter and changed the `slug` value. Now opening http://localhost:3000/en-US/docs/MDN/Kitchensink you get a nice descriptive error. 
Also, 
```
yarn build /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/mdn/kitchensink/index.html
```
(still) fails but now with much better error message.

document-watch worker and finding files

---

tool/cli.js

I've wanted and needed this for too long and I often have to mess around to get it to work. 
Now I can type `BUILD_FOLDERSEARCH=bla/bla yarn build` and take any of the lines it spits and out then do something like:
```
▶ yarn tool preview /Users/peterbe/dev/MOZILLA/MDN/yari/client/build/en-us/docs/web/css/_colon_focus-visible -p 3000
```

make 'tool preview' take a built folder argument

---

deployer/src/deployer/search/__init__.py
deployer/src/deployer/search/models.py

Fixes #3004
Now:
```
▶ DEPLOYER_ELASTICSEARCH_URL=localhost:9200 poetry run deployer search-analyze "<a> <video>"
token         '_a_'
start_offset  0
end_offset    3
type          '<ALPHANUM>'
position      0
token         '_video_'
start_offset  4
end_offset    11
type          '<ALPHANUM>'
position      1
token         'video'
start_offset  5
end_offset    10
type          '<ALPHANUM>'
position      1
```
Here are the results:
The way Elasticsearch works is that you define your token filters and your char filters. Now both indexing and searching goes through the same path. So
```
<video> =indexing=> ['_video_', 'video']
<video> =searching=> ['_video_', 'video']
video =searching=> ['video']
```

Search for <a>

---

libs/fundamental-redirects/index.js
testing/integration/headless/map_301.py
testing/integration/headless/test_redirects.py
testing/tests/redirects.test.js

This PR arose from https://github.com/mdn/yari/issues/3012#issuecomment-783722097, but it's only one of two reasons why the DOM redirects didn't work:
1. The first reason was because the behaviors for the `dev`, `stage`, and `prod` CDN's hadn't been updated with the latest Lambda@Edge function which included the new `@yari-internal/fundamental-redirects` package.
2. The second reason (and the reason for this PR) was that https://github.com/mdn/yari/pull/2872 was broken. For example, it would redirect `/en-US/DOM/element.addEventListener` to `/en-US/docs/DOMelement.addEventListener` instead of the correct `/en-US/docs/DOM/element.addEventListener`.
This PR fixes the second, and once it lands, needs to be deployed to the CDN's to take effect.
Adding both @fiji-flo and @peterbe just so …

fix DOM fundamental redirects

---

server/index.js

Remember, this is only used in local development so I don't mind the proxy timeout being quite long. 
You can still get a 504 Bad Gateway when you refresh your Yari page whilst your `docker-compose up` is restarting. But it's just a lot more patient now.

add a proxyTimeout to the http-proxy-middleware

---

build/flaws.js

As of this change, I was able to build ALL translated content using the uplift branch. ...with the default flaw levels.

heading links flaws and id-less headings

---

testing/tests/headless.test.js

Headless end-to-end test should test switching language

---

deployer/src/deployer/search/models.py

Fixes #3074
Fixes #3070
Here's what you get now:
As you can see, some of the "rest results", pages beyond the 1st hit are a bit off. But who looks beyond the first search result these days?
I don't know how long this whack-a-mole race is going to go for, but I think it makes us look professional to support these kinds of things. This kind of detail-work is why it's good to own search. Had we gone for something shrink-wrapped (aka. Saas) we probably would be unable to solve things like this.

respect character unicorns

---

build/index.js
build/translations.js
server/index.js

Try by setting the `CONTENT_TRANSLATED_ROOT` and then `yarn dev` and then visit a page like
http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment 
Yes, since the `memoization` is switched off in local dev, we have to do ~30 attempts to `fs.readFile` but it's so incredibly fast that you don't notice anyway. It's just one document at a time so it doesn't need to be optimized.

link translations when doing local dev

---

build/feedparser.js

HTML escaping in feed titles

---

server/document-watch.js

Part of #3091
Here's how I tested this...
I have `yarn dev` running in one terminal. And any file that `nodemon` watches open in my IDE. 
In another terminal I'm ready to run:
```
▶ run-forever.sh  time curl -I http://localhost:5000/en-US/search-index.json
```
[run-forever.sh](https://www.peterbe.com/plog/run-forever.sh)
Now, hit save in and watch `nodemon` restart which will trigger a new search index crawl. E.g. 
```
4:31:12 PM server.1     |  Populate search-index: 5.041s
4:31:12 PM server.1     |  Populated search-index found 11,669 files.
```
By the way, it's fun that in this particular copy of the server outputs it clocked in at `5.041s` which is unusual. But perhaps my computer was busy at the moment. 
But `curl` is just a way to simulate the fix. What's more likely, and I've …

add internal retries to the search-index handler

---

build/spas.js

Before:
(part of `yarn prepare-build`)
After:

quiet down spa creation tool

---

deployer/src/deployer/main.py
deployer/src/deployer/upload.py

I need this when doing PR builds because then redirects are not useful at all. And it takes quite a long time to upload all 12k redirects when it's all in vain. 
Also, as you know Ryan, last week I didn't notice that I had `--dry-run` set and I was desperately trying to figure out why no uploads happened. So I make the `info.log()` lines aware that it might be a dry-run mode. 
```
▶ poetry run deployer --dry-run upload --content-root=/Users/peterbe/dev/MOZILLA/MDN/content/files --no-redirects --bucket=peterbe-yari /Users/peterbe/dev/MOZILLA/MDN/content/build
Deployer (0.3.0)
Upload files from: /Users/peterbe/dev/MOZILLA/MDN/content/build
Upload into: main/ of peterbe-yari
Not going to upload any redirects
Total pending file uploads: 124 (3.7ms)
Total existing S3 objects: 52,065 (45.2s)
No …
```

skip uploading of redirects

---

deployer/src/deployer/search/models.py

There are more operators (e.g. `Unsigned right shift assignment (>>>=)`). I picked through the ones that aren't too obscure or ones that could cause confusion. For example, the `in` operator turns up in too many titles and bodies as a regular stopword so it's probably best to leave it alone. 
This'll cover a bunch of more typical ones. 
Some examples:

support more search operators

---

testing/tests/headless.test.js

Fixes #3116
Prior to this change I would run `yarn test:testing headless` and sometimes it would break with:
```
node:internal/process/promises:218
triggerUncaughtException(err, true /* fromPromise */);
^
Error: Navigation failed because browser has disconnected!
at CDPSession.<anonymous> (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/puppeteer/lib/LifecycleWatcher.js:46:107)
at CDPSession.emit (node:events:329:20)
at CDPSession._onClosed (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/puppeteer/lib/Connection.js:215:10)
at Connection._onMessage (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/puppeteer/lib/Connection.js:105:17)
at WebSocket.<anonymous> (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
at WebSocket.onMessage …
```

don't wait for networkidle2 unless a reason to

---

deployer/src/deployer/search/__init__.py
deployer/src/deployer/search/models.py

Fixes #3113
Can't argue with the results:
The reason the `Using Fetch` document turns up there is because that page has such a high popularity that simply matching the start of the word gives it a tiny matchness and combined with its popularity it comes up pretty high. 
But the most important thing is the first search result which is what people expect.

search for function*

---

kumascript/macros/L10n-JavaScript.json
kumascript/macros/jsxref.ejs

There's no point anymore in trying to localize the slugs since there are no more localized slugs.

jsxref shouldn't localize slugs

---

build/check-images.js

Bad warning when an `img` lacks a `src`

---

client/src/document/on-github.tsx

Fixes #3166
Not only did I change `needs triage` to `needs-triage` but I also noticed that all the labels prefixed with `Content:` are spelled without a space after the `:`. So I fixed that too. 
Also, I learned the hard way that if you have multiple `labels` you need to make it a comma-separated list. E.g. 
```diff
-&labels=foo&labels=bar
+&labels=foo,bar
```
I don't know how long that's been busted. 
Seems to work now:

needs-triage label for new content issues

---

build/flaws.js

Fixes #3072
```
▶ curl -I https://www.w3.org/TR/2017/WD-css-timing-1-20170221/step-timing-func-examples.svg
HTTP/2 200
...
content-type: image/svg+xml; qs=0.85
```
Thanks to this fix I was able to fix the external images flaws in https://github.com/mdn/content/pull/2982

cope with odd svg content-types

---

.github/workflows/developing.yml
client/src/writers-homepage/index.tsx
testing/tests/developing.test.js

I'm killing two birds with one stone here. 
First of all, it doesn't have to be extensive (and opening is better than doing nothing) but at least this checks that the Flaws Dashboard is there and that it can be opened. 
Second of all, I like this use of `if: failure()` instead of a hacky `bash` trick looking for exit codes.

test Flaws dashboard in CI

---

kumascript/macros/GroupData.json
kumascript/macros/InterfaceData.json

Mixin work is so thankless. Really.
I forgot to remove mixin pages from the infamous InterfaceData and GroupData macros.
This is what is happening: Mixin pages are made redirects to some sensible real interface pages like Element. 
Great for readers because they'll land somewhere, but these lovely macros still make calls to get the sub pages and so they can be rendered twice (once from Element, and also from e.g. NonDocumentTypeChildNode which is now a redirect to Element.)
I'll add this to my mixin checklist, so it doesn't happen again.
Closes https://github.com/mdn/yari/issues/3119

Remove mixins that have been removed from MDN content

---

.github/workflows/npm-published-simulation.yml

check out mdn/content after 'npm pack'

---

build/check-images.js
build/index.js
testing/translated-content/files/fr/web/foo/index.html

Part of #3174
This is just one of the cases. But it's an important one, to start with. 
Imagine there's an `en-US` page that contains `<img src="foo.png">` in that English page and that works (and that there exists a `foo.png` next to that English `index.html`). Now you copy that page to `translated-content/files/fr/*`. The page should work. No flaw. And the final `cheerio` transformation, for both the `en-US` and the `fr` page, should become: `/en-US/docs/Foo/bar/foo.png`. 
Perhaps a better way to explain it is to look at the test fixtures. We have, in English:
```html
<figure>
<figcaption>A perfectly normal image</figcaption>
</figure>
```
and on the `fr` equivalent we have:
```html
<figure>
<figcaption>Une image parfaitement normale</figcaption>
</figure>
```
What you get in the end …

Image flaw checking should be different for translated content

---

client/src/document/ingredients/browser-compatibility-table/legend.tsx
kumascript/macros/SpecData.json

Suggested change to legend used for non-standard track features from 
```
"non-standard": "Non-standard. Expect poor cross-browser support.",
```
to
```
"non-standard": "Non-standard. Check cross-browser support before using.",
```
This comes from discussion here: https://github.com/mdn/browser-compat-data/pull/8785#issuecomment-793650145 which says that while expecting poor cross browser support is probably correct in most cases the actual support data should tell readers whether they should expect cross-browser support.
We could reduce this further to "Non-standard." but I think it is a good hint that they check the support rather than expect poor support.

Improve legend for non-standard track features

---

client/public/index.html
client/src/document/index.scss
client/src/document/index.tsx
client/src/document/organisms/metadata/index.scss
client/src/site-search/index.scss
client/src/site-search/index.tsx
client/src/site-search/search-results.scss
client/src/site-search/search-results.tsx

Fixes underlines and colors of links in main page content.
Fix #2901

fix: links in article content

---

.gitignore

Otherwise, you'll get that `testing/translated-content/files/fr/_githistory.json` file too after running the end-to-end test suite.

ignore translated-content/**/_githistory.json too

---

libs/fundamental-redirects/index.js
testing/integration/headless/map_301.py

Fixes #3199
I didn't test it but it looks sufficiently safe.

add fundamental redirects for /en-US/Security/CSP

---

content/document.js
kumascript/index.js
tool/cli.js

Adds a new `yarn tool macros` command to either `render` or `remove` one or more macros from a tree of documents.

add tool command for rendering/removing macros

---

build/index.js
client/src/document/organisms/metadata/index.tsx
content/constants.js
content/document.js
libs/constants/index.js

only show "onGithub" for active locales

add active locales

---

build/check-images.js
build/flaws.js

Fixes #3174
Seems to work! I was able to create https://github.com/mdn/translated-content/pull/110 with this change. 
And just to check that then `en-US` fixable external image flaws still work, I was able to create https://github.com/mdn/content/pull/3040
It almost seemed too good to be true. 
The assumption this is based on is that the basename of the external image URL would match perfectly the en-US equivalent. 
I think it's a safe assumption. It COULD be that someone has a "localized image" which they uploaded under a different ID but with the exact same basename. I find that unlikely enough to not care. 
I've noticed that in `fr` there are a lot of images that are genuinely different. For example `choix-firefox.png` was one I found. In these cases, if a `fr` translator downloads it, …

downloading external images for translated-content

---

build/flaws.js
testing/content/files/en-us/web/unsafe_html/index.html
testing/tests/index.test.js

Fixes #3215
It looks like this now:
Contrast that with: https://github.com/mdn/content/pull/3064/checks?check_run_id=2095600358

skip empty srcs for safe iframe srcs

---

kumascript/macros/CSSSyntax.ejs

https://developer.mozilla.org/de/docs/Web/CSS/border#formale_syntax 
vs 
https://developer.mozilla.org/en-US/docs/Web/CSS/border#formal_syntax
I think also we should avoid marcos inside `<pre>` in general.

generate pre in CSSSyntax

---

filecheck/checker.js
testing/tests/filecheck.test.js
testing/tests/samplefiles/index.html
testing/tests/samplefiles/onhandler.svg
testing/tests/samplefiles/script.svg

Fixes #3249
First of all, I don't know why CI wasn't running on https://github.com/mdn/content/pull/3162
What's up with that?!
Anyway, based on the file in [that PR](https://github.com/mdn/content/pull/3162/files), it does correctly throw:
```
MOZILLA/MDN/yari  3249-check-of-unsafe-html-in-svg-files ✔
▶ yarn filecheck /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/mozilla/developer_guide/development_process_overview/workflow.svg
$ cd filecheck && node cli.js /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/mozilla/developer_guide/development_process_overview/workflow.svg
Error: /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/mozilla/developer_guide/development_process_overview/workflow.svg <svg> contains an unsafe attribute key: 'onload'
at Node.<anonymous> …
```

Check of unsafe HTML in SVG files

---

kumascript/macros/SpecData.json

The [CSS Cascading and Inheritance Level 5 specification](https://www.w3.org/TR/css-cascade-5/) got published as Working Draft earlier this year. Therefore, I've added it to the SpecData macro.

Added CSS Cascade Level 5 spec. to SpecData macro

---

.github/workflows/prod-build.yml
.github/workflows/stage-build.yml

Part of #3229
I've never done this before so I'm not 100% certain it's correct. 
There are also certain actions that run on pushes to `main`. For example, if people merge in the latest `main` from `mdn/yari` and then push that to their fork, that'll trigger a build too. E.g. https://github.com/escattone/yari/commits/main
Perhaps @escattone has, manually, disabled Actions on his fork because I don't see the little green checkmarks.

only run scheduled workflows on mdn/yari

---

build/flaws.js
kumascript/src/api/web.js
testing/tests/index.test.js
testing/translated-content/files/fr/web/foo/index.html

Fixes #3104
Take http://localhost:3000/bg/docs/Web for example. 
Compare it with https://developer.mozilla.org/bg/docs/Web
There are lots of broken links on that page (in Prod). And a lot of them are really broken because when you click on one of them (e.g. https://developer.mozilla.org/bg/docs/Web/Apps) you get a 404 Page not found, but *without* that helpful "Good news!" (green) message that it's available in English. That's because that Belarusian link is so broken and old that it doesn't check for redirects. 
Now it becomes this:
```html
<a href="/en-US/docs/Web/Progressive_web_apps" class="only-in-en-us" 
title="Currently only available in English" data-flaw="link14">Разработка на уеб приложения (en-US)</a>
```

Broken link checkers should fallback to en-US if possible

---

build/cli.js
content/document.js

Fixes #3253
It's not gorgeous, but it'll work better since it's now only printing that stuff in the CLI. Once.

Stop saying "Building roots:" twice

---

kumascript/macros/SpecData.json

We now have a CSS Color Level 5 https://drafts.csswg.org/css-color-5/
Adding it to SpecData.

adds Level 5 Color Spec

---

kumascript/macros/CompatibilityTable.ejs

Fixes #3269
http://localhost:3000/ru/docs/Web/API/Element/classList#_flaws used to have "Unsafe HTML" flaws. Now it no longer does.

CompatibilityTable.ejs injects HTML that's considered unsafe

---

.github/workflows/dev-build.yml
.github/workflows/stage-build.yml
deployer/src/deployer/main.py
deployer/src/deployer/upload.py

Part of #2224
Here's how I tested it:
1. Run a complete build of all of CONTENT_ROOT and all of CONTENT_TRANSLATED_ROOT
2. Then I ran: `DEPLOYER_LOG_EACH_SUCCESSFUL_UPLOAD=false poetry run deployer upload --content-root=/Users/peterbe/dev/MOZILLA/MDN/content/files --bucket=peterbe-yari --prune --archived-files ../content/archived.txt ../client/build` (this is using my personal AWS account)
3. Now, it should have uploaded all en-us docs, uploaded all archived docs, deleted all translated non-archived docs. 
4. It worked!
For example:

--prune should leave archived S3 keys

---

client/src/app.tsx
client/src/constants.ts
client/src/hooks.ts
client/src/page-not-found/fallback-link.tsx
client/src/ui/molecules/main-menu/index.tsx
server/index.js

Fixes #3224
Fixes #3287
Here's how I tested it, first run `yarn dev` and then use the "production mode" because that's more like how Lambda works. Now, open:
- http://localhost:5000/pagenotfound
- http://localhost:5000/en-US/pagenotfound
- http://localhost:5000/en-US/docs/pagenotfound
- http://localhost:5000/en-US/
- http://localhost:5000/en-US/search/
- http://localhost:5000/en-US/signin/
- http://localhost:3000/en-US/
The most important one is the first one. That's what this PR really fixes. 
What used to happen is that it would render the home page component. I.e. `<Home/>` and within that component, it would think the current locale is `pagenotfound` because it's the first word in the URL. Just like `/en-US` or `/fr`. 
Now, I'm forcing it to render the `<PageNotFound/>` component if …

/pagenotfound is rendering the homepage route

---

client/src/document/index.scss

Add underline on hover and focus for linked headings
Fix #3205

fix: heading underline on hover and focus

---

.github/workflows/stage-build.yml

Now the `diff .github/workflows/prod-build.yml .github/workflows/stage-build.yml` should only mention stuff that actually is and *should* be different across the two files. Otherwise you'd also get a mention of ...
```diff
230c243
<           poetry run deployer upload --prune --archived-files ../content/archived.txt ../client/build
---
>           poetry run deployer upload  --prune --archived-files ../content/archived.txt ../client/build
```

correct spacing for simpler diff

---

deployer/aws-lambda/content-origin-request/index.js
deployer/aws-lambda/content-origin-request/server.test.js

Fixes #3225
Basically, any request for something like `//////whatever` becomes a 302 to `/whatever` and then we'll see what happens next. 
I think this is much better than what we had before. 
For example request for `https://deverloper.m.o//evil.com/` becomes a redirect to `https://deverloper.m.o/evil.com/` which just ends up being a 404 in the end. But a request for `https://developer.m.o//en-US/docs/Web` actually becomes a 302 to `/en-US/docs/Web` which will eventually 200 OK. 
I think it'll have to be a separate issue but check out:
```
▶ curl -I https://developer.mozilla.org/en-US/docs/Web//JavaScript
HTTP/2 301
...
location: /en-US/docs/Web_JavaScript
```
What the heck is `Web_JavaScript`? :)
I think it would be better that `/en-US/docs/Web//JavaScript` becomes a 302 to …

don't even attempt files URIs that start with //

---

client/src/user-context.tsx
server/index.js

Fixes #3319
Now, the `userUserData` hook will return `null` initially (until the `/api/v1/whoami` XHR request has resolved). 
I still think there might a good opportunity to inject a `sessionStorage` cache into that hook which'll almost always resolve faster than the XHR.

Settings page, briefly, says you're not signed in

---

client/src/app.scss
client/src/minimal-prism.scss

Fixes #3279
This incomplete because it's going to require a change to minimalist too. 
In particular, [this line needs to be deleted](https://github.com/mdn/mdn-minimalist/blob/1e2d9294d34a019f44fef10f53e88e732214a6c8/sass/mdn-minimalist.scss#L29).
Now, we're only using the bare essentials for Prism. This actually makes a decent difference. 
When I build the static assets based on this branch, and then compare with what I'd get on the `main` branch, the difference is as follows:
```
▶ ls -ltr main.*
-rw-r--r--  1 peterbe  wheel  50317 Mar 24 22:35 main.optimized.chunk.min.css
-rw-r--r--  1 peterbe  wheel  51600 Mar 24 22:37 main.main.chunk.min.css
```
This new optimized CSS is 1,283 bytes lighter. It's only 238 bytes smaller when you compare the Brotli compressed files but after the …

Get rid of 'pre.language-*`

---

build/spas.js
client/src/settings/index.tsx
testing/tests/headless.test.js
testing/tests/index.test.js

Fixes #3345
It's quite sad that right now the page title is hardcoded in two places. It kinda has to be like that because the React code is compiled into a bundle that the Yari builder can't easily reach.

It's "Account settings" not "Account Settings"

---

client/src/app.scss
client/src/minimal-prism.scss

Merge prismjs overrides from minimalist with minimal-prism in Yari
Fix #3344

fix: merge prism styles from minimalist with minimal-prism

---

.github/workflows/prod-build.yml
.github/workflows/stage-build.yml

Part of #3359
The default behavior is that it wipes the Elasticsearch index and fills it back up again. Recently we've seen lots `ReadTimeoutError` problems. [For example](https://github.com/mdn/yari/runs/2214594218?check_suite_focus=true)
This changes the strategy to instead just update the index. 
The right and full solution is to treat the index "transactionally" by using aliases. Then we don't even need a priority solution.

update search-index till we figure out yari/issues/3359

---

kumascript/macros/InterfaceData.json

This changes in this PR make some macros in MDN work as expected.  Otherwise, the removed items in this PR cause some macros used in MDN to break.

Drop obsolete items from InterfaceData macro

---

client/src/auth/sign-up.tsx

Fixes #3377
This only makes sense once [Kuma starts returning a 400 JSON response](https://github.com/mdn/kuma/pull/7818) instead of  302. 
The explanation for this was that originally the sign-up was always from Yari to Kuma with a HTTP form POST. But then later I realized it's better for Yari to submit the sign-up to Kuma via a POST XHR. But clearly I forget to take care of the error handling when you might have 400 errors. 
We still need to solve https://github.com/mdn/yari/issues/3376 and that's the most important one. This PR (plus the kuma counterpart) is only really about stop hiding the errors if there are errors.

show errors if a 400 on sign-up

---

.github/dependabot.yml

This should reduce [the crazy traffic of `boto3` upgrades](https://github.com/mdn/yari/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+is%3Aclosed+boto3)

calm down the Dependabot upgrades for pip

---

client/src/settings/app.tsx

Fixes #3378
The horrible terrible thing that happened was that if you kept your Web console open you'd see an XHR request to `/api/v1/settings` if you're not yet signed in. Oh nooooos! (sarcasm emoji here)

don't fetch /api/v1/settings till you're authenticated

---

client/src/constants.ts
client/src/site-search/search-results.tsx
docs/debugging-sitesearch.md

I like this approach a lot more than having to set a local environment variable. 
The underlying data is always present in the JSON anyway. E.g. see https://developer.mozilla.org/api/v1/search?q=foreach&locale=en-US
Now, you can just add `&debug` to the end of the URL and you can see these bits without having to view the raw JSON of the XHR request.

make it easier to debug site-search

---

client/src/constants.ts
client/src/document/toolbar/edit-actions.tsx
client/src/document/toolbar/flaws.tsx
client/src/document/toolbar/index.tsx
client/src/sitemap/index.tsx
docs/envvars.md

Now the read-only is determined by the `window.location.hostname` NOT being in the default list of `localhost`, `localhost.org`, or `127.0.0.1`. 
To test this, let's pretend that `localhost.org` (or `127.0.0.1`) is the equivalent of `pr123.dev.content.mozit.cloud`. 
So type this:
```
export REACT_APP_CRUD_MODE_READONLY_HOSTNAMES=localhost
export REACT_APP_CRUD_MODE=true
yarn prepare-build && yarn start:server
```
Now it's like using the Yari preview server from the perspective of the mdn/content repo. 
To got http://localhost.org:5000/en-US/docs/Games/Tutorials#_flaws and http://localhost:5000/en-US/docs/Games/Tutorials#_flaws and compare. 
Or go to http://localhost.org:5000/en-US/_sitemap/Games vs. http://localhost:5000/en-US/_sitemap/Games
Man I'm so thankful for TypeScript for this! It …

read-only crud mode by hostname

---

kumascript/macros/GroupData.json

The page exists - it should be linked.

GroupData.json - Add overview page link for Presentation API

---

kumascript/macros/LearnSidebar.ejs

This PR updates the LearnSidebar.ejs macro to include the Angular tutorials.
The equivalent content PR to add the documents linked to by these new menu items is at https://github.com/mdn/content/pull/3972
I tested both together locally using my branches on the yari and content repos, and the yari dev server. Looks like it works fine.

adding angular docs to the learning area sidebar

---

build/document-extractor.js

Noticed while I was poking around testing #2966 that entries with additional flagged versions didn't have a release date tooltip. After some digging, I tracked that down to the code that adds in the release date in the first place, which did not account for [support statements with multiple entries](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#the-support_statement-object) (for example, a version with flags or a prefix and then a version with full support), so these entries did not have a release date entry in the support data, and thus no tooltip in the compatibility table.
This PR extends the release date population so that it annotates the release date for all versions in an `array_support_statement`. Happy to get feedback on code structure, the …

Add release date for support statements with multiple versions

---

kumascript/macros/L10n-SVG.json
kumascript/macros/SVGData.json
kumascript/macros/svginfo.ejs

Per https://svgwg.org/svg2-draft/text.html#elementdef-text the permitted content for the SVG `<text>` element includes “text content child elements” — not “text content elements” (which is something different).
Fixes https://github.com/mdn/content/issues/3882
This change also makes a change to the `svginfo` macro to cause it to use all-lowercase for the link anchors it generates (rather than initial cap).

Fix SVG <text> “Permitted content”

---

client/src/document/ingredients/browser-compatibility-table/feature-row.tsx

Fixes https://github.com/mdn/yari/issues/3238. 
BCD has version ranges to signal that the exact support version is unknown still. This is useful for data maintenance and data improvements but displaying the "≤" hint to readers on MDN compat tables has lead to confusion and the tooltip we've provided didn't really help with that either (apparently). So, let's not expose this to readers at all.

Treat BCD ranges as exact versions to avoid confusion for the reader

---

build/flaws.js
testing/content/files/en-us/web/homepage_links/index.html
testing/tests/index.test.js

/en-US/ isn't a broken link

---

kumascript/index.js
kumascript/macros/Compat.ejs

Fixes #3258
In principle, this was an easy fix. Now I can make this change in the content:
```diff
diff --git a/files/en-us/web/api/headers/index.html b/files/en-us/web/api/headers/index.html
index d7e613f48..72eeaf9b3 100644
--- a/files/en-us/web/api/headers/index.html
+++ b/files/en-us/web/api/headers/index.html
@@ -9,6 +9,7 @@ tags:
- Headers
- Interface
- Reference
+browser-compat: api.Headers
---
<div>{{APIRef("Fetch API")}}</div>
@@ -118,7 +119,7 @@ myHeaders.get('Content-Type') // should return 'text/xml'
<h2 id="Browser_compatibility">Browser compatibility</h2>
-<p>{{Compat("api.Headers")}}</p>
+<p>{{Compat}}</p>
<h2 id="See_also">See also</h2>
```
and it works! It works because now any key in the front-matter becomes available in that `env` object you get inside the context of KS …

make all front-matter available in KS rendering

---

client/src/site-search/search-results.tsx
docs/experiments/0001_site-search-x-cache.md

Part of #3420
This isn't a ground-breaking piece of experimentation, but it's the first and an attempt to try to get structured and organized about experimentations. 
Please review the "structure" as much (if not more!) as the code. 
My intention here is to demonstrate that every experiment (which measurements is a subset of) should have its own `docs/experiments/*.md` file with those headings. 
We mustn't go crazy with this but what matters to me is that there *exists a record* and that an *end date* is picked. That means that if you find the code beyond the experimentation "Due date" you can just delete it without having to worry about "Is somebody still measuring and looking at it? Hello?!"
What do you think @schalkneethling and @escattone ?
Reminder how to test this:
Set:
``` …
```

Intention to measure: Find out the x-cache values in site-searches

---

deployer/aws-lambda/content-origin-request/index.js
deployer/aws-lambda/content-origin-request/server.test.js

Fixes #3425
This certainly seems to solve the problem. To test, use:
```
cd deployer/aws-lambda/content-origin-request
yarn serve
curl -I http://localhost:7000/search\?q=text%2Dshadow
```

don't double-encode the query string when redirecting

---

build/flaws.js
content/document.js
testing/content/files/en-us/web/homepage_links/index.html

Fixes #3515
Steps to test, 
Go to http://localhost:3000/en-US/docs/Web/API/DirectoryReaderSync before this patch
But to really mess with it, create an empty file called `index.html` (or a directory!) in the `files` directory of your `$CONTENT_ROOT`. 
Basically, doing `Document.findByURL('/')` doesn't make sense. It'll never be a document. `Document.findByURL('/en-US/')` doesn't make sense either. 
Our `broken_links` flaw detection already [knows to treat links to the home page differently](https://github.com/mdn/yari/pull/3507) and not expect them to lead to a document. But clearly it was buggy in that it wouldn't treat the URL as bare. That's what this fixes.

don't broken_links check home page urls with hash

---

content/translations.js

I know it's slow but I'd like to understand it more. We do other measurements like this that stem from the `yarn build` CLI.

always measure how long gatherTranslations() takes

---

deployer/src/deployer/main.py
deployer/src/deployer/upload.py

Fixes #3516
If we land this, we can change [this line](https://github.com/mdn/content/blob/2c6f017de416f5817a109191417d549c60e90055/.github/workflows/pr-review-companion.yml#L102) to add `--default-cache-control 0`

Ability to control default cache-control in Deployer uploads

---

kumascript/macros/Glossary.ejs

The current Glossary macro doesn't change locale part of URL to translation locale .
Example; 
http://localhost:5000/ja/docs/Web/HTTP/Headers
The first of link list, https://developer.mozilla.org/en-US/docs/Glossary/General_header, should be https://developer.mozilla.org/ja/docs/Glossary/General_header.
In the current Glossary macro, page.translations loop doesn't work, but  if translation doesn't exist,  the page not found page displays en-US page URL, so I removed this loop and changed to use $env.locale to make URL as other macros.

fix locale part in Glossaly macro

---

client/src/document/index.scss

Fixes #3260
Here's a regular `iframe`:

Live samples should have a border

---

build/flaws/unsafe-html.js
testing/content/files/en-us/web/unsafe_html/index.html
testing/tests/index.test.js

It's hard to conceive what could be done without this protection. What if someone makes a content PR that looks harmless but sneaks in some really carefully crafted CSS that makes the page look like something it isn't. Or, what if they use something clever like `*{background-image: url('/api/v1/subscriptions')}`. 
Also, beyond security, I can't imagine a sensible reason why we should allow the content to dictate style at all. That would just make the Markdown effort even harder and weirder.

consider <style> to be unsafe

---

build/flaws/broken-links.js
testing/content/files/en-us/web/brokenlinks/index.html
testing/tests/index.test.js

Fixes #3565
This will increase the number of `broken_link` flaws quite a bit. To find out exactly how many, I ran `BUILD_FLAW_LEVELS="*:ignore, broken_links: warn" yarn build` before and after. 
- Before: 1,560
- After: 2,190
I'm working in producing a complete report of all of these. When I did the build, I recorded every known `http://` link we have and now we can post-process that.

http links should be considered a flaw

---

client/src/app.tsx
client/src/constants.ts
docs/envvars.md

Fixes #3646
Now it's only visible in local development (e.g. <http://localhost:3000>) and if you want to test it in a production-like environment you can run:
```
export REACT_APP_ENABLE_MDNPLUSPLUS=true
yarn prepare-build
yarn start:static-server
```
Now you get the MDN++ app on (e.g. <http://localhost:5000>)

MDN++ iframe visibility

---

.github/dependabot.yml

Because we reached the limit and it was causing a problem.

More concurrent open npm PRs

---

client/src/document/forms/form.tsx
package.json
yarn.lock

supersedes #3441
use-debounce changed its return value so there was some manual migration necessary.

build(deps-dev): bump & migrate use-debounce to 6.0.0

---

build/spas.js
client/public/index.html
ssr/render.js
testing/tests/index.test.js

Part of #3590
This adds `<meta property="og:title" content="...">`, `<meta property="og:url" content="...">`, and `<meta property="og:description" content="...">`
It [seems that](https://github.com/mdn/yari/issues/3590) Twitter won't display MDN URLs nicely unless you have the `twitter` card HTML meta tags or Open Graph HTML meta tags. 
Thankfully, it seems that Twitter will fall back to Open Graph if Twitter card tags don't exist.

add Open Graph HTML meta tags

---

build/flaws/broken-links.js
client/src/document/toolbar/flaws.tsx
testing/content/files/en-us/web/brokenlinks/broken_http_link/index.html
testing/tests/index.test.js

Fixes #3698
Before... it crashed. 
Now...

invalid external URLs should be considered broken

---

client/src/document/index.scss
client/src/document/index.tsx
client/src/document/molecules/_breadcrumb-locale-container.scss
client/src/document/molecules/_notecards.scss
client/src/document/molecules/localized-content-note/index.scss
client/src/document/molecules/localized-content-note/index.tsx
client/src/ui/molecules/grids/_document-page.scss

Moves notecards into Yari.
Add localized content notes for active and inactive translated content.
Fix #3588

fix: localized content notes

---

client/src/search.tsx

Fixes #3718
Fixes #3695
Let's not move to the autocomplete search widget until this is resolved. 
The change makes sense. I'm just not sure I'm doing the hooks and effects right. Always makes me nervous. 
What can happen is that almost simultaneously (e.g. within less than 100ms) you quickly put the mouse into the search field and you type really fast. Typing triggers the `updateResult()` function (which searches the `searchIndex`) but until the slow XHR request has finished that `searchIndex` will be `null`.
So what this fix does is that it notices if the `updateResult()` was called when `searchIndex` is `null` and then, there's a `useEffect` that waits for the `searchIndex` to become truthy and when it is, it manually forces a call to `updateResult()` again. 
Feels like it makes sense. …

make search execute after search-index comes in

---

server/index.js
testing/tests/headless.test.js

Part of #3642 
Fixes the local development server to properly handle URL's with query strings, likes the ones added when redirecting retired locales.

fix local server to handle retired-locale redirects

---

client/src/document/ingredients/spec-section.tsx

It was a bit naive to think that we will find anchored links for all specification urls.
There are in fact a few features that won't have it, see https://github.com/mdn/browser-compat-data/pull/10353
So, the renderer should check if it is there and only then display the anchor.
The other change is duplicate titles: Sometimes the w3c/browser-specs package uses the same `title` and `shortTitle`. Displaying both looks weird. So, we shouldn't do that. Test case: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#specifications

Spec section: Avoid dupe titles; treat anchors as optional

---

build/document-extractor.js

This was released in https://github.com/w3c/browser-specs/releases/tag/1.37.0
The story is that CSS specifications come in series like 
https://drafts.csswg.org/css-box/
https://drafts.csswg.org/css-box-3/
https://drafts.csswg.org/css-box-4/
We want to match against https://drafts.csswg.org/css-box/ which is stored in `series.nightlyUrl`.
Additional info: https://github.com/w3c/browser-specs/issues/279#issuecomment-832862800

Specs: Look for nightly series spec urls as well

---

deployer/src/deployer/search/__init__.py
deployer/src/deployer/search/models.py

Fixes #3735
Yes, allowing a bunch more stop words can introduce some surprising and not great results but the `title` is always more important and most people only want and care about the first result. In my view, all of the examples [mentioned in the issue](https://github.com/mdn/yari/issues/3735#issue-877766661) now get much better.

custom stop words and split_on_case_change

---

client/src/ui/molecules/search/index.scss

Fixes #3717
But using `.search-results div` to set the padding, it captures not just the `.nothing-found` but also when there's an error loading the search-index (hard to simulate) or whilst there's that yellow text that says "Initializing search index...". 
Also, I took the liberty of making the "Fuzzy searching by URI" smaller so it stands out as less important and not to be confused as a "result".

padding in notifications in auto-complete search

---

build/check-images.js
testing/tests/index.test.js
testing/translated-content/files/zh-tw/web/foo/index.html

Fixes #3786
Demonstrated here:
```js
const DEFAULT_LOCALE = "en-US";
const doc = { locale: "zh-TW" };
const finalSrc = "/zh-Tw/docs/Foo";
const enUSFinalSrc = finalSrc.replace(
// `/${doc.locale}/`,
new RegExp(`^/${doc.locale}/`, "i"),
`/${DEFAULT_LOCALE}/`
);
console.log({ enUSFinalSrc });
```
It basically makes it case-agnostic to turn a potential image URL into the `en-US` equivalent.

Getting img references from en-US didn't work if not lowercase

---

client/src/banners/active-banner.tsx
client/src/banners/ids.ts
client/src/banners/index.tsx
client/src/constants.ts
client/src/ga-context.tsx
client/src/user-context.tsx
docs/envvars.md

Part of #3780
This PR isn't closing the issue, yet, because the exact copy on the banner hasn't been decided. 
But we can land this in favor of breaking up the work into manageable chunks.
To test this, it's a bit complicated, because of the random chance (currently set to 10%). 
1. Run `export REACT_APP_ENABLE_MDNPLUSPLUS=true` and `yarn dev`
2. Go to any page.
3. If the banner doesn't appear, it's probably because your random chance was outside 10%. To override that type the following into the web console: `localStorage.setItem('banner.mdnplusplus_banner_v1.chance', 'true')` and refresh the page
I know [we discussed](https://github.com/mdn/yari/discussions/3753) stop relying on waffle flags but I didn't want to mess with that today. But I also didn't want to completely delete all that …

mdn++ cta banner

---

deployer/aws-lambda/content-origin-response/index.js

See https://github.com/mdn/yari/pull/3798#issuecomment-844056483
Basically, this is manually "cherry picked" from https://github.com/mdn/yari/pull/3798
If we land this, and upgrade Stage and Dev Cloudfront's latest version on the origin response handler, then those environments will be prepared to...
1. Handle URLs like `/en-US/docs/Web/Foo/_samples_/SampleID/index.html` *and* `/en-US/docs/Web/Foo/_sample_.SampleID.html` when that starts coming in.
2. We will make sure we don't set the CSP headers for any live samples.

make content-origin-response work for old and new style live samples

---

kumascript/macros/AvailableInWorkers.ejs

Fixes #3708
Seems to work. I edited the content like this:
```diff
diff --git a/files/en-us/web/api/xmlhttprequest/index.html b/files/en-us/web/api/xmlhttprequest/index.html
index 6bc15b31b..783da14fc 100644
--- a/files/en-us/web/api/xmlhttprequest/index.html
+++ b/files/en-us/web/api/xmlhttprequest/index.html
@@ -22,7 +22,7 @@ tags:
<p>If your communication needs to involve receiving event data or message data from a server, consider using <a href="/en-US/docs/Web/API/Server-sent_events">server-sent events</a> through the {{domxref("EventSource")}} interface. For full-duplex communication, <a href="/en-US/docs/Web/API/WebSockets_API">WebSockets</a> may be a better choice.</p>
-<p>{{AvailableInWorkers}}</p>
+<p>{{AvailableInWorkers("service")}}</p>
<div class="notecard note"> …
```

AvailableInWorkers.ejs should take take a smart optional argument

---

deployer/src/deployer/search/models.py

Fixes #3840
I've tested this quite carefully on my local yari + kuma setup and it worked. 
As you can see `score` is almost identical now. Which is fair and good. Now, it means the popularity boost will benefit better. 
It's never a perfect science but a constant nudging and poking till you get something you *think* users will expect and like.

Field-length norm is too overpowering

---

client/src/document/index.scss
kumascript/macros/htmlattrdef.ejs

Wraps the heading generated by the `htmlattrdef` macro into a self-link to allow for easy linking.
Closes #3148

Generate clickable anchor links for the `htmlattrdef` macro.

---

client/src/auth/sign-up.scss
client/src/banners/banner.scss
client/src/document/index.scss
client/src/document/ingredients/browser-compatibility-table/atoms/_bc-browsers.scss
client/src/document/ingredients/browser-compatibility-table/atoms/_bc-history-link.scss
client/src/document/ingredients/browser-compatibility-table/atoms/_bc-history.scss
client/src/document/ingredients/browser-compatibility-table/atoms/_bc-icons.scss
client/src/document/ingredients/browser-compatibility-table/atoms/_bc-legend.scss
client/src/document/ingredients/browser-compatibility-table/atoms/_bc-platforms.scss
client/src/document/ingredients/browser-compatibility-table/atoms/_bc-table.scss
client/src/document/molecules/_breadcrumb-locale-container.scss
client/src/document/molecules/_notecards.scss
client/src/document/molecules/localized-content-note/index.scss
client/src/document/organisms/sidebar/index.scss
client/src/document/organisms/toc/index.scss
client/src/page-not-found/index.scss
client/src/settings/index.scss
client/src/site-search/search-results.scss
client/src/ui/molecules/a11y-nav/index.scss
client/src/ui/molecules/blog-feed/index.scss
client/src/ui/molecules/breadcrumbs/index.scss
client/src/ui/molecules/home-contribute/index.scss
client/src/ui/molecules/home-hero/index.scss
client/src/ui/molecules/language-menu/index.scss
client/src/ui/molecules/language-toggle/index.scss
client/src/ui/molecules/search/basic-search-widget.scss
client/src/ui/molecules/search/index.scss
client/src/ui/organisms/footer/index.scss
client/src/ui/organisms/header/index.scss

Switch to using `math.div` in SASS
fix #3859

chore: switch to math.div for sass

---

.github/workflows/prod-build.yml
.github/workflows/stage-build.yml

@escattone Let's merge this on Monday. That means Stage will become "hot". If we can't wait till the (Monday) evening, we can kick off a build so it's hot from the afternoon already. Then we know the env var trick works. 
Then, Hermina, Daryl, etc. will carefully test the landing page on Stage on the following Tuesday morning. 
They will not be able to test the CTA banner even if they do the `localStorage` web console trick. 
Then, on Tuesday, after a go-ahead signal we'll uncomment the lines in `prod-build.yml` and kick off a build and we're live-live.

pre-launch plus experiment

---

libs/constants/index.js

values taken from https://blog.codepen.io/2017/02/06/allowing-codepen-via-csp/

CSP script-src for codepen

---

content/redirect.js

I'm working on getting https://github.com/mdn/content/pull/5193 to pass and deploy. Looks like redirects had a hardcoded `index.html` file which I extended to also consider `index.md`. Maybe also a place in which we'll want to switch to using `Document.read()`? Not sure. For now this seems to work.
1. checkout https://github.com/mdn/content/pull/5193
2. run `yarn tool validate-redirects en-us --strict` which should now work on this branch

Also check for md files when validating redirects

---

build/cli.js
testing/tests/index.test.js

Fixes #3871
I'm stunned we didn't notice this till now! Ah well... 
My fix was to first write a test, then I made the fix.
Thankfully we don't send these `noIndexing` documents into Elasticsearch but we've been including every archived document into sitemaps for a long time. 
I'm glad we discovered this before we enabled auto-complete search.

orphaned and conflicting URLs should not be added to sitemaps

---

client/src/plus/index.scss
client/src/plus/landing-page-survey/index.tsx

sign-up form nits and copy changes

---

kumascript/macros/SpecData.json

The `categories`, `description`, `iarc_rating_id` and `screenshots` members of [Web App Manifest](https://w3c.github.io/manifest/) have been moved into new [Web App Manifest - Application Information](https://w3c.github.io/manifest-app-info/) specification.
I will also soon create a separate PR to https://github.com/mdn/content to update needed spec links.

Add Web App Manifest Application Information specification

---

kumascript/macros/SpecData.json

"CSS Basic Box Model" is now "CSS Box Model". I'm going to update the MDN page but this fixes the name of the spec.
https://www.w3.org/TR/css-box-3/

Renaming CSS Box Model spec

---

deployer/aws-lambda/content-origin-response/index.js
deployer/aws-lambda/tests/server.js
deployer/aws-lambda/tests/server.test.js

fix stage/prod CSP selection and add test

---

build/index.js

There are none of these in the en-US content. I manually deleted them ages ago. 
And last week I removed them from all the active locales. 
- https://github.com/mdn/translated-content/pull/506
- https://github.com/mdn/translated-content/pull/505
- https://github.com/mdn/translated-content/pull/487
- https://github.com/mdn/translated-content/pull/486
- https://github.com/mdn/translated-content/pull/485
- https://github.com/mdn/translated-content/pull/763
- https://github.com/mdn/translated-content/pull/764
- https://github.com/mdn/translated-content/pull/765
If there's some left in some unsupported locales, it's fine.

remove removal of .alllinks from HTML

---

client/src/ui/molecules/a11y-nav/index.tsx

Conditionally adds the skip to lang menu link to the a11y nav based on the presence of `docs` in the URL.
I tested this on the homepage, docs page, and settings page. It only shows the "Skip to select language" skip link on docs pages.
fix #2756

fix: conditionally add skip to lang menu link

---

build/document-extractor.js
testing/tests/index.test.js

So the first thing this does is to relax the tests for specifications. It now doesn't test against real data anymore but it checks if the functionality works by checking if `bcdSpecificationURL` is there. We should always have at least this property with some value.
The second thing this does is that it falls back nicer when there are data changes or there is just no title data in browser-specs. In that case we still have a `bcdSpecificationURL` we should display it no matter if we were able to get information from browser-specs or not
.
I made the title "Unknown specification" then. (This is how the old macro system does this, too, see https://github.com/mdn/yari/blob/main/kumascript/macros/SpecName.ejs#L45 and I should have done it this way from the start...)
This should make …

Relax spec tests; use a better fallback

---

kumascript/macros/SpecData.json

It will be great if I can add these two specs to the following pages as reference:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/Code_Values

Add UI Events KeyboardEvent key/code Values

---

client/public/index.html

Fixes #3941
One thing to ponder is; should components know about not appearing in print or should we continue to control it globally.
For example, I could put this:
```css
@media print { .hide-in-print { display: none }}
```
and then, the `<LanguageMenu>` component could do this:
```diff
export function LanguageMenu({
locale,
translations,
native,
}: {
locale: string;
translations: Translation[];
native: string;
}) {
// ...
return (
<form
-     className="language-menu"
+     className="language-menu hide-in-print"
```
It's the same solution, both done very differently. The same goes for all sort of other components which are today listed by each and every CSS selector here: https://github.com/mdn/yari/blob/c52ff314897c37332f0c03f4b84d432711e67c2a/client/public/index.html#L67-L74
Our …

"Change your language" appears in print

---

client/src/document/ingredients/browser-compatibility-table/feature-row.tsx

The BCD table renderer assumes that you only need to render notes when there are `some((item) => item.prefix || item.notes || item.alternative_name || item.flags)`. This is a wrong assumption. 
The table should also render notes whenever the support statement is complex (an array) with more than one entry. It could be that support used to be partial, or that support was removed. Also, the range in which full support was gained should be shown.
Fixes: https://github.com/mdn/yari/issues/3839
Test pages:
http://localhost:3000/en-US/docs/Web/CSS/gap#support_in_grid_layout
http://localhost:3000/en-US/docs/Web/CSS/appearance#browser_compatibility
http://localhost:3000/en-US/docs/Web/SVG/Attribute/stop-opacity#browser_compatibility
http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Global_ …

Fix how BCD renderer determines the need for notes

---

client/src/plus/app.tsx

Clearly, I missed one in https://github.com/mdn/yari/pull/3917
This resolves https://twitter.com/karlhorky/status/1398530432463953922
Before:
After:

remove waitlist anchor on plus page

---

kumascript/index.js
testing/tests/index.test.js
testing/translated-content/files/fr/web/spec_section_extraction/index.html

Fixes #3953
Now all the translated content can reap all the front-matter, that it doesn't already have, from the en-US parent. 
Now, in `translated-content/files/fr/web/javascript/reference/global_objects/array/foreach/index.html` can use `{{Compat}}` and `{{Specifications}}` and it gets the `browser-compat` automatically from the en-US parent doc.

merge en-US metadata with translated metadata

---

content/document.js

For context see [this discussion](https://github.com/orgs/mdn/teams/yari-content-fr/discussions/2) 
The localization dashboard did not display any result in Windows because of path manipulation with "/" rather than "\". I was able to check this fix fixes this. (cf. screenshots on the aforementioned discussion)

Fixing l10n dashboard for Windows

---

build/index.js
client/src/document/toolbar/flaws.tsx
content/document.js
testing/content/files/en-us/markdown/index.md
testing/tests/index.test.js

fixes #3924, fixes #3958
Turns out bad pre tags flaws already work in md, given that we are searching the rawContent for such HTML and markdown could contain just that.
I also wanted to tackle #3957 in here but I think it's gonna get a bit more complicated. Same for MacroLinkError. Might need a meeting to think it through together.

Markdown Flaws - Toolbar and bad pre

---

client/src/document/hooks.ts
client/src/document/index.scss

Fixes #3982
Now, the user message is only created when needed. And if needed more than once, it re-uses the `span` element.

create user-message for clippy on demand

---

kumascript/macros/GroupData.json

The issue mdn/content#2649 was opened to get https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API created.
@rachelandrew created the overview in mdn/content#5433 .
This PR adds it to the GroupData.json, allowin as to close mdn/content#2649

Add overview page for Web MIDI API in GroupData.json

---

client/src/setupProxy.js

The sign-up didn't break because of https://github.com/mdn/kuma/pull/7825
It broke because when we made file attachments, inside the docs, work directly on file attachments. 
Now I was able to use this and your kuma branch to sign up.

make sign-up work again

---

client/src/document/ingredients/browser-compatibility-table/feature-row.tsx

The en dash is narrower and more commonly used for ranges.

Use en dash (–) for ranges in compat tables

---

testing/integration/headless/test_cdn.py
testing/integration/headless/test_endpoints.py

Due to changes in kuma (https://github.com/mdn/kuma/pull/7825 and https://github.com/mdn/kuma/pull/7883), this PR updates the integration tests (and even adds a test for the kuma search API). This has already been tested against stage (which has those kuma changes deployed).

remove obsolete tests

---

content/document.js

[Daniel found out that the ListSubPages macro is not working in Markdown land](https://github.com/mdn/content/pull/5193#discussion_r651047082). I dug a little and found that I did not touch `Document.findChildren` yet which so far only worked for HTML files. This PR fixes that.
For testing it you can check-out the page mentioend by Daniel in the referenced PR (it's https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors) and run it with this PR.

include MD files in Document.findChildren

---

markdown/cli.ts

This PR intends to add support for a locale option to the `yarn md h2m` command allowing a user to target only a given locale.
I believe this could be useful once the converter is used by localizers in order to target conversion operations and logging (md-conversion-problems-report files)
This would, for instance, help \<locale\> localizers submit PR on \<locale\> content only and read a report where only errors on \<locale\> content.
In order for this to be backward compatible, I have added a "all" default. This seems to me a bit unelegant to add such an edge case so let me know if you think of a better way :x
I don't know what should be the strategy for the migration regarding retired languages so I opted for `VALID_LOCALES`.
Gently poking @wbamberg here.

Add locale parameter to markdown converter

---

deployer/aws-lambda/content-origin-response/index.js
deployer/aws-lambda/tests/server.test.js
libs/constants/index.js
server/index.js
server/middlewares.js

This PR turns CSP on (enforcement mode), removes the `report-uri` directive, and updates the tests.

turn CSP on

---

kumascript/macros/GroupData.json

In the CSS Typed OM API docs, the sidebar doesn't appear: this PR fixes this as the name of the API were not corresponding.
I also added the link to the Guide that has been written.

Update CSS Typed OM API name and add link to guide

---

README.md
client/src/setupProxy.js
kumascript/src/constants.js

After upgrading to macOS Monterey, I was not able to run the dev server (`yarn dev`) successfully due to the following error:
`Error: listen EADDRINUSE: address already in use :::5000`
From running `lsof -i tcp:5000`, I found out that `ControlCe` (ControlCenter.app) is the program causing this.
To get around this error, I did the following:
1. added two new overrides to `.env` file: `SERVER_PORT` and `BUILD_LIVE_SAMPLES_BASE_URL`to point to an unused port
2. replace the hardcoded port in `setupProxy.js` with `SERVER_PORT` variable
When I investigated the issue, I saw references to port `5000` in few other packages which  I'm not familiar with - so even though the fix solves the main issue, I believe that it is not complete.

replace hardcoded server port with envvar

---

build/flaws/broken-links.js
package.json
testing/content/files/en-us/web/brokenlinks/index.html
testing/content/files/en-us/web/brokenlinks_markdown/archived/index.md
testing/content/files/en-us/web/brokenlinks_markdown/broken_http_link/index.md
testing/content/files/en-us/web/brokenlinks_markdown/index.md
testing/content/files/en-us/web/brokenlinks_markdown/self_links/index.md
testing/content/files/en-us/web/brokenlinks_markdown/without_locale_prefix/index.md
testing/tests/index.test.js
yarn.lock

What this does:
- adds a `isMarkdown` conditional branch in `getBrokenLinksFlaws` that traverses the AST to find URL-matching markdown nodes
- used `h2m` to turn the `brokenlinks` test files into `brokenlinks_markdown` and run the same tests on them

BrokenLinks checking for Markdown documents

---

client/src/document/ingredients/browser-compatibility-table/atoms/_bc-icons.scss

At least on some browsers on some OSes (e.g., Chrome and Safari on macOS) end up with taking a line-break opportunity after the "-x". We don't want this atom to ever have a line-break within it.

Avoid "-x-" prefix atom getting broken across lines

---

kumascript/macros/GroupData.json
kumascript/macros/InterfaceData.json

In mdn/content#6135, we removed DeviceLightEvent.
This cleans the sidebar and the interface data information.

Remove info related to Ambient Light Events

---

kumascript/macros/GroupData.json
kumascript/macros/InterfaceData.json

`AbstractWorker` is gone from MDN; see the related change at https://github.com/mdn/content/commit/13859f1.
Otherwise, without this change, with end up with thing where member names/links get duplicated in the API sidebar.
Fixes https://github.com/mdn/content/issues/6408

Expunge AbstractWorker

---

server/flaws.js

Fixes #4082
First, test in regular yari:
```
yarn dev
```
``` 
yarn build
```
And then open <http://localhost:3000/en-US/_flaws> in your browser. Should show stuff. 
Ultimately the raison-d'etre for this PR is so that https://github.com/mdn/content/pull/6349 can start to work.

make Flaws Dashboard work in mdn/content

---

kumascript/macros/GroupData.json

The RenderingContext typedef documentation is in the progress of being removed in mdn/content#6592. This cleans the sidebar too.

Remove RenderingContext typedef from Canvas API sidebar

---

kumascript/macros/GroupData.json

Add PublicKeyCredential to the Credential API sidebar (where the other credential interfaces are already listed)

Add PublicKeyCredential to Credential API sidebar

---

kumascript/macros/GroupData.json

The sidebar for Background Fetch APi was missing. This creates it, with the interfaces that are currently documented.

Create sidebar for Background Fetch API

---

content/constants.js

Steps to test:
```
▶ export CONTENT_TRANSLATED_ROOT=~/dev/MOZILLA/MDN/translated-content   # Oops! To err is human
▶ yarn prepare-build  # Should now work
▶ BUILD_FOLDERSEARCH=getting_started BUILD_FLAW_LEVELS="*:ignore, macros:warn" yarn build -l zh-tw
$ cross-env NODE_ENV=production node build/cli.js -l zh-tw
Corrected the CONTENT_TRANSLATED_ROOT environment variable to /Users/peterbe/dev/MOZILLA/MDN/translated-content/files
CONTENT_ROOT:            /Users/peterbe/dev/MOZILLA/MDN/content/files
CONTENT_TRANSLATED_ROOT: /Users/peterbe/dev/MOZILLA/MDN/translated-content/files
CONTENT_ARCHIVED_ROOT:   not set
```
Note how it corrected it to `CONTENT_TRANSLATED_ROOT: /Users/peterbe/dev/MOZILLA/MDN/translated-content/files`

add /files to CONTENT_TRANSLATED_ROOT if necessary

---

client/src/document/on-github.tsx

This is *not* a solution https://github.com/mdn/yari/issues/4048 
but it inches us slightly towards something. 
Now, the first link there is about editing. We want this to be slightly more prominent because a lot of issues are filed when the user could just make a quick edit themselves. 
*Order of links*
*When you mouse-hover over the link*

"Edit on GitHub" link first

---

content/document.js
content/redirect.js

Fixes #4123
```
▶ yarn tool delete --redirect /gargbage Web/API/BluetoothRemoteGATTService/getIncludedService
$ node tool/cli.js delete --redirect /gargbage Web/API/BluetoothRemoteGATTService/getIncludedService
error: The URL is expected to start with /$locale/docs/: /gargbage
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
And now it no longer executed the deletion part.

dry-run redirect argument as part of deletion

---

client/src/document/on-github.tsx

Part of #4060 
Fixes "Heading elements are not in a sequentially-descending order" in Accessibility section of Lighthouse Audit. Since the `<h4>` was hardcoded before, we could always add a `className` to mimic the `<h4>` styles for the final heading produced by `<OnGitHubHeading />` if it is an `<h3>`.
My original plan was to use cheerio and replace the heading with the correctly ordered heading, but I quickly found out I could only access stuff with cheerio that was within `doc.body` and since the `<aside id="metadata">` is not apart of that, I couldn't select the heading in aside. The functional component to determine which heading to use seems better anyways since it was already React to begin with.

Make sure heading within .on-github container is in sequentially-descending order

---

client/src/document/ingredients/browser-compatibility-table/atoms/_bc-legend.scss

Change vertical-align to bottom on bc-legend atoms for better alignment

---

kumascript/macros/EmbedLiveSample.ejs
kumascript/tests/macros/EmbedLiveSample.test.js

Part of #4060
> 1. <frame> or <iframe> elements do not have a title attribute
Fixes the above accessibility issue from Lighthouse audit. The `<iframe>` elements generated from EmbedLiveSample KS macros now include unique `title` attributes. I used the `sampleId` value that is being passed into the KS macros as `$0` and the deslugified it and concatenated the text "sample" to end. I noticed some `sampleId` values already have the word "example" in them so I opted for "sample" instead considering they are embedded live samples and for the cases when "Some thing example sample" is better than "Some thing example example". This situation only occurs periodically and I'm not sure how many times it does, therefore I chose to add "sample" to the end of each `sampleId` to attempt creating unique …

Add title attribute to live sample <iframe>'s created by EmbedLiveSample KS macro

---

content/translation.js
testing/tests/index.test.js

Good page to test: http://localhost:3000/zh-CN/docs/Web/API/MediaElementAudioSourceNode#_flaws
Before:
After:
After this is merged, it might be a good idea to announce this to all the translation communities so they can help to do what @hamishwillee has been doing in https://github.com/mdn/content/issues/3196 but for each locale.

'page' macro considered important for translation differences

---

client/src/document/index.scss
client/src/document/organisms/metadata/index.scss
client/src/ui/molecules/language-menu/index.scss
client/src/ui/organisms/footer/index.scss

Part of #4060 
Specifically, failed audits in the SEO section: 
- tap targets are overlapping eachother
- tap targets are not appropriately sized (87% of the 48px by 48px requirement)

Fix tap size and spacing for tap targets

---

build/feedparser.js

My Wifi was down and I couldn't use `yarn dev`. 
Granted, the macOS `tmp` dir will periodically clean itself up and completely wipe when you restart the computer so there it wouldn't save you either. 
But introducing a simple disk-based cache is cheap and it makes `yarn dev` a little bit more pleasant.

reuse saved feed entries for homepage SPA

---

.github/workflows/dev-build.yml
.github/workflows/prod-build.yml
.github/workflows/stage-build.yml

@fiji-flo set up a cron job in Athena that updates two S3 objects, from our CDN logs, every month. 
But we're not doing anything with those CSV files. 
[Week before last we manually updated the file checked in git](https://github.com/mdn/content/pull/4945) but it doesn't feel smart to keep doing that every month. 
Also, if we can increase the cron job to weekly, we'd still need to wait until some human updates the file in git. 
By running this right before the build, we'll always get the latest and greatest popularities, that are available, right before building the pages.

fetch and update popularities before building

---

.github/workflows/dev-build.yml
.github/workflows/prod-build.yml
.github/workflows/stage-build.yml

Testing it out in: https://github.com/mdn/yari/actions/runs/1034317579
This is what was going wrong: https://github.com/mdn/yari/runs/3077697402?check_suite_focus=true
Basically, the merge of https://github.com/mdn/yari/pull/3844 broke the build. That PR was bad, but instead of reverting, this PR fixes it a bit better so we can keep the good functionality but not doing in the wrong order. 
The CLI `yarn tool popularities` can't be run until *after* you've run (some part of) `yarn prepare-build`. That's what this PR fixes.

unbreak clean build

---

content/redirect.js

This is a "desperate" follow-up from https://github.com/mdn/content/pull/6979 
Check out version 0e14524aa5282ad673f076857b9f52c920fed9fa of mdn/content and the latest version of mdn/yari and run:
```
yarn tool validate-redirects en-us --strict
```
...which is what our CI runs for mdn/content. It was failing because we recently emptied the `archived.txt` file as we're going to completely abandon archived content. All you would get is:
```
_redirects.txt for en-us is causing issues: Error:  _redirects.txt for en-us is flawed
```
which is "useless" because it doesn't give you any clues to what's possibly wrong with the `_redirects.txt` file. 
In this PR here, I'm desperately trying to elevate *something* that can at least give you *some* clue as to where to start looking. Now you get:
```
▶ …
```

make validate-redirects a teeny bit more insightful

---

kumascript/macros/InterfaceData.json

Navigator\* mixins are gone from MDN and so need to be dropped from `kumascript/macros/InterfaceData.json` as well.
Otherwise, without this change, with end up with the thing where member names/links get duplicated in the API sidebar.
Fixes https://github.com/mdn/content/issues/7036
Cc @Elchi3

Expunge all Navigator* mixins

---

kumascript/src/live-sample.js

We should have done this long ago, but better late than never! Let's block indexing of the live-sample pages.

block indexing of live samples

---

markdown/h2m/handlers/dl.ts

<dl>
<dt>thing</dt>
<dd>nested definition:
<dl>
<dt>thang</dt>
<dd>stuff</dd>
</dl>
<p>I'm what breaks it</p>
</dd>
</dl>
was broken

fix nested dl's with p

---

kumascript/macros/GroupData.json

ChildNode has been removed a few weeks ago (as ParentNode, …) but was still there.
@Elchi3 Can you confirm this from the content point of view?

Remove ChildNode from DOM sidebar

---

.github/workflows/dev-build.yml
.github/workflows/prod-build.yml
.github/workflows/stage-build.yml

It looks something like this:
Now, if any failure happens inside `(dev|stage|prod)-build.yml` it will post a Slack message to `secrets.SLACK_WEBHOOK`
That current env var is a secret URL which I generated on https://api.slack.com/apps/A01EQTY3F5L/general? which might be entirely tied to my username, I'm not sure. But it's an app that I created, called `Yari Builder`, which as been approved my someone in Mozilla who approves Mozilla Slack apps. 
At the time of writing, that webhook URL encodes exactly channel it goes to and right now it's set to `#mdn-notifications` which is a channel that nobody watches (enough). So I'll change it to `#mdn-dev`. 
NOTE! It's important that just because we can post from GitHub Actions to Slack that we don't "abuse" this. The most important thing right now …

Slack notify

---

kumascript/macros/WebRTCSidebar.ejs

I removed `RTCIdentityEvent` and `RTCIdentityErrorEvent` removed from the spec and MDN (and marked as _flaws_ on each page using the macro).
I added `RTCDataChannel` one of the most important interface of WebRTC, that was missing.
cc/ @Elchi3 for the review from the content point of view.

Update interface list on {{WebRTCSidebar}}

---

build/cli.js

This is useful when using yari as SPA

a flag to not build index.html

---

yarn.lock

That'll take care of that pesky reminder...
```
1:56:13 PM web.1        |  Starting the development server...
1:56:16 PM web.1        |  Browserslist: caniuse-lite is outdated. Please run:
1:56:16 PM web.1        |  npx browserslist@latest --update-db
```

upgrade browserslist 2021-07-22

---

client/src/search.tsx

Fixes #4282
To test, 
- open any page and type a single character in the search, like `c`. 
- scroll down a bit
- click the last search result

scroll to top on picking search result

---

kumascript/macros/InterfaceData.json

`RTCDtlsTransport` inherits methods and properties from `EventTarget`.
cc/ @Elchi3 to review from the content point of view

Add RTCDtlsTransport to InterfaceData

---

kumascript/macros/InterfaceData.json

We are in the process of removing mixins from MDN. Mixins that doesn't have a page anymore are creating numerous flaws when building sidebars.
This removes any mentions of `ParentNode`, `ChildNode`, `GeometryUtils`, `Animatable`, `LinkStyle` and `Body`.
(It will lower our macro flaw counters, by 100-200.)
cc/ @Elchi3 for a review from the content point of view
[I dream of the day we will get rid of `InterfaceData.json`, removing the mixins from the content is a first step towards this mid-term goal)

Remove deleted mixins from InterfaceData

---

content/document.js

This PR fixes #4210 by only attempting to perform a redirect as needed.  This prevents an error when attempting to delete a document without specifying another page to redirect to.

CLI delete command: dry redirect only as needed

---

.github/workflows/dev-build.yml
build/cli.js

An experiment to speed up the `yarn build` time by spreading the work across 2 CPUs. 
Building one locale is thread-safe by design but it's not safe to spread the documents within a locale. 
As a reference, I kicked off a Dev build earlier today and it clocks in at...
It's hard to tell exactly how long each locale takes so we could experiment with some measurements there to find a good balance.

building by locales in parallel

---

.github/workflows/pr-deployer.yml
deployer/README.md

See https://github.com/snok/install-poetry/issues/43#issuecomment-887529694 and https://www.peterbe.com/plog/install-python-poetry-github-actions-faster for the background. 
The context is that I want to make https://github.com/mdn/content/actions/workflows/pr-review-companion.yml much faster. Its slowest part is the installation of `poetry` itself. When a PR author has created a PR, it's a very cognitively high probability that that author wants quick feedback about their work. A) we want fast automated CI, and B) fast preview URLs.

Cache .local for a faster poetry installation

---

kumascript/macros/InterfaceOverview.ejs

Now that it's not used anywhere in mdn/content or mdn/translated-content. 
@teoli2003 r?

delete InterfaceOverview.ejs now

---

client/src/document/organisms/sidebar/index.scss

Fixes #4326 
Related #4241 
To prevent sidebar text from overflowing into the `<main>` content, I changed the `white-space` and `word-wrap` properties from:
```scss
code {
white-space: nowrap;
word-wrap: break-word;
}
```
to
```scss
// overrides the above code {} styles in _code.scss
.sidebar code {
whites-space: normal;
word-wrap: normal;
}
```
https://user-images.githubusercontent.com/48612525/127099973-48de49ec-ba98-48ef-af15-539189233080.mov
With the already in place `hyphens` usage, this works nicely to fix the overflow problem and avoids the "odd" word-break placement where the final closing method parentheses wrapped to the next line which was happening with `word-wrap: break-word`.
cc @schalkneethling

Update styling for code elements in sidebar to better handle overflowed content

---

client/src/document/lazy-bcd-table.tsx

Fixes #4260
Fixes #4236
At least three people have suffered this fate now. It happens because the JS chunk of the BCD table is always lazy loaded and if that chunk fails to load, for whatever reason, it causes the whole page to crash and just becomes white. 
First, to test this, use Chrome (has more intuitive tooling for blocking URLs in the devtools)
Go to https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API
Open Network panel and filter by "JS" look for a URL like https://developer.mozilla.org/static/js/6.71db03d1.chunk.js which is supposed to be one of the last ones to load. Right-click and "Block request URL" and then reload the page. 
This is what I get:
Now, check out *this* branch locally and run `yarn dev`. 
Then go to …

failed BCD JS chunk shouldn't kill the page

---

kumascript/macros/InterfaceData.json

These mixins have been either removed from spec or from MDN. 
They lead to 5 flaws in each and every Window.* pages! (and there are a lot of them!)
cc/ @Elchi3 for the review from content.
(Removal of GlobalCrypto from spec: https://github.com/w3c/webcrypto/pull/200 )

Remove no-more-documented mixins on InterfaceData

---

libs/fundamental-redirects/index.js
testing/integration/headless/map_301.py
testing/tests/redirects.test.js

We have a [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1660250) request to redirect this slug to the new home of the tech-speakers website.

Redirect mozilla-teach-speakers

---

client/src/document/toolbar/flaws.tsx
client/src/document/types.tsx

Part of #4333
Part of #4392
Before:
After:
This is better than [getting cryptic 500 ISE from the server](https://github.com/mdn/translated-content/pull/1717).
...for now.

hide 'fix fixable flaws' button for now

---

client/src/ui/molecules/language-toggle/index.scss

Address the alignment, spacing, and size of the new globe icon.
fix #4396

fix: new globe icon alignment

---

markdown/cli.ts

As mentioned with @wbamberg a few times, it's useful not to have a limit at 20 in order to display unhandled elements. As a matter of facts, there are likely several "one-offs" (e.g. for French, after a first pass I still had 15 w/ a single occurrence)
This short PR removes this limitation.
@wbamberg let me know if this does not work for you.

Remove limitation of 20 displayed unhandled elements to h2m conversion report

---

.gitignore
content/popularities.js
package.json
tool/cli.js
tool/popularities.js

Part of #4217
The idea is that we drive the popularities from `/popularities.json` instead. Reading it is always done via the `getPopularities()` function and it now hardcodes the location of the file. 
If you're doing local development in `yari` with `yarn dev` you get:
```
info: Reusing exising /Users/peterbe/dev/MOZILLA/MDN/yari/popularities.json (Thu Jul 22 2021 14:34:37 GMT-0400 (Eastern Daylight Time)) for popularities.
info: Reset /Users/peterbe/dev/MOZILLA/MDN/yari/popularities.json by running: yarn tool popularities --refresh
```
which makes consecutive runs of `yarn dev` fast. 
Then, when it bundles up yari as an NPM package, you're going to get a tarball that, at its root, contains a `popularities.json` which got created (every time) from the …

Make popularities.json dynamic instead of checked into git

---

kumascript/macros/CSSSyntax.ejs

This will help some of the confusion in https://github.com/mdn/yari/pull/3918
Basically, the macro should always create anchor links that are lowercase. 
E.g. `<a href="...#hash_mark">` instead of `<a href="...#Hash_mark">` because any page that has:
```html
<h2 id="Hash_mark">Hash mark</h2>
```
...in its raw form will always become, when rendered:
```html
<h2 id="hash_mark">Hash mark</h2>
```

CSS syntax anchors should always be lowercase

---

build/index.js

As of https://github.com/mdn/content/pull/7591 there's no more links to `fxsitecompat.com` or `fxsitecompat.dev` in any of the mdn/content. 
There's still some in the translated-content. See https://github.com/mdn/translated-content/issues/1634
But even if we allow some of them in the translated content, it's no longer horrible because the new domain is a redirect to a URLs that will always respond with `410 Gone`. It used to be worse. It used to redirect to a domain squatters site with "seedy" banner ads. 
So I think we can finally delete this added complexity, once [the content updates](https://github.com/mdn/content/pull/7591) and it'll make the build marginally faster.

remove link rewrites for fxsitecompat.com

---

markdown/cli.ts

Git was complaining my local mdn/translated-content was out of the git repo when I ran `yarn md h2m web/javascript --locale fr --mode replace`.
In other words, I needed this (and  https://github.com/mdn/yari/pull/4251) for https://github.com/mdn/translated-content/pull/1835
The fix uses an existing utils fonction :)

Make git ops work for h2m replace when targeting translated-content

---

markdown/h2m/handlers/index.ts

Fixes https://github.com/mdn/yari/issues/4308.
I think adding "hidden" to `canHaveClass` means h2m will treat this as convertible, and the change in `filter` will make it actually write the hidden class into the GFM info string.
It might be better to change the conditional in `filter` to look in a list of allowed classnames, but I wasn't sure where I ought to put that. So I just extended the conditional.
I don't know what the array of classnames at lines 209-220 is doing.
With this change, something like this: https://github.com/mdn/content/blob/609ec8e90205f8db69e6755287de11448828f0cb/files/en-us/web/css/background-blend-mode/index.html#L62-L80
...will give us Markdown like this:
```
\```
html hidden
<div id="div"></div>
<select id="select">
<option>normal</option> …

h2m: support hidden class in code blocks

---

markdown/h2m/handlers/cards.ts
markdown/m2h/handlers/index.js

In Markdown we support "notes", "warnings", and "callouts", which are all little highlighted boxes containing content.
There are lots of details about this in here: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN#notes_warnings_and_callouts. The different between callouts and the other two is that notes and warnings must start with "**Note:**" or "**Warning:**", while callouts don't start with any fixed text, and people can write anything they like in there.
In the current callout implementation, the h2m tool requires that a callout starts with an H4 heading (for example, see the "Looking to become a front-end web developer?" bit in https://developer.mozilla.org/en-US/docs/Web/JavaScript). Having looked at some content I think this is too restrictive. For example, …

Markdown: relaxing the requirement for callouts to begin with an h4

---

kumascript/macros/InheritanceDiagram.ejs

https://github.com/mdn/yari/commit/00dc256 (https://github.com/mdn/yari/pull/4211) broke all inheritance diagrams, because it mistakenly removed the `width: 100%` CSS property on the `div` element Yari generates for inheritance diagrams (that change/PR was meant to just change `iframe` elements, and should not have touched the `div` element in `InheritanceDiagram.ejs`.
So this change reverts the part of https://github.com/mdn/yari/commit/00dc256 that changed `InheritanceDiagram.ejs`
Fixes https://github.com/mdn/content/issues/7700

Unbreak inheritance diagrams (InheritanceDiagram.ejs)

---

kumascript/macros/GroupData.json

1. We don't document dictionaries, types, and callbacks on separate pages. I removed them here.
2. XR has been renamed to XRSystem

Update WebXR group data

---

kumascript/macros/InterfaceData.json

The `AudioNodePassThrough` mixin has been deleted and this is generating more than 100 MacroPagesError flaws.
cc/ @Elchi3

Remove deleted AudioNodePassThrough mixin from InterfaceData

---

markdown/h2m/handlers/index.ts

We support syntax highlighting for SVG when code blocks have the classes `"brush: svg"`. See for example https://developer.mozilla.org/en-US/docs/Web/CSS/filter#brightness.
Because this isn't documented (https://developer.mozilla.org/en-US/docs/MDN/Guidelines/CSS_style_guide#code_syntax_highlighting), it never made it into the converter, so the converter treats code blocks with an `"svg"` class as unconvertible.
This change just tells the converter about this class, so it will be accepted and written into the GFM info string like any other language identifier.

Support svg syntax highlighting

---

client/src/search.tsx

Part of #4407
To test:
1. Type something in the search so you see results
2. Press <kbd>Esc</kbd>
What it used to do: Blur the whole input field
What it should do: just hide the search results

Esc should just hide the search results, not blur

---

kumascript/macros/GroupData.json

_WebHID API_ has no proper sidebar, although it calls the sidebar macro. In addition, this API doesn't appear in the [API list](https://developer.mozilla.org/en-US/docs/Web/API).
The reason for these flaws is that it doesn't have an entry in `GroupData.json`.
This PR fixes this.
cc/ @rachelandrew for a review from the content point-of-view.

Add sidebar for WebHID API

---

kumascript/macros/InterfaceData.json

Two types of data get removed in this PR:
- `Moz` prefixed mixins that are technical mixins used by Mozilla to group Mozilla-specific features. We never documented these, and we are removing mixins anyway.
- A significant number of `Moz` prefixed interfaces: not documented at all, they are not part of the web platform as they were Firefox OS-specific interfaces (long gone from MDN).
cc/ @Elchi3 for a review from the content point of view.
This will remove about 50 flaws generated by macros.

Remove undocumented Mozilla specific stuff from `InterfaceData.json`

---

kumascript/macros/HTMLSidebar.ejs

without, has a slightly weird alignment to other sidebar items
before:
after:

Add missing parent element for sidebar item

---

content/document.js

Fixes #4453
I renamed a folder to have a space in it. Now...
```
▶ BUILD_FOLDERSEARCH=webassembly/exist yarn build
$ cross-env NODE_ENV=production node build/cli.js
CONTENT_ROOT:            /Users/peterbe/dev/MOZILLA/MDN/content/files
CONTENT_TRANSLATED_ROOT: not set
Error: Folder contains whitespace which is not allowed ('/Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/webassembly/existing c to wasm/index.html')
```

Specify folder that contains whitespace

---

client/src/constants.ts

TypeScript is smart but it can't predict the many return types of `JSON.parse()`. E.g. `JSON.parse('true') === true`.
But by using `Boolean()` around these, it means that it doesn't matter so much what the env var strings were. For example:
```js
Boolean(JSON.parse('1')) === true
```
By the way, by doing this, these variables now have a known type signature throughout where they're used which is quite a lot of places.

tighten typescript types on constants

---

content/document.js
kumascript/macros/CSSSyntax.ejs

In `{{CSSInfo}}` (as well as in `{{Specification}}` and `{{Compat}}`, although the mechanism is different), when the structured data is missing, an error message is displayed.
In `{{CSSSyntax}}`, an exception is thrown, the name of the macro is displayed in the page, and a flaw is generated.
The behavior of `{{CSSInfo}}` is better: there is nothing wrong in the page (as the macro flaw hints) and the message helps diagnose and to fix the actual problem.
This PR fixes this.
cc/ @peterbe: do you think you can still squeeze this review? The only issue in macros preventing me to go down to 0 for MacroExecutionError flaws :-)

Display error rather than generate flaw for {{CSSSyntax}}

---

.github/workflows/npm-publish.yml
.github/workflows/performance.yml

This solves the same issue as this: https://github.com/mdn/content/issues/8014
What can happen is that you get a race condition on 2 different GHA workflows that try to store or use the same Cache key and thus failing. 
Besides, making each possible cache key in the `actions/cache` per workflow is a good idea because it assures that the caching is unique for the whole workflow.

cache node_modules in CI by unique workflows

---

client/src/document/index.scss

maybe a typo in 00dc256f8dd4384f2b94cba022335d19ecf09b89

Change iframe width from 100 to 100%

---

client/src/document/organisms/bookmark/app.tsx

Fixes #4504
This happened because the JSON from Kuma wasn't in sync with the JSON expected in TypeScript. An inevitable problem till we one day share type definitions and use something like GraphQL.

fix date display in toggled bookmark

---

client/src/document/ingredients/browser-compatibility-table/atoms/_bc-table.scss
client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
client/src/document/ingredients/browser-compatibility-table/index.scss

Update styling to prevent bc-table-row-header text from overflowing its content-box

---

package.json
yarn.lock

Dependabot won't roll majors automatically AFAIK, so here I am doing it
manually.

Update to @mdn/browser-compat-data v4.0.0

---

.github/dependabot.yml

Problem:
Real problem :)
https://github.com/mdn/yari/pulls/app%2Fdependabot

allow more open PRs from Dependabot for npm

---

build/format-notecards.js
build/index.js
client/src/document/molecules/_notecards.scss
testing/content/files/en-us/web/check_notecards/index.html
testing/tests/index.test.js

Fixes #4394
Replaces h4s for notecards that have it, otherwise leaves them be.
Page in screenshot: http://localhost:3000/en-US/docs/Glossary/HTML5

Replaces all pre-existing h4 tags in notecards with <strong>

---

markdown/m2h/handlers/index.js

```md
> **Callout:** **Fancy Title**
>
> Something important!
```
should be 
> ** Fancy Title**
>
> Something important!
But currently is rendered as 
> Something important!

fix callout rendering

---

client/src/document/molecules/_breadcrumb-locale-container.scss

Fixes #4528 
ping @schalkneethling

Add media query to fix missing top margin on .breadcrumb-locale-container

---

client/src/document/ingredients/browser-compatibility-table/headers.tsx
client/src/document/ingredients/browser-compatibility-table/index.tsx

With the addition of Deno in compat tables, the tables now often show
Node.js in places it previously wasnt shown. In all of these new places
it is shown, it just shows a bunch of question marks, because it doesn't
have data.
I brought this up on Matrix, and @ddbeck and me agreed that the best
path forward would likely be to show the Node.js column only if there is
data for Node in the BCD data.
﻿This commit changes the table, so that Node.js is only shown if the
category is "javascript", or there is compat data for Node for the given
BCD entry. Deno is shown just like it is now.

Only show Node in compat tables if there is data

---

kumascript/src/api/util.js

This fixes a regression introduced by commit 49f5317df4963018c8be94dfc5f50b6e56b1079c.
Fixes: mdn/content#8020
Fixes: mdn/content#8124

Fix EmbedLiveSample when there are subheadings

---

kumascript/macros/CSSRef.ejs

This fixes macro flaws that appear on every page that CSSRef is used.
> wrong xref macro used (consider changing which macro you use)

Fix MacroWrongXRefError from CSSRef macro

---

kumascript/macros/CSSRef.ejs

We moved these last week and now, when building the pages, we get:
> In CSSRef the smartLink to /en-US/docs/Web/CSS/CSS_Background_and_Borders/Box-shadow_generator is broken (redirects to /en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Box-shadow_generator)
> In CSSRef the smartLink to /en-US/docs/Web/CSS/CSS_Background_and_Borders/Border-image_generator is broken (redirects to /en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Border-image_generator)
(And 1888 flaws, …)
cc/ @Elchi3 for a review from the content perspective.

Fix links in CSSRef.ejs

---

package.json
yarn.lock

In case dependabot is slow or not proposing this today, here's a PR to bump BCD to 4.0.2. 
It's not a major / breaking release but a change for about 15 (important / high traffic) pages was made. So, we want this to go out soon.
See https://github.com/mdn/browser-compat-data/releases/tag/v4.0.2
Closes https://github.com/mdn/content/issues/8542
cc @escattone

build(deps): bump @mdn/browser-compat-data from 4.0.1 to 4.0.2

---

kumascript/macros/GamesSidebar.ejs

Fixes mdn/content#8602
The Apps area is gone. Linked to the overview page of the API instead.
cc/ @Elchi3 for a review from the content-side point-of-view.

Fix broken link in GameSidebar

---

kumascript/macros/CanvasSidebar.ejs

Hit Regions have been removed from spec, implementations, and MDN Web Docs.
This fixes mdn/content#3780.
cc/ @Elchi3

Remove hit regions from Canvas Sidebar

---

package.json
yarn.lock

Reverts mdn/yari#4375
I merged mdn/yari#4375 because the CI was green, but it broke the `h2m` tool due to the fact that we failed to also use the new ESM import style. I tried locally changing the import style, but am getting a TS error that I can't seem to resolve, so I'm reverting this for now to un-break the `h2m` tool.

Revert "build(deps-dev): bump rehype-minify-whitespace from 4.0.5 to 5.0.0"

---

client/src/document/ingredients/browser-compatibility-table/atoms/_bc-table.scss

Fixes #4514
- adds `-webkit` vendor prefix for Firefox and Edge (Since I wasn't sure if there was already some auto-prefixer in place happening during build time)
- updates `word-wrap: break-word` to `word-wrap: anywhere` for `.bc-table-row-header code` since that is what works to allow the text to break onto the next line in Firefox and Edge. Using `break-word` works in Chrome but fails in Firefox/Edge, thus introducing `anywhere` solves the problem.
Screenshot in Firefox (`hyphens: auto` won't appear as they aren't supported)

Fix problem where word-wrap wasn't wrapping text as intended in Firefox and Edge

---

markdown/h2m/handlers/index.ts

Yari's syntax supports some extra languages that h2m didn't know about, so h2m would complain that code blocks marked up with those language codes were unconvertible.
This PR teaches h2m about these language codes, so they make it into the Markdown info string, and get syntax highlighting.
These are some pages that use these language identifiers:
* php: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler/Web-based_protocol_handlers#example_3
* xml: https://developer.mozilla.org/en-US/docs/Web/API/XSLTProcessor/Basic_Example
* glsl: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_model_view_projection#webglbox_draw
* python: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction (but note that this page will …

Make h2m support some more languages

---

markdown/h2m/handlers/index.ts

Fixes #4608 
Note that #4599 provided support for `brush: python`, so this PR simply adds support for `brush: sql`.

add h2m support for sql code blocks

---

kumascript/macros/CSSSyntax.ejs

Formal syntax for [range restrictions and range definition notation](https://www.w3.org/TR/css-values-4/#numeric-ranges) is broken. Currently grouping brackets are matching the range notation within data types and the regex that matches the data types doesn't match the bracketed range notation.
This PR prevents bracket groups from matching within data type angle brackets and adds the bracketed range notation to the data type regex.
**Examples where syntax currently breaks:**
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-clip-margin#formal_syntax
https://drafts.csswg.org/css-overflow/#overflow-clip-margin
`<visual-box> || [0,∞]>`
should be:
`<visual-box> || <length [0,∞]>`
https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#formal_syntax …

fix css syntax range definition notation

---

client/src/document/index.scss

- Fixes #4569 and mdn/content#8412
- `width: 100%` for the example iframes is being applied here https://github.com/mdn/mdn-minimalist/blob/main/sass/atoms/_examples.scss#L10 so taking off this property from here fixed the scrollbar issue on `InheritanceDiagram`
- Another way to tackle this would be removing height and width properties or even just the height property here(https://github.com/mdn/yari/blob/main/kumascript/macros/InheritanceDiagram.ejs), but then this would lead to more refactoring and removing height and width arguments passed to all the instances of `InheritanceDiagram` macro just for the diagram to cover 100% of the parent a be visible a bit bigger!!

Fix inheritanceDiagram getting a scrollbar

---

client/src/search-utils.ts

Fixes #4719, fixes #4718.
1. Checks that the character produced by pressing the key is `/`, instead of checking that the physical key is the one labelled `/` on US-keyboards.
2. Excludes the key combos that include either Ctrl or Meta (⌘ on Mac), e.g. `⌘/` or `^⇧/`, as they are more likely to be some preëxisting keyboard shortcut than a way to output “/”.

Corrections around the capture of ”/” keypress used to focus the search input

---

client/src/document/ingredients/browser-compatibility-table/index.scss

Fixes [#819](https://github.com/mdn/mdn-minimalist/issues/819) in [mdn/minimalist](https://github.com/mdn/mdn-minimalist)
This proposed change removes display: flex from the .bc-table-row-header code selector. This resolves the issue of `<code>` elements nested in .bc-table-row-header to occupy an entire line creating a very hard to read cell
_screenshot of a bcd table cell on [addEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) before any changes were made_
After removing the `display: flex` declaration from the `.bc-table-row-header code` selector within `/ingredients/browser-compatibility-table/index.scss`, the formatting looks good again and doesn't seem to negatively affect any other cells. 
I'm inclined to believe there weren't any other …

Removes flex declaration from .bc-table-row-header code selector

---

package.json

From the logs:
```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.
The react-scripts package provided by Create React App requires a dependency:
"babel-loader": "8.1.0"
Don't try to install it manually: your package manager does it automatically.
```

chore: remove babel-loader from dependencies

---

client/src/document/index.scss

I guess the rule that set the bottom for paragraph tags in content was lost during the merge of the latest minimalist release.
This fixes that.
fix #4929

fix: margin bottom on p tags got lost in translation

---

markdown/localizations/zh-CN.json
markdown/localizations/zh-TW.json

After discussion with other zh team members, we decided to change a little bit `msgstr`.

chore: update h2m zh-* l10n

---

kumascript/macros/CSS_key_concepts.ejs

The link to "Visual formatting model" includes an old URL. Update it.

Fix URL for "Visual formatting model"

---

client/src/document/molecules/localized-content-note/index.tsx

Fix grammatical error in German translation of the inactive locale note.

Fix German translation of locale note

---

client/src/document/ingredients/browser-compatibility-table/headers.tsx

Over in BCD, @jdatapple has submitted compat data for WebExtensions on iOS. 
In order for MDN to show a column for Safari iOS in the WebExtension docs, we need to add safari to the "webExtensions-mobile" browsers. See for example https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs#browser_compatibility where we currently have no Safari iOS in the mobile column. This PR adds Safari iOS
See also https://developer.apple.com/documentation/safari-release-notes/safari-15-release-notes#Web-Extensions

Safari iOS is now a WebExtensions browser

---

kumascript/src/api/util.js
kumascript/src/live-sample.js

Fixes #4883 
I modified `files/en-us/web/css/_colon_active/index.md` locally. I removed the argument to both of its `EmbedLiveSample` macro calls (so they both became simply `EmbedLiveSample()`), and then reloaded http://localhost:5000/en-US/docs/web/css/:active.

fix regression of embedlivesample fallback algorithm

---

.github/workflows/testing.yml

If the tests fails before starting the server (for instance while running eslint), the step debugging the server output was producing weird errors due to output files not being found.
See https://github.com/mdn/yari/runs/4223370492?check_suite_focus=true for an example

Avoid confusing CI reporting

---

.github/workflows/mark-as-idle-issues-pr.yml

Add the mark-as-idle workflow to Yari
fix #5000

chore: add mark as idle workflow

---

.github/workflows/new-issues.yml

New workflow to automatically add `needs-triage` to new issues
Depends on https://github.com/mdn/workflows/pull/4

Workflow to add needs triage label to new issues

---

client/src/ui/organisms/footer/index.scss

Fixes #4949
Cleans up #4950
Remove `z-index` declaration from `src/ui/organisms/footer.scss` to avoid footer covering search results as it will have a higher value in the stacking context.

Removes z-index declaration to avoid footer covering search results on 404 page

---

client/src/document/index.scss

Set images in the main content to `inline-block` by default.
fix #5029

fix: inline images by default in main content

---

deployer/aws-lambda/tests/server.test.js
libs/fundamental-redirects/index.js
testing/integration/headless/map_301.py
testing/tests/redirects.test.js

A video highlighting contribution process for MDN that was recently published includes a link to a 404-ing page. This redirects to the intended page.
I have no idea what I'm doing, so I basically copied from https://github.com/mdn/yari/pull/4845/.

Add redirect for contribution video

---

kumascript/src/api/web.js

When used as a verb, it should be spelled "fall back" and conjugated accordingly.

fix grammar in broken-link error message

---

client/src/document/toolbar/index.scss

Fixes https://github.com/mdn/mdn-minimalist/issues/795.  This PR removes the media query that makes the toolbar for developers only display on larger widths.  I've explained why I am making this change in the linked issue.

Display dev toolbar on any display width

---

kumascript/macros/InheritanceDiagram.ejs

The inheritanceDiagram macro was written for the MDN Wiki and therefore includes a variety of hacks that are no longer needed.
It amazingly (ab)used the "live sample" system to render SVGs because in the wiki you couldn't write SVGs directly. This means it generated svg code in a pre element which was then picked up for rendering by the live sample system and showed up on MDN in an iframe. We should avoid this hack now that we're out of the wiki. This PR renders the SVG directly and so iframes on roughly 250 MDN pages can be avoided(!).
The iframe hack also made it difficult to properly size the SVG viewbox. Without the iframe, the macro call parameters to define the width, height and offset are no longer needed. I'm opening an mdn/content PR to remove macro calls that contain these …

InheritanceDiagram: cleanup code; avoid iframe hack; use single parameter

---

client/src/ui/organisms/header/index.scss

| Before(`21px`) |  After(`27px`)  |
---|---
|<img src="https://user-images.githubusercontent.com/61609033/143691546-ae2f7f0d-a9c9-46e6-a740-26befad45797.png" width=350/>|<img src="https://user-images.githubusercontent.com/61609033/143691557-b05fb64a-6906-4d3f-a850-b7832be45517.png" width=350/>|
Closes #5009

increase main-menu-toggle icon size for better accessibility

---

kumascript/macros/JSRef.ejs

The `id` attribute value should be `Quick_links` and not `Quick_Links`
fix #5180

(fix:kumascript) fix jsref

---

build/document-extractor.js

When building a BCD document section, the support statement object don't receive the browser release date if the version is ranged.
The effect is that some of the browser compatibility table cells don't receive the `title` attribute with the browser version release date. Thus, the user get no tooltip when the cursor is over that cell.
For example, the `@mdn/browser-compat-data` says that the `api.CanvasRenderingContext2D.beginPath` method was added to Opera in "≤12.1" version (https://github.com/mdn/browser-compat-data/blob/main/api/CanvasRenderingContext2D.json).
Here is how it looks like in the browser (https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D):
This PR fixes the bug. After applying the fix:

Trim "≤" sign from version when searching for browser release date

---

client/src/document/ingredients/browser-compatibility-table/legend.tsx

This PR is a follow-up to #3997.  In that PR (and BCD 4.0.0), we introduced rendering support for a browser's preview release, where the background becomes blue and the word "preview" is replaced with the browser's preview channel name automatically.  https://github.com/mdn/browser-compat-data/issues/14656 was opened, however, wishing for a description to be added to the legend.
This PR adds a section for "preview" releases when applicable.

Add "preview" statement to BCD legend

---

client/src/document/ingredients/browser-compatibility-table/legend.tsx

A follow up to https://github.com/mdn/yari/pull/5207 that amends the text a bit ("channel" is a bit jargony) and places it with other parts of the legend that are more similar.

Browser compatibility table: revise preview legend copy

---

client/src/translations/dashboard/index.tsx

The "Date delta" columns of translation dashboard (e.g. `/ko/_translations/dashboard`) always show "Fresher than English" even for stale documents.
This PR fixes it by actually using `documentDetail.info.dateDiff`.

Fix translation dashboard showing "Fresher than English" for stale translations

---

kumascript/macros/EmbedLiveSample.ejs
kumascript/macros/page.ejs
kumascript/src/api/util.js
kumascript/tests/macros/EmbedLiveSample.test.js
markdown/m2h/handlers/dl.js
testing/tests/headless.index.spec.js

This change causes all `dt` elements in rendered HTML output from Markdown source to have ID values auto-generated based on their text content — in the same way all heading values in rendered HTML output have auto-generated IDs.
Related: https://github.com/mdn/content/pull/12165#issuecomment-1016873079 cc @wbamberg
---
This is an initial naïve proof-of-concept attempt at implementing ID generation for `dt` output — I’d be happy to further iterate on this patch as much as needed.
I’d also be happy to write up an additional patch for generating IDs in output from HTML sources (in addition to Markdown sources), if somebody can point me to where I’d need to patch — and if we think it’s actually important enough to have this for the HTML-source case, given that we have almost no HTML sources …

Auto-generate IDs for all <dt> elements

---

kumascript/macros/AddonSidebarMain.ejs

Correct the feedback reported in  [Content bug: /docs/Mozilla/Add-ons/Themes 404's #11214](https://github.com/mdn/content/issues/11214): the add-on sidebar menu item  "Themes" is linked to a non-existent MDN page not to the themes page on extension workshop.

Themes menu item link to extension workshop

---

kumascript/macros/InheritanceDiagram.ejs

Currently, the maximum number of rows when drawing an inheritance diagram is 2 and the maximum number of rectangles in a row is 4. Therefore, in some cases, the inheritance diagram doesn't fit in the svg viewbox:
- https://developer.mozilla.org/en-US/docs/Web/API/SVGTextElement
- https://developer.mozilla.org/en-US/docs/Web/API/SVGTSpanElement
- https://developer.mozilla.org/en-US/docs/Web/API/BackgroundFetchUpdateUIEvent
This PR adds the ability to draw a diagram for inheritance chain of any length.
This became possible by checking whether the connecting line and rectangle fit in the viewbox before drawing.
What was done to achieve the result:
- Added a utility function for drawing triangles.
- `lineWithTriangle()`, `connectingLineWithTriangle()`, `rectWithText()` functions are now pure. …

Add ability to draw diagram for inheritance chain of any length

---

build/document-extractor.js
kumascript/macros/Specifications.ejs

Fixes https://github.com/mdn/yari/issues/4704 • Related: https://github.com/mdn/yari/pull/5277
This change adds support for listing specs in the **Specifications** section based on the value of the `spec-urls` frontmatter key — instead of or in addition to listing specs based on the value of the `browser-compat` frontmatter key, or the value of the parameter passed to the `Specifications` macro.

Add support for 'spec-urls' frontmatter key

---

content/document.js

This PR directs `yarn content create` and `yarn content edit` to `index.md` rather than `index.html` when creating new files or editing existing ones.  The function altered is used only for these two commands, so no other portions of code are affected.  Fixes #5298.

Point create/edit commands to Markdown files

---

.github/workflows/performance.yml

Bumps Nodejs version to version 14 for `performance.yml` as this is a requirement for the latest version of `@lhci/cli`
fix #5327

(fix:testing) bump nodejs to v14

---

client/src/document/ingredients/browser-compatibility-table/feature-row.tsx

Some cells do not have notes causing `getNotes` to crash because `item` is undefined.
Ensure that a cell has notes before making it clickable.
As mentioned here https://github.com/mdn/yari/issues/5385#issuecomment-1055771641
I am hoping this will also resolve other similar issues that have been logged.
fix #5385

(fix:bcd) do not make cells clickable that do not have notes

---

client/src/document/organisms/sidebar/index.tsx

When scrolling the page to the very bottom, the height of the sidebar starts to grow:
https://user-images.githubusercontent.com/23465488/156199087-74e25870-1b8c-4a6d-8257-5fcd1e3b814c.mp4
This happens because `visible-height-of-header` CSS variable becomes less than zero when the sidebar starts scrolling off the page.
This PR prevents `visible-height-of-header` CSS variable to be less than zero and fixes incorrect behavior.

fix: sidebar starts to grow when it scrolls off page

---

client/src/search.tsx

Previously, the search form could only be submitted by pressing
the Enter key while having focus in the input field, and any
regular submits via the submit button were prevented.
This was meant to prevent submitting the form without a query term,
but it also prevented submitting it *with* a non-empty query term.
Fixes #5359.

fix(search): allow submitting non-empty query via button

---

client/src/ui/base/_themes.scss
client/src/ui/molecules/notecards/index.scss

Previously, notes (e.g. warnings) had a background color, which helped to
easily recognize them in articles. This got lost as part of the redesign.
This simply adds background colors to notes again.
Closes #5367.

feat(theme): add bgcolor to notes

---

client/src/document/index.tsx

Previously, "Overview" headings were not rendered. This caused the
corresponding table-of-contents item to not work.
Now, we render these headings again, provided they have an ID.
Closes #5476.

chore(render): restore overview heading

---

client/src/document/ingredients/browser-compatibility-table/browser-info.tsx
client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
client/src/document/ingredients/browser-compatibility-table/legend.tsx
client/src/document/ingredients/browser-compatibility-table/utils.ts

Reverts mdn/yari#5311
This is breaking BCD on production. Apparently, we use filtered BCD data on prod that's why this wasn't caught. We'll work on fixing this. @queengooborg fyi

Revert "Mark beta/nightly/planned browsers releases as preview"

---

client/src/document/hooks.ts
client/src/document/index.scss

The copy to clipboard icon is was not visible on light and dark modes.
The icon would only become visible on hover and even then, it was hard to
see in dark mode due to size and color.
<details>
<summary>Before</summary>
</details>
<details>
<summary>Afrter</summary>
This is the default state. When hovered, the icon will go to 100% opacity.
</details>
fix #5446
fix #5516

fix: improve visibility of copy to clipboard icon

---

client/src/ui/molecules/language-menu/index.tsx
client/src/ui/organisms/article-actions/index.tsx

Before we had a scenario where, on mobile, after having selected a languages, the article menu would not close.
This change ensures that both the language drop-down and the articles menu is always closed after a selection.
fix #5343

fix: always close article actions menu after choosing a language

---

client/src/ui/molecules/notecards/index.scss

Currently, the copy of the first paragraph in notecards is much smaller than the rest of the notecard.
This change ensures that it is always consistent.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
fix #5517

fix(typography): use regular font size in notecards

---

client/src/ui/atoms/switch/index.scss

We were relying on browser specific styles and it was broken in
webkit.
broken: ![webkit-broken](https://user-images.githubusercontent.com/3604775/157483545-639af48f-96c1-48d4-9704-a759e52d245c.png)
fixed: ![webkit-fixed](https://user-images.githubusercontent.com/3604775/157483555-2b1c7acc-4b0d-4b43-940f-385bc1d1f686.png)

fix switch margin

---

client/src/document/ingredients/browser-compatibility-table/feature-row.tsx

Previously, the BCD cells had a title on the cell and on the icon.
The cell title had the release date, and the icon its explanation.
For now, we keep two titles, but the release date is now on the version.
https://user-images.githubusercontent.com/495429/157484280-5d594426-270c-4849-a04a-7344440a4ee0.mov
Fixes #5371.

chore(bcd): move release-date title to version label

---

client/src/ui/molecules/notecards/index.scss

This PR resolves a second issue mentioned in #5522. It makes the icon align with the first line of the text.

fix(notecards): adjust icon position

---

client/src/document/index.scss

Restore underlines for `:link` and `:visited` states for links in the main document content.
fix #5394

(fix:a11y) restore underlines for links in main content

---

kumascript/macros/LearnSidebar.ejs

Fixes #5584
[Asynchronous JavaScript overview](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous) page is not accessible from the sidebar
Added the page to `LearnSidebar.ejs` 
---

Fix: make `Asynchronous JavaScript overview` page accessible from sidebar

---

client/src/document/on-github.tsx

There is a "Found a problem with this page?" at the end of each article, and it links to the article's source.
Previously, we would link to the so-called "rendered blob", which doesn't *really* show the source, just another *rendered* version.
Now, we link to the so-called "source blob", i.e. the raw markdown.
---
- I opened http://localhost:3000/en-US/docs/Learn locally.
- Then I verified that "Source on GitHub" now links to: https://github.com/mdn/content/blob/main/files/en-us/learn/index.md?plain=1
- And it no longer links to: https://github.com/mdn/content/blob/main/files/en-us/learn/index.md

fix(document): link to source, not rendered blob

---

client/src/document/toolbar/flaws.tsx

Fixes #5591.
`location` changes after a history back(`#_flaws` -> ` `); this causes the effect I removed in this PR to fire. But the `show` state remains `true`. Thus, `show && !hasShowHash === true`, which in turn pushes `#_flaws` to browsing history stack again and again, neutralizing user-made history stack popping (i.e. history back button).
We can consider `location` itself as a (global) state, especially since it's managed by `react-router`. By removing local `show` state, we don't have to worry about discrepancy between local (`show`) and global states (`location`) the effect block is trying to solve at all. There will be no local state at all.
---
Ran locally:
1. History back/forward closes or opens the toolbar. I can exit the document by history backs.
2. Navigating to a document …

fix(toolbar/flaws): avoid #_flaws navigation in useEffect

---

client/src/document/index.scss

Fixes #5511 
Callouts should not be center-justified. 
It's hard to read as it is not consistent with current document flow.
---
1. small callout
2. big callout
1. small callout
2. big callout

chore(callouts): left align content

---

client/src/document/index.scss

Fixes #5537 
Code section "Copied!" message is not visible for multiline code sections.
Change the message foreground and background colors according to theme.
The message was staying behind the code section due to z-index set to -1000. 
Colors are hardcoded so they don't change as per theme.
Remove z-index property from the CSS rule `..copy-icon-message`.
Also set color using CSS vars.
---
The message was not visible.
1. Light Theme:
2. Dark Theme:

fix(live-samples): make Copied! message visible + use theme

---

.github/workflows/dev-build.yml
.github/workflows/prod-build.yml
.github/workflows/stage-build.yml

Fixes #5594
The last modified date is currently incorrect for localized docs. As @alattalatta pointed out, this is due to the build workflows not fetching all of the git history with https://github.com/actions/checkout.
This PR is quite naive as it uses the same depth as mdn/content. Regarding the current warning, mdn/content has 8437 commits on main while mdn/translated content has 4922 commits so I'd think this is as acceptable.
If this is not, that means another way of computing the last edit should be found
Not yet, I need to setup `act` on my machine.

build(workflows): fetch full translated-content git history

---

client/src/search.tsx
client/src/ui/molecules/search/index.scss

Fixes #5424.
Search results could not be opened in a new tab (using middle-click or right-click).
This PR wraps all search results in a link to support this use case.
---
(No changes, but I'm attaching screenshots just for reassurance.)
---
1. Opened http://localhost:3000/en-US/docs/Web/HTML/Element/acronym locally.
2. Typed "dialog" in the search field.
3. Clicked right on the first item and "Open in new tab".
4. The article opened in a new tab, without navigating the current tab to that article.

feat(search): allow items to be opened in new tab

---

kumascript/README.md
kumascript/macros/Index.ejs

Index pages are no longer a thing in our content.
We shouldn't maintain outdated wiki macros. However, the macro can only be removed entirely if translations removed all calls to it, so let them know by raising a deprecation error.
Encourage translators to remove index pages with a MacroDeprecatedError.
Put the {{index}} macro on a page and see a flaw like "MacroDeprecatedError from index. Fixable 👍🏼" appearing.
https://github.com/mdn/content/pull/13770

Deprecate the {{index}} macro

---

kumascript/macros/manch.ejs

The {{manch}} macro brings nothing more since we migrated to Markdown. A regular Markdown link should be used instead.
@SphinxKnight detected it (while removing {{anch}} from fr/ and removed its 3-4 occurrences in en-US. It is now only used in translated-content.

Deprecate the {{manch}} anchor

---

README.md

A portion of the README that isn't code is marked as code. This is a minor adjustment to that. 😬 
|Main|This PR|
|---|---|
|<img width="855" alt="image" src="https://user-images.githubusercontent.com/9947422/157746003-33d390e8-6590-4be1-8741-d8ff623067de.png">|<img width="1028" alt="image" src="https://user-images.githubusercontent.com/9947422/157746104-fe51cc8b-5dcb-4f60-9351-33bab45e5806.png">|

docs(README): fix clone instruction indentation

---

client/src/app.scss
client/src/ui/organisms/article-actions-container/index.scss

Fixes #5620.
Previously, when the sticky breadcrumbs were shown on mobile, the currently targeted heading was covered by these.
By adding a `scroll-margin-top` to `:target` elements (as suggested by @e3dio), the browser will show the targeted heading below the sticky breadcrumbs.
---
---
1. Opened http://localhost:3000/en-US/docs/Web/CSS/:target#examples locally.

fix(layout): move :target below sticky header

---

content/document.js

When running the `content delete` command, we are able to pass a slug without including the locale part of the URL.  However, when passing a `--redirect` argument, one must type out the full URL.  This PR fixes this by allowing us to pass a slug without a locale to the `--redirect` argument.

Allow for simplified slugs in content delete --redirect arg

---

client/src/setupProxy.js
package.json
server/dev.js
server/middlewares.js
yarn.lock

Fixes #5663.
Ref: https://stackoverflow.com/a/42205955

fix(server): add webpack middlewares + don't proxy hot-update.json

---

kumascript/macros/FirefoxSidebar.ejs
kumascript/tests/macros/firefoxsidebar.test.js

Fixes #5096.
Thanks @schalkneethling for your time and help in making these changes!
Non-working links under `Firefox internals` and `Building and contributing`
As suggested in the issue, replaced the two menus `Firefox internals` and `Building and contributing` with `Firefox documentation` (see After screenshot), which now links to https://firefox-source-docs.mozilla.org/.
In addition, the following changes have been made:
- Renamed `Firefox developer release notes` (see Before screenshot) to `Firefox releases` (see After screenshot)
- Updated text for `Firefox developer release notes` to `Firefox release notes for developers` [title on landing page needs to be updated. I'll submit a separate PR on mdn/content.] - https://github.com/mdn/content/pull/14010
- Added a submenu to link to …

Firefox sidebar changes

---

client/src/ui/molecules/collection/menu.tsx
client/src/ui/molecules/notifications-watch-menu/index.scss
client/src/ui/molecules/notifications-watch-menu/index.tsx

Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/34.
https://user-images.githubusercontent.com/495429/159053932-0d7a2316-6ca2-45a9-8f7e-d282111f3280.mov
The problem here is that the `border-top` of the "Not watching" button was shown on top of the `outline`-"bottom" of the "Watch page" button.
See also: https://stackoverflow.com/q/11802399
1. Prefer `border-bottom` over `border-top`.
2. Move the `outline` (on focus) and `background-color` (on hover) effects to the `&-wrap` element inside the button.
The problem is that only buttons and input elements are focusable in those menus, because other elements like text ("Notifications") shouldn't be focusable. However, `open-on-focus-within` keeps the menu open **only as long as an element inside it has focus**.
1. Remove …

fix(notifications): improve watch submenu

---

client/src/ui/molecules/mandala/index.scss

There is a rotating mandala on the [home page](https://developer.mozilla.org/en-US/). But it is barely visible.
Changed font-weight from `lighter` to `normal`. 
Also added/set flags `animate` and `animateColors`.
It was not visible before.
View following image in fullscreen or in a new tab to see all the details:
Tested in Google chrome on Windows 10. 
And tested on all small smartphones available in Device Toolbar in Chrome dev tools.

Home page: made mandala visible

---

client/pwa/src/fetch-interceptors.ts

Fixes logging out/logging in issues when service worker is running. 
The service worker was trying to service requests going to /users/fxa out of the cache. (This wasn't detected locally as the requests are sent directly to api server localhost:8000 and not proxied).
Add path prefix /users/fxa to the api interceptor that directly forwards the request upstream. 
Tested locally.

Fix:Service worker intercepting fxa requests.

---

client/src/ui/molecules/guides-menu/index.tsx
client/src/ui/molecules/reference-menu/index.tsx

Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/40 as a workaround.
When navigating from the Notifications list to `/Web/` or `/Learn/`, we're getting a _Page not found_ error, even though yari doesn't even try to fetch the `index.json`. This did not affect links to `/Learn` (without a trailing slash).
Remove the trailing slashes from those links, especially as `/Web/` redirects to `/Web`.
---
1. Tested that the links still work.
2. Couldn't verify that it fixes the problem, but I'm very confident, as the _Guides_ menu (itself linking to `/Learn/`) has an item _MDN Learning Area_ that links to `/Learn` (without a trailing slash).

fix(menu): avoid links with trailing slash

---

client/src/ui/molecules/plus-menu/index.scss
client/src/ui/molecules/plus-menu/index.tsx

Fixes https://github.com/mdn/yari-private/issues/944.
On mobile, the top-level navigation items toggle their submenu. For this reason, the Guides and Learn menus have a submenu item that refers to the same location as the main item, but the Plus menu was missing such an item.
Added an "Overview" item on mobile-only.
---
### Mobile
---
1. Checked desktop and mobile views using DevTools responsive mode (see above).

fix(plus-menu): add mobile-only overview item

---

client/pwa/src/service-worker.ts

- Add users/fxa to skip handling for prefer online. 
- The request was being made as a post then as res.ok was false (for opaqueredirect) it was being made again and failing. 
---
- 1. Login on localhost. 2. Set service worker to 'prefer online' mode.  3. Logout (This should redirect without failing).

Fix redirect error on users/fxa

---

kumascript/macros/FirefoxSidebar.ejs

Adds remaining Russian translations for the new Firefox sidebar. Related to mdn/translated-content#4706
Ping @mdn/yari-content-ru and @schalkneethling for review

Update Russian translation of FirefoxSidebar

---

client/src/hooks.ts
client/src/plus/collections/collection-list-item.tsx
client/src/plus/icon-card/index.tsx
client/src/plus/notifications/index.scss
client/src/plus/notifications/notification-card-list-item.tsx
client/src/plus/notifications/notification-select.tsx
client/src/ui/molecules/collection/menu.tsx
client/src/ui/molecules/notifications-watch-menu/index.tsx

Fixes https://github.com/mdn/yari-private/issues/940 by greying out the menu items, instead of showing a toast when the action fails (which we might want to do additionally).
Watch/Save actions are not available when offline, but this is not indicated in the UI.
- Added a ~~`useOffline()`~~ `useOnlineStatus()` hook that returns two `isOnline` and `isOffline` flags.
- Used the `isOffline` flag to disable the buttons responsible for the Watch/Save menus.
- Used the `isOnline` flag to show some toolbars/buttons/dropdowns on the Collections/Notifications page conditionally.
---
---
1. Opened http://localhost:3000/en-US/docs/Web/API/Navigator/onLine in Edge.
2. Set Network > (Throttling) to Offline in the DevTools.

Disable watch/save and hide collection/notification management actions when offline

---

client/src/ui/molecules/user-menu/index.tsx

Adds a feedback link to the user menu pointing at the feedback repo on GitHub. I did not test this locally as my Kuma instance seems buggy but, technically it "should just work" 😄 
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/53.

chore(plus): add feedback link to user menu
