mdn/yari

- client/src/app.scss
Visit page https://developer.mozilla.org/en-US/docs/Web/API/MediaSource 
Scroll all the way down.
Notice the horizontal scrollbar looks thicker than the vertical one:
Set scrollbar height to `12px`.
```css
::-webkit-scrollbar {
width: 12px;
height: 12px;   /* <---- */
background-color: auto;
background-color: var(--scrollbar-bg,auto);
}
```
On Chrome 99.0 on Windows 10.
> fix: Horizontal scrollbar thicker than vertical

- client/src/ui/molecules/guides-menu/index.scss
- client/src/ui/molecules/guides-menu/index.tsx
- client/src/ui/molecules/reference-menu/index.scss
- client/src/ui/molecules/reference-menu/index.tsx
Resolves https://github.com/mdn/foxfooding-mdn-plus/issues/59.
- On mobile, the top-level menu items toggle the submenu.
- Both the References and Guides menus already have a submenu item that refer to the same page as the top-level item.
- Users that know the References / Guides links on desktop, cannot know how to get there on mobile.
Now, we show an "Overview / ..." item and hide the existing
"..." item on mobile, whereas we keep "..." on desktop.
---
Desktop does **not** change:
---
1. Open http://localhost:3000/en-US/ locally.
2. Test using Firefox DevTools responsive mode.
> chore(menus): add mobile-only overview items

- client/src/document/index.tsx
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/43.
Loading errors were shown outside of any layout.
Wrap the `LoadingError` root node in a `<div>`, reusing the layout for standard pages.
---
---
1. Opened http://localhost:3000/en-US/docs/404-city locally.
> fix(loading-error): wrap in standard-page layout

- .github/workflows/stage-build.yml
- client/src/constants.ts
- client/src/plus/offer-overview/index.tsx
- client/src/plus/offer-overview/offer-hero/index.tsx
- client/src/ui/organisms/top-navigation-main/index.tsx
- client/src/utils.ts
- docs/envvars.md
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/69.
- Below the "Coming to your region soon." teaser, there were no buttons.
- The allow list was completely reverted for testing purposes.
1. Restore the allow list.
2. Override it in on stage.
3. Add two buttons "What's included" and "Frequently asked questions" below the "Coming to your region soon." teaser.
---
---
1. Add `REACT_APP_PLUS_IS_AVAILABLE_OVERRIDE=false` to `.env`
2. Restart `yarn dev`
3. Open http://localhost:3000/en-US/plus/ locally.
**Note**: The FAQ page is added in https://github.com/mdn/yari/pull/5707, so not yet available in this branch.
> Restore allow list + override it on stage + add whats included to teaser

- build/document-extractor.js
Fixes #5492.
```diff
-<h3 id="curly_braces_"><a href="#curly_braces_" title="Permalink to Curly braces ({ })">Curly braces (<code>{ }</code>)</a></h3>
+<h3 id="curly_braces"><a href="#curly_braces" title="Permalink to Curly braces ({ })">Curly braces (<code>{ }</code>)</a></h3>
```
> chore(document-extractor): trim underscores from id

- build/spas.js
- client/src/plus/common/tabs.tsx
- client/src/plus/index.tsx
- client/src/ui/molecules/manage-upgrade-dialog/index.tsx
- client/src/ui/molecules/plus-menu/index.tsx
- client/src/ui/molecules/user-menu/index.tsx
- testing/integration/headless/map_301.py
- testing/tests/headless.plus.bookmarks.spec.js
- testing/tests/index.test.js
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/66.
The URLs for Notifications and Collections were inconsistent:
- `/plus/notifications` (plural)
- `/plus/collection` (singular)
Pluralize the collection urls: `/plus/collections`
**Note**: The kuma API routes are still singular, because technically users can only manage a single collection. But from a user perspective, the "Frequently viewed articles" could be considered a second collection.
---
1. Open http://localhost:3000/en-US/ locally.
2. Navigate to Collections via MDN Plus menu.
3. Navigate to Collections via User menu.
4. Searched for `collection` in VS Code with _Match Case_ and _Match Full Word_ to make sure I didn't miss any spot.
> chore(plus): move /plus/{collection => collections}

- client/src/plus/offer-overview/offer-overview-feature/index.scss
- client/src/plus/offer-overview/offer-overview-feature/index.tsx
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/71.
Previously, the Plus product page only described and visualized the features, without actually **naming** them.
We add a title on top of each feature description, similar to the title on the Plus docs.
---
---
1. Opened http://localhost:3000/en-US/plus/ locally.
> chore(plus/offer-overview): add feature titles

- client/src/plus/notifications/notification-card.tsx
- client/src/plus/notifications/notifications-tab.tsx
- client/src/plus/notifications/watched-items-tab.tsx
Correct instances where "collections" is used instead of "notifications".
fix #5741
> fix:copy ~ change instance mentioning collections in the notifications dashboard

- client/src/offline-settings/settings.tsx
- On autoupdate enabled a case was hit where the settings state would fall into a rerender loop (http://localhost:3000/en-US/offline-settings):
```
Error: Too many re-renders. React limits the number of renders to prevent an infinite loop.
```
- Added useRef to guard against rerender loop.
- In offline settings tab enabled auto-update. And wait for update to begin.
- After update complete click clear data, state should fall into STATE.updateAvailable. This won't now spin off into a rerender loop.
> Fix:Rerender loop on auto update enabled

- client/src/plus/common/api.tsx
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/42.
When searching the "Frequently viewed articles", the results were filtered using case-sensitive comparison, e.g. "api" didn't return "Screen Capture API".
This changes the filtering to use lowercase versions of both search terms and document title.
---
---
1. Open http://localhost:3000/en-US/plus/collection/frequently_viewed locally
2. Search for "walker" (because the list contained the "TreeWalker" article with a different casing).
> fix(collections): make fva search case-insensitive

- client/src/plus/offer-overview/offer-overview-feature/index.tsx
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/64.
When switching to the MDN Plus overview from a non-English article, the "Learn more" buttons lead nowhere.
For now, I hard-coded the `en-US` locale on the "Learn more" links.
The better, but less trivial solution would be to properly fallback to the English version.
---
1. Open http://localhost:3000/en-US/docs/Web locally.
2. Switch to French version.
3. Click on "MDN Plus" in the top menu.
4. Click on "Learn more".
> fix(offer-overview): override docs locale for now

- client/src/plus/collections/collection-list-item.tsx
- client/src/ui/atoms/limit-banner/index.tsx
- Closes collection edit menu on edit form submission
Resolves https://github.com/mdn/foxfooding-mdn-plus/issues/49
Also fix a little spacing issue in limit reached banner
Open collections tab. 
Click edit kebab menu on an item in the list. 
Make changes and click save or remove.
Observe the edit menu is closing.
> Fix: Close edit menu on submit

- build/spas.js
- client/src/constants.ts
- client/src/plus/collections/collections-tab.tsx
- client/src/plus/collections/frequently-viewed-tab.tsx
- client/src/plus/collections/index.tsx
- client/src/plus/common/tabs.tsx
- client/src/plus/index.tsx
- client/src/plus/notifications/notifications-tab.tsx
- client/src/plus/notifications/watched-items-tab.tsx
- client/src/plus/plus-docs/index.tsx
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/80.
Example: When visiting https://developer.allizom.org/en-US/plus, the browser tab quickly shows "Plus" before updating to "MDN Plus". This is because the SPA has an initial title, which is overwritten in the Plus component.
1. All MDN Plus pages should have the `| MDN Plus` suffix.
2. The SSR title should be equivalent to the dynamically set title.
3. The "Offline settings" should have the title _Offline Settings | MDN Plus_.
---
_This cannot be tested locally, because the SPA title doesn't apply there._
> fix(plus): rework document titles

- client/src/ui/molecules/collection/edit-collection.tsx
- client/src/ui/molecules/collection/menu.tsx
- copy/plus/features/collections.md
Updates the button copy for collections.
On the dashboard, it replaces "Remove Bookmark" with "Delete"
On a page pop-up, it replaces "Remove collection" with "Delete"
Also updates the reference in the docs
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/77
> fix:copy ~ fix button copy for collections

- client/src/homepage/static-page/index.tsx
- client/src/plus/index.tsx
1. When opening Plus pages for the first time, sometimes a "Page not found" message displays.
2. Same happens when opening Plus docs.
1. Return the Plus `Routes` during SSR, but with a `Loading` message.
2. Differentiate loading errors from actualy loading.
> fix(plus): avoid "Page not found" messages

- build/spas.js
- client/pwa/README.md
- client/pwa/package.json
- client/src/offline-settings/index.tsx
- client/src/offline-settings/settings.tsx
- client/src/offline-settings/update.tsx
- client/src/plus/index.tsx
- client/src/plus/offer-overview/offer-overview-subscribe/index.tsx
- client/src/ui/molecules/user-menu/index.tsx
- copy/plus/features/offline.md
Reopens https://github.com/mdn/yari/pull/5763, targeting `main` instead of merged `mdn-offline`.
1. The `document.title` of the Offline settings was not consistent.
2. The Offline settings was not in the `/plus` path and so it didn't have the Plus design.
3. The path `/plus/offline` is not taken yet, so we can use that instead of `/plus/offline-settings`.
1. Use _Offline settings_ consistently.
2. Move the Offline settings route into the `Plus` routes.
3. Rename the Offline settings path to `offline`.
---
---
1. Open http://localhost:3000/en-US/plus/offline locally.
> Fix some nits of the offline settings page

- client/src/banners/active-banner.tsx
- client/src/banners/banner.scss
- client/src/banners/ids.ts
- client/src/banners/index.tsx
- client/src/ui/base/_themes.scss
> fix:banner ~ adds mdn plus launch banner

- client/src/homepage/static-page/index.tsx
Fixes https://github.com/mdn/yari/issues/5793.
The right sidebar in the MDN Plus docs doesn't work. Clicking does not have the expected effect.
Remove a `scrollTo()` call that was obviously triggered when the hash changes. :(
---
1. Open http://localhost:3000/en-US/plus/docs/faq locally.
2. Click on the right sidebar links.
> fix(static-page): remove scrollTo effect

- client/src/plus/common/tabs.tsx
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/89.
The MDN Plus feature is called "Collections", but the tab should still be called "Collection".
Rename tab.
---
---
1. Open http://localhost:3000/en-US/plus/collections locally.
> chore(plus/collections): use singular for tab

- client/src/homepage/static-page/index.tsx
- client/src/plus/plus-docs/index.scss
Fixes https://github.com/mdn/yari/issues/5787.
The breadcrumbs on the MDN Plus docs didn't span the full width.
Make sure it does. 🤷 
---
---
1. Open http://localhost:3000/en-US/plus/docs/features/offline locally.
2. Switch between `main` and this branch to verify only the breadcrumb (article-actions-container) changes.
> fix(plus-docs): make breadcrumbs span full width

- client/src/homepage/static-page/index.tsx
- client/src/plus/plus-docs/index.tsx
Fixes #5796.
It appears that MDN Plus Docs page are sometimes hydrated with the wrong data.
Avoid using existing hydration data in client context.
---
To test, I have deployed this branch to stage (https://github.com/mdn/yari/actions/runs/2036537637).
> fix(static-page): avoid wrong hydration

- client/src/document/organisms/sidebar/index.tsx
Fixes an error in the browser console where a timeout was setting a class on an unrendered component.
> fix(sidebar): clear useEffect() timeout

- client/src/plus/plus-docs/index.tsx
The RelatedTopics component does not properly set a key on a loop.
> fix(plus-docs): add key to RelatedTopics

- client/src/utils.ts
Enables Plus subscribers to continue using Plus outside of the US/CA.
Previously, Plus features were disabled as soon as a user is outside of US/CA.
Now, Plus subscribers will be able to continue using Plus features as long as they are logged in.
**Limitation**: It still won't be possible to login outside of US/CA.
---
_Unable to test locally._
> fix(plus): assume available if subscriber

- client/src/banners/active-banner.tsx
- client/src/plus/utils.ts
- client/src/ui/atoms/subscribe-link/index.tsx
- client/src/ui/molecules/plus-menu/index.tsx
Fixes https://github.com/mdn/yari/issues/5821.
Fixes https://github.com/mdn/yari/issues/5820.
PS: This also fixes the issue that the "Overview" item in the mobile Plus menu was only available to subscribers.
1. "MDN Plus" in the banner looks like a link, but doesn't actually link to the MDN Plus product page.
2. "Get MDN Plus" doesn't have any effect on the MDN Plus product page.
3. "MDN Plus" in the Plus menu doesn't have any effect on the MDN Plus product page.
- (1.) Convert "MDN Plus" in the banner into a link.
- (2./3.) Make "Get MDN Plus" (and "MDN Plus") link to the Plans section, if we're on the product page.
---
1. Open http://localhost:3000/en-US/ locally.
2. Make sure that both "MDN Plus" (in the banner) and "Get MDN Plus" (in the toolbar) link to the (top of the) MDN Plus …
> Make "MDN Plus" a link in the banner + make Plus links refer to "Choose a plan" section when on product page

- content/document.js
#5813
See https://github.com/mdn/yari/issues/5813
This would help add redirects for deleted content which now lives outside of MDN (e.g. Fx DevTools)
I added a check to switch case when the URL is absolute (vs when it's not where it uses the existing logic)
---
---
I ran the following command from `yari`s directory:
`yarn tool delete Tools/3D_View fr --redirect https://firefox-source-docs.mozilla.org/devtools-user/3d_view/index.html` 
and then manually check the redirects file and ran 
`yarn tool validate-redirects fr --strict` (resp. w/ `yarn content` under `content`)
> feat(CLI): Make it possible to use an absolute URL when providing a redirect during a deletion

- client/src/app.scss
Fixes #5666 
In dark mode there is a white spot when both scrollbars are visible.
Add following CSS rule to set the scrollbar corner background color to current theme color:
```CSS
*::-webkit-scrollbar-corner {
background-color: var(--scrollbar-bg, auto);
}
```
Dark mode:
Light mode:
In Chrome Version 99.0.4844.82 (Official Build) (64-bit) on Windows 10
> fix: Dark mode weird white spot with both scrollbars visible

- build/spas.js
- testing/tests/index.test.js
1. No SPAs were built for the Plus docs.
2. The Plus product page had `<meta name="robots" content="noindex, nofollow">`.
1. Build SPAs for all Plus docs.
2. Flip the indexing flag for the Plus product page.
---
1. Opened http://localhost:3000/en-US/plus/docs/features/offline#clear-stored-data locally.
2. The page loaded instantly, rather than briefly showing blank content.
> fix: build SPAs for Plus docs + allow indexing Plus product page

- client/src/plus/collections/collections-tab.tsx
- client/src/plus/collections/frequently-viewed-tab.tsx
Adds copy to empty states for both curated collections and frequestly viewed pages.
Fix: https://github.com/mdn/foxfooding-mdn-plus/issues/88
> fix:collections ~ add copy to empty state

- client/src/ui/molecules/notecards/index.scss
Inline notecard is very big in size. 
Inline notecard needs to be of same size as other badges.
Utilize unused class `.notecard.inline` to reduce the size:
```css
&.inline {
padding: 0.125rem 0.375rem 0.125rem 1.5rem;
margin: 0.5rem;
font: var(--type-body-s);
}
&.inline::before {
top: 0.1875rem;
left: 0.2rem;
display: block;
width: 0.8rem;
height: 0.8rem;
}
```
In Chrome on Windows 10.
> Inline notecard: reduced its size

- client/src/ui/molecules/plus-menu/index.tsx
Extracted from partially reverted #5823.
The "Overview" item in the Plus menu, which is only visible on mobile, was only shown to subscribers.
Moved the item out of the `isAuthenticated` section.
---
---
1. Opened MDN locally and logged out.
2. Used Responsive Design Mode to verify how it looks.
> fix(plus-menu): make overview public

- client/src/banners/active-banner.tsx
- client/src/plus/utils.ts
- client/src/ui/atoms/button/index.tsx
- client/src/ui/atoms/internal-link/index.tsx
- client/src/ui/atoms/subscribe-link/index.tsx
- client/src/ui/molecules/guides-menu/index.tsx
- client/src/ui/molecules/plus-menu/index.tsx
- client/src/ui/molecules/reference-menu/index.tsx
Fixes #5820.
This PR is based on #5823, which I reverted on Friday, because it didn't resolve the issue on staging, even though it worked locally.
1. "MDN Plus" in the banner looks like a link, but doesn't actually link to the MDN Plus product page.
2. "Get MDN Plus" doesn't have any effect on the MDN Plus product page.
3. "MDN Plus" in the Plus menu doesn't have any effect on the MDN Plus product page.
4. The `Link` component cannot be used to refer to a specific section of a page using a hash.
- (1.) Convert "MDN Plus" in the banner into a link.
- (2./3.) Make "Get MDN Plus" (and "MDN Plus") link to the Plans section, if we're on the product page.
- (4.) Add an `InternalLink` component that returns a `Link` or an `a`nchor, depending on whether the link target contains a hash or not, and …
> Make Plus links refer to "Choose a plan" section when on product page

- client/src/banners/active-banner.tsx
Fixes #5866.
Hooks must be called only within components or other hooks.
Turns `SendCTAEventToGA` into a `useSendCTAEventToGA` hook.
See repro steps in the issue. I <kbd>Ctrl</kbd>+clicked the _Learn more_ link and the MDN tab did not have a console complaint from React.
Sending this as a quick fix for #5866 even though the issue isn't marked as accepted. No worries if you don't want it; I just thought it'd be fun to get started on the repo & make it a quicker fix if you do accept the issue!
> fix: obey React rules of hooks in active banner

- libs/constants/index.js
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/92.
Firefox Accounts falls back to Gravatar images, if no Profile picture is selected, but these were not shown properly on the MDN site, because Gravatar was not part of our Content-Security-Policy.
Add `*.gravatar.com` to our `CSP_DIRECTIVES` constant.
**Note**: While the [Gravatar docs](https://en.gravatar.com/site/implement/images/) mention the domain `www.gravatar.com`, the issue above mentions `secure.gravatar.com`, and [this page](https://rapidsec.com/csp-packages/gravatar) (not verified) recommends `*.gravatar.com` for `image-src`, so I decided to go with this wildcard, to be on the safe side.
---
_Did not test, as it's a trivial change, similar to https://github.com/mdn/yari/pull/5786._
> fix(csp): add *.gravatar.com to img-src

- kumascript/macros/EmbedInteractiveExample.ejs
Fixes #5868 
#5667 added a string which was not localizable, thus mixing localized content with English 
This adds a `mdn.localStringMap` to leverage a simple and existing mechanism to localize this new string
---
---
I tested it on a local environment and checked it worked correctly on an English (displaying the original "Try it") and on a French page (with the "Exemple interactif" string that I provided)
> fix: #5868 - Adds localization for ELS new heading

- build/document-extractor.js
When building Specifications sections, if a spec URL is not found in browser-specs, fall back to looking up the spec title in `SpecData.json`. Related: https://github.com/mdn/content/pull/13170#discussion_r812657490
> Make spec-name lookup fall back to SpecData if not in browser-specs

- kumascript/macros/EmbedInteractiveExample.ejs
Related to #5874 and #5868
Adds `es` localization for ELS new heading in EmbedInteractiveExample "Try it"
Related to #5874 and #5868
Missing `es` string which was not localizable, thus mixing localized content with English
added a `es` string which was not localizable, thus mixing localized content with English
---
---
I tested it on a local environment and checked it worked correctly on an English (displaying the original "Try it") and on a Spanish page (with the "Pruébalo" string that I provided)
> Related to #5868 - Adds localization for ELS new heading [es]

- client/src/ui/molecules/mandala/index.scss
Mandala decoration characters are selectable. 
Buy double clicking or dragging mouse on home page user can accidentally select mandala characters. It doesn't look good.
Use `user-select: none` property in the CSS rule.
---
The video shows both before and after cases:
https://user-images.githubusercontent.com/87750369/161205188-8c57e51c-452d-4598-b971-5b1531e5d066.mov
In Google Chrome on Windows 10.
> fix: made mandala characters non selectable

- client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
- client/src/document/ingredients/browser-compatibility-table/utils.ts
Fixes #5709
When a vendor prefix was added after full support already existed for compatibility reasons, it showed as if it was needed.
Stop showing vendor prefix symbol in un-expanded table if full support already existed. 
---
https://developer.mozilla.org/en-US/docs/Web/CSS/flex-flow#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/API/Window#browser_compatibility
http://localhost:3000/en-US/docs/Web/CSS/flex-flow#browser_compatibility
http://localhost:3000/en-US/docs/Web/API/Window#browser_compatibility
> fix(bcd): hide the prefix symbol if feature has unprefixed full support as well

- client/src/document/hooks.ts
- client/src/document/organisms/toc/index.tsx
This makes the "In this article" table of contents (TOC) more reliable.
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/63.
Previously, we determined the currently viewed section
"In this article" by listening to the scroll event.
Now, we use an [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver) to get notified when relevant sections move in/out of the viewport.
---
https://user-images.githubusercontent.com/495429/160675734-fb89d918-d392-4c5c-9664-d76aeb401ad2.mov
https://user-images.githubusercontent.com/495429/161737619-3e99bc58-12a5-40b0-a592-30aad4062e01.mov
---
Tested scrolling locally on these pages:
- http://localhost:3000/en-US/plus/docs/faq
- http://localhost:3000/en-US/docs/Web/API/IntersectionObserver
> fix(toc): migrate to IntersectionObserver

- client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
- client/src/document/ingredients/browser-compatibility-table/utils.ts
This PR replaces the `isRoot` property of BCD features with a `depth` property instead, which should provide a better base for #5851.  The `isRoot` property is also non-functional; properties on the third depth are marked as `isRoot` when they shouldn't be.
Before, this PR attempted to perform a similar change as in #5851 as described below.  It has now been stripped of style changes in favor of the other PR.
<hr />
~~This PR adds a small left margin to the names of child features within BCD tables to better represent parent-child relationships between features.  This should help reduce confusions such as https://github.com/mdn/browser-compat-data/issues/15608.~~
~~Before:~~
~~After:~~
~~To check to make sure the table is still functioning as intended, I checked the following two pages:~~ …
> BCD tables: replace `isRoot` with `depth`

- client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
- client/src/document/ingredients/browser-compatibility-table/index.scss
Fixes #5843 and fixes #3321
There is no indication of sub-features in the browser compatibility table
Indents sub-features in the browser compatibility table using border-left-width
---
> Indicate subfeatures in compatibility table through indenting

- client/src/homepage/index.tsx
Replace color-scheme featured article on the homepage with the revert-layer article.
fix #5890
> fix:featured-articles ~ swap color-scheme featured article with revert-layer

- client/src/document/molecules/localized-content-note/index.tsx
Updating the link to activate a locale
Current link in the banner follows to wrong target. You can find this link in German or Polish translations, for example [here](https://developer.mozilla.org/pl/docs/Web/HTML). This pr updates the link
> Update the link to activating a locale

- client/src/document/ingredients/browser-compatibility-table/index.scss
Fixes #5924
The browser history on mobile is black even in dark mode
Specifically set the color to --text-primary.
---
> Fix dark mode on mobile in BCD

- kumascript/macros/FirefoxSidebar.ejs
Related to https://github.com/mdn/yari/issues/5096
Add `es` localization for FirefoxSidebar.ejs
Related to https://github.com/mdn/yari/issues/5096
New menu entries that need `es` strings.
added `es` strings
---
---
I tested it on a local environment and checked it worked correctly
> Related #5096, Adds [es] for FirefoxSidebar.ejs

- kumascript/macros/CSSRef.ejs
Fixes #5764 
CSSRef macro to build the sidebar links based on folder sorting so property such as `border`, `background`, etc is placed on the bottom after their `border-*`, `background-*`, etc content.
After get the whole properties content, we sort it first using [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) to make sure the `border`, `background`, etc comes first.
---
> fix(cssref-macros): sort css properties content before render

- client/src/document/organisms/sidebar/index.scss
- kumascript/macros/DeprecatedBadge.ejs
- kumascript/macros/ExperimentalBadge.ejs
- kumascript/macros/NonStandardBadge.ejs
- kumascript/tests/macros/Deprecated.test.js
- kumascript/tests/macros/ListGroups.test.js
- kumascript/tests/macros/apiref.test.js
Fixes the remainder of number 3 (deprecated icon is different in badges.svg) from #5571 and just seems nicer
Also fix #5844
Stop using badges.svg.
Uses the same type of code used for the BCD
---
> chore(icons): replace badges.svg with icon classes

- client/src/document/on-github.tsx
This is a follow-up to https://github.com/mdn/yari/pull/5887. `Doc.mdn_url` is a relative URL (path) — so to pass the full MDN URL in the _“Report a problem with this content on GitHub”_ link, we need to prefix “https://developer.mozilla.org” to `Doc.mdn_url`.
> Pass full MDN URL in “Report a problem with this content on GitHub” link

- client/src/search-utils.ts
- client/src/search.tsx
Fixes #5935
Vimium overrides / by default.
Add another keyboard shortcut for search
Locally on Firefox, tried Ctrl+k and Ctrl+K (capital and lowercase). Locally on Chrome, tried ⊞ + k (which is the metaKey for Chromium browsers on Windows, like Cmd is for browsers on Mac: see https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey)
> Add Ctrl/Cmd+K as a Keyboard Shortcut for search

- kumascript/macros/SVGRef.ejs
SVG sidebars don't work anymore. They appear in the main content:
This is caused by the incorrect capitalization of the `id`. This fixes it.
(There should be more work on these sidebars, but that's the minimal set to fix the current problem.)
> Fix SVG sidebar (displays in main content)

- client/src/constants.ts
- client/src/hooks.ts
- server/static.js
- testing/content/files/en-us/web/unsafe_html/index.html
Fixes #5989.
Some kuma API routes expect a trailing slash, but we omitted it in two locations, causing a delay due to an unnecessary HTTP 301.
Update those routes to match what kuma expects.
*Note*: The `/whoami` endpoint does neither expect nor support a trailing slash (because it's a single route, not a router with a `/` route).
---
---
1. Login to MDN Plus.
2. Disable MDN Offline (to avoid side-effects).
3. Open http://localhost:3000/en-US/plus or any other page.
4. Open the "Network" tab of the DevTools, and filter for "XHR" requests.
5. Open the MDN Plus user menu.
> fix(api): use trailing slash where expected

- content/utils.js
- kumascript/index.js
The `lru-cache@del` method is deprecated since `7.0`.
> https://github.com/isaacs/node-lru-cache/blob/ff322ad364c727a419a77ad962915a625aaf1b52/index.js#L730
Use `delete` instead of `del`.
---
N/A
---
I just run `yarn run test`. 
And I checked the current [lru-cache@del](https://github.com/isaacs/node-lru-cache/blob/ff322ad364c727a419a77ad962915a625aaf1b52/index.js#L730) method. It's just returns delete method. So, nothing affects the result.
Thank you :)
> refactor: use `delete` instead of `del` in the `LRU` package

- kumascript/macros/h3_gecko_minversion.ejs
In mdn/content#15086, I removed the last occurrence of this macro in en-US. Time to mark it deprecated so that it doesn't reappear. [Still [60 occurrences in translated-content](https://github.com/mdn/translated-content/search?q=h3_gecko_minversion)]
cc/ @schalkneethling  : what's the process to get a macro removal on the radar of l10n for purging it out of translated-content, so that it actually can be removed from Yari's KumaScript?
> Deprecated h3_gecko_minversion

- client/pwa/src/db.ts
- client/pwa/src/service-worker.ts
- client/pwa/src/unpack-cache.ts
Phase 1 of 3, extracted from https://github.com/mdn/yari/pull/5955.
The ServiceWorker starts to use IndexedDB, but still accepts the
local version from the client as a fallback on the update message,
and still emits messages to inform clients about the status.
For the ServiceWorker, however, the IndexedDB is the truth.
Edge:
1. Deleted MDNOfflineDB database.
2. Stopped and unregistered ServiceWorker.
3. Went to MDN Offline page.
4. Enabled  offline storage.
5. Downloaded content.
6. Verified that IndexedDB and LocalStorage had the same local version.
7. Cleared content.
> chore(pwa): manage ContentStatus in IndexedDB, but be backward-compatible (Phase 1 of 3)

- client/src/document/index.tsx
- client/src/homepage/static-page/index.tsx
- client/src/page-not-found/index.scss
- client/src/page-not-found/index.tsx
- client/src/site-search/form.tsx
- client/src/site-search/index.scss
- client/src/site-search/index.tsx
- client/src/ui/atoms/page-content/index.tsx
- client/src/ui/molecules/grids/_document-page.scss
Fixes #5986.
Both the PageNotFound page and the Search page did not have the regular MDN layout.
Apply the regular page layout to those pages.
---
*Note*: The top nav search results are currently always visible when there is a search query, which may cause an overlap with the dedicated search results using the common layout. This will be fixed by #5988.
---
1. Opened [non-existent page](http://localhost:3000/en-US/test) locally.
2. Performed [search](http://localhost:3000/en-US/search?q=test) locally.
> chore(ui): migrate 404 and search to page layout

- kumascript/macros/LearnSidebar.ejs
Fixes mdn/translated-content#1882
The translation about `How CSS is structured` is not correct in `zh-CN`. Correct it by keeping the same with the title of this article.
Correct the translation.
---
> correct the `zh-CN` translation

- client/src/document/ingredients/browser-compatibility-table/index.scss
Address a couple of bugs with the BCD table since the readability update.
> fix:bcd ~ address a couple of regressions since readability update

- client/src/document/index.tsx
- client/src/document/ingredients/prose.tsx
- testing/content/files/en-us/web/externallinks/index.html
- testing/tests/index.test.js
Makes sure we use `<section>` elements with ~~`aria-describedby`~~ `aria-labelledby` in MDN articles.
Previously, we were just using `<div>`s to wrap MDN article sections, which is not ideal.
I replaced the `<div>`s with `<section>`s and added ~~`aria-describedby`~~ `aria-labelledby` where possible.
---
---
I did not see any differences, **but** I did not check for potential CSS rules targeting those `div`s.
> fix(document): use <section>s with aria-labelledby

- client/src/document/index.scss
Fixes #6033
On https://developer.mozilla.org/en-US/docs/Web/API/SVGElement, the properties without associated pages and the sidebar elements without associated pages don't have href's, so are still indistinguishable from normal links until hovered over.
This is what I was referring to with [this comment](https://github.com/mdn/yari/issues/5546#issuecomment-1096865094).
Add &:not([href]) to the CSS rule for missing links and use text-decoration itself since sidebar links don't have underlines ever.
---
> Highlight missing links without hrefs

- package.json
Fixes https://github.com/mdn/yari/issues/6006.
The`watch:ssr` script is used in Procfile.dev, but was accidentally removed.
Restore the script.
---
(n/a)
---
> fix(ssr): restore watch script

- build/spas.js
- client/src/homepage/index.tsx
- client/src/homepage/latest-news/index.scss
- client/src/homepage/latest-news/index.tsx
Fixes https://github.com/mdn/yari/issues/6020.
Previously, we had to link manually to Hacks posts.
Now, we show a list of Hacks posts directly on the homepage.
---
---
1. Run `yarn dev` (which runs `yarn tool spas`).
1. Open http://localhost:3000/en-US/_homepage locally.
> chore(homepage): add LatestNews with Hacks articles

- client/src/search.tsx
Fixes a React warning when focusing the Search locally and the Search index was not yet initialized.
An element in the `InnerSearchNavigateWidget` component did not have a key. This caused a React warning:
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `InnerSearchNavigateWidget`. See https://reactjs.org/link/warning-keys for more information.
div
InnerSearchNavigateWidget@http://localhost:3000/static/js/main.chunk.js:17227:7
SearchErrorBoundary@http://localhost:3000/static/js/main.chunk.js:17653:5
SearchNavigateWidget
div
Search@http://localhost:3000/static/js/main.chunk.js:28486:7
div
TopNavigationMain@http://localhost:3000/static/js/main.chunk.js:31288:7
div
Container@http://localhost:3000/static/js/main.chunk.js:18909:7
header …
```
> fix(search): add missing key to nothing-found element

- client/src/document/on-github.tsx
- client/src/document/organisms/metadata/index.scss
Fixes #6000. Very similar to #4107 (which regressed during the redesign).
Lighthouse flags it when heading elements are not in a sequentially-descending order.
Switch h4 to h3 with styling making it look like an h4.
---
User interface not changed (CSS rules were were put in place to ensure that).
Ensured the user interface was unchanged and ran a Lighthouse report in Chrome after making the changes. That report did not flag this.
> fix(metadata): Switch heading for Github reporting links to be in sequentially-descending order

- kumascript/macros/interface.ejs
We have removed the `interface` macro from mdn/content:
```
rg "\{ *interface" | wc -l
0
```
Still 288 in mdn/translated-content. 
Meanwhile, we want to be sure they don't reappear in mdn/content, so marking it as deprecated will warn us in the flaw system if a new one is added. (As we have 0 deprecated macros left in mdn/content, we will notice it.)
For translators: this was used to mark internal Firefox interfaces, so this should be used only for links to outdated/removed parts of mdn (E.g. `{{interface("nsIDOMWindowUtils")}}`) Replacing them by the argument in codeface should do it: (E.g. `nsIDOMWindowUtils`).
> chore(macros): mark interface.ejs as deprecated

- .github/workflows/dev-build.yml
- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
Fixes https://github.com/mdn/yari/issues/5947.
Previously, we had to invalidate the CDN manually, or wait for the TTL.
Now, CDN invalidations are created automatically after build deployments.
---
1. Reduced the `stage-build.yml` workflow to the "Configure AWS Credentials" and "Invalidate CDN".
2. Triggered the action manually (see [result](https://github.com/mdn/yari/runs/6099994054?check_suite_focus=true)).
> build(workflows): invalidate CDN after deployment

- client/src/document/index.scss
- client/src/document/ingredients/prose.tsx
Fixes #6042.
#5908 changed the document structure by wrapping section content in `<section>` elements, but one CSS rule targeted the section content using `> div:not([class])`, which no longer matched section content in a `<section>`.
- Mark section content with a CSS class (`.section-content`).
- Use that CSS class to set style specific to section content.
---
---
1. See http://localhost:3000/en-US/docs/Learn/CSS/Building_blocks/Selectors#summary locally.
> fix(document): target section content with className

- client/src/ui/organisms/footer/index.tsx
Issue TBD
When I ran Grammalecte to review localization, I stumbled upon this one.
The label doesn't follow GitHub's case
Just fixed the case
Ran Grammalecte on a locally served page to ensure the fix worked.
> fix: typo / GitHub case in a11y label

- client/src/document/index.scss
remove the underscore added to `h1` elements on the reference and learn documentation pages.
fix #6044
> fix:style ~ remove underscore from h1 elements in reference docs

- .prettierrc
- testing/content/files/en-us/markdown/tool/h2m/expected.md
This reverts commit 5111d71e3330c28f4c22886d77dfdda660d6df4c.
Interim fix for https://github.com/mdn/yari/issues/6075
> Revert "chore(prettier): automatically wrap markdown files"

- client/pwa/src/db.ts
- client/pwa/src/service-worker.ts
- client/src/offline-settings/clear.tsx
- client/src/offline-settings/db.ts
- client/src/offline-settings/mdn-worker.tsx
- client/src/offline-settings/settings.tsx
- client/src/offline-settings/update.tsx
- package.json
- testing/tests/offline-db.test.js
- yarn.lock
Phases:
1. https://github.com/mdn/yari/pull/5980
2. https://github.com/mdn/yari/pull/5955
3. TODO
Fixes https://github.com/mdn/yari/issues/5920.
Previously, we managed state regarding the Offline Content (e.g. what version do we have locally, what is the latest version remotely, what are we currently doing) in the Client, by handling messages from the Service Worker.
However, not every message was necessarily handled, because clients cannot handle messages while performing a classic page navigation. This caused an inconsistent state, i.e. client and Service Worker were not on the same "page".
Now, we manage the ContentStatus exclusively in the ServiceWorker, persisting it in the IndexedDB, and access it in the Client.
Details:
- Added a `contentStatusHistory` table to the `MDNOfflineDB` …
> chore(offline-settings): use ContentStatus from IndexedDB (Phase 2 of 3)

- markdown/h2m/index.ts
- testing/content/files/en-us/markdown/tool/h2m/expected.md
Fixes #6075.
The Prettier config change is unexpectedly affecting Markdown files from `h2m` command.
This PR will override Prettier's [prose wrap](https://prettier.io/docs/en/options.html#prose-wrap) config to a default value (`preserve`) for `h2m`'s `remark-prettier`.
I've ran `yarn md h2m web/api/document --mode keep --locale ko` before and after the change. I can confirm that this PR will restore the old behavior which I seek.
Sidenote, I'm willing to ~~change the commit~~ change the title to follow Conventional Commits but not quite sure how to actually write it. `fix(prettier)`, `chore(prettier)`, or `chore(markdown)`?
> fix(h2m): override Prettier config to preserve Markdown wrapping

- client/src/document/ingredients/browser-compatibility-table/index-mobile.scss
- client/src/document/ingredients/browser-compatibility-table/index.scss
Bc-history cell in bc table has extra left border.
Remove excess border at left.
---
---
1. Visit https://developer.mozilla.org/ru/docs/Web/CSS/:where for the test
> fix(bcd): remove double border from bc-history

- client/src/document/organisms/toc/index.tsx
Fixes #6041.
In #5908, we changed the document structure by wrapping (most) document sections in a `<section>` element. This caused a regression on the TOC highlighting. The TOC wrongly associated the new `<section>` elements with the _previous_ heading, causing the previous TOC entry to be highlighted.
This was because the section's _actual_ heading is a child element of the section itself, and therefore essentially comes _after_ the section element. This goes against the heuristic of the TOC implementation, which assumes that headings precede corresponding content.
Don't consider `<section>` as relevant elements for determining the currently visible element.
_Note_: It would be nice to only observe `<section>`s or (even better) `<div class="section-content">` instead, but this doesn't …
> fix(toc): ignore <section>s when observing visible elements

- client/src/document/index.scss
- client/src/document/ingredients/browser-compatibility-table/index-desktop-xl.scss
- client/src/document/ingredients/browser-compatibility-table/index.scss
- client/src/homepage/latest-news/index.scss
- client/src/homepage/recent-contributions/index.scss
- client/src/plus/offer-overview/offer-overview-feature/index.scss
- client/src/ui/_vars.scss
- client/src/ui/molecules/breadcrumbs/index.scss
- client/src/ui/molecules/grids/_document-page.scss
- client/src/ui/organisms/article-actions-container/index.scss
- client/src/ui/organisms/footer/index.scss
Required for #6074.
We only have four responsive breakpoints at 426 / 769 / 1200 / 1441 px, with a big gap between 760 and 1200 px. This does not give us enough flexibility for elements that are slightly larger than ~769px.
This PR inserts a new `screen-lg` breakpoint at 992px (adopted [from Bootstrap](https://getbootstrap.com/docs/5.0/layout/breakpoints/#available-breakpoints)), renaming the existing `screen-{lg,xl}` breakpoints to `screen-{xl,xxl}`.
---
---
_Not tested._
> chore(css): insert breakpoint between screen-md + screen-lg

- client/src/document/ingredients/browser-compatibility-table/index.tsx
This PR updates the link to file an issue in BCD to use the new form-style template we've just merged into BCD, similar to what mdn/content uses.
> Adapt BCD issue link to new issues template

- client/public/index.html
- client/src/ui/base/_themes.scss
- client/src/utils.ts
- libs/constants/index.js
Fixes #6101, based on #6054.
Chrome was always showing light scrollbars, because it apparently relies on the [`color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) property being set.
1. Set the `color-scheme` property on the `:root` element (i.e. `document.documentElement` or the HTML element).
2. Set the `.dark` and `.light` classes on the `:root` element, not the `body` element.
3. Apply dark/light theme based on [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) only if `:root` element has no `dark`/`light` class.
---
---
1. Opened http://localhost:3000/en-US/docs/Web/CSS/@media/prefers-color-scheme locally in Chrome.
2. Switched theme between "OS Default" (and then used OS settings to switch), "Light" and …
> fix(theme): set color-scheme

- client/src/banners/active-banner.tsx
- client/src/banners/banner.scss
Hermina asked to make these small tweaks to the copy and style of the launch banner.
* change markets to countries
* Do not bold `and` and `your`
> fix:banner - small copy update to launch banner

- kumascript/macros/JSRef.ejs
Add `WebAssembly .Tag` and `WebAssembly .Exception` to the sidebar. These were added to spec recently and are in FF100.
You can see related docs work in https://github.com/mdn/content/issues/14392
These were missing from the sidebar.
Isn't this how JS sidebar works?
---
I did not.
> JSRef macro: Add WebAssembly .Tag and .Exception

- client/src/document/hooks.ts
Fixes #6113.
Older browsers that don't support the IntersectionObserver got a blank page on pages with a TOC since  #5852. This was because
Be backwards-compatible by checking for IntersectionObserver support before using it.
---
_Not relevant._
---
1. Open http://localhost:3000/en-US/docs/Web/API/ResizeObserver locally and make sure the TOC highlighting still works.
> fix(hooks): check for IntersectionObserver support

- client/src/search.tsx
- client/src/ui/molecules/search/index.scss
Fixes my issue in #6107, though I'm unsure if that's the reported issue. I can't find any other cause for that issue, but I'm mainly unsure since this affects right click and middle click as well, but the OP for that issue said those were not affected.
Ctrl+click was not working when clicking the non-text part of search results
Change the links in the search results to take up the whole div (using `display: block;`, moving the padding from the div to the link, moving the lines of text for site search inside the links, and switching the site search links to anchor elements with similar code to the search results).
---
Locally by ctrl-clicking the edge of search results, including site search results.
> Make whole div area part of search result link

- build/sync-translated-content.js
- content/constants.js
- content/document.js
- content/index.js
- package.json
- server/flaws.js
We started to switch for performance, so let's finish it.
glob() is slow.
Use fdir() everywhere.
> perf(build): use fdir instead of glob

- client/src/ui/base/_themes.scss
Fixes a design regression on the MDN Plus product page.
In #6102, I decoupled the dark theme from the light theme, but I didn't copy all missing variables that were only present in the light theme. Accordingly, some things didn't look like they should in the dark theme.
Copy over those missing variables.
---
---
- Opened http://localhost:3000/en-US/plus locally.
- Verified that the page looks like before.
> fix(themes): copy missing vars from light to dark

- client/src/document/organisms/sidebar/index.scss
Fixes #6144.
When we implemented sticky headers, we encountered the issue that the sidebars scrolled behind the article-actions-container, and added a `top` value as a workaround. However, we did not adjust the sidebar height (`100vw`), causing the bottom of the sidebar to be hidden.
- Reduced the sidebar max-height by the sidebar offset.
- Extracted CSS variables `--offset` and `--max-height` for this.
---
---
1. Opened http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys locally.
2. Scrolled the sidebar down, without scrolling the main content.
3. Verified that the last sidebar item is visible.
> fix(sidebar): reduce max-height by offset

- build/syntax-highlight.js
Used in the page templates `files/en-us/mdn/structures/page_types/` and causing a warning running the build
---
---
> build(syntax-highlight): allow Markdown and CSharp Prism grammar

- package.json
The `cssesc` dependency is unnecessary. 
It is never using after https://github.com/mdn/yari/pull/4481
Delete `cssesc` dependency from the `package.json`
---
N/A
---
I confirmed run tests and build.
```
$ yarn run test
$ yarn run build
```
Other dependencies depend on `cssesc: 3.0.0`. So `yarn.lock` is nothing change.
---
Thank you :)
> build(deps): remove unused cssesc

- client/src/document/molecules/localized-content-note/index.tsx
Points the URL for localized content notes to the MDN/Contribute/Localize page and section of the corresponding locale with an en-US fallback URL.
The localized content notes on translated pages currently all lead to `/en-US/docs/MDN/Contribute/Localize#active_locales` even when the `MDN/Contribute/Localize` page exists in the locale (e.g. these notes on French pages could/should point to `/fr/docs/MDN/Contribute/Localize#langues_actives`).
This PR adds the locale Contribute page URL (with the section anchor, e.g. `#langues_actives`) to the JSON if one exists sets the note's `url` to either the locale URL or the en-US fallback URL.
---
For French:
For Korean (no corresponding page/URL, points to en-US fallback):
---
I tested with yari on my local machine by opening several translated …
> fix(localized-content-note): link to page/section of locale

- kumascript/macros/TODO.ejs
Once mdn/translated-content#5180 is merged, there won't be any occurrence of the macro `{{TODO}}` left. We can then delete it:
In mdn/content:
```
rg "\{ *TODO" | wc -l
0
```
In mdn/translated-content (before the merge of mdn/translated-content#5180):
```
rg "\{ *TODO"
files/de/web/css/align-items/index.html
68:<p>{{ TODO() }}</p>
files/ko/mdn/guidelines/writing_style_guide/index.html
779:<p><strong>{{TODO("Finish this once we finalize the landing page standards")}}</strong></p>
```
> chore(macros): remove TODO.ejs

- client/src/page-not-found/fallback-link.tsx
Fixes #5615
Often, MDN links are given to users with their localization in the path from Firefox UI. Some UI links require redirects to work. If a user encounters a localized URL to a link that requires a redirect, the helpful Fallback link does not show up because the fallback checker looks at $path/index.json and the re-director does not know about the /index.json stuff.
Instead of just looking for the English `index.json` file for the missing article, which is not typically redirected, the search proceeds in two stages:
1. Look for the English version of the article, which will follow the redirects.
2. If such an article exists, get its `index.json` file using the URL that gave a success for the article.
---
---
Manually tested locally. Ensured the new code followed the redirect and …
> fix(page-not-found): show fallback link for moved pages

- kumascript/macros/Exception.ejs
In mdn/content#15677, I removed the last occurrences of the `{{exception}}` macro.
In order to be sure this macro doesn't sneak back in `mdn/content` while it gets removed from `mdn/translated-content`, we want a `MacroDeprecationError` flaw to be raised if a page is committed again with this macro.
This flaw can be noticed by the committer, the reviewer, and, via the flaw dashboard, all `mdn/content` owners. (Given we normally have 0 such flaws, it will be very noticeable)
> Deprecate {{exception}} macro

- .github/workflows/dev-build.yml
- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
- deployer/README.md
- deployer/src/deployer/constants.py
- deployer/src/deployer/main.py
- deployer/src/deployer/update_lambda_functions.py
Automatize Lambda deployment to CloudFront distributions.
Currently, we have to manually update CloudFront distribution behaviors whenever we change the corresponding lambdas (`deployer/aws-lambda/*`).
1. Collect the Lambda updates.
2. Find CloudFront behaviors that use the updated Lambda, and update them accordingly.
3. (Related) Reset Lambda file timestamp for reproducible ZIP files.
---
_Not relevant._
---
1. Ran `poetry run deployer --dry-run update-lambda-functions --distribution E2MLRMA1VTVDHX`
1. Ran `poetry run deployer --dry-run update-lambda-functions --distribution E2MLRMA1VTVDHX --force`
1. Ran `poetry run deployer update-lambda-functions --distribution E2MLRMA1VTVDHX --force`
> chore(deployer): deploy Lambda updates to CloudFront

- build/document-extractor.js
Fixes #5829.
When hovering over a browser version of a feature whose nesting level is 2 or more, the tooltip says "Toggle history" instead of the browser release date.
This was because when traversing the features, only 1 level of nesting was checked.
The problem is solved by extracting `__compat` objects of the feature recursively using the `_extractCompatBlocks()` function.
---
---
1. Opened http://localhost:3000/en-US/docs/Web/API/HTMLCanvasElement/getContext#browser_compatibility locally.
2. Hovered over Chrome browser version of the "`options.alpha` parameter" feature.
> fix(bcd): extract browser release date for nested features at any depth

- libs/fundamental-redirects/index.js
- testing/tests/redirects.test.js
Fixes #4435
We have some "fundamental" redirects, that redirect whole sections that were moved.
However, https://developer.allizom.org/Web/JavaScript/ is wrongly redirected to https://developer.allizom.org/Web/docs/JavaScript/ instead of https://developer.allizom.org/docs/Web/JavaScript/, because "Web" is being interpreted as a locale (as mentioned [in this comment](https://github.com/mdn/yari/issues/4435#issuecomment-895581734)).
Reduce the locale pattern from `[a-zA-Z0-9]{2,3}(-[a-zA-Z0-9]{2})?` to `[a-zA-Z]{2}(-[a-zA-Z]{2})?`, because all our locales use tags consisting of two characters.
Note that the primary tag consists of only characters anyway (see https://www.rfc-editor.org/rfc/rfc3066#section-2.1).
---
_Not applicable._
---
Added a testcase.
> fix(fundamental-redirects): don't treat 'Web' as locale

- client/src/homepage/homepage-hero/index.scss
Follow up to #6132
The home page search padding was incorrect and not part of the link
Move the padding
---
This stylesheet wasn't being applied locally for some reason, so testing was done purely through DevTools.
> fix(search): apply padding to links on homepage search

- deployer/src/deployer/constants.py
Fixes #6171.
The deployer was using a different env variable for the CloudFront distribution than was specified in the workflows.
Update the deployer to use the env variable defined in the workflows.
---
Ran `deployer update-lambda-functions` locally:
```console
$ DEPLOYER_DISTRIBUTION_ID=E2MLRMA1VTVDHX poetry run deployer --dry-run update-lambda-functions                                                                      130 ↵
Deployer (0.3.0)
Updating all lambda functions within: aws-lambda
Found content-origin-request: would have published a new version of mdn-content-origin-request
Found content-origin-response: would have published a new version of mdn-content-origin-response
Found mdn-stripe-price-ids: would have published a new version of mdn-stripe-price-ids
Deploying lambda …
```
> fix(deployer): use correct env for distirbution

- build/bcd-urls.js
- build/document-extractor.js
- build/flaws/bad-bcd-queries.js
- kumascript/macros/Compat.ejs
- kumascript/tests/macros/Compat.test.js
Extracted from #6165.
Previously, the macro would add `id="bcd:{QUERY}"`, which is an
invalid id, and is being reported by html-validate 6.9.0 and later.
Now, we add `data-query="{QUERY}"` instead of an invalid id.
> fix(macros/Compat): move query from id to dataset

- kumascript/macros/LearnBox.ejs
In mdn/content#15738, @wbamberg removed the last 2 occurrences of the `{{LearnBox}}` macro on MDN.
This PR marks the macro as deprecated so that the flaw dashboard will notify us if somebody uses them again.
There are still 19 occurrences in mdn-translation, but I've opened a [discussion](https://github.com/mdn/mdn-community/discussions/65) on mdn/community to get them removed there too.
> Mark LearnBox macro as deprecated

- client/pwa/src/db.ts
- client/src/homepage/featured-articles/index.scss
- client/src/offline-settings/db.ts
Extracted from #5970, this resolves two issues reported by ESLint.
1. We're using `align-items: end;` and supposedly the value `end` has mixed support.
2. [TypeScript-ESLint](https://github.com/typescript-eslint/typescript-eslint) is complaining about unused interfaces (although they are used).
1. Replace `end` by `flex-end`, as suggested by ESLint.
2. Export those "unused" interfaces, to suppress the warning.
---
_None._
---
_Not tested._
> fix(eslint): resolve two issues

- deployer/src/deployer/search/__init__.py
Should fix the following deployer error on dev builds:
```
Deleting any possible existing index and creating a new one called 'mdn_docs_20220506172812'
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/runner/.cache/pypoetry/virtualenvs/deployer-nuEoiHvI-py3.8/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/home/runner/.cache/pypoetry/virtualenvs/deployer-nuEoiHvI-py3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/home/runner/.cache/pypoetry/virtualenvs/deployer-nuEoiHvI-py3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File …
```
> fix(deployer): handle index error of type str

- build/index.js
The `lru-cache@reset` method is deprecated since 7.0.
> https://github.com/isaacs/node-lru-cache/blob/ff322ad364c727a419a77ad962915a625aaf1b52/index.js#L812-L815
use `clear` instead of `reset`.
---
N/A
---
run `yarn build`.
Thank you :)
> refactor: use `clear` instead of `reset` in the `LRU` package

- .eslintrc.js
Follow-up #6176. 
The puppeteer has been deleted in  #6176
N/A
delete `allowModules: ["expect-puppeteer"],` from  `.eslintrc.js`
---
N/A
---
run `yarn run eslint` and confirmed nothing changes.
Thank you :)
> chore(eslint): delete `expect-puppeteer` settings from `.eslintrc.js`

- client/src/site-search/index.scss
- client/src/site-search/index.tsx
The current seach page cut off on mobile.
- Warp `display: block;`
- Delete `main-page-content`
-  The current search results are wrapped in `main-page-content` twice.
---
---
run locally and check result manually.
Thank you :)
> chore(ui): wrap search page result with `display: block`

- build/spas.js
Fixes the SPA prefixes for the MDN Plus feature docs, as noticed by @fiji-flo while reviewing #5952.
The MDN Plus feature docs are located at `/plus/docs/features/*`, but `spas.js` uses just `/plus/docs` as a prefix, omitting the `features` path.
Fixed the prefixes accordingly.
---
_Should not effect the UI._
---
Opened locally:
- http://localhost:3000/en-US/plus/docs/features/notifications
- http://localhost:3000/en-US/plus/docs/features/collections
- http://localhost:3000/en-US/plus/docs/features/offline
> fix(spas): correct prefix for feature docs

- kumascript/macros/ifattribute.ejs
- kumascript/macros/ifmethod.ejs
`{{ifmethod}}` and `{{ifattribute}}` create only red links as the linked content has been deleted.
This is similar to what we did for `{{interface}}` in mdn/yari#6011.
After mdn/content#15848 will land, this is what we have in mdn/content:
As soon as it does, I'll open a request in mdn/mdn-community to get it removed from mdn/translated-content.
> Deprecate {{ifmethod}} and {{ifattribute}}

- client/src/ui/molecules/manage-upgrade-dialog/index.tsx
Previously, the "Manage" link for the "Watch" action linked to
the "All notifications" page, which doesn't allow removing pages.
Now, it links to the "Watch list", which allows the user to
unwatch other pages, in order to watch a different page instead.
_See above._
_See above._
---
Context:
---
1. Logged in with a Free account.
2. Watched 5 pages.
3. Opened [another page](http://localhost:3000/en-US/docs/Web/Accessibility) and clicked on "Watch".
4. Then clicked on "Manage".
5. Verified that I got referred to the "Watch list", not the "All notifications" tab.
> fix(plus/manage-upgrade-dialog): manage via "Watch list"

- deployer/src/deployer/update_lambda_functions.py
Fixes #6194.
When updating Lambda functions, they aren't directly `Active`, and they cannot be deployed to CloudFront as long as they are `Pending`.
Wait until function is no longer `Pending`, and additionally only deploy functions that are `Active`. (They could be in state `Inactive` or `Failed`, see [here](https://docs.aws.amazon.com/lambda/latest/dg/API_FunctionConfiguration.html#SSS-Type-FunctionConfiguration-State.)
---
---
1. Tested by running `DEPLOYER_DISTRIBUTION_ID=E2MLRMA1VTVDHX poetry run deployer update-lambda-functions`
2. Noticed a slight delay when publishing the functions, due to the additional waiting time.
> fix(deployer): wait until lambda is active

- kumascript/macros/Draft.ejs
We just merged the removal of the two last occurrences of this macro on mdn/content. Let's make sure it doesn't sneak back in.
This is one of the two preconditions to merge #4943. The other is to have 0 occurrences left in `mdn/translated-content`.
> Deprecate the {{Draft}} macro

- .github/dependabot.yml
Previously, we couldn't update eslint and webpack, because
react-scripts v4 was expecting specific versions.
Now that we use react-scripts v5, this limitation is gone.
_See above._
_See above._
> build(dependabot): unignore eslint + webpack

- kumascript/macros/Pref.ejs
The link created by this macro never really worked (they were 99% red links).
I removed the last occurrence in mdn/content#15746
> Deprecate {{Pref}} macro

- package.json
- yarn.lock
Removes unused `resolutions` from our `package.json`.
Background: `mixin-deep` and `set-value` were an indirect dependency of webpack v4,
and they are no longer part of the webpack v5 dependency tree.
> build(node): remove unused resolutions

- .github/workflows/developing.yml
- .github/workflows/npm-published-simulation.yml
- package.json
- testing/README.md
This allows running `yarn test:developing` without setting any ENV var.
Previously, we would set 2-3 environment variables as part of the GitHub workflows, and `yarn test:developing` would only succeed if those environment variables were set manually beforehand.
Now we always set those variables as part of the `test:developing` run using `cross-env`.
---
---
- Ran `yarn test:developing` locally.
> test(developing): move env variables from workflow to script

- client/src/plus/plus-docs/index.tsx
Fixes #6253.
Navigating in the MDN Plus docs only changed the URL and the highlighted item in the TOC, but not the content.
Replaced `<Link>`s with `<a>` to avoid client-side navigation.
---
https://user-images.githubusercontent.com/495429/168038320-2e31cb70-6325-48ba-ae53-0c67fb1cd8e4.mov
https://user-images.githubusercontent.com/495429/168038398-9594dcbf-7234-47ad-b2d5-579980cb4c0d.mov
---
1. Opened http://localhost:3000/en-US/plus/docs/faq locally.
2. Clicked on "MDN Offline" on the left.
> fix(plus-docs): replace <Link> by <a>

- kumascript/macros/mediawiki.external.ejs
We are trying to remove this one since… August 2008, when MDN migrated away from Mediawiki (to Dekiwiki)
For the first time we are at 0 in mdn/content (see the last PR: mdn/content#15983).
Let's mark it as deprecated and wait until it goes away in mdn/translated-content.
> Deprecate {{mediawiki.external}}

- kumascript/macros/Tag.ejs
I'm removing the last occurrence of `{{Tag}}` in mdn/content#16006.
Let's mark it as deprecated.
> Deprecate {{Tag}}

- kumascript/macros/HTMLRef.ejs
`<listing>` and `<isindex>` are the two old HTML elements that have actually been removed from browsers. Docs are gone too.
> Delete HTML elements that are not part of the platform (in {{HTMLRef}})

- build/syntax-highlight.js
MDN shows batch files in a number of code blocks. Usually the fenced blocks are marked up with `bat` and then it later gets changed to `bash` to hide the error. Note that the actual key is `batch` according to this doc: https://lucidar.me/en/web-dev/list-of-supported-languages-by-prism/
This comes out of the discussion here: https://github.com/mdn/content/pull/16077#discussion_r873245304
If this fix goes in, we will need to change the [files/en-us/web/security/subresource_integrity/index.md](https://github.com/mdn/content/pull/16077/files/691d0e65ff48d899121067ac46ae239a89df115c#diff-58e33a19ce64773c6540bf790766a75bc7624ac76633c75a0b7ce9dd6fdd36f5) to use `batch` instead of `bash`.
> syntax-highlight.js - add batch as a supported language

- package.json
- yarn.lock
The `babel-eslint` packages has been deprecated and replaced with `@babel/eslint-parser`.  This PR replaces the packages accordingly.
> Replace babel-eslint with @babel/eslint-parser

- kumascript/macros/property_prefix.ejs
This PR marks the `{{property_prefix}}` macro as deprecated, as the last calls were removed in https://github.com/mdn/content/pull/16023.
> Deprecate {{property_prefix}} macro

- kumascript/macros/spec.ejs
Quick follow-up to the deprecation of the `{{spec}}` macro.  The final instances in en-US were removed, but I forgot to update the comment to reflect this.  :P
> Update deprecation comment for {{spec}} macro

- kumascript/macros/SVGRef.ejs
`animateColor` was never implemented and is long gone from the docs (it redirects to `animate`.
Time to remove it from the sidebar.
> Remove animateColor from SVGRef

- deployer/aws-lambda/mdn-stripe-price-ids/index.js
- deployer/aws-lambda/mdn-stripe-price-ids/tests/handler.test.js
Stripe plans lambda was not correctly determining environment. 
Header format was 
"x-mdn-env": [{ key: "x-mdn-env", value: env }]
not
"x-mdn-env": { key: "x-mdn-env", value: env }
---
---
> FIX: Stripe plans - Cloudfront custom header value

- client/src/document/ingredients/browser-compatibility-table/headers.tsx
- client/src/document/ingredients/browser-compatibility-table/index.tsx
- package.json
- yarn.lock
This PR updates Yari to utilize the new "type" and "accepts_webextensions" variables that have been introduced in BCD to simplify some of the code and simplify the addition of new browsers.  This also bumps BCD to v4.2.1 to fix a TypeScript definitions issue.
> Use new "type" and "accepts_webextensions" variables from BCD

- client/src/document/ingredients/browser-compatibility-table/index.tsx
This PR fixes #6314 by enforcing a specific order for the browsers to render in.  In #6308, the code was adjusted to filter for browsers matching the platforms specified; however, this did not enforce any specific order.  Additionally, the original code used a `Set` to generate the list of browsers, which does not actually guarantee an order of values; with both that plus the fact that it's destructured into an array anyways, this PR creates an array instead to ensure a specific order.
> Ensure browsers in BCD tables are always rendered in the correct order

- build/build-options.js
- build/constants.js
- content/constants.js
- deployer/aws-lambda/content-origin-request/build.js
- server/constants.js
- ssr/index.js
Separates the `require("dotenv")` calls from their usage.
We ran `require("dotenv").config()` in several places, which is fine in CommonJS, but causes trouble when migrating to ESM, because ESM doesn't support directly consuming imported symbols.
This prevents tools like `cjs-to-esm` from automatically migrating this statement.
Separate the calls as follows:
```patch
-require("dotenv").config();
+const dotenv = require("dotenv");
+dotenv.config();
```
**Note**: In doing so, I noticed that `server/constants.js` requires dotenv, but doesn't use it, so I removed that call.
---
_No change._
---
- Ran `yarn start` locally.
> refactor: separate `require("dotenv")` calls

- client/src/document/ingredients/browser-compatibility-table/index-mobile.scss
BCD table is broken on 426px browser width.
Reduce the max-width by 1px so the browser doesn't apply `sm` and `md` style at
the same time.
> fix(bcd): show table with md style at 426px

- client/src/homepage/static-page/index.tsx
Resolves the following React warning in the MDN Plus docs:
> Each child in a list should have a unique "key" prop.
---
_No change._
---
Opened http://localhost:3000/en-US/plus/docs/features/notifications locally, and compared this branch with `main`.
> fix(static-page): add key to sections

- client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
- client/src/document/ingredients/browser-compatibility-table/index.scss
Use partial support symbol in the timeline of notes
There is a "No support" symbol in historical notes for partially supported technologies.
Remove that symbol while keeping it for non timeline view of removed notes
---
Page: https://developer.mozilla.org/en-US/docs/Web/API/Document#browser_compatibility
Page: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#browser_compatibility
Page: http://localhost:3000/en-US/docs/Web/API/Document#browser_compatibility
Page: http://localhost:3000/en-US/docs/Web/HTML/Element/video#browser_compatibility
> fix(bcd): Use partial support symbol in the timeline of notes

- client/src/ui/molecules/mandala/index.tsx
Rationale: because the component is built around an inline SVG made of textual content using lose characters like forward slashes, curly braces, and the likes it was exposed in the accessibility tree, making it passive to be read out loud by a screen reader (i.e VoiceOver on macOS).
A demonstration of the issue is [recorded and shared as an unlisted video on YouTube](https://youtu.be/ILD7FyeseRU)
Fixes #6332 
The characters composing the Mandala component were read out loud by VoiceOver, which could cause confusion to users of assistive technologies, given the contents of the component are purely decorative.
Check the screen capture with VoiceOver video: https://youtu.be/ILD7FyeseRU
Add `aria-hidden="true"` to the Mandala container so that is is not exposed in the Accessibility tree …
> fix(molecules/mandala): remove `<Mandala />` from the accessibility tree

- .eslintrc.js
- build/constants.js
- build/flaws/broken-links.js
- build/spas.js
- client/pwa/webpack.config.js
- client/pwa/webpack.production.config.js
- content/constants.js
- content/popularities.js
- deployer/aws-lambda/content-origin-request/build.js
- kumascript/src/templates.js
- kumascript/tests/macros.test.js
- kumascript/tests/macros/Compat.test.js
- kumascript/tests/macros/DefaultAPISidebar.test.js
- kumascript/tests/macros/HTTPSidebar.test.js
- kumascript/tests/macros/ListGroups.test.js
- kumascript/tests/macros/apiref.test.js
- kumascript/tests/macros/page-api.test.js
- kumascript/tests/macros/utils.js
- kumascript/tests/render.test.js
- kumascript/tests/templates.test.js
- markdown/h2m/handlers/cards.ts
- markdown/m2h/handlers/index.js
- server/constants.js
- ssr/index.js
- ssr/render.js
- ssr/webpack.config.js
- testing/tests/filecheck.test.js
- tool/cli.js
This prepares us for ESM, which no longer provides __dirname,
by introducing a variable `dirname`, which can be replaced
by `fileURLToPath(new URL('.', import.meta.url))` later.
Used regular expression: `(?<!const dirname = )__dirname`
We use `__dirname` in several places, but this will no longer be available when we switch to ESM, and needs to be replaced by something like `fileURLToPath(new URL(., import.meta.url))`.
To make this migration smoother, this PR already introduces a `dirname` variable, which is initialized after all `require()` calls.
---
_No change._
---
_Not tested._
> refactor(esm): extract dirname = __dirname

- client/pwa/src/caches.ts
Fixes the following warning:
461665bf8dfe3f1b0a9a8488d4ee26e36d5f7655 introduced a `globals` comment, which ESLint complains about.
Remove the comment, which seems superfluous given the `declare` statement.
---
This PR does not have this warning. 🎉
> fix(client/pwa): remove unnecessary globals comment

- package.json
- yarn.lock
Essentially replaces `@babel/helper-builder-react-jsx` with `@babel/preset-env`.
The `babel-loader` README suggests installing `@babel/preset-env` alongside `@babel/core`, but we don't have it. Instead, we have installed `@babel/helper-builder-react-jsx`, which doesn't sound right to me.
Add `@babel/preset-env`, remove `@babel/helper-builder-react-jsx`.
---
_No change._
---
- Ran `yarn dev` locally.
> build(deps): add @babel/preset-env, remove @babel/helper-builder-react-jsx

- .github/labeler.yml
Updates the [actions/labeler](https://github.com/actions/labeler) config to assign more labels.
We're using [actions/labeler](https://github.com/actions/labeler) to mark PRs with labels based on the files they touch, but so far we only had one (incomplete) rule for the `macros` label.
Fix the `macros` rule, and add more rules.
> build(workflows/labeler): fix pattern, add more labels

- build/spas.js
Makes sure that the Contributor Spotlight link uses the `en-US` locale.
When opening the homepage with a locale other than `en-US`, clicking the Contributor Spotlight link leads to an empty page, because these pages aren't built in other locales.
Example:
- https://developer.mozilla.org/fr/ links to https://developer.mozilla.org/fr/community/spotlight/vinyl-da-i-gyu-kazotetsu
Always use `en-US` in the link.
---
_No visual change._
---
1. Ran `yarn tool spas` and `yarn start`
2. Opened http://localhost:3000/fr/_homepage and clicked on the Contributor Spotlight link.
> fix(contributor-spotlight): link to en-US

- ssr/webpack.config.js
Aligns the `ssr` webpack config with the `client` webpack config regarding `@svgr/webpack`.
`ssr` and `client` transform SVGs differently, and this has caused some hydration errors, see: https://github.com/mdn/yari/pull/6403
Since most users are effectively seeing the `client` version, use that webpack config for `ssr` as well.
---
_Should not cause any visual change, except for SSR SVGs no longer being optimized with svgo._
---
Ran `yarn build:ssr`, but will also run a dev build to verify.
> fix(ssr): use same @svgr options as client

- deployer/aws-lambda/content-origin-request/build.js
Makes it easier to debug what redirects are considered in the `content-origin-request` lambda.
For some reason, the `redirects.json` is incomplete (so the lambda doesn't handle mdn/content redirects), and I don't know why.
Add `console.log()` calls to the build of the `content-origin-request` lambda.
---
---
- Ran `yarn build` in `deployer/aws-lambda/content-origin-request`.
> chore(aws-lambda): log parsed redirect files

- client/src/app.tsx
Fixes #4615
Clicking search suggestion on 404 page yields another 404 because of `useEffect` condition. Currently, `PageOrPageNotFound` component looking for `initialPathname.current && initialPathname.current !== pathname` to be true before `setNotFound(false)` but `initialPathName` and `pathname` always the same. It isn't triggering because of that.
- Trigger setNotFound() after client renders the page.
On my local environment. Steps:
1. Go somewhere which throws 404 like: `http://localhost:5042/en-US/Games/Tutorials/2D_Breakout_game_pure_JavaScript`
2. Search something from search bar and click one of the results.
2.1. Old behaviour was yields you to another 404.
2.1. New behaviour is showing correct page.
> fix(app): fix 404 page yields another 404

- package.json
- yarn.lock
Adds `@types/node` to resolve the following warning:
> ts-node@10.8.0" has unmet peer dependency "@types/node@*".
---
Ran `yarn` and the warning no longer appeared.
> build(deps-dev): add @types/node 16.11.38

- .eslintignore
- .gitignore
- .prettierignore
- scripts/developing.sh
- scripts/testing.sh
Adds scripts to simulate the testing and developing workflows locally.
Currently there is no easy way to run the testing/developing workflows locally.
Adds scripts that mirrors exactly what those workflows do.
---
1. Ran `scripts/testing.sh` locally.
2. Ran `scripts/developing.sh` locally.
> test: add scripts to simulate developing/testing workflow

- client/src/ui/molecules/breadcrumbs/index.scss
Fixes #6452
Chevron icon's width value should not change according to his parents' width.
Adding `flex-shrink: 0` should protect its' width value.
---
---
1. Run on your local environment
2. Go to page which has more than 2 breadcrumb item. [Click here](http://localhost:5042/en-US/docs/Glossary/Hoisting) to shortcut.
3. Display page in responsive view
> fix(breadcrumbs): disable flex-shrink of chevron icon

- content/translations.js
Resolves the following regression caused by https://github.com/mdn/yari/pull/6378:
```
2:31:37 AM server.1     |  Error in buildDocumentFromURL(/en-us/docs/web/api) TypeError: Cannot read properties of undefined (reading 'values')
2:31:37 AM server.1     |      at findDocumentTranslations (/Users/claas/github/mdn/yari/content/translations.js:59:38)
2:31:37 AM server.1     |      at buildDocumentFromURL (/Users/claas/github/mdn/yari/server/index.js:54:29)
2:31:37 AM server.1     |      at /Users/claas/github/mdn/yari/server/index.js:268:25
2:31:37 AM server.1     |      at Layer.handle [as handle_request] (/Users/claas/github/mdn/yari/node_modules/express/lib/router/layer.js:95:5)
2:31:37 AM server.1     |      at next (/Users/claas/github/mdn/yari/node_modules/express/lib/router/route.js:1 …
```
> fix(content/translations): import VALID_LOCALES from /libs/constants

- client/src/app.tsx
Fixes #6161.
https://github.com/mdn/yari/pull/6437 fixed an issue regarding navigating away from a SSR 404, by toggling a state in that case. However, the other direction was not fixed, i.e. going back to the page that the SSR 404 referred to.
Consider `pageNotFound` again if the SSR page was a 404 and the new pathname is the same as the original pathname.
---
1. Opened http://localhost:5042/en-US/docs/404 locally.
2. Typed in "Web" in the search.
3. Opened a found page via keyboard.
4. Go back via browser UI.
> fix(404): handle going back to 404

- kumascript/macros/Compat.ejs
- kumascript/tests/macros/Compat.test.js
MVP to support multiple Array values for the `browser-compat` frontmatter.
May supersede:
- https://github.com/mdn/yari/pull/5972
- https://github.com/mdn/yari/pull/6004
- https://github.com/mdn/yari/pull/6358
---
---
> chore(macros/Compat): support query array

- client/src/app.tsx
- client/src/banners/README.md
- client/src/banners/active-banner.tsx
- client/src/banners/banner-utils.ts
- client/src/banners/ids.ts
- client/src/banners/index.tsx
~~Disables the MDN Plus announcement banner, as discussed with @HerminaC on 2022-05-22.~~
Refactors the banners as follows:
1. Introduces a `BannerId` enum which has all the banner ids, instead of working with unrelated constants.
2. Replaces `hasActiveBanners` by `currentBannerId` variable (and remove its reference from `app.tsx`, which shouldn't care), to avoid repeating the current id all over the place.
3. Extracts `daysToEmbargo` variable.
> refactor(banners): introduce BannerId enum + currentBannerId

- .github/workflows/npm-publish.yml
- .github/workflows/npm-published-simulation.yml
- .gitignore
- build/cli.js
- package.json
- server/index.js
- tool/cli.ts
- tool/tsconfig.json
- tsconfig.dist.json
This PR:
1. Adds a `build:dist` script that uses `tsconfig.dist.json` to transpile TypeScript in `/tool` in place (i.e. putting `cli.js` next to `cli.ts`).
2. Declares binaries `yari-build`, `yari-filecheck`, `yari-server` and `yari-tool` in `package.json`.
3. Updates the integration test (npm-published-simulation) to also run these binaries in the context of mdn/content.
**Note** that 1. is a compromise. It's not the perfect solution, but the best backward-compatible approach in terms of complexity. Transpiling to `/dist` or `/tool/dist` (using TypeScript's `outDir` option) doesn't work out of the box and would require us to enable `allowJS` as well, but then we would essentially end up mirroring the whole repository in `/dist`.
Converting `/tool/` to TypeScript broke the scripts in …
> build: transpile /tool in-place before npm publish + declare binaries `yari-{build,filecheck,server,tool}`

- build/spas.js
- build/sync-translated-content.js
- content/document.js
- deployer/aws-lambda/content-origin-request/build.js
- kumascript/tests/macros/Compat.test.js
- kumascript/tests/macros/DefaultAPISidebar.test.js
- kumascript/tests/macros/HTTPSidebar.test.js
- kumascript/tests/macros/ListGroups.test.js
- kumascript/tests/macros/apiref.test.js
- kumascript/tests/macros/page-api.test.js
- kumascript/tests/render.test.js
- ssr/render.ts
- tool/cli.ts
Extracted from #5017, calls `fs.{read,write}FileSync()` with 'utf-8', not 'utf8'.
We call `fs.{read,write}FileSync()` inconsistently with `utf-8` and `utf8`.
**Note**: [Both values are supported](https://github.com/nodejs/node/blob/7ad5b420aebc1bcd07be187481cf48a4180a60c0/lib/buffer.js#L685-L692).
Use `utf-8` consistently.
---
_No visual change._
---
_Not specifically tested, apart from running `yarn dev` successfully._
> fix(fs): call {read,write}FileSync() with 'utf-8', not 'utf8'

- build/document-extractor.js
- kumascript/macros/Compat.ejs
See https://github.com/mdn/yari/pull/6464#pullrequestreview-995065446. When a `browser-compat` value contains multiple BCD queries (feature names), so that the output has multiple BCD tables, this change causes a heading to be shown before each table — in order to make clear exactly which feature the table shows compat data for.
For the patch in the PR branch as currently written, the contet of the heading is the full BCD query (feature name).
The main rationale for using the full BCD query rather than a portion of it or the BCD `description` field for the feature is that in some cases, the only way to disambiguate some BCD features from one another is by showing the BCD query.
Consider https://pr16267.content.dev.mdn.mozit.cloud/en-US/docs/Web/Security/Subresource_Integrity#browser_compat …
> Add headings to BCD tables in multi-table output case

- build/document-extractor.js
Without this change, if there are multiple BCD features (array value in `browser-compat`), the Specifications section isn’t populated as expected.
There are two commits in this branch; the second commit addresses the case of some features — e.g., `css.properties.justify-content` — which have no compat data themselves but have subfeatures with compat data. In the case where we’re processing a browser-compat value which is an array, unless we explicitly check for the `__compat`-less-feature-with-subfeatures case, and handle it, we can end up with expected specifications being entirely missing from the rendered Specifications section.
The commits here are ports of https://github.com/mdn/yari/pull/6358/commits/4ddd22a and https://github.com/mdn/yari/pull/6358/commits/8829336.
> Make Specifications work as expected with multiple BCD queries

- client/src/search.tsx
Follow up to https://github.com/mdn/yari/pull/5988#issuecomment-1146144938
Quoting from the original:
> Summary
> Problem
> 
> Search results from the top navigation search are permanently visible if the search input is not empty. To hide the search results, the user has to manually reset the search input.
> 
> This also means that those search results were visible on the dedicated search page, because the search input is prefilled with the search query parameter.
> Solution
> 
> Show the search results only while the search input has focus, i.e. hide them as soon as the search input no longer has focus.
> fix(search): hide results unless focused

- client/src/document/index.scss
Remove padding from live sample frame to address the problem highlighted in the following discussion:
https://github.com/orgs/mdn/discussions/127
> fix: remove padding from live sample frame

- kumascript/macros/CSSSyntax.ejs
This is a tweak to the pretty-printing for CSS syntax.
Currently it figures out the length of the longest term and pads all terms to that length. This works well usually, but if the longest term is longer than the width of the box, then it forces all terms to wrap, as seen in https://developer.mozilla.org/en-US/docs/Web/CSS/font#formal_syntax for example:
This PR clamps the amount of padding, so that padded lines never exceed 50 characters:
Not fantastic, but better I think.
> CSS formal syntax rendering: clamp space-padding to line length

- client/src/ui/molecules/plus-menu/index.tsx
- client/src/ui/organisms/article-actions/index.tsx
- client/src/ui/organisms/top-navigation-main/index.tsx
The PR #6403 fixed all the hydration errors for guest users. But there are still hydration errors for signed in users and users with subscription.
This PR fixes hydration errors for signed in users.
SSR doesn't know whether a user is authenticated. But client knows the authentication status.
Current implementation of menus and navbar actions do not consider this fact.
Put the features for signed in users behind `!isServer` check.
Also, in plus-menu/index.tsx file the class `bookmarks-icon` has not been defined or mentioned anywhere in the yari repo. So removed the redundant text.
Firefox and chormium on Fedora 36.
> fix: hydration errors for logged in users

- markdown/cli.ts
Fixes #6607.
see issue.
- for matching folder only, adding trailing slash to match folders only
- for working on some specific folder like `web/css/colon-moz-only-whitespace`, use `doc.fileInfo.folder` instead of `slug`
> fix(markdown): match folder only for h2m cli

- build/sync-translated-content.js
verified by re-running https://github.com/mdn/translated-content/commit/91eded2a25d22ae38523a72053575fea1f25297b
which introduced the duplicates files/ja/web/api/window/blur_event.html and files/ja/web/api/window/focus_event.html
```
vscode@d47eeeeb9bfd:/workspace/translated-content$ git checkout 91eded2a25d22ae38523a72053575fea1f25297b~1
HEAD is now at b950fc2622 Translation: DOMException [es] - Fix #6334 (#6471)
vscode@d47eeeeb9bfd:/workspace/translated-content$ cd ../yari/
vscode@d47eeeeb9bfd:/workspace/yari$ yarn tool sync-translated-content
[...]
vscode@d47eeeeb9bfd:/workspace/yari$ cd ../translated-content/
vscode@d47eeeeb9bfd:/workspace/translated-content$ ls files/ja/web/api/window/blur_event
index.md
vscode@d47eeeeb9bfd:/workspace/translated-content$ ls …
```
> fix(sync-translated-content): don't add index.* duplicates

- markdown/tsconfig.json
- ssr/tsconfig.json
- tsconfig.json
Bumps the [target](https://www.typescriptlang.org/tsconfig#target) of our TypeScript configs to ES2020.
Previously, we were using ES2018 and ES2019, and it's probably time to move on.
> If you are wondering about the difference between ES2015 (aka ES6) and ES2020, ES2020 adds support for dynamic imports, and import.meta. (Source: https://www.typescriptlang.org/tsconfig#module)
Bump to ES2020, which is more defensive than going to ES2021 or even ES2022.
---
_No change._
---
1. Ran `yarn dev` locally.
> build(ts): bump target to ES2020

- package.json
This PR fixes the `start:dev-server` command to run the `index.ts` file within the `server` folder.  Without specifying the file `node-dev` attempts to import and run `index.js`, not realizing it's supposed to transpile TypeScript.
> Fix start:dev-server command

- content/redirect.js
This PR fixes the output for the redirect validation script, ensuring that the pairs are properly displayed.
Before:
```
info: _redirects.txt for en-us is causing issues: Error: Invalid redirect for /en-US/docs/Web/API/GlobalEventHandlers/onselectstart -> /en-US/docs/Web/API/GlobalFetch/GlobalFetch.fetch() or /en-US/docs/Web/API/HTMLInputElement/selectstart_event -> /en-US/docs/Web/API/fetch
```
After:
```
info: _redirects.txt for en-us is causing issues: Error: Invalid redirect for /en-US/docs/Web/API/GlobalEventHandlers/onselectstart -> /en-US/docs/Web/API/HTMLInputElement/selectstart_event or /en-US/docs/Web/API/GlobalFetch/GlobalFetch.fetch() -> /en-US/docs/Web/API/fetch
```
> Fix redirect validation output

- client/src/plus/collections/collection-list-item.tsx
- client/src/plus/collections/collections-tab.tsx
- client/src/plus/collections/frequently-viewed-tab.tsx
- client/src/plus/icon-card/index.scss
this was undefined, so always showed "added a few seconds ago"
also fixes them having no key in the list
tightened up the types a bit in the process
before:
after:
> fix(plus): frequently viewed articles showed added time

- kumascript/macros/MDNSidebar.ejs
Fixes the link syntax in the `mdnsidebar`. ~~For some reason Prettier changes `<a href=...` to `<ahref=...`~~ - Turns out it was a different extension causing the problem.
> fix: links in mdnsidebar

- build/syntax-highlight.js
See mdn/mdn-community#149.
This adds an alias in Prism for `js`: `jssyntax`.
The plan is to use it with syntax boxes (Web APIs and JS) that have pseudo-JS. We want them to be highlighted as JavaScript by Prism, but distinct so that tools like Prettier and ESLint can skip them.
> Add jssyntax as Prism alias for syntax boxes

- kumascript/macros/CanvasSidebar.ejs
This link has been archived (and is in the MDN museum). It must be removed from the sidebar, too.
> Remove archived link (Basic raycaster)

- client/src/community/index.tsx
Fixes hydration error in the Contribute component on community page.
In file ./client/src/community/index.tsx, in `Quote` component, the title is split over two lines. The server sends the title as it is, i.e. with extra white spaces. But on client the white spaces are removed and the hydration complains about mismatch in title:
```
react-dom.production.min.js:118 Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
at Qr (react-dom.production.min.js:118:466)
at yu (react-dom.production.min.js:205:127)
at ys (react-dom.production.min.js:280:85)
at bs (react-dom.production.min.js:279:450)
at vs …
```
> fix: hydration error in Contribute component

- client/src/document/toolbar/index.scss
A `broken links` content is overflowing.
Remove `white-space: nowrap;`
---
---
run `yarn dev` locally and check it manually.
---
Thank you :)
> fix(flaws): overflowing content in broken links

- kumascript/macros/event.ejs
This PR deprecates the `{{event}}` macro.  All of the uses in English content are now removed, leaving the localized content.
> Deprecate {{event}} macro

- kumascript/macros/CSS_key_concepts.ejs
This intends to deprecate a macro (prudent step before effective deletion)
This macro only creates links and should be removed
Added `mdn.deprecated()` as in other cases of such deprecation.
I didn't
https://github.com/mdn/content/pull/19105
https://github.com/mdn/translated-content/pull/7334
> Deprecate `{{css_key_concepts}}`

- kumascript/macros/CSSSyntax.ejs
This is a piece of https://github.com/orgs/mdn/discussions/138. I thought it might be good to implement this in little pieces. Each piece is still useful.
This PR just adds support for CSS data types and CSS functions as well as CSS properties, and means you can add a formal syntax section to, say, https://developer.mozilla.org/en-US/docs/web/css/easing-function or https://developer.mozilla.org/en-US/docs/web/css/color_value or https://developer.mozilla.org/en-US/docs/web/css/gradient.
Follow-ups to this could:
1. change the way syntax is rendered so that when rendering the syntax for a type that's a constituent part of a property (or another type) we just link to the other page instead of embedding the whole syntax. This would mean, for example, that in …
> Support formal syntax for types and functions as well as properties

- client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
- client/src/document/ingredients/browser-compatibility-table/utils.ts
This PR fixes the rendering of the `prefix`, `altname` and `flags` icons on BCD cells to ensure they aren't unintentionally shown when not applicable.  This should help reduce issues and confusion such as https://github.com/mdn/browser-compat-data/issues/17208.
> Fix icons displayed in BCD cells

- markdown/localizations/de.json
This PR adds localizations for Note/Warning/Callout for Markdown conversion.  The strings come from the localized files themselves, and will help future translators if the German locale is ever unfrozen.
> Add Markdown localizations for German

- kumascript/macros/xref_csscomputed.ejs
- kumascript/macros/xref_cssinherited.ejs
- kumascript/macros/xref_cssinitial.ejs
For the same document, they have the same slug for both `en-US` and `l10n`. So the URL in `{{CSSInfo}}` macro should be updated.
see **Screenshots**.
update URLs.
run `yarn dev` and check this url: `http://localhost:5042/zh-TW/docs/Web/CSS/border-color#formal_definition_%E8%AA%9E%E6%B3%95%E5%AE%9A%E7%BE%A9`
see rendered page in browser.
> fix(macros): correct the links in {{CSSInfo}} macro

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
- build/cli.js
Fixes: #6738.
The sitemap was generated twice, and will only include the specific locales.
https://github.com/mdn/yari/blob/e3b755e1cacbc84a57a09dca3e80e3f35549ed8d/.github/workflows/prod-build.yml#L201-L207
For example, when we run a job, like:
```bash
yarn build --locale     en-us --locale     ja --locale     fr & 
build1=$! 
yarn build --not-locale en-us --not-locale ja --not-locale fr & 
build2=$! 
wait build1
wait build2
```
and the first job takes more time. Then, the `sitemap.xml` will only include `en-US`, `fr`, and `ja` (see: <https://developer.mozilla.org/sitemap.xml>).
To generate the sitemap with all built locales in spread build:
1. collect all existed `sitemap.xml.gz` in `BUILD_OUT_ROOT`
2. generate `sitemap.xml` with collected `sitemap.xml.gz` filepaths.
> fix: make the sitemap generator work with spread build

- kumascript/macros/CSSSyntax.ejs
This PR implements a sort of pragmatic version of one of the ideas in https://github.com/orgs/mdn/discussions/138 .
In that discussion is was suggested that when rendering formal syntax, instead of expanding out all the CSS types that we could, we should not expand out types that had their own separate MDN page, and instead just link to those pages.
A reason for wanting to do this is to make the formal syntax shorter, which is a good thing especially as pretty-printing has made it much longer than it used to be.
But as mentioned in https://github.com/orgs/mdn/discussions/138#discussioncomment-3035090, doing this for *every* type risks making formal syntax too fragmentary, forcing readers to chase across many pages to get a complete picture.
So instead this PR suppresses "inline expansion" …
> Suppress formal syntax expansion for <color> and <gradient>

- package.json
- yarn.lock
The `fast-xml-parser` is unnecessary dependency.
Any scripts do not reference the `fast-xml-parser`.
- The `fast-xml-parser` installed [PR 2917](https://github.com/mdn/yari/pull/2917/files#diff-68f18456493b71321a584edd84d146d973d1c7a224bf178b707609bdd8e6822cR2) for `build/feedparser.js`.
- But, the `build/feedparser.js` has been deleted [PR 5337](https://github.com/mdn/yari/pull/5337/files#diff-68f18456493b71321a584edd84d146d973d1c7a224bf178b707609bdd8e6822cL6).
Delete the `fast-xml-parser` from dependencies.
N/A
N/A
---
Thank you :)
> build(deps): delete `fast-xml-parser`

- content/document.js
Fixes: #6493.
When use command in content repo: 
```bash
yarn content move Web/API/AbortController/signal Web/API/AbortController/signals
```
The `page-type` key in front matter will be moved after tags.
And I found the `page-type` is not included in `optionalFrontMatterKeys`:
https://github.com/mdn/yari/blob/60747895d4058455707fd5d269f3c57a6bb76bfd/content/document.js#L86-L113
So, the insertion of `page-type` is after the insertion of `tags` and `bcd`, and the iteration of object after ES 2015 is by insertion order (if keys are not number). Finally in the dump, this key is also after `tags` and `bcd`.
Add the `page-type` key to `optionalFrontMatterKeys`, and before `tags` key.
---
see above.
---
run `yarn tool move Web/API/AbortController/signal Web/API/AbortController/sign -y` in yari.
> fix: add "page-type" to optional front matter keys

- .github/workflows/dev-build.yml
I've ignored the dev build. Add sitemap generate in this workflow.
See: #6791
None.
> ci: add sitemap generate in dev build

- markdown/localizations/pl.json
This PR adds the Markdown blockquote localization in Polish.  The strings come from analyzing the Polish files themselves.  This should help if Polish is ever unfrozen.
> Add Markdown localizations for Polish

- client/src/hooks.ts
- client/src/ui/atoms/signout/index.tsx
- client/src/ui/molecules/notifications-watch-menu/index.tsx
Fixes https://github.com/mdn/yari/issues/6846.
The `/api/v1/settings` route no longer exists in rumba, so the `useCSRFMiddlewareToken` hook
no longer has any effect apart from triggering HTTP 404s.
Note: The "csrftoken" cookie is still available and being used.
Remove the `useCSRFMiddlewareToken` hook and its usages.
---
> chore(client): remove useCSRFMiddlewareToken hook

- kumascript/macros/APIRef.ejs
- kumascript/macros/JSRef.ejs
- kumascript/macros/WebExtAPISidebar.ejs
Fixes #6719.
The icons (badges) would "jump" to their own line for the sidebar item of the current page.
Observable on pages like:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/contextMenu
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/arguments
Accumulate the badges in their own variable, then put them inside the ``<em>`` tag. This ensures "the same line" placement.
---
---
I made sure to visit appropriate sections of the website while editing the files to make sure they apply to the correct templates.
The fix works as expected, in all sections of the side it's applicable to.
I was [made aware](https://github.com/mdn/yari/issues/6719#issuecomment-1187009882) of an [ongoing](https://github.com/mdn/yari/discussions/4033) …
> fix(macros): inconsistent sidebar icon placement

- client/src/document/molecules/localized-content-note/index.tsx
1. We have [moved to the new contrib docs](https://github.com/mdn/content/pull/19117). So update the links to [`Translated_content#active_locales`](https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Translated_content#active_locales)
2. use optional chaining to simplify the logic
We have [moved to the new contrib docs](https://github.com/mdn/content/pull/19117). The links should be updated to reduce redirect.
---
---
run `yarn dev`.
> chore(client): update links and use optional chaining

- client/src/ui/molecules/reference-menu/index.tsx
Fixes https://github.com/mdn/yari/issues/5876.
The old MDN design had a "Browser extensions" item in the "Technologies" menu (see [here](https://web.archive.org/web/20210401045240mp_/https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions)), but the menus of the new MDN design do not have this menu item anymore.
Add a "Browser extensions" item to the "References" menu.
---
---
- Open http://localhost:3000/en-US/plus locally.
> chore(reference-menu): add Web Extensions item

- client/src/ui/molecules/breadcrumbs/index.tsx
Fixes #6581 
(Originally discovered by inspecting the HTML of the webpage)
Using the Windows 10 Narrator app, I visited the [production MDN article about the navigation role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/navigation_role). On this page, I navigated through the landmarks (Capslock + D) until I got to the breadcrumbs landmark, and it read out "Breadcrumb navigation, navigation landmark."
The solution was to remove the redundant word `"navigation"` from the `aria-label` of the affected `nav` element.
I followed the steps in the quick setup section of this repo's readme to load my change into the browser. I then followed the same steps as described in the section `Problem`. The narrator read the nav out as "Breadcrumb, navigation landmark."
> fix: redundant word 'navigation' in breadcrumb nav

- client/src/document/ingredients/browser-compatibility-table/index.tsx
This PR updates the rendered BCD tables to hide Internet Explorer's compatibility data, since Internet Explorer is dead.  Although IE is still available for enterprise customers and through Edge's "IE Mode", no new website should be written for IE support, so hiding IE's compatibility should help dissuade web developers from writing new IE-compatible websites.
> Hide Internet Explorer in BCD tables

- .github/workflows/pr-commit-signatures.yml
Adds a check that detects unsigned/unverified commits in PRs.
See:  #6130
We regularly see unsigned/unverified commits in PRs, which is frustrating for both the PR author and us, because it delays the merge.
Adds a check, so that PR authors can easily notice the unsigned/unverified commits themselves, and fix them.
---
1. Committed unsigned commit to this PR, see: :x: https://github.com/mdn/yari/runs/7924608819?check_suite_focus=true
2. Then force-pushed a signed commit instead, see: ✅ https://github.com/mdn/yari/runs/7924654266?check_suite_focus=true
> ci(workflows): check commit signatures

- kumascript/tests/macros/Deprecated.test.js
Follow-up to #6920.
I removed an unused `DeprecatedGeneric` branch in #6920, which caused corresponding tests to fail, but the PR got merged anyways.
Remove the corresponding tests, as `DeprecatedGeneric` is no longer used in that way.
---
Looked through usages of `DeprecatedGeneric` via `rg -i DeprecatedGeneric content translated-content` and verified that it is no longer called with just a version number as the second parameter.
> fix(macros/DeprecatedGeneric): remove failing tests

- client/src/ui/molecules/menu/index.tsx
- client/src/ui/molecules/submenu/index.tsx
Partly fixes #6870.
Our primary navigation menu uses misleading ARIA attributes:
- `aria-haspopup` for a button that doesn't trigger a popup.
- `role="menu"` and `role="menuitem"` for elements that don't behave like a menu.
Remove those ARIA attributes in those specific locations.
---
---
Verified via "View Page source" that the attributes are no longer present on the specific elements.
> fix(menu): remove misleading ARIA attributes

- kumascript/src/api/web.js
Fixes #6802.
The `smartLink()` function wrote to a `/tmp/read.log` file, but /tmp is not available on Windows, which broke macros. Also, the file being written to was not actually used.
Stop writing to that file. (Other locations use `tempy`, but since we don't read that file anywhere, we can just omit the write.)
---
Verified that the {{APIRef}} macro renders again on http://localhost:5042/en-US/docs/Web/API/SVGStyleElement.
> fix(macros): remove write to /tmp

- build/index.js
Avoids Rumba to fail if a document has a null title.
There is a [document in translated-content ](https://github.com/mdn/translated-content/blob/36c6660dc8732a0a2977352de479129c90697670/files/de/web/html/element/u/index.html#L2) that has an empty title, and this causes some Rumba search requests to fail.
Avoid that `doc.title = null` by using the empty string as a fallback.
---
Trivial change, didn't test.
> fix(build): prevent doc.title = null

- kumascript/macros/NonStandardBadge.ejs
support localization for `{{NonStandardBadge}}` macro which is used by `{{APIRef}}`, `{{Non-standard_Inline}}`, etc.
This macro should support l10n. But it won't. (the `title` is fixed with an `en-US` text)
using `mdn.localString` to select a l10n title for this macro.
---
test on this pr: mdn/translated-content#6699
Non-standard_Inline:
APIRef:
Non-standard_Inline:
APIRef:
see renderd html.
> feat(macros): localize NonStandardBadge

- .github/workflows/npm-publish.yml
Avoids our checks to fail on commits added to `main` by Dependabot.
`NPM_AUTH_TOKEN` is a secret that is not available if the workflow was triggered by Dependabot [merging one of its own PRs].
Skip the workflow, as it would fail anyway.
---
---
Haven't tested, but a condition on the job is documented [here](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#example-only-run-job-for-specific-repository).
PS: Using `github.triggering_actor` allows us to still run the workflow manually:
> ci(workflows): skip npm-publish if dependabot merged

- kumascript/macros/DeprecatedBadge.ejs
support localization for {{DeprecatedBadge}} macro which is used by {{APIRef}}, {{Deprecated_Inline}}, etc.
This macro should support l10n. But it won't. (the `title` and `abbreviation` is fixed with en-US text)
use `mdn.localString` to select l10n `title` and `abbreviation` for this macro.
---
In <http://localhost:5042/zh-CN/docs/MDN/Writing_guidelines/Page_structures/Macros/Commonly_used_macros#已弃用>
---
run `yarn dev` and check the rendered html.
> feat(macros): localize DeprecatedBadge

- .github/workflows/dev-build.yml
Notifies PRs about [Dev builds](https://github.com/mdn/yari/actions/workflows/dev-build.yml) that we run from time to time to test PRs.
So far, we have to wait for the Dev build to finish, manually construct the URL at which the build is available and write it in the PR to allow the PR author to participate in testing.
Add a step to the Dev build to notify all PRs that include the built commit once the deployment succeeds.
---
---
Commented out the actual build steps and ran just the notification step (see screenshot above).
See: https://github.com/mdn/yari/runs/7997530913?check_suite_focus=true#step:4:1
> ci(dev-build): notify PRs about successful builds

- kumascript/macros/Exception.ejs
The `{{Exception}}` macro has been deprecated. And now, this macro has been removed from mdn/translated-content. I've run the command below to verify it:
```bash
rg -i "\{\{\s*Exception" -l | wc -l # got 0
```
There is no `{{Exception}}` macro left in content and translated-content. It's time to remove it.
https://github.com/orgs/mdn/discussions/64
Verified by using `rg`.
> chore(macros): delete {{Exception}} macro

- client/src/plus/collections/v2/new-edit-collection-modal.tsx
the previous fix meant that the modal wouldn't be cleared after creating a new collection
> MP-96 clear new collection modal

- kumascript/macros/warning.ejs
`{{warning}}` macro has been removed from mdn/content (mdn/content#20015).
It's time to deprecate it.
> Note: there are some escaped `{{warning}}` macros in issue template:
>
> https://github.com/mdn/content/blob/1c8f3af9f3c9e7caf084fd9072c263b86e25ac1b/files/en-us/mdn/community/issues/index.md?plain=1#L19-L35
> chore(macros): deprecate {{warning}} macro

- testing/tests/developing.spec.ts
- testing/tests/headless.sitesearch.spec.ts
Fixes https://github.com/mdn/yari/issues/6960.
Fixes https://github.com/mdn/yari/issues/6990.
There are two flaky tests that fail from time to time.
Stabilize these tests by waiting for `networkidle` or a selector respectively.
---
Hard to test, as the test failures are random.
> fix(tests): stabilize flaky tests

- client/src/plus/collections/v2/api.ts
- client/src/plus/collections/v2/collection.tsx
- client/src/plus/collections/v2/index.scss
- client/src/plus/collections/v2/index.tsx
- client/src/plus/collections/v2/new-edit-collection-modal.tsx
- client/src/ui/atoms/modal/index.scss
- client/src/ui/atoms/modal/index.tsx
- client/src/ui/organisms/article-actions/bookmark-menu/menu-v2.tsx
- client/src/ui/organisms/article-actions/index.scss
first commit moves the item edit/delete modals into separate components to keep the logic simpler
the second adds the loading and error states, as well as changing post/delete methods to work much more like get methods: so they become hooks, and have `isPending` and `error` keys, to avoid having to manage this state in the components themselves (this is what I was originally doing, and it was very messy)
this works a lot like [the useSWRMutation hook coming in the next version of useSWR](https://github.com/vercel/swr/releases/tag/2.0.0-beta.0) which should make migration easier
I'd suggest reviewing the commits separately, otherwise the diff is a bit unwieldy
disabled button styling is messed up, there's a separate issue for that here: https://mozilla-hub.atlassian.net/browse/MP-101
> MP-69 MP-70 add loading and error states to collections

- package.json
Drops support for Node.js 17, which is is EOL since 2022-06-01.
See: https://github.com/nodejs/Release/#end-of-life-releases
> build(deps): drop node 17

- .github/workflows/testing.yml
- scripts/lint.sh
- scripts/testing.sh
Splits up the testing workflow into two lint and test jobs.
If there are linting errors, the tests are not run.
Separate linting from testing.
---
See checks of this PR.
> ci(testing): separate lint from test

- client/src/document/index.tsx
- client/src/document/molecules/retired-locale-note/index.tsx
Updates the link that appears when visiting a URL belonging to the newly retired German and Polish locales:
It was unconditionally linking to https://hacks.mozilla.org/2021/03/mdn-localization-in-march-tier-1-locales-unfrozen-and-future-plans/, which doesn't mention the retirement of German and Polish.
For German and Polish, link to https://github.com/orgs/mdn/discussions/147 instead.
---
Tested locally by visiting http://localhost:5042/de/docs/Learn/HTML and http://localhost:5042/fa/docs/Learn/HTML
> fix(retired-locale-note): link de/pl to GitHub discussion

- content/document.js
- content/utils.js
Formats the `_wikihistory.json` with Prettier, if it is available.
Supersedes https://github.com/mdn/content/pull/20139.
`yari-tool delete` update the `_wikihistory.json` file, but format it using `JSON.stringify()`, whereas mdn/content formats JSON files with prettier.
Format the JSON with prettier.
---
Updated `node_modules/@mdn/yari/content/document.js` in mdn/content accordingly and made sure that the changes to `_wikihistory.json` were only minimal.
> style(wikihistory): format with prettier, if available

- client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
- client/src/document/ingredients/browser-compatibility-table/legend.tsx
- client/src/document/ingredients/browser-compatibility-table/utils.ts
This PR is a quick follow-up to #6777.  In between the creation and merge of that PR, there were some updates to the rest of the code that makes the `support` object an array even for single-item support statements.  This PR updates the code to verify that the support statement is an array AND has more than one item in it before displaying the "more" icon.
> fix(bcd): show "more" icon only for 2+ entries

- client/public/index.html
- client/src/ui/molecules/theme-switcher/index.tsx
- client/src/utils.ts
- libs/constants/index.js
Fixes https://github.com/mdn/yari/issues/6727.
Pages with interactive examples throw following error because yari tries to send theme change message before the iframe content is loaded:
> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://interactive-examples.mdn.mozilla.net') does not match the recipient window's origin ('https://developer.mozilla.org').
Steps to reproduce:
1. Open page https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit.
2. Set them to "Dark".
3. Do force page reload using ` Ctrl + F5`.
4. In the logs you'll see the error message.
The problem is the iframe content takes time to load but yari starts sending theme change message multiple times. The iframe with empty content throws origin mismatch error.
Also, yari sends the …
> fix: interactive iframe post message error

- libs/constants/index.js
:warning: #6352 introduced a wrong hash for the current script on the main page (index.html). At the moment the current and previous hashes are exactly the same.
In Firefox seeing following error:
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). Source: document.body.addEventListener("load",(t=>{t.target.classList.contains("interactive")&&t.target.setAttribute("data-readystate","complete")}),{capture:!0});const c={light:"#ffffff",dark:"#1b1b1b"};if(window&&document.documentElement)try{const t=window.localStorage.getItem("theme");t&&(document.documentElement.className=t,document.documentElement.style.backgroundColor=c[t])}catch(t){console.warn("Unable to read theme from localStorage",t)}.
```
***
The hash for the latest script: …
> :warning: fix: Update the script hash on the main page

- client/public/index.html
- libs/constants/index.d.ts
- libs/constants/index.js
- testing/tests/csp.test.ts
Prevents us from forgetting to update the CSP entry when we update the inline `<script>` tags in `client/public/index.html`, and makes it easier to review such changes.
If we update inline `<script>` tags in `client/public/index.html`, we **always** have to update the corresponding CSP entry in `libs/constants/index.js`, but so far we didn't ensure this with a test.
Adds a test that verifies that all inline script tags have a corresponding CSP entry.
PS: This also avoids having to manually calculate the hash, as the failing test will print it out.
---
Ran `npx jest testing/tests/csp.test.ts --watch` locally and removed a required CSP value from `libs/constants/index.js`.
> test(csp): verify that inline scripts have CSP entry

- package.json
- tsconfig.json
- yarn.lock
Improves the ts-node startup speed by switching to the much faster Rust-based [SWC compiler](https://swc.rs/).
Fixes https://github.com/mdn/yari/issues/7034.
Since migrating our CLI codebase to TypeScript, the commands take longer to start due to the compilation.
Use the Rust-based _Speedy Web Compiler_ to improve the start-up speed, as suggested by @yin1999.
---
n/a
---
Ran `yarn start:server` and `yarn start:static-server` locally.
> perf(ts-config): use @swc/core

- deployer/src/deployer/analyze_pr.py
- deployer/src/deployer/test_analyze_pr.py
The PR addresses: https://github.com/orgs/mdn/discussions/51#discussioncomment-3525961
> Links don't need to appear fully qualified (with host and everything).
This will shorten the link texts. For example:
from
https://pr20099.content.dev.mdn.mozit.cloud/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_conditional_rendering
to
[/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_conditional_rendering](https://pr20099.content.dev.mdn.mozit.cloud/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_conditional_rendering)
> fix(pr-companion): shorten the preview links

- kumascript/macros/LearnSidebar.ejs
MDN learn pages [1] have a sidebar to quickly access various sections (HTML, CSS, JavaScript, etc). This PR adds the corresponding ones for the MathML tutorial added in [2]. Fixes #6952.
[1] https://developer.mozilla.org/en-US/docs/Learn
[2] https://github.com/mdn/content/pull/19467
MathML tutorial is not accessible from the learn sidebar, so users cannot find it from the Learn pages.
Add links for the MathML tutorial to existing sidebar.
I used `yarn dev` and opened a few subpages of http://localhost:3000/en-US/docs/Learn ; checking the added MathML sections properly display in the sidebar and that the links are not broken, and that one can fold/unfold the "MathML first steps" subsections by clicking on it.
> chore(macros/LearnSidebar): add MathML tutorial

- kumascript/macros/SectionOnPage.ejs
add l10n-zh translation for `{{SectionOnPage}}` macro.
In `http://localhost:5042/zh-CN/docs/Web/API/Clipboard/write`
---
Run `yarn dev`.
> chore(macros/SectionOnPage): add l10n-zh translation

- build/syntax-highlight.ts
This PR replaces the Prism alias for `jssyntax` with `jsnolint`, and adds `htmlnolint`.
`jssyntax` was added in #6682, but we decided not to use it as it is too semantic, and we wanted to avoid a potentially long list of semantic aliases.
The idea is to have such code blocks styled by Prism with the right color scheme but skipped when linter run, like Markdownlint, or Prettier, as these blocks are not valid (for example our syntax box), or should not be formatted by linters (like examples of invalid code, or TML templates that require an unusual alignment).
In a meeting a couple of weeks ago, I understood that we have a consensus on these two names (we need `htmlnolint` for some templates in the Learning Area).
So, first: do we have a consensus? @Rumyra @wbamberg @Josh-Cena @elchi3 can …
> chore(syntax-highlight): add nolint aliases for html/js

- kumascript/macros/CSSSyntax.ejs
Fixes a problem with the CSSSyntax macro reported by Jean-Yves, but not filed AFAIK.
Update CSSSyntax to handle the combination of a hash and curly brackets, like `#{3}`: https://web.archive.org/web/20220424210922/https://drafts.csswg.org/css-values/#component-multipliers
@teoli2003 , this ought to fix the syntax for [`clamp()`](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp#formal_syntax).
The `csssyntax` macro can't handle the combination of the `#` and `{}` notations.
This combination is described in the spec (https://drafts.csswg.org/css-values/#component-multipliers):
> A hash mark (#) indicates that the preceding type, word, or group occurs one or more times, separated by comma tokens (which may optionally be surrounded by [white …
> fix(macros/CSSSyntax): handle combination of hash mark + curly brackets

- client/src/document/index.scss
- kumascript/macros/CSS_Ref.ejs
Starts a new set of columns for each character in the (`CSS_Ref`) index.
Fixes #6601.
The whole index was distributed among 3 (very long) columns, making them very hard to read/navigate.
1. Create columns on the character-level, not on the whole index.
2. Use `<h3>` again for the characters, dropping the pre-redesign style (background-color with rounded corner).
---
| ------ | ------ |
| <img width="779" alt="image" src="https://user-images.githubusercontent.com/495429/188894700-c701764e-4a92-4fff-975d-cfa27220963d.png"> | <img width="779" alt="image" src="https://user-images.githubusercontent.com/495429/188894615-691b0db6-5934-43af-bf17-2a98e8ab8a26.png"> | 
---
Opened http://localhost:3000/en-US/docs/Web/CSS/Reference#index locally.
> fix(macros/CSS_Ref): start new set of columns for each character in index

- deployer/src/deployer/analyze_pr.py
The "[on GitHub](https://github.com/mdn/content/blob/20417/merge/files/en-us/web/css/value_definition_syntax/index.md)" links produced by the PR companion are broken. And we simply need to remove them.
Consider following URL for the discussion: (PR https://github.com/mdn/content/pull/20417)
`https://github.com/mdn/content/blob/20417/merge/files/en-us/web/css/value_definition_syntax/index.md?rgh-link-date=2022-09-08T04%3A15%3A01Z`
There are multiple issues that make the URL wrong:
1. The workflow [uses merge commit](https://github.com/mdn/content/blob/bff24d63155e704ab353e82c4f5963ca9da0d45c/.github/workflows/pr-test.yml#L26) instead of [pull request HEAD commit](https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit). So the code uses the merge …
> fix(pr-companion): remove broken 'on GitHub' links

- kumascript/macros/JsSidebar.ejs
- kumascript/macros/ListSubpagesForSidebar.ejs
Fixes #6724.
The `JsSidebar` macro was listing subpages, but omitting links to the parent page (Overview). Even though the `ListSubpagesForSidebar` supported a parameter to include the parent page, it didn't work expected, displaying the parent page **instead of** its subpages.
1. Fix the `ListSubpagesForSidebar` macro to list _both_ the parent page _and_ its subpages, if requested.
2. Update the `JsSidebar` to use the aforementioned parameter to include the parent page (Overview).
---
| ------ | ------ |
| ![image](https://user-images.githubusercontent.com/495429/188748891-1efc914b-eca7-4f83-80f0-bfc18f9e5d75.png) | ![image](https://user-images.githubusercontent.com/495429/188748787-e9ff4016-c549-4bf9-a8ea-a6f5e2bcab67.png) | 
---
Opened …
> fix(macros): add Overview items via ListSubpagesForSidebar, enable for JsSidebar

- .gitignore
- build/spas.ts
- markdown/index.js
- markdown/index.ts
- markdown/m2h/cli.ts
- markdown/m2h/handlers/code.ts
- markdown/m2h/handlers/dl.ts
- markdown/m2h/handlers/index.ts
- markdown/m2h/handlers/mdast-util-to-hast-utils.ts
- markdown/m2h/index.ts
- markdown/tsconfig.json
- markdown/utils/index.ts
- package.json
- tsconfig.dist.json
Converts `/markdown` to TypeScript.
~~⚠️ Blocked by:~~
- https://github.com/mdn/yari/pull/6683
- https://github.com/mdn/yari/pull/7006
> refactor(markdown): convert to typescript

- build/document-extractor.ts
- build/index.ts
- client/src/document/organisms/sidebar/index.scss
- kumascript/macros/JSRef.ejs
Highlights the current page in the sidebar, and expands the corresponding menu.
Fixes #5547.
Fixes #5641.
1. The current page is not highlighted in the sidebar.
2. When opening a page from an expanded menu, the menu is collapsed again.
1. Mark the current page with [aria-current](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current).
2. Open `<details>` elements that contain links to the current page.
---
|-------|-------|
| <img width="675" alt="image" src="https://user-images.githubusercontent.com/495429/188864171-a22a2521-69e1-4ac8-89da-ea43dda835dd.png"> | <img width="677" alt="image" src="https://user-images.githubusercontent.com/495429/189112863-c8eb0b71-395d-40c1-b3e1-5fecb19022cd.png">  |
---
Opened these pages locally:
- …
> fix(sidebar): open menu, highlight current page

- client/src/ui/atoms/form/index.scss
Prevent `<select>`s from overflowing, and use ellipsis ("...") in case of overflow instead of clipping.
Fixes [MP-93](https://mozilla-hub.atlassian.net/browse/MP-93).
The Collection select overflows for a very long collection name.
Limit its width and add ellipsis if it overflows.
---
| --- | --- |
| <img width="478" alt="image" src="https://user-images.githubusercontent.com/495429/189341041-6d4b3d94-5e1c-4790-bde1-897158aa4c51.png"> | <img width="478" alt="image" src="https://user-images.githubusercontent.com/495429/189341118-af0b5196-8179-498f-bd22-7f3db506e1cb.png"> |
---
As rumba is currently refusing to run for me locally, I tested it as follows: Open https://developer.allizom.org/en-US/docs/Learn/CSS (logged in as Supporter), apply the CSS changes manually.
> fix(form): prevent selects from overflowing

- deployer/src/deployer/analyze_pr.py
- deployer/src/deployer/test_analyze_pr.py
We are trying to reduce the size of the comment created by our PR companion as much as possible.
We've started it by removing redundant stuff first. 
This PR aims to remove some logs that are not necessary: [[ref](https://github.com/orgs/mdn/discussions/51#discussioncomment-3606826)]
a. `No *new* external URLs` or `No external URLs`
b. `*no external links in the built pages* 👱🏽` (when no external URLs found)
c. `*None!* 🎉` (when there are no flaws)
Logs mentioned in a. add 7 lines to the comment.
Logs b. and c. unnecessarily add a section to the comment.
It is not necessary to tell contributors that there are no flaws or there are not new URLs. We need to tell only about errors.
- Do not show the section if there are no errors or new info.
- Do not include a log if there is no new URL. …
> fix(pr-companion): remove redundant entries

- client/src/document/ingredients/browser-compatibility-table/index.tsx
- client/src/document/ingredients/browser-compatibility-table/legend.tsx
Following up from #6602, don't include IE legend items (note: I'm not fully sure if I agree with IE having been removed already, but nonetheless now that it's done these legend items constitute a bug).
The legend could include symbols not present in the visible BCD if only IE had the indicated support.
Skip IE checks when adding to the legend.
---
https://developer.mozilla.org/en-US/docs/Web/CSS/isolation#browser_compatibility
http://localhost:3000/en-US/docs/Web/CSS/isolation#browser_compatibility
> fix(bcd): Don't include IE specific compatibility in the legend

- kumascript/macros/Compat.ejs
- kumascript/macros/Specifications.ejs
- kumascript/tests/macros/Compat.test.js
- kumascript/tests/macros/Specifications.test.js
- testing/content/files/en-us/web/api/page_visibility_api/index.html
- testing/content/files/en-us/web/badbcdqueries/index.html
- testing/content/files/en-us/web/bcd_table_extraction/index.html
In current MDN article content, we no longer have any `Compat` or `Specifications` macros which have arguments — instead all articles use the `browser-compat` frontmatter key or the `spec-urls` frontmatter key.
And in no cases is it any longer necessary to ever call the `Compat` or `Specifications` macros with any arguments — instead in all cases, the `browser-compat` and `spec-urls` frontmatter keys can be used; therefore, it’s appropriate to report flaws for any new cases where a PR adds content that has arguments in `Compat` or `Specifications` macro calls.
> Deprecate Compat/Specifications macro parameters

- .github/PULL_REQUEST_TEMPLATE.md
Fixes https://github.com/mdn/yari/issues/6130 by updating the PR template.
Notes:
- Replaces the formatting item, because prettier is run automatically.
- Also removes the locale from URLs, not to enforce the English version.
> chore(github): update PR template to mention signed commits

- build/spas.ts
Prevents PRs from showing up in "Recent contributions" that have been merged long time ago.
Activity on old PRs resets the `updated` timestamp, so they show up in our "Recent contributions", and GitHub doesn't support sorting by `merged` yet.
Additionally filter the PRs to only show those that have been merged in the last 48 hours (usually there are always more than 10).
---
Note that the first item is PR 1 (!), caused by [this comment](https://github.com/mdn/content/pull/1#issuecomment-1235481669).
---
Ran `yarn tool spas` once on `main` (see Before screenshot) and once on this branch (see After screenshot).
> fix(build/spas): filter recently merged contributions

- client/src/search-utils.ts
Restricts the search shortcut to <kbd>Ctrl</kbd>+<kbd>K</kbd>, excluding <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd> which is already used by Firefox to toggle the web console.
Fixes #6964.
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd> focuses the search field on MDN instead of opening the web console.
Make sure that only <kbd>Ctrl</kbd>+<kbd>K</kbd> focuses the search field on MDN.
---
n/a
---
Ran `yarn dev` and verified with Firefox on Mac OS that Ctrl-Shift-K no longer focuses the search field. (It didn't open the web console though, because the shortcut is Ctrl-Alt-K on Mac OS.)
> fix(search-utils): focus search with Ctrl-K, not Ctrl-Shift-K 

- kumascript/macros/ExperimentalBadge.ejs
support localization for {{ExperimentalBadge}} macro which is used by {{APIRef}}, {{experimental_inline}}, etc.
This macro should support localization. But it won't. (the `title` and `abbreviation` is fixed with en-US text)
use `mdn.localString` to select l10n `title` and `abbreviation` for this macro. (Just like #6954)
---
In <hocalhost:5042/zh-CN/docs/Web/API/CharacterData#方法>
---
run `yarn dev` and check the rendered html.
> feat(macros): localize ExperimentalBadge

- build/syntax-highlight.ts
- Same as https://github.com/mdn/yari/pull/7017 but for CSS
- Addresses https://github.com/mdn/content/pull/20655#pullrequestreview-1105538164
> The idea is to have such code blocks styled by Prism with the right color scheme but skipped when linter run, like Markdownlint, or Prettier, as these blocks are not valid (for example our syntax box), or should not be formatted by linters (like examples of invalid code, or TML templates that require an unusual alignment).
We are finding may places where manual formatting is more readable than the Prettier. For example,
```
.multiple {
box-shadow: 1px 1px 1px black,
2px 2px 1px black,
3px 3px 1px red,
4px 4px 1px red,
5px 5px 1px black,
6px 6px 1px black;
}
```
We need `css-nolint` for such cases and for `example-bad` code fences.
Also, CSS …
> chore(syntax-highlight): add nolint alias for CSS

- client/src/ui/_vars.scss
Fixes #6534 by increasing the contrast of punctuation and comments in code samples.
The punctuation and comments did not have enough contrast against the background color.
Make them brighter in dark theme, and lighter in light theme.
---
| --- | --- |
| <img width="287" alt="image" src="https://user-images.githubusercontent.com/495429/189733951-279b9f7a-0f13-4367-9ee5-a59ff34932c8.png"> | <img width="287" alt="image" src="https://user-images.githubusercontent.com/495429/189733989-07c486bf-a138-4b99-8515-3d209d459f4f.png"> |
| <img width="287" alt="image" src="https://user-images.githubusercontent.com/495429/189734077-43cc3301-2c08-4d0e-8b69-31b805103d60.png"> | <img width="287" alt="image" src="https://user-images.githubusercontent.com/495429/189734112-5d830ed9-fd3f-4c11 …
> fix(a11y): increase contrast of code sample punctuation/comments

- client/src/document/index.scss
- kumascript/macros/EmbedLiveSample.ejs
Restores the live sample design/layout, as intended by the redesign.
The padding of live samples was removed in https://github.com/mdn/yari/pull/6506, following [this discussion](https://github.com/orgs/mdn/discussions/127), because it had caused scroll bars in some cases.
Unfortunately, the change caused a layout regression, as the samples have no longer been aligned with code blocks:
| Before (with padding) | After (without padding) |
|-------|-------|
| ![image](https://user-images.githubusercontent.com/495429/188730761-e86fd98e-792d-4383-af56-567dea17aaa3.png) | ![image](https://user-images.githubusercontent.com/495429/188730805-b20a3942-b288-4d5f-b9f0-c82db91b2bec.png) |
| ![image](https://user-images.githubusercontent.com/495429/188732630-fbbe6432-6d3f-44d0-bb29-774e804fa757.png) | …
> fix(live-samples): restore padding, use content-box sizing, reduce MIN_HEIGHT to 24px

- client/src/document/ingredients/browser-compatibility-table/index-mobile.scss
Fixes #6514 by properly containing the BCD-related style that hides the header of the BCD table.
Some tables were missing their headers on mobile, because BCD-related styles were leaking into unrelated areas.
Wrap the styles in a local selector.
---
| --- | --- |
| <img width="361" alt="image" src="https://user-images.githubusercontent.com/495429/189756726-fe0abc3c-5b9d-4f99-bd44-e0923ae0da54.png"> | <img width="361" alt="image" src="https://user-images.githubusercontent.com/495429/189756646-03665bbe-d08d-4e91-a0c4-b422472811e7.png"> |
---
Opened http://localhost:3000/en-US/docs/Web/HTTP/Headers/Cache-Control#cache_directives locally in responsive mode.
> fix(bcd): apply mobile style only to bc-table

- markdown/m2h/handlers/code.ts
Related to https://github.com/mdn/yari/pull/7017
Recently we introduced new aliases `js-nolint`, `html-nolint`, and `css-nolint` in order to avoid some code fences getting linted.
But current live sample code doesn't recognize the new language tags.
The live sample code collector doesn't recognize `-nolint` language aliases.
Widen the Cheerio CSS attribute style selector using [wild card](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#attrvalue_6) e.g. `pre[class*="${part}"]` 
Use same code for a live sample but with `-nolint` added to all language code fences.
cc/ @caugner @teoli2003
> fix(livesample): support nolint aliases

- ssr/render.ts
Fixes https://github.com/mdn/yari/issues/4961 by escaping the colon (`:`) in the `<title>` tag and the SEO fields.
Google omits the first part of our HTML element titles:
Compare this with DuckDuckGo:
Apparently, escaping the colon does the trick and avoids that Google ignores it.
---
(See above.)
---
Didn't test, but others have tested this before in https://github.com/mdn/yari/issues/4961.
> fix(ssr): escape colon in <title>

- build/spas.ts
Fixes https://github.com/mdn/yari/issues/5732 by refactoring `build/spas.ts` to use ~~`klawSync`~~ `fdir` for gathering the static page files.
n/a
---
Ran `yarn tool spas` locally.
> refactor(build/spas): use fdir

- package.json
- tool/cli.ts
- yarn.lock
Removes `klaw-sync` in favor of `fdir`.
See: https://github.com/mdn/yari/pull/7153#discussion_r971691542
---
n/a
---
Ran `yarn tool inventory` before and after.
> build(deps): remove klaw-sync

- package.json
- yarn.lock
`node-gettext` seems unnecessary.
It was installed in #4251 and used by `markdown/h2m/handlers/cards.ts`. But the current main branch does not contains `cards.ts` and any script does not require it.
> https://github.com/mdn/yari/pull/4251/files#diff-0f919606f76e72c94cf68c97d6f47295dee810ad44ab5625c5d3f8db06da576bR1
delete it from `package.json`
---
N/A
---
1. delete `node-gettext` from `package.json`
2. run `yarn dev` and confirmed an operation complete without error
3. run `yarn build` and confirmed an operation complete without error
> chore(deps): delete `node-gettext` from dependencies

- kumascript/macros/GlossaryDisambiguation.ejs
- kumascript/macros/HTMLRefTable.ejs
- kumascript/macros/SubpagesWithSummaries.ejs
- kumascript/src/info.ts
The summary getter was being evaluated without being used. This was rather costly. Let's move to method.
> fix(kumascript): don't always eval summary

- kumascript/macros/WebAssemblySidebar.ejs
- kumascript/tests/macros/WebAssemblySidebar.test.ts
Accompanying change of https://github.com/mdn/content/pull/20603
---
---
> chore(macros/WASMSidebar): remove use of jsxref

- deployer/src/deployer/analyze_pr.py
- deployer/src/deployer/test_analyze_pr.py
We are trying to reduce the size of the comment created by our PR companion as much as possible. The redundant stuff has been removed.
This PR aims to reduce the comment height further by folding the sections using `<details>` tag.
Not everyone is interested in all the sections. Showing all the section in full increases the height of the comment tremendously.
Put the sections in `<details>` tags so that contributors will expand only the required sections.
Also show section summary in the title to give overall idea without opening the section.
See [the first comment](https://github.com/mdn/yari/pull/7110#issuecomment-1242667057) below this post for the sample output.
---
**Note:** The PR aims to get the feel of folded sections. This is not the final change. Final changes will be done after …
> fix(pr-companion): fold sections with count

- client/src/document/on-github.tsx
Updates the "Report on GitHub" link for localized pages to use the new `page-report.yml` template (this may require more discussion). **This should be merged together with mdn/translated-content#8538.**
`translated-content` is still using the old issue template, which is less descriptive and less instructive than the new `page-report.yml` used on `content`.
This PR modifies the `NewIssueOnGitHubLink` to create an issue using `page-report.yml` on translated-content, and not only on `content` (The YAML template will be added on `translated-content` in mdn/translated-content#8538).
---
I tested on my local machine with a `yarn dev` server.
> Use `page-report.yml` for locales

- build/document-extractor.ts
- build/index.ts
- kumascript/index.ts
- kumascript/src/api/util.ts
- kumascript/tests/index.test.ts
- server/index.ts
Apparently this doesn't change build time / actually improves it since we now can just parse less html (render now returns a `CheerioAPI` object).
> fix(build): stop caching kumascript render

- kumascript/macros/CSSSyntax.ejs
Use page-type instead of tags for the CSSSyntax macro.
We recently defined and added page types for pages under Web/CSS: https://github.com/mdn/content/issues/15540 .
One of the purposes of this was to replace tags for describing the type of thing a page documented. @teoli2003 observed that it would be a good idea to start using page types as soon as possible, as this gives us an incentive to keep them maintained.
So this PR updates the CSSSyntax macro to use page types instead of tags.
UI should look exactly the same, except in places where tags and page-type don't agree, in which case page-type should be more accurate.
Ran yarn dev, looked at some Web/CSS pages. Really what we are testing is that the macro can figure out how to get the formal syntax from webref for each of the four …
> Use page type instead of tags for CSSSyntax macro

- client/src/plus/collections/api.ts
- client/src/plus/collections/collection.tsx
add additional link to go back on collection page
testing requires fully disabling the service worker, otherwise it'll interfere in the error responses
> MP-120: display error message from rumba

- kumascript/macros/HTTPSidebar.ejs
Removes the link to HTTP Public Key Pinning (HPKP) from the HTTPSidebar macro. Fixes https://github.com/mdn/yari/issues/7224.
https://github.com/mdn/yari/issues/7224 explains well what the problem is and the suggested solution.
Remove the link to the page.
---
Ran yarn dev, visited http://localhost:3000/en-US/docs/Web/HTTP/Headers .
> Remove HPKP from HTTP Sidebar

- client/src/watch.tsx
`client/src/watch.tsx` component is never used anywhere.
Delete `client/src/watch.tsx`.
---
N/A
Confirmed to work `yarn run start` and `yarn run build` locally without any error.
---
Thank you :)
> refactor: delete unnecessary `client/src/watch.tsx`

- build/document-extractor.ts
Within the last few releases, a pull request was merged to BCD that replaces links to `drafts.csswg.org` with `w3c.github.io/csswg-drafts`.  This was done because `drafts.csswg.org` is almost always unavailable, leaving MDN readers (including and especially contributors) with no spec to refer to.  The downtime issues have persisted for over a year, with no end in sight.  Because of this, various developers have created their own mirrors with reliable build engines, including https://andreubotella.com/csswg-auto-build/, whose code was then used to create a new official mirror.
As an unfortunate result, however, any spec URLs using the new mirror will show "Unknown specification".  This has been resolved in `browser-specs` by adding a new `alternateUrls` property that contains the URL to …
> Allow alternate nightly spec URLs

- kumascript/macros/CSSRef.ejs
This PR updates the CSSRef.ejs macro, which builds the CSS sidebar, to use the `page-type` key to classify pages, instead of tags.
Tags are an unreliable way to classify pages and their semantics is often unclear. For example, https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions and https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types are tagged as "CSS Data Type" pages, which is understandable because they are about CSS types. But they aren't reference docs pages for individual CSS types, which means it's incorrect for them to show up in the sidebar as part of such a list:
Use page types instead of tags to group pages.
I changed the code to use a switch instead of a collection of `filter` calls, as the logic seemed clearer that way (there's one item, and we're doing …
> Use page types, not tags, for CSS sidebar

- content/document.ts
- kumascript/index.ts
Fixes: #7196.
~It seems that the `findByURL` doesn't pass roots as a string array. Just fix this.~ refeactor the `read` function: pass roots as rest parameters.
And for the `remove` function, we can search with the specific root (not both `en-us` and `l10n`). And we can throw error when the locale is not specified (or not exists).
Minor fixes.
---
for en-US (`yarn tool delete Web/API/ShadowRoot/onslotchange --redirect=Web/API/HTMLSlotElement/slotchange_event`)
for fr (`yarn tool delete conflicting/Glossary/Firefox_OS fr --redirect Glossary/Boot2Gecko`)
for en-US:
for fr:
---
run `yarn tool delete`
> fix(content/document): let `roots` as rest parameters of read

- client/src/document/on-github.tsx
This modifies the "Report on GitHub" link for localized pages to use translated issue templates (e.g. `page-report-fr.yml` for French). Part of mdn/translated-content#8918.
Currently, all locales use the English `page-report.yml` template, but MDN viewers may prefer to read instructions and/or to create issues in a locale language.
A `page-report-<locale>.yml` will be added for each active locale on the `translated-content` repo. The "Report on GitHub" link will point to `page-report-<locale>.yml` on localized pages and `page-report.yml` on en-US pages.
---
I tested this with `yarn dev` on my local machine.
> chore(on-github): use localized issue templates for translated-content

- kumascript/macros/HTMLRefTable.ejs
Wrong typo of the words "especialy" instead of "especially" and "prototypt" instead of "prototype" and no verb to be before
the word "especially"
"This is especially" instead of "This especialy"
and "prototype" instead of "prototypt".
> chore(macros/HTMLRefTable): fix typos

- .github/dependabot.yml
Adds dependabot config for the remaining nested yarn.lock files.
Also unignores the Storybook dependencies since they're no longer used
---
---
> chore: add Dependabot for remaining yarn.lock

- kumascript/macros/APIRef.ejs
- kumascript/tests/macros/apiref.test.ts
- kumascript/tests/macros/fixtures/apiref/commonl10n.json
- kumascript/tests/macros/fixtures/apiref/subpages.json
In the APIRef sidebar, have separate lists for static and instance properties and methods.
Currently the APIRef sidebar lists just "Properties" and "Methods", combining instance and static members and not distinguishing them.
This PR uses page types to build separate lists for instance and static members, as @Elchi3 suggested in https://github.com/mdn/yari/pull/7223#pullrequestreview-1129982474.
This is in line with the recent work @hamishwillee  has been doing in https://github.com/mdn/content/pull/21353 and so on, and contributes to https://github.com/openwebdocs/project/issues/104 .
This PR has a dependency on the l10 strings in https://github.com/mdn/content/blob/main/files/jsondata/L10n-Common.json. I've added strings for en-US in …
> chore(macros/APIRef): separate static and instance members

- kumascript/macros/LearnSidebar.ejs
@schalkneethling
cc @hmatrjp @potappo 
- [Building Angular applications and further resources の翻訳 #637 ](https://github.com/mozilla-japan/translation/issues/637)  のPRです。
still en-us only
taranlate japanese for LearnSidebar.ejs
still en-us only
add taranlate japanese for LearnSidebar.ejs
> chore(macros/LearnSidebar): add Japanese translation(Angular Building)

- content/document.ts
- testing/content/files/en-us/markdown/tool/m2h/expected.html
Prettier has been adding this spacing upstream, but files moved with Yari are undoing those changes
---
---
> fix(content/document): preserve metadata spacing on write

- .stylelintignore
This file doesn't appear to exist anymore, so it doesn't need to be ignore. Think it is now `_vars.scss`, which is being linted now
---
---
> chore: remove old Stylelint ignore

- kumascript/macros/source.ejs
Deprecates the `{{source}}` macro, which is no longer used in content and already tracked for removal in translated-content: https://github.com/mdn/translated-content/issues/7178
> chore(macros): deprecate {{source}}

- client/src/document/ingredients/browser-compatibility-table/index.scss
- client/src/document/ingredients/browser-compatibility-table/utils.ts
Fixes #5041
When parent and children had no compatibility data, grandchild data was not shown
Show the grandchildren only when neither the parent nor its immediate children have any data. Determine at what depth we have the first data, then show that depth + 1.
---
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/panels#browser_compatibility **unchanged**:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#browser_compatibility **unchanged**:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools#browser_compatibility:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy#browser_compatibility:
http://localhost:3000/en-US/docs/Mozilla/Add-ons/WebExtensions/API/d …
> fix(bcd): list descendant features even if parent has no data

- kumascript/macros/CSSRef.ejs
Fixes https://github.com/mdn/yari/issues/7437 by adding combinators to the CSS sidebar.
See https://github.com/mdn/yari/issues/7437.
Adds combinators to CSS sidebar.
---
en-US:
fr (Note that titles are not translated due to https://github.com/mdn/yari/issues/7438.):
Ran yarn dev, looked at some pages.
> chore(macros/CSSRef): add Combinator pages

- kumascript/macros/HTMLSidebar.ejs
- kumascript/src/api/web.ts
Addresses https://github.com/mdn/content/pull/21617#issuecomment-1286240392
The PR:
- removes "Documentation" section
- adds a new "Guides" section to include miscellaneous pages under `mdn/content/files/en-us/web/html` directory
- adds localized text for links in the new "Guides" section, iff the page has been translated
There are two sidebar macros for HTML pages at the moment: `HTMLSidebar` and `HTMLRef`. And some pages are not included in any of the macros. Also, `HTMLRef` macro doesn't add extra content compared to `HTMLSidebar`.
Make `HTMLSidebar` complete and use it everywhere. Then deprecate `HTMLRef` macro.
https://web.archive.org/web/20221019094528/https://developer.mozilla.org/en-US/docs/Web/HTML
In local dev environment.
/cc @teoli2003 , @wbamberg , @caugner
> fix(macros/HTMLSidebar): replace Documentation section by Guides section

- client/src/document/index.tsx
- client/src/page-not-found/fallback-link.tsx
- client/src/ui/molecules/notecards/index.scss
Fixes https://github.com/mdn/yari/issues/6629.
Fixes https://github.com/mdn/yari/issues/5853.
When users access a page that no longer exists and doesn't have a redirect in place, they are essentially stuck.
Suggest users to search the site for the URL paths beginning from the right, ~~and mention the https://github.com/mdn/archived-content repository where removed content can be found~~.
---
Example: http://localhost:3000/en-US/Core_JavaScript_1.5_Guide/Exception_Handling_Statements/try...catch_Statement
---
Opened http://localhost:3000/en-US/Core_JavaScript_1.5_Guide/Exception_Handling_Statements/try...catch_Statement locally.
> feat(page-not-found): suggest search terms

- build/spas.ts
- content/document.ts
- libs/types/document.ts
- tool/cli.ts
- tool/sync-translated-content.ts
Moves `build/sync-translated-content.ts` to `tool/sync-translated-content.ts`, because it is only used by `tool/cli.ts`.
After this change, `tool/` no longer depends on `build/`! 🎉 
---
n/a
---
Ran `yarn tool sync-translated-content` locally.
> refactor(sync-translated-content): move from /build to /tool

- client/src/ui/organisms/article-actions/index.scss
in Chromium Linux, before:
after:
> fix(plus): remove always-displayed scrollbars on article action dropdowns

- client/src/plus/collections/collection.tsx
- client/src/plus/collections/new-edit-collection-modal.tsx
- client/src/ui/organisms/article-actions/bookmark-menu/index.tsx
this was causing the name/title field to not be validated as required,
and so showing an api error
also add `required` to item name in bookmark dropdown
> MP-128: validate collections forms when submitting with return key

- build/index.ts
- client/src/document/index.scss
- client/src/document/index.tsx
- kumascript/src/errors.ts
Fixes #7106 by improving the way `MacroInvocationError`s are displayed (both in the command line and in the browser).
Macro errors were always confusing and hard to locate, because the shown line number did not correspond to the Markdown file.
Remove the line numbers in favor of showing the source context (+/- 2 lines).
---
---
Opened http://localhost:3000/en-US/docs/MDN/Kitchensink locally and introduced a syntax error in my local mdn/content checkout by removing the second `"` in this line:
https://github.com/mdn/content/blob/6fdcfb2bb5862d89d84cc511cf31a0e4fffc72bf/files/en-us/mdn/kitchensink/index.md?plain=1#L300
> fix(kumascript): improve MacroInvocationError display

- client/src/app.scss
- kumascript/macros/htmlattrdef.ejs
Fixes #6427 by making the self-referencing anchor an inline-block.
We use a `scroll-margin-top` to make sure targeted anchors display below our sticky header, but Safari seems to ignore `scroll-margin-top` for inline elements (see [here](https://stackoverflow.com/a/73120680)), so the targeted anchor ends up behind the sticky header.
Make the anchor an inline-block via a newly introduced utility class.
---
---
Opened http://localhost:3000/en-US/docs/Web/HTML/Element/button#attr-autocomplete locally in Safari.
> fix(macros/htmlattrdef): use inline-block for self-link

- build/flaws/broken-links.ts
Fixes https://github.com/mdn/yari/issues/5269 by syncing the fallback-link behavior of the broken-links flaw with `web.smartLink()`.
Yari automatically replaces links to missing translated pages to their English counter-part, adding a "(en-US)" inside the link, but this was discarding formatting of the link text.
Sync the implementation of the broken-link flaw that does this for inline links, with the implementation of `web.smartLink()` which is used by macros and already did this correctly.
---
---
Locally added a missing inline-link in the Spanish locale [here](http://localhost:3000/es/docs/Web/JavaScript/Reference/Global_Objects#propiedades_de_valor).
> fix(build): sync broken-links flaw with web.smartLink()

- client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
This PR fixes the issue reported in https://github.com/mdn/browser-compat-data/issues/18139.  During #5679, some logic was accidentally removed that handles the case for when `version_added` is `true` and `version_removed` is truthy.  This adds such logic back in.
> Fix BCD rendering when added is "true" and removed is truthy

- client/src/document/ingredients/browser-compatibility-table/utils.ts
Fixes #7466
See https://stackoverflow.com/questions/53978067/hasownproperty-is-not-a-function-in-node-js/53978289#53978289.
Use the simpler value.__compat
---
Tested on dev site
> fix(bcd): Allow check for __compat on objects that don't inherit from Object

- build/document-extractor.ts
Expand all sidebar sections, not just the closest.
If a sidebar has collapsible sections, we expand the one containing the link to the current page. But we only expand the closest one, so if the sidebar has nested collapsible sections, then the current-page link is still not visible.
I don't know if we have nested collapsible sections in any sidebars at the moment, but https://github.com/mdn/yari/pull/7441 proposes a sidebar design that has some.
Use [`parents()`](https://api.jquery.com/parents/) instead of [`closest()`](https://api.jquery.com/closest/) to find elements to expand.
> Expand all collapsible sidebar sections, not just the closest

- tool/cli.ts
Wrapping original error and failing at the end, after all the checks are done, makes it hard to figure out what went wrong.
Refer https://github.com/mdn/translated-content/pull/8171#issuecomment-1256879734
The check run https://github.com/mdn/translated-content/actions/runs/3114446745/jobs/5050295335 failed with following log:
```log
Run yarn content validate-redirects --strict
yarn run v1.22.19
$ env-cmd --silent cross-env CONTENT_ROOT=files yari-tool validate-redirects --strict
Skipping: non en-us locale: /en-US/docs/Secciones_y_contornos_de_un_documento_HTML5	/es/docs/Sections_and_Outlines_of_an_HTML5_document
Skipping: non en-us locale: /en-US/docs/Web/API/WebGL_API/Getting_started_with_WebGL/Commencer_avec_le_WebGL	/fr/docs/Web/API/WebGL_API/Tutorial/Commencer_avec_WebGL
Skipping: …
```
> fix(check_redirects): make the checks fail fast

- kumascript/macros/CSSSyntax.ejs
Support at-rules and at-rule descriptors in the formal syntax.
When we switched to use webref for formal syntax, we dropped support for at-rules and at-rule descriptors. This restores it as promised in https://github.com/mdn/yari/pull/4656#issuecomment-1137467121.
There are a few code changes here:
- the `getNameAndSyntax()` function is the entry point to the bit of this macro that interfaces with webref, and is basically a switch on the different page types. I've extended it to support the additional cases of `css-at-rule` and `css-at-rule-descriptor`
- I've added new functions, `getAtRuleSyntax()` and `getAtRuleDescriptorSyntax()`, to fetch the syntax for these things
- very minor refactoring of a bit of shared code out of `getPropertySyntax()` and into a new function …
> feat(macros/CSSSyntax): support at-rules and at-rule descriptors

- build/document-extractor.ts
This PR fixes https://github.com/mdn/content/issues/22061 by adding some logic to ensure that when there is a match for the series nightly URL, it will always grab the latest version of the series.
Testing Method:
Navigated to http://localhost:3000/en-US/docs/Web/SVG/Attribute/orient and ensured that the specifications section shows "SVG 2" instead of "SVG 1.1 (Second Edition)".
> Always use latest series version of spec when using series nightly URL

- build/cli.ts
- build/index.ts
- libs/types/document.ts
- server/index.ts
Adds a `metadata.json` per locale. This contains the sha256sum of all `index.json`s, too. This will be used to sync metadata with rumba in the future.
> enchance(build): write metadata.json with hashes and browser compat

- .eslintrc.js
Was going to bump it higher because I noticed an issue with VSCode flagging `?.` on some of the compiled JS (related to the differnce happening with the ignores on Windows). Rather than bump the ESLint higher, I matched it to the TypeScript version
---
---
> chore: match ESLint ES version tsconfig.json

- content/utils.ts
- server/dev.ts
Should fix the failing check when bumping yari in mdn/content https://github.com/mdn/content/pull/22218.
https://github.com/mdn/yari/pull/7430 changed the way we import dependencies by moving from `require` to `import`, and `import` statements cannot be imported _conditionally_, because they must appear at the top of the file. However, when `import`ing (or `require`ing) an optional dependency (e.g. a `devDepencency`) _unconditionally_, this will cause an error.
Specifically, we `require` prettier and webpack, which are available when developing yari, but not when using yari as part of mdn/content.
PS: ESLint actually complains about this via the `n/no-unpublished-import` rule, but we don't currently run ESLint on TypeScript until https://github.com/mdn/yari/pull/7454 lands and that PR has …
> fix: require optional dependencies conditionally

- client/src/ui/_mixins.scss
Webkit shows a black band in the line-clamp gradient - this is actually correct according to the spec, as it defines `transparent` as "transparent black".
Use a `mask-image` with the gradient in it instead, where we can use a gradient from transparent black to black for all background colours (turning a css variable transparent isn't yet a supported css feature).
Though I wonder if it's worth just going back to the `-webkit-line-clamp` property which we used before (and I didn't like). It's imperfect, but so is this approach. It's also far less code:
```scss
@mixin line-clamp($lines) {
display: -webkit-box;
-webkit-box-orient: vertical;
-webkit-line-clamp: $lines;
overflow: hidden;
}
```
---
---
Tested across Firefox/Chromium/GNOME Web across dark/light themes on …
> fix(css): line-clamp on webkit showing black in gradient

- client/src/document/index.scss
Fixes https://github.com/mdn/yari/issues/6166 by specifying a font-family for code samples.
The Japanese locale used a different (default) font.
Specify `--font-code` for `<code>`.
---
| --- | --- |
| <img width="861" alt="image" src="https://user-images.githubusercontent.com/495429/189762462-1588d7e3-64ae-4a5e-8c14-328c1f3da639.png"> | <img width="861" alt="image" src="https://user-images.githubusercontent.com/495429/189762382-d27302e0-21ba-4486-af7b-5a1a03273c87.png"> |
---
Opened http://localhost:3000/ja/docs/Web/HTML/Element/head#%E4%BE%8B locally.
> fix(document): use --font-code for <code>

- kumascript/macros/JsSidebar.ejs
There are some entries that are duplicated between the "Tutorials" and "References" sections, which IMO is unnecessary. I figured it's best to keep the "References" part strictly to those pages with `/Reference/` in its slug.
Also removed an entry that points to a nonexistent page (`Transitioning_to_strict_mode` has been merged into `Strict_mode`).
cc @mdn/yari-content-javascript
> Deduplicate JS sidebar entries

- client/src/document/organisms/sidebar/index.scss
- client/src/document/organisms/sidebar/index.tsx
Make the sidebar scroll to the entry for the currently open page
Although the sidebar is manually scrollable, it doesn't auto-scroll to show the entry you are currently on.
I don't entirely know what I'm doing here so I may be off in the weeds, but I thought it was worth a go, since this would be a great feature to have.
I've just added a bit of React code to scroll the current item into view when the page loads...I think.
It doesn't quite work because the main content area scrolls a bit too. I think somehow the sidebar isn't accounting for the header, and that is making it happen? Would love some help with that.
...ran yarn dev, loaded some pages...
> feat(sidebar): scroll to the current page

- client/src/ui/organisms/footer/index.tsx
The link links to the wrong page that does not contain information about the Creative Commons license. I make a correction by changing href attribute to /docs/MDN/Writing_guidelines/Attribu_copyright_license now the link redirects us to https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Attrib_copyright_license.
Changing the URL link of the creative commons license as the link attached with it didn't provide information about the creative commons license.
Fixes #6036.
The link is not linked to the creative commons license it is linked to the page that describes rules for writing guidelines.
This makes visitors easy to find the creative commons licenses page and helps them to know more about it without navigating other pages.
Changing the link in href attribute to …
> fix(footer): update Creative Common license link

- build/wrap-tables.ts
- client/src/document/ingredients/browser-compatibility-table/index-desktop-md.scss
- client/src/document/ingredients/browser-compatibility-table/index-desktop-xl.scss
- client/src/document/ingredients/browser-compatibility-table/index-desktop.scss
- client/src/document/ingredients/browser-compatibility-table/index-mobile.scss
- client/src/document/ingredients/browser-compatibility-table/index.tsx
Fixes https://github.com/mdn/yari/issues/5358 by wrapping tables in a `<figure>` with a CSS class doesn't contain the keyword `scroll`.
Firefox Reader View was not showing our tables, which were wrapped in a `div.table-scroll` to make them horizontally scrollable (when overflowing, especially for long tables and on mobile).
Wrap them in a `figure.table-container` instead.
---
(https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate)
---
Opened http://localhost:5042/en-US/docs/Web/HTTP/Headers/WWW-Authenticate locally in Firefox Reader Mode.
**Note**: Firefox Reader Mode is not available on http://localhost:3000/, because it parses the site without JavaScript (i.e. requires SSR, which is only available on port 5042).
> fix(tables): wrap in figure.table-container, not div.table-scroll

- tool/cli.ts
Fixes #4106.
`yarn tool add-redirect` expects its arguments `from` and `to` to be absolute URLs without origin, (e.g. `/en-US/docs/...`) and providing a URL with origin (e.g. `https://developer.mozilla.org/en-US/docs/...`) does not work.
Accept any URL and just use their `pathname`.
---
---
Ran `yarn tool add-redirect https://developer.mozilla.org/en-US/docs/Foo https://developer.mozilla.org/en-US/docs/Bar`.
> chore(tool/add-redirect): accept URLs with origin

- client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
- client/src/document/ingredients/browser-compatibility-table/utils.ts
- package.json
- yarn.lock
Fixes #6667
The version range showed the version where support was removed as well, which was confusing.
Get version before that version using a helper function, and show that version number instead.
---
https://developer.mozilla.org/en-US/docs/Web/API/DocumentType#browser_compatibility
http://localhost:3000/en-US/docs/Web/API/DocumentType#browser_compatibility
> fix(bcd): show previous version in range when feature was removed

- .github/workflows/dev-build.yml
- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
prevent `Node.js 12 actions are deprecated` warning (see: https://github.com/mdn/yari/actions/runs/3493057700)
use `v1-node16` branch instead. see issue: https://github.com/aws-actions/configure-aws-credentials/issues/489#issuecomment-1278145876
---
NA.
> ci(build): use node16 as runtime of configure-aws-credentials

- client/pwa/src/db.ts
- client/pwa/src/service-worker.ts
- client/src/plus/collections-quicksearch.ts
- client/src/search.tsx
- client/src/settings/db.ts
- client/src/settings/mdn-worker.tsx
- client/src/settings/offline-settings.tsx
- client/src/user-context.tsx
The service worker runs for all logged in users. Let's run it only for users which have MDN offline enabled.
We need the service only for MDN Offline these days. But we run it for all logged in users and it sometimes causes random request failures.
- disable the service worker if MDN Offline is disabled
- refactor after removing code
---
> fix(pwa): don't start the service worker if offline is disabled

- build/document-extractor.ts
- client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
- client/src/document/ingredients/browser-compatibility-table/utils.ts
- package.json
- yarn.lock
Fixes https://github.com/mdn/yari/issues/6667 on prod
See https://github.com/mdn/yari/pull/7589#issuecomment-1318433195
Put `version_last` (version before version_removed when version_removed is a string) in BCD info in document-extractor. Then show it in BCD version range.
---
No difference compared to https://github.com/mdn/yari/pull/7589
---
`yarn build`
> fix(bcd): Fix version range in production

- kumascript/src/templates.ts
Our kumascript macros sometimes fail under certain circumstances (e.g. https://github.com/mdn/yari/issues/4670), but there is no indication as to why they failed. This makes it almost impossible for users to report them, and hard for developers to investigate them.
Catch errors when rendering macros, and print them to the console.
---
---
Introduced a syntax error into `kumascript/src/api/web.ts` (`web.smartLink()`), and visited http://localhost:3000/en-US/docs/Web/API/Window#deprecated_methods locally.
> chore(kumascript): log macro failures

- package.json
Otherwise `correctContentPathFromEnv()` in libs/env fails.
Running `yarn filecheck` in the yari repo has been failing if a relative path (e.g. `../content`) was specified as `CONTENT_ROOT`:
```
% yarn filecheck
Debugger attached.
yarn run v1.22.19
$ cd filecheck && ts-node cli.ts
Debugger attached.
Error: ENOENT: no such file or directory, lstat '/Users/claas/github/mdn/yari/content/files'
at Object.realpathSync (node:fs:2503:7)
at correctContentPathFromEnv (/Users/claas/github/mdn/yari/libs/env/index.js:98:17)
at Object.<anonymous> (/Users/claas/github/mdn/yari/libs/env/index.js:67:22)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at Object.require.extensions.<computed> [as .js] …
```
> fix(filecheck): run from repository root

- client/src/community/index.tsx
Whitespace is missing before the `Join us!` link:
This PR fixes the link and adds some missing punctuation.
> chore(docs) Fix missing whitespace before Join us! link

- build/spas.ts
- client/src/app.tsx
Fix double rendering for SSR pages.
We render the document again when we hdyrate. This can be observed by looking at the network panel. Assets get loaded twice.
Stop lazy loading the routes.
> fix(rendering): don't render everything twice

- .github/workflows/auto-merge.yml
Unblocks the failing auto-merge check by moving away from `ahmadnassri/action-dependabot-auto-merge`.
The auto-merge check is currently failing, preventing us from having minor/patch dependency updates merged automatically.
Replace `ahmadnassri/action-dependabot-auto-merge` by `dependabot/fetch-metadata` and GitHub CLI to automatically "squash and merge" minor/patch dependency updates.
---
n/a
---
_I'm not sure how to test this._
> ci(auto-merge): use dependabot/fetch-metadata + GitHub CLI

- kumascript/macros/web.link.ejs
The {{web.link}} macro has been deprecated. And now, this macro has been removed from mdn/translated-content. I've run the command below to verify it:
```bash
rg -i '\{\{\s*web\.link' | wc -l
```
There is no {{web.link}} macro left in content and translated-content. It's time to remove it.
---
Verified by using `rg`.
> chore(macros): delete {{web.link}} macro

- kumascript/macros/ServiceWorkerSidebar.ejs
The Service Worker API has its own dedicated sidebar, implemented using the [ServiceWorkerSidebar.ejs](https://github.com/mdn/yari/compare/main...wbamberg:deprecate-sw-sidebar?expand=1#diff-88d7716c52b0d8196b92ac5158533aac6fe2251c9002dcaa8fc9af277409062f) macro.
There's no special reason it needs to do this, and in https://github.com/mdn/content/pull/22469 I replaced it in en-US with the standard `{{DefaultAPISidebar}}` macro.
If we can do the same for translated content we can delete this sidebar.
> Deprecate Service Worker sidebar

- .github/workflows/auto-merge.yml
Fixes a nit in https://github.com/mdn/yari/pull/7662.
If a workflow step is not given an id, the following steps cannot reference its outputs via this id. Accordingly, the "squash and merge" step would _always_ be skipped ([example](https://github.com/mdn/yari/actions/runs/3543062427/jobs/5949177965)).
Specify an id.
---
n/a
---
> ci(auto-merge): specify name/id

- build/flaws/index.ts
- build/index.ts
- build/utils.ts
- client/tsconfig.json
- content/popularities.ts
- content/utils.ts
- filecheck/checker.ts
- kumascript/src/api/mdn.ts
- kumascript/src/api/page.ts
- kumascript/src/api/util.ts
- kumascript/src/api/web.ts
- kumascript/src/api/wiki.ts
- kumascript/src/environment.ts
- kumascript/src/errors.ts
- kumascript/src/render.ts
- kumascript/tests/render.test.ts
- markdown/m2h/cli.ts
- tool/cli.ts
- tool/sync-translated-content.ts
- tsconfig.json
ESLint is checking a bunch more on the TS files, but there are still some things that the compiler is suppressing. With just `strict` there were 800+ issues, but with the other 2 options it's down to 76
Either the remaining issues could be suppressed inline or addressed before landing this
---
---
> style(typescript): enable strict except noImplicitAny and strictNullChecks

- .github/workflows/glean-probe-scraper.yml
Follow-up of https://github.com/mdn/yari/pull/7652.
https://github.com/mdn/yari/pull/7652 added a "Glean probe-scraper" workflow, but it runs twice on PRs from non-fork mdn/yari branches: Once for the `push` event and once for the `pull_request` event.
Only run the workflow for pushes to the default branch (`main`) and for PRs.
_Note_: This is the same behavior as our "Testing" workflow:
https://github.com/mdn/yari/blob/d8b827cc72bd4f035787d41c228c28f26e2193d6/.github/workflows/testing.yml#L6-L10
---
n/a
---
The workflow only ran once for this PR, as intended.
> ci(glean-probe-scraper): run on PR + main pushes only

- .github/workflows/auto-merge.yml
Follow-up to https://github.com/mdn/yari/pull/7662 and https://github.com/mdn/yari/pull/7663.
The auto-merge workflow fails, because we don't `actions/checkout` the repository and so the `gh pr comment` call doesn't know the repository to post the PR comment in.
Use the fully-qualified PR url, as `gh pr comment` also accepts that.
---
n/a
---
Time will tell.
> ci(auto-merge): use pull_request.url for comment

- .github/workflows/auto-merge.yml
Follow-up to https://github.com/mdn/yari/pull/7670.
The `pull_request.url` contains the API url, so it cannot be used as a parameter of `gh pr comment`.
Use `pull_request.html_url` instead.
---
n/a
---
🤞
> ci(auto-merge): use html_url, not [api] url

- kumascript/macros/WebRTCSidebar.ejs
Current mission is to remove custom sidebars from the Web/API docs, so everyone can use the standard ones. This will make life easier if we ever want to do anything about sidebars in the future.
https://github.com/mdn/content/pull/22486 removed all references to the custom WebRTCSidebar, and this PR deprecates it.
There's more information about this sidebar at https://discourse.mozilla.org/t/defaultapisidebar-apiref-and-groupdata/40210/24.
> Deprecate WebRTCSidebar

- libs/env/index.js
As we start to accept audio/video/font files, we want to avoid that files are checked into content that are bigger than necessary.
Rationale: There is only one file attachment larger than this, but this is not an issue, as filecheck only checks modified files.
Currently, the `MAX_FILE_SIZE` is at 100 MB, which is too high.
Reduce it to the lowest reasonable value, i.e. 500 KB.
```console
% ufind files/ -type f -size +500k
files/en-us/_githistory.json
files/en-us/web/api/htmlimageelement/sizes/new-york-skyline-wide.jpg
files/en-us/web/api/web_animations_api/using_the_web_animations_api/growing-shrinking_article_optimized.gif
files/en-us/_redirects.txt
files/en-us/_wikihistory.json
```
---
n/a
---
n/a
> chore(env): reduce MAX_FILE_SIZE to 500 KiB

- deployer/src/deployer/analyze_pr.py
Changing the formatting of the PR companion comment to be more readable.
We don't need microsecond-resolution for the "comment last modified" value.
Use `.strftime("%Y-%m-%d %H:%M:%S")` to format `datetime` value to be second-level resolution.
```
Current date and time:
2022-11-29 09:59:37.118367
2022-11-29 09:59:37
```
> chore(pr-companion): minor formatting fix for PR comment timestamp resolution

- client/src/search.tsx
- testing/tests/headless.search.spec.ts
We cannot debug where people come from if using quick search, now we can.
We cannot debug where people come from if using quick search.
Add the input used as parameter.
---
> enhance(quicksearch): add a qs paramater

- client/src/document/index.scss
Resolves an issue with Safari, which computed a font-size of 13px for the `<pre>` block and 19.69px for the `<code>` block.
Fixes https://github.com/mdn/yari/issues/7695.
Safari calculated a wrong font-size for code blocks, causing them to appear much bigger than in Chrome/Firefox. The reason was that we applied a `font-size` to `pre/code/.code-example`, but the `font-family` only to `code`.
Apply the `font-family` to `pre/code/.code-example`, not just `code`.
---
(Safari)
---
Ran `yarn dev` and opened http://localhost:3000/en-US/docs/Web/API/PerformanceResourceTiming/nextHopProtocol#examples and https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/nextHopProtocol#examples in Safari to compare.
> fix(code): move font-family to pre/code/.code-example 

- client/src/ui/atoms/form/expanding-textarea.tsx
Fix text area growing when zoomed out.
When zooming out the textarea in the add collection item menu was growing while entering whitespaces.
Remove the 2px for borders in the update logic.
---
> fix(plus): textarea grow broken when zoomed out

- kumascript/src/api/util.ts
- kumascript/src/live-sample.ts
MathML is only supported by Firefox and Safari, so we load both a font and a polyfill for pages that use MathML _directly_. However, this does not apply to live samples.
For example, 
Inject font and polyfill into live samples that use MathML.
---
---
Opened this live sample in Chrome:
- https://developer.mozilla.org/en-US/docs/Learn/MathML/First_steps/Getting_started#the_display_attribute
- http://localhost:5042/en-US/docs/Learn/MathML/First_steps/Getting_started#the_display_attribute
> fix(live-sample): inject MathML font/polyfill

- .eslintrc.js
- deployer/aws-lambda/content-origin-request/build.js
- deployer/aws-lambda/content-origin-request/index.js
- deployer/aws-lambda/content-origin-request/package.json
- deployer/aws-lambda/content-origin-response/index.js
- deployer/aws-lambda/content-origin-response/package.json
- deployer/aws-lambda/mdn-stripe-price-ids/index.js
- deployer/aws-lambda/mdn-stripe-price-ids/package.json
- deployer/aws-lambda/mdn-stripe-price-ids/tests/handler.test.js
- deployer/aws-lambda/tests/package.json
- deployer/aws-lambda/tests/server.js
- deployer/aws-lambda/tests/server.test.js
- deployer/aws-lambda/tests/yarn.lock
Our lambdas are mostly independent from the rest of yari, which allows us to migrate them to ESM independently. Yet we haven't done so yet.
Migrates them to ESM.
_Note_: AWS Lambda supports ESM [since January 2022](https://aws.amazon.com/about-aws/whats-new/2022/01/aws-lambda-es-modules-top-level-await-node-js-14/), and we're currently using their Node.js 16.x runtime.
---
n/a
---
> refactor(aws-lambda): convert to ESM

- client/public/index.html
- libs/constants/index.js
- testing/tests/csp.test.ts
Removes the polyfill for [Array.flat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#browser_compatibility) (see [caniuse](https://caniuse.com/mdn-javascript_builtins_array_flat)) and ES6 (see [caniuse](https://caniuse.com/es6)), originally introduced in https://github.com/mdn/yari/pull/2387, as those features now have wide support.
We have this polyfill, but we don't need it anymore.
Remove the polyfill.
---
n/a
---
> chore(client): remove Array.flat/ES6 polyfill

- ssr/render.ts
Fixes the `<title>` on 404 pages like https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Obsolete_Pages/The_Employee_Example.
The `<title>` is `<title>🤷🏽‍♀️ Page not found | null</title>`, when it should be `<title>🤷🏽‍♀️ Page not found | MDN Web Docs</title>`.
Provide a fallback value for the section part of the title.
---
n/a
---
Ran `yarn dev` and opened http://localhost:5042/fr/docs/Web/JavaScript/Guide/Obsolete_Pages/The_Employee_Example locally and verified that the `<title>` no longer contains `null`.
> fix(ssr): avoid null in <title> on 404 pages

- client/src/document/index.scss
Fixes https://github.com/mdn/yari/issues/5875.
Our layout prevents us from fitting 80 characters into one line of a code block.
Reduce the font-size.
_Note_: Before https://github.com/mdn/yari/pull/7131, code blocks were already using a smaller default font in Chrome, 
---
---
Ran `yarn dev`, then opened http://localhost:3000/en-US/docs/Web/CSS/CSS_Counter_Styles/Using_CSS_counters#basic_example locally and compared it to https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Counter_Styles/Using_CSS_counters#basic_example.
> fix(client): reduce pre/code font-size

- kumascript/macros/cssxref.ejs
- kumascript/tests/index.test.ts
- kumascript/tests/macros/cssxref.test.ts
- testing/content/files/en-us/web/css/number/index.html
Replace the use of tags in cssxref with the page type.
cssxref used tags: [we would like to retire tags eventually](https://github.com/mdn/mdn/issues/262), and this one is an easy fix since we already have page types for CSS.
Use page type!
Ran yarn dev and added an edit like:
```
It's a {{cssxref("sign")}} of the {{cssxref("time")}}s.
It's a {{cssxref("sign()")}} of the {{cssxref("&lt;time&gt;")}}s.
```
....which gave me:
> chore(macros/cssxref): use page-type to detect CSS Functions/Data Types

- client/src/document/index.scss
Fixes #7735 
Links to pages that haven't been created yet lose their styles when the target page is `:visited`.
Persist the `a.page-not-created` styles for `:visited` links
---
https://user-images.githubusercontent.com/35560568/205434915-7313b360-49f6-470f-8976-e24caee2e593.mov
https://user-images.githubusercontent.com/35560568/205434904-878cf04e-812c-4377-8ac4-00dd008445df.mov
> fix(links): keep page-not-created styles on visited links

- build/document-utils.ts
The parents of Web/JavaScript/Reference/Classes/constructor are broken. The last element is missing the title. This is because we use an Object as a Map and looking up `contructor` breaks it.
We use an Object from random look ups.
Use a Map.
> fix(build): fix broken parents for constructor

- kumascript/macros/CanvasSidebar.ejs
Current mission is to remove custom sidebars from the Web/API docs, so everyone can use the standard ones. This will make life easier if we ever want to do anything about sidebars in the future.
https://github.com/mdn/content/pull/22586 removed all references to the custom CanvasSidebar from en-US, and this PR deprecates it.
There's more information about this sidebar at https://discourse.mozilla.org/t/defaultapisidebar-apiref-and-groupdata/40210/24.
> chore(macros): deprecate CanvasSidebar

- libs/constants/index.js
Follow-up of https://github.com/mdn/yari/pull/7689.
We removed the Polyfill and the CSP entry for the inline script, but not the CSP entry for the polyfill itself.
Also remove the CSP entry for the polyfill.
---
n/a
---
n/a
> fix(csp): remove polyfill.io from script-src

- build/cli.ts
- content/document.test.ts
- content/document.ts
- content/translations.ts
- markdown/m2h/cli.ts
- server/translations.ts
- tool/cli.ts
Splits up the `iter({ pathOnly})` method returned by `Document.findAll()` into two methods `iterPaths()` and `iterDocs()`.
`iter()` currently returns `string`s or `Doc`s depending on the value of `pathOnly`, which makes it unnecessarily hard for TypeScript to infer the return type.
Split it up into `iterPaths()` returning `string`s and `iterDocs()` returning `Doc`s.
---
n/a
---
-
> refactor(content): split Document.findAll().iter{Paths,Docs}()

- kumascript/macros/WebGLSidebar.ejs
This PR deprecates the last custom sidebar macro in Web/API 🎉 
https://github.com/mdn/content/pull/22782 removed all references to the custom WebGLSidebar macro from en-US, and this PR deprecates it.
There's more information about this sidebar at https://discourse.mozilla.org/t/defaultapisidebar-apiref-and-groupdata/40210/24.
> chore(macros): deprecate WebGLSidebar

- kumascript/macros/HTMLSidebar.ejs
Related to https://github.com/mdn/content/pull/22730
The two guide pages have been moved to `Web/HTML/` hierarchy. These pages are not part of the HTMLSidebar.
The PR adds them to the sidebar macro.
@wbamberg let me know if the pages are in right order in the sidebar list.
> chore(macros/HTMLSidebar): add "Content categories" / "Constraint validation"

- kumascript/macros/js_property_attributes.ejs
refactor(macros): use `mdn.localStringMap` instead of switch.
Add zh-CN and zh-TW translation.
n/a
> refactor(macros/js_property_attributes): use `mdn.localStringMap` instead of switch

- .github/workflows/pr-deployer.yml
When python version changed, the cache should not be used for the deployer. We just have the same problem in translated-content and content. See mdn/translated-content#6568 and mdn/translated-content#6804. But I forgot the check the usage in mdn/yari. We can see the same problem (as the listed workflow run):
- The old python version works well: https://github.com/mdn/yari/actions/runs/3645561868/jobs/6155813422#step:8:7
- The new python version would break this: https://github.com/mdn/yari/actions/runs/3645618869/jobs/6155917363#step:8:7
Specific the cache key with python version. We have fix this problem in translated-content/content:
- mdn/translated-content#6569
- mdn/translated-content#6805
---
N/A
N/A
> ci(pr-deployer): cache with specific python version

- client/public/index.html
Fixes #7767.
In https://github.com/mdn/yari/pull/7400, we changed our `.sidebar` from `nav` to `aside`, but we used the specific `nav.sidebar` selector to hide the sidebar when printing.
Update the print style to use the unspecific `.sidebar` selector.
---
|--------|------|
| <img width="469" alt="image" src="https://user-images.githubusercontent.com/495429/206499049-cf50dc4d-93e0-41e5-abf3-1c4dae1e4c44.png"> | <img width="469" alt="image" src="https://user-images.githubusercontent.com/495429/206498941-aff0aa0c-d952-4639-848e-9e0f85cd25e3.png"> |
---
Ran `yarn dev` and checked out the print preview for http://localhost:5042/en-US/docs/Web locally, comparing it to the print preview of https://developer.mozilla.org/en-US/docs/Web.
> fix(print): hide sidebar (+ banner)

- ssr/render.ts
Reverts mdn/yari#7166.
This caused more problems than it solved.
See for example: https://duckduckgo.com/?t=ffab&q=mdn+wheel+event&ia=web
When in fact, the title is `Element: wheel event` (HTML: `<title>Element&colon; wheel event - Web APIs | MDN</title>`). 🤷
> Revert "fix(ssr): escape colon in <title>"

- kumascript/macros/CSSInfo.ejs
Following on from https://github.com/mdn/content/pull/22829, this PR updates [CSSInfo.ejs](https://github.com/mdn/yari/blob/main/kumascript/macros/CSSInfo.ejs) to use page types instead of tags.
CSSInfo uses tags for a rather esoteric thing. In mdn/data, [strings can embed KumaScript xref macros](https://github.com/mdn/data/blob/ce9c8377b57428d26d0c99942761554a93064088/l10n/css.json#L419). Because, as CSSInfo says, [KS macros can't call other KS macros from within functions](https://github.com/mdn/yari/blob/b5de80980950cbe5dd857f92a2bdeb7b193c834d/kumascript/macros/CSSInfo.ejs#L29)*, [CSSInfo reimplements some version of these xref macros](https://github.com/mdn/yari/blob/b5de80980950cbe5dd857f92a2bdeb7b193c834d/kumascript/macros/CSSInfo.ejs#L36-L50).
In the course of this it uses tags to …
> fix(macros/CSSInfo): use page-type instead of tags

- .eslintignore
- .gitignore
- .prettierignore
This PR updates the ESLint, Prettier and Git ignore lists to perform the following:
1) Ignore built files in the SSR folder
2) Ignore formatting a generated file (`/client/public/service-worker.js`)
3) Don't ignore SSR's Webpack configuration file (accidentally ignored while attempting to ignore TypeScript build output)
> Update ignored files lists

- kumascript/tests/macros/Compat.test.ts
- kumascript/tests/macros/HTTPSidebar.test.ts
- kumascript/tests/macros/firefoxsidebar.test.ts
- kumascript/tests/macros/gamessidebar.test.ts
- kumascript/tests/macros/mdnsidebar.test.ts
This PR simplifies the imports and calls for the `jsdom` package, simply importing the `JSDOM` export rather than calling `jsdom.JSDOM` everywhere.
> Simplify imports/calls for JSDOM

- kumascript/macros/SubpagesWithSummaries.ejs
I'm trying to remove some of the places we use tags in KS macros, to enable us to remove tags from content (cc @hamishwillee ).
This PR removes the use of "Junk" and "Important" from the [SubpagesWithSummaries.ejs](https://github.com/mdn/yari/blob/main/kumascript/macros/SubpagesWithSummaries.ejs) macro.
That macro uses these tags to:
- exclude pages tagged "Junk"
- list pages tagged "Important" first
This never really caught on. We have zero pages tagged "Important" in mdn/content, and only two pages tagged "Junk":
https://developer.mozilla.org/en-US/docs/web/css/tutorials 
https://developer.mozilla.org/en-US/docs/Learn/Forms/Property_compatibility_table_for_form_controls 
I don't think either of these pages are currently in scope for this macro, and we should not have a "Junk" tag - if a …
> fix(macros/SubpagesWithSummaries): remove junk and important tag handling

- jest.config.json
- package.json
This PR takes the Jest configuration out of `package.json` and moves it to its own file.  This will help reduce merge conflicts and keep all configuration for packages out of `package.json`.
> Move Jest configuration to separate file

- client/src/document/on-github.tsx
Minor change to point to our CONTRIBUTING.md instead of the README. 
Opening as draft pending team feedback.
> chore(footer): Point to CONTRIBUTING.md instead of README in footer

- deployer/aws-lambda/content-origin-request/index.js
- deployer/src/deployer/constants.py
We'll serve data for bcd from a new static API.
1. The deployer removes bcd data on each deployment as it lives next to the content.
2. The lambda transforms the uri into lower case and this breaks the bcd queries (there exists `api.crypto` and `api.Crypto`.
1. Add an exception to the deployer.
2. Don't lowercase uris starting with `/bcd/`
---
Manual deployment to stage: https://github.com/mdn/yari/actions/runs/3686702028
> chore(deployer): ignore /bcd when deploying and add /bcd to lambda

- filecheck/checker.ts
Relates to https://github.com/mdn/content/pull/22914#issuecomment-1347697650.
Windows paths never include `/files/`, just `\files\`, so the filecheck was just ignoring all files on Windows.
Change the check to split the paths using `path.sep` instead of a RegExp with a OS-specific path separator.
---
n/a
---
Tested on a Windows machine.
> fix(filecheck): check path using path.sep

- kumascript/macros/WebAssemblySidebar.ejs
- kumascript/tests/macros/WebAssemblySidebar.test.ts
Remove caching modules.
Fixes #7807.
It’s been removed.
Remove it from yari.
---
---
> fix(macros/WebAssemblySidebar): remove link to deleted page

- content/translation.ts
- kumascript/index.ts
- kumascript/macros/IncludeSubnav.ejs
The `{{IncludeSubnav}}` macro has been [removed from translated-content](https://github.com/mdn/translated-content/pull/10577). So it's time to remove it from yari. See: https://github.com/mdn/translated-content/search?q=IncludeSubnav
> chore(macros): delete {{IncludeSubnav}} macro

- client/src/document/on-github.tsx
This issue is originally reported by @iwanderer in [translated-content](https://github.com/mdn/translated-content/issues/10633#issuecomment-1350635809). And I found that the issue template file's name is in lowercase. We should match with that. For we used to use `lowercase` in other folder <https://github.com/mdn/translated-content/tree/main/docs>, <https://github.com/mdn/translated-content/tree/main/files>.
match issue template whose filename is in lowercase
Affect: `pt-BR`, `zh-CN`, `zh-TW`.
> fix(on-github): match issue template whose filename is in lowercase

- kumascript/src/info.ts
Fixes #7799.
We're deprecating tags, e.g. by using the `status` instead, but ~~there is no equivalent helper `page.hasStatus()` like `page.hasTag()`~~ it is not yet available on the `page` object.
Add the `status` to the `page` object.
---
n/a
---
~~Added `status: ['deprecated']` to `content/files/en-us/web/api/merchantvalidationevent/index.md`, updated `APIRef.ejs` to use `hasStatus` instead of `hasTag`, then ran `yarn dev` and opened http://localhost:3000/en-US/docs/Web/API/MerchantValidationEvent locally.~~
> feat(kumascript): expose status on page object

- client/config/webpackDevServer.config.js
Fixes the following warnings when running `yarn dev` (or `yarn start`):
```
12:27:29 PM web.1       |  (node:5123) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
12:27:29 PM web.1       |  (Use `node --trace-deprecation ...` to show where the warning was created)
12:27:29 PM web.1       |  (node:5123) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
```
The webpack devserver config options `onBeforeSetupMiddleware` and `onAfterSetupMiddleware` have been deprecated in favor of `setupMiddleware`, but we're still using the deprecated options in our client/config (which …
> fix(client/config): migrate to setupMiddlewares option

- kumascript/macros/JSRef.ejs
Use page types instead of tags in JSRef.
The [JSRef.ejs](https://github.com/mdn/yari/blob/main/kumascript/macros/JSRef.ejs) macro builds the sidebar that appears on "JS object" pages, like the page for [`Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) and its children.
It uses tags to divide up members into properties and methods, and also to exclude non-prototype properties of objects that the current object inherits from (for example, although `Array` inherits from `Object`, it does not inherit [`freeze()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) from it.
Now we have [page types for JS](https://github.com/mdn/content/issues/16156), we can replace this usage of tags with page types, and that's what this PR does. …
> fix(macros/JSRef): use page type instead of tags

- kumascript/macros/LearnSidebar.ejs
@schalkneethling @caugner 
cc @hmatrjp @potappo 
- [Client-side tooling overview の翻訳 #651 ](https://github.com/mozilla-japan/translation/issues/651)  のPRです。
- [ feat(translate): Client-side tooling overview の翻訳 #9442 ](https://github.com/mdn/translated-content/pull/9442)
still en-us only
tranlate japanese for LearnSidebar.ejs
still en-us only
add tranlate japanese for LearnSidebar.ejs
> chore(macros/LearnSidebar): translate Client-side_tooling_overview in Japanese

- client/src/ui/molecules/plus-menu/index.tsx
Part of [MP-186](https://mozilla-hub.atlassian.net/browse/MP-186).
We added a new feature in https://github.com/mdn/yari/pull/7814, but it's not yet linked anywhere.
Add it to the "MDN Plus" menu.
---
| --- | --- |
| <img width="1437" alt="image" src="https://user-images.githubusercontent.com/495429/208420235-379ce45e-2e7e-4c5a-b891-b0da0a4f46ee.png"> | <img width="1437" alt="image" src="https://user-images.githubusercontent.com/495429/208420362-43c9931f-55ff-4555-9851-cfcca88a4dea.png"> |
| --- | --- |
| <img width="1437" alt="image" src="https://user-images.githubusercontent.com/495429/208420144-b0baa16c-3582-4254-872b-c82c60106817.png"> | <img width="1437" alt="image" src="https://user-images.githubusercontent.com/495429/208419981-1c0b207d-5ee4-415e …
> chore(plus-menu): add Updates link

- client/src/plus/updates/index.tsx
- client/src/telemetry/constants.ts
- client/src/ui/molecules/paginator/index.tsx
Resolves [MP-205](https://mozilla-hub.atlassian.net/browse/MP-205).
We landed a new feature (https://github.com/mdn/yari/pull/7814), but we don't have metrics yet to understand how it's being used.
Add three metrics:
1. Click event when a feature support event is expanded.
2. Click event when a feature support event is collapsed.
3. Click event when ~~a specific page (0, 1, 2, …) is opened~~ switching from one page (e.g. 0) to another (e.g. 1).
---
n/a
---
Added `REACT_APP_GLEAN_DEBUG=true`, reran `yarn dev` and verified that the events show up in the console.
> chore(plus/updates): add metrics for expand/collapse/pagination

- client/src/plus/updates/api.ts
Fixes an issue where the Updates page is blank for new unauthenticated users whose `whoami` request doesn't return quick enough.
`useUserData()` can return `null`, but TypeScript doesn't want to accept that, which prompted me to use its return value as if it's never null.
Check that `user` is not null before using its properties.
---
n/a
---
> fix(plus/updates): check that user != null

- client/src/plus/updates/index.tsx
Currently, we show the Updates loosely ordered by category, but not at all by path:
Order the Updates by path, which implies ordering them by category (which is the first path element).
---
---
Opened http://localhost:3000/en-US/plus/updates locally.
> fix(plus/updates): sort update events by path

- client/src/constants.ts
- client/src/hooks.ts
- client/src/plus/updates/index.tsx
- client/src/ui/molecules/menu/index.scss
- client/src/ui/molecules/menu/index.tsx
- client/src/ui/molecules/plus-menu/index.tsx
- client/src/ui/molecules/submenu/index.tsx
Currently, we highlighted the new Updates feature only **inside** the MDN Plus menu (using a "New" badge), but this is barely noticeable for users intentionally opening that menu.
Use the existing "dot" feature (used in the MDN Plus user menu for Notifications) and add a top-level "dot" if any submenu entry has a "dot". Also, use localStorage to remember whether the user has visited the Updates page and hide the "dot" then.
---
---
To test, visit any other page first, and run `localStorage.removeItem('viewed.plus_updates_v2')` in the browser console (if necessary) to bring back the dot.
> feat(plus/updates): use dots in plus-menu to highlight feature until viewed

- client/src/hooks.ts
The "unviewed feature" dot pops up quickly on each load, even after the feature was viewed, because we assumed `isViewed = true` on SSR.
Inverse it, so that `isViewed = false` on SSR.
---
n/a
---
> fix(useViewedState): assume isViewed on SSR

- client/src/search.tsx
- client/src/ui/molecules/search/index.scss
The search loading/error messages are not properly styled, and the messages themselves are rather technical.
Use the same style as result items (and "Not seeing what you're search for" item), and rephrase the messages.
---
---
- Edited `if (searchIndexError)` and `if (!searchIndex)` in `search.tsx` to be temporarily `if (true)` to enforce showing the corresponding message.
- Ran `yarn dev`, then opened http://localhost:3000/en-US/docs/Web/HTML locally and typed in "test" into the quicksearch.
> fix(search) improve loading/error message

- package.json
- server/index.ts
- yarn.lock
change from default to named export ensures cross-compatibility with esm
ref https://github.com/mdn/bcd-utils/pull/5
blocks https://github.com/mdn/yari/pull/7623
> fix(server): update bcd-utils-api to 0.0.3

- client/src/document/on-github.tsx
- client/src/document/organisms/metadata/index.tsx
A. Fixes part of https://github.com/mdn/yari/issues/7656
1.
`Edit on GitHub` is now `Edit it on GitHub`
`Source on GitHub` is now `View the source on GitHub`
2. a)
`Last modified: Sep 25, 2022,` [by MDN contributors](https://developer.mozilla.org/en-US/docs/Web/CSS/contributors.txt)
is now
`Last modified: Sep 25, 2022, by` [MDN contributors](https://developer.mozilla.org/en-US/docs/Web/CSS/contributors.txt)
B. Makes minor changes to "Learn..."
The link is now on the whole phrase and the exclamation is removed
==> With the above changes, the only thing remaining in https://github.com/mdn/yari/issues/7656 to be fixed will be `2. b)`
> fix(on-github): improve copy language

- client/pwa/src/fetch-interceptors.ts
any 5xx error code seemed unsuitable, as it's not originating from the
server, whereas 418 is a nice easter egg, and should allow us to easily
catch these errors in future if we want to handle them specially
When truly offline, the serviceworker replaces api responses with `{ "error": "offline" }`, but was "responding" with a 200 ok. This makes our type checking break down, hence the error: `T.map is not a function`.
Add an error code in the "response".
---
Deployed to stage, on the next branch: https://github.com/mdn/yari/commit/bf4b40aee8290b23838ffeaed95c7bfc545aba56
> fix(offline): when actually offline article pages error out

- .github/workflows/testing.yml
- .lintstagedrc.json
- build/cli.ts
- build/spas.ts
- client/pwa/tsconfig.json
- lint-staged.config.js
- package.json
- scripts/lint.sh
- server/index.ts
- testing/tests/developing.spec.ts
- testing/tests/headless.sitesearch.spec.ts
- fix errors found
- add to github actions
It wasn't possible to easily run typescript across the entire project with all the separate tsconfigs we have.
Add command to run `tsc --noEmit` in every directory with a tsconfig.json, excluding the root directory (it only acts as a partial config for the others to expand on) and node_modules.
---
`yarn check:tsc`
> chore: add yarn check:tsc command to check all files

- client/src/search.tsx
Allows to find the `Map.prototype.get()` page by searching for "map.get".
Fixes https://github.com/mdn/yari/issues/7859.
Currently, we split the quicksearch query at space only, which means "map.get" is treated as a single word, and therefore won't find the `Map.prototype.get()` page.
Preprocess the query so that "map.get" is treated like "map .get", resulting in two words "map" and ".get".
---
---
Typed "map.get" into the quicksearch on any page at http://localhost:3000/.
> fix(quicksearch): split query before dot

- kumascript/macros/gecko.ejs
This PR marks the `{{gecko}}` macro as deprecated.  This macro is not used in any English content, and there are only 103 instances in translated content left.
> Deprecate {{gecko}} macro

- kumascript/macros/ARIARole.ejs
@estelle removed the last occurrences in mdn/content. We can mark it as deprecated.
> Deprecate ARIARole macro

- kumascript/macros/MDNSidebar.ejs
- Completes https://github.com/mdn/content/pull/23789
The PR adds the new page https://developer.mozilla.org/en-US/docs/MDN/Community/Communication_channels to the sidebar.
> chore(macros): Update {{MDNSidebar}}

- deployer/aws-lambda/content-origin-request/index.js
https://github.com/mdn/yari/issues/8056
Dev builds (which run on content/translated-content PRs to preview the changes) have no bcd tables.
This makes the lambda route to a single set of bcd files, so we don't have to upload them for every differently-named dev build (of which most of them are).
I still need to author the PR on the bcd-utils side to add an action for dev build.
---
I haven't :yolo:
> fix(lambda): use single set of bcd api jsons across all dev builds

- client/src/hooks.ts
wrap whole block in try/catch for extra safety
https://github.com/mdn/yari/issues/7969
`navigator.sendBeacon` can be undefined - babel doesn't handle this, apparently
conditionally call `navigator.sendBeacon`, also wrap the entire hook in a try/catch for extra safety
---
Disabled `beacon.enabled` in `about:config`, observed the error, made the changes, observed no error.
Note: you need to be logged in, and `next-ping` in localstorage needs to be cleared before each page reload when testing, otherwise the problematic code won't be executed.
> fix(client/hooks): sendBeacon can be undefined

- content/document.ts
Fixes #7986.
yari errors when run under file hierarchies containing space characters.
Check for spaces only in the portion of the path corresponding to the actual content folder, not its parent directories.
---
Manual testing, by running `yarn dev` in such file hierarchies before and after the change, and with and without content folders containing spaces.
> fix(content): allow whitespace above content folder

- README.md
Fixes #7944
The "Production Build" badge in README is broken, which is caused by a workflow renaming from "Production Build" to "Prod Build" in commit 09568d0.
Replace "Production Build" with "Prod Build".
PS 1: Should I use workflow file name (e.g., `prod-build.yml`) instead of workflow name (e.g., `Prod Build`) in badge svg urls? Because only workflow file name is documented in corresponding [GitHub Docs page](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-workflow-file-name).
PS 2: Though out of the scope of current PR, do badges of other two builds ("Dev Build" and "Stage Build") need to added to README?
---
Visit my fork https://github.com/muzimuzhi/yari/tree/readme-badge#yari
---
Visit …
> docs(README): fix broken "Production Build" badge

- package.json
Avoids `nproc`, which might not be available.
Avoids `nproc`, which might not be available in the developer environment.
Supersedes https://github.com/mdn/yari/pull/8088.
https://github.com/mdn/yari/pull/8083 added parallelization for check:tsc, but it uses nproc, which isn't always available (as reported by @NiedziolkaMichal).
Just run with 2 processes, which doesn't seem to be slower than 4 or even 8 processes.
---
n/a
---
- Ran `yarn check:tsc` with different hard-coded process counts.
> fix(lint): run check:tsc with 2 processes

- build/syntax-highlight.ts
This PR adds `django` as an available syntax highlighting language in response to https://github.com/mdn/content/pull/24048#discussion_r1093126283.
> Add django to list of Prism.js languages

- build/extract-specifications.ts
- package.json
- yarn.lock
Replace the "browser-specs" package with "web-specs". 
browser-specs doesn't contain all specs that we are interested in. web-specs does.
"web-specs is a small super-set of browser-specs and it should be a drop-in replacement for MDN"
See https://github.com/w3c/browser-specs/pull/817#issuecomment-1377207689 for more details.
commands used:
yarn add web-specs
yarn remove browser-specs
There should be no difference other than that a few more specification tables will render. For example, Do Not Track is not in browser-specs as of 3.38 anymore so the spec table on https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack will soon stop working. With web-specs the table will continue to render fine.
BCD will make this change in https://github.com/mdn/browser-compat-data/pull/18615
> chore(deps): replace browser-specs with web-specs

- .github/workflows/pr-commit-signatures.yml
The commit-signatures workflow sometimes fails for unknown reasons, and we don't know why.
Pipe some intermediate results to `tee` so that we can see what we get from the GitHub API and what our filtered result looks like.
---
n/a
---
I will look at the run in this PR.
> chore(workflows/pr-commit-signatures): use GitHub CLI + tee

- client/src/search.tsx
Fixes https://github.com/mdn/yari/issues/7047.
Currently, some pages (e.g. [Element]() and [with](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with)) cannot be found via quicksearch, some pages cannot be found directly (e.g. [a](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a), [p](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p) or [head](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head)), and pages like [Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object) or [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) don't appear at the top when searching specifically for them.
Boost exact matches, where the query is identical to the title or the "slug tail" (last …
> feat(quicksearch): boost exact matches

- build/syntax-highlight.ts
This PR adds Handlebars as a language for syntax highlighting.  We have a few instances of Handlebars in our documents already.
> Add Handlebars to syntax highlighting

- lint-staged.config.js
Removes `check:tsc` from the lint-staged configuration, so it's no longer run as a pre-commit hook.
On every commit, `yarn check:tsc` is run, but this takes more than a few seconds to run (e.g. 30s on a MacBook Pro from 2019).
No longer run it as a pre-commit hook.
---
Committing this change only took 3s instead of 30s+:
```
% git commit -m "chore(lint-staged): don't run check:tsc                                                                            ✚
dquote> 
dquote> It takes 30s to run on some systems,
dquote> which disrupts dev workflows."
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.54s.
yarn run v1.22.19
$ /Users/claas/github/mdn/yari/node_modules/.bin/lint-staged
✔ Preparing lint-staged...
✔ …
```
> chore(lint-staged): don't run check:tsc

- client/src/plus/collections/index.tsx
- client/src/plus/icon-card/index.tsx
- client/src/plus/search-filter/index.tsx
- client/src/ui/atoms/button/index.tsx
- client/src/ui/molecules/theme-switcher/index.tsx
- client/src/ui/molecules/user-menu/index.tsx
- client/src/ui/organisms/article-actions-container/index.tsx
- client/src/ui/organisms/article-actions/language-menu/index.tsx
- client/src/ui/organisms/top-navigation/index.tsx
- fix: pass through aira- props on Button component
- fix: improve aria labels on mobile sidebar button
fixes https://github.com/mdn/yari/issues/8015
- Sidebar button had on aria label on it.
- It was set in the code, but as `aria-label` rather than `ariaLabel` which is the prop the `Button` component was expecting
- TypeScript doesn't type check any prop with a dash in it (e.g. `aria-label` but also `foo-bar`), including not checking if a component with typed props hasn't specified it as a prop it takes, so this bug was silently introduced
- https://github.com/microsoft/TypeScript/issues/32447
- Remove our camelCase aria props on `Button`, and pass through all dashed props to underlying elements in `Button` component
- This seemed safest as there's no way of preventing a developer adding …
> fix(Button): pass through ARIA attrs

- kumascript/macros/MDNSidebar.ejs
fix(macros/MDNSidebar): remove repeated `<details>` tag
See screenshot
---
---
run `yarn dev`
> fix(macros/MDNSidebar): remove repeated `<details>` tag

- client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
- client/src/document/ingredients/browser-compatibility-table/index.scss
This PR adds `(Release YEAR-MONTH-DAY)` text in the Browser Compatibility Data timeline, instead of placing it in the title.
Fixes #6812
Fixes #7603 
Additionally, I have removed `See implementation notes` icon from the timeline. It took up space and it didn't really make sense to keep it there, considering that the user has already clicked to see those notes.
---
I checked [yield](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield) and [mask-image](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image)
> enhance(bcd): add release date label to timeline

- server/translations.ts
Resolves [this "critical" alert](https://github.com/mdn/yari/security/code-scanning/56) detected by CodeQL.
HTTP request parameters may be either an array or a string.
Convert the parameters in question to string.
---
Verified the types as inferred by TypeScript.
> fix(server): avoid type confusion

- docs/envvars.md
- kumascript/src/templates.ts
Removes an unused feature: The `BUILD_MACROS_USED_LOGFILE` env variable could be set to log used features, but we can now determine used features statically since https://github.com/mdn/yari/pull/7087.
---
Trivial change, relying on tests otherwise.
> chore(kumascript): remove BUILD_MACROS_USED_LOGFILE feature

- client/src/document/organisms/sidebar/index.scss
- client/src/document/organisms/sidebar/index.tsx
Removes the "Related Topics" header, as agreed upon at the Mozilla/OWD meetup.
The header takes up unnecessary space.
Remove it, and make sure that the [section] "headers" line up with the page title (in the middle) and "In this article" header (on the right).
---
| --- | --- |
| <img width="698" alt="image" src="https://user-images.githubusercontent.com/495429/216618880-02c07565-6d93-4899-a3bc-4ea735739ec6.png"> | <img width="698" alt="image" src="https://user-images.githubusercontent.com/495429/216618942-5a86648b-49c5-4071-b1fb-8a14cac2dabb.png"> |
---
Ran `yarn start` and opened http://localhost:3000/en-US/docs/Web/HTML locally.
> chore(sidebar): remove "Related Topics" header

- client/src/plus/search-filter/index.tsx
- client/src/ui/atoms/search/index.scss
- client/src/ui/atoms/search/index.tsx
- client/src/ui/molecules/search/index.scss
Adds a clear button to the search field on the Updates page.
The search field on the Updates page is not consistent with the top-level search field in that it lacks a clear button.
Adds the clear button, which is only shown if the search field has a value and is **not** focused.
The focus restriction avoids problems due to the input's blur event (which applies the current value) firing before the clear button's click event (which clears the value). Otherwise the current value would shortly pop up, which would be poor UX.
---
---
Ran `yarn dev` and opened http://localhost:3000/en-US/plus/updates locally, testing with different combinations of applied value vs current value.
> feat(plus/search-filter): add clear button

- client/src/plus/offer-overview/offer-overview-feature/index.tsx
- client/src/ui/molecules/menu/index.tsx
fixes: https://github.com/mdn/yari/issues/8106
fixes: https://github.com/mdn/yari/issues/8107
The above problems are related, but have different underlying causes.
The first ("Learn more" opens an empty page) is a result of doing client side navigation from homepage -> plus overview -> plus docs. The `hyData` value remains the same throughout, so when loading the plus docs is still that of the homepage's, and predictably causes the component to error out.
The second ("Learn more" opens the wrong plus docs) is a result of doing client side navigation from plus docs -> plus overview -> plus docs. Again, the `hyData` value remains the same throughout, but is at least structurally consistent, so the second load of plus docs just has outdated data, rather than erroring out.
I have been …
> fix(plus): clicking "learn more" links caused stale or broken pages

- kumascript/macros/APIRef.ejs
- kumascript/macros/CSS_Ref.ejs
- kumascript/macros/Deprecated_Inline.ejs
- kumascript/macros/HTMLRefTable.ejs
- kumascript/macros/JSRef.ejs
- kumascript/macros/WebExtAPISidebar.ejs
- kumascript/macros/spec2.ejs
- kumascript/src/lib/badges.ts
- kumascript/tests/macros/apiref.test.ts
- kumascript/tests/macros/fixtures/apiref/subpages.json
Removes usages of the deprecated "Obsolete" tag, which is no longer used in content.
Replaces https://github.com/mdn/yari/pull/7827.
**Note**: This does not remove the "Obsolete" macros, which are still used in translated-content.
---
Relying on the kumascript tests.
> chore(macros): remove usage of the obsolete tag

- build/syntax-highlight.ts
This PR updates the syntax highlighting so that any language we have loaded may be appended with the `-nolint` suffix, instead of having to manually add them in for each language.
> chore(syntax-highlight): accept `-nolint` suffix for all syntax languages

- package.json
- yarn.lock
`rehype-remark` is no longer used since #6849.
Remove it.
---
Not tested, relying on the checks and the fact that `rehype-remark` is not referenced anywhere.
> chore(deps): remove rehype-remark

- kumascript/macros/ListGroups.ejs
- kumascript/src/lib/badges.ts
- kumascript/tests/macros/ListGroups.test.ts
Fixes: mdn/translated-content#11499
Some pages are not localized, so the `page.badges` function may throw an error when get an "empty object" page (the `aPage` object may be an empty object `{}`).
Only get badge info from en-US, as the metadata of localized pages are also from `en-US` by default, see mdn/translated-content#7412.
---
---
Run `yari dev` and open `http://localhost:5042/zh-CN/docs/Web/API`
> fix(kumascript/ListGroups): get page's metadata from default locale only

- .github/workflows/npm-published-simulation.yml
Upstream: https://github.com/yarnpkg/yarn/issues/6811
Locally: https://github.com/mdn/yari/pull/5524#issuecomment-1422872041
Installing from a tarball seems to cause some stale dependencies to hang around, see: https://github.com/mdn/yari/actions/runs/4127042686/jobs/7129752267#step:8:990
```
../content/node_modules/@mdn/yari/node_modules/unified/package.json
{
"name": "unified",
"version": "9.2.1",
```
This was in a PR to upgrade unified to v10.
Followed advice from upstream issue:
- Clean yarn cache - this doesn't seem to work by itself, but it *should*
- Run yarn install
See success here: https://github.com/mdn/yari/actions/runs/4127532853/jobs/7130855135
---
Lots of `dnm: debug` commits in this PR to trigger github actions with various configs: https://github.com/mdn/yari/pull/5524
> fix(npm-published-simulation): stale dependencies when installing tar

- libs/env/index.js
When trying to run `yarn start` in content and view some local hosted pages. The server throw an error: `Error: ENOENT: no such file or directory, stat '/path/to/content/client/build/en-us/_spas/404.html'`.
I found that the `ROOT` variable is not setted correctly (just got by `cwd()`). We still need a relative path to yari, as lib file would be in `node_modules`.
See summary.
Use [`import.meta.url`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta) to get the current filepath. And remove the leading slash when run on windows.
---
Only try to run the following script on linux and windows.
```mjs
import { fileURLToPath } from "node:url";
import path from "node:path";
console.log(import.meta.url);
const currentDir = …
```
> fix(libs/env): get correct `ROOT` by relative path

- package.json
- yarn.lock
`rehype-minify-whitespace` is no longer used since https://github.com/mdn/yari/pull/6849.
See also: https://github.com/mdn/yari/pull/8173
Remove it.
---
Not tested, relying on the checks and the fact that `rehype-minify-whitespace` is not referenced anywhere.
> chore(deps): remove rehype-minify-whitespace

- package.json
We [noticed an error](https://github.com/mdn/yari/pull/8188#issuecomment-1425912863) when upgrading to Node.js v18 due to `ts-node` being called on a directory.
Call `ts-node` with the containing `index.ts` instead.
---
---
Ran `yarn start:server` locally.
> fix(server): point start:server to index.ts

- kumascript/macros/JSRef.ejs
Fixes: #8191
As a split part of #8134
see issue.
Add missing `await` keyword, as the following async function calls.
> fix(macros/JSRef): add missing `await` keyword for async function call

- kumascript/macros/GamesSidebar.ejs
We deleted the _Examples_ pages a long time ago, as:
- it was outdated
- it was unmaintainable
- it was attracting spam.
This PR only removes the link in the Games sidebar. This was reported in mdn/content#24342.
> Remove deleted page from GamesSidebar

- kumascript/macros/gecko.ejs
This macro has been [removed from translated-content](https://github.com/mdn/translated-content/issues/11284). Let's remove it from yari.
```bash
rg -i "\{\{\s*gecko\s*\(" | wc -l # got 0
```
> chore(macros): remove {{gecko}} macro

- client/src/settings/offline-settings.tsx
When navigating away from the "Settings" page, a confirmation dialog would always appear, because the "Offline settings" would think that the worker is running and busy, even if disabled.
Treat the "initial" phase like idle.
This is the default phase, even if the worker is not running, and this was interpreted as "busy", causing a dialog whenever closing the "Settings" page.
(Note: Originally, the Offline settings were on a separate page.)
---
---
Opened http://localhost:3000/en-US/plus/settings locally and navigated away.
> fix(offline-settings): treat initial phase like idle

- kumascript/macros/CSSRef.ejs
- kumascript/macros/LearnSidebar.ejs
Fixes https://github.com/mdn/content/issues/23645
Relates to https://github.com/mdn/content/pull/23814
Currently the sidebar in https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks is missing some links, for example, this one https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors 
Also the order of the links is wrong with respect to the content (see https://github.com/mdn/content/issues/22005 )
This PR adds missing links and fixes their order.
---
---
> chore(macros): add missing CSS selectors pages to sidebars

- .npmignore
- libs/env/index.d.ts
- libs/env/index.js
- ssr/index.ts
Fixes https://github.com/mdn/yari/issues/8201.
On Windows, `yarn start` was failing with `File URL path must be absolute` when run inside the mdn/content repository, and previously it was accessing the local server showed `no such file or directory, stat '/path/to/content/client/build/en-us/_spas/404.html'` (which was partly fixed in https://github.com/mdn/yari/pull/8177).
Properly determine the `dotenv` path in `libs/env` and `ssr/`:
- In `libs/env`, load the `dotenv` file from the current working directory (cwd).
- In `ssr`, load the `dotenv` file from the parent directory.
**Note**: What makes this a bit tricky is the fact that the `.env` file is _usually_ in the yari root, **unless** we are in the content repo. And it's _usually_ in the cwd, **unless** we build the `client`, the …
> fix(lib/env,ssr): determine env path properly 

- .github/workflows/dev-build.yml
- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
GitHub actions run on different CPUs, and the duration depends on these, which makes it hard to compare build times.
Print `/proc/cpuinfo` in builds so that we can better compare build times.
---
---
> ci(builds): print cpuinfo

- kumascript/macros/HTMLRefTable.ejs
In mdn/content#24515, we are removing the only page in en-US using `HTMLRefTable`.
This macro is blocking us from removing the `Tags:` YAML header.
This PR marks the macro as deprecated, and we can remove it in translations before deleting it.
> chore(macros): deprecate HTMLRefTable

- kumascript/src/lib/badges.ts
Fixes: #8237.
We used to load badge template for only once. The loaded template are not differ by locale.
Let the badge template be a map, we could load different template by locale.
---
see http://localhost:5042/en-US/docs/Web/CSS/abs
en-us
fr
---
run `yarn dev`
> fix(kumascript): load badge templates by locale

- tool/macro-usage-report.ts
Adds a missing `/` in the output of the `macro-usage-report`.
`YARI_PATH` has a trailing slash, but `CONTENT*_ROOT` does not.
When replacing `YARI_PATH`, add a trailing slash.
---
```
% yarn tool macro-usage-report --format json | grep yari
(node:37633) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
"yarikumascript/macros/unimplementedGeneric.ejs"
"yarikumascript/macros/WebExtAllCompatTables.ejs"
...
"yarikumascript/macros/EmbedLiveSample.ejs",
"yarikumascript/macros/LiveSampleLink.ejs"
"translated-content/ko/orphaned/mdn/yari/index.md",
"translated-content/pt-br/orphaned/mdn/yari/index.md",
"translated-content/ru/orphaned/mdn/yari/index.md",
```
```
% …
```
> fix(tool/macro-usage-report): add trailing slash for yari

- client/src/telemetry/constants.ts
- client/src/ui/molecules/breadcrumbs/index.tsx
We don't know how our breadcrumbs are used.
Add a metric `breadcrumb_click: i/n` that measures a click on the `i`th breadcrumb of `n` (counting from the right, i.e. 1 = current page's breadcrumb).
Examples:
- `breadcrumb_click: 1/4` is a click on the current page's crumb, out of 4 crumbs.
- `breadcrumb_click: 2/3` is a click on the parent page's crumb, out of 3 crumbs.
- `breadcrumb_click: 2/2` is a click on the "top level" crumb, out of 2 crumbs.
---
> chore(breadcrumbs): count clicks

- kumascript/macros/CSSRef.ejs
The Browser_compatibility_and_scroll_snap page is now a redirect to the main article, after a fusion. It shouldn't be listed in the sidebar anymore.
This created build errors:
`In CSSRef the smartLink to /en-US/docs/Web/CSS/CSS_Scroll_Snap/Browser_compat is broken (redirects to /en-US/docs/Web/CSS/CSS_Scroll_Snap)`
and broken user experience as two consecutive entries link to the same page.
cc/ @wbamberg  for the content review
> Remove Browser_compatibility_and_scroll_snap page from CSSRef

- kumascript/macros/LearnSidebar.ejs
@schalkneethling @caugner 
cc @hmatrjp @potappo 
- [ Command line crash course の翻訳 #679 ](https://github.com/mozilla-japan/translation/issues/679)  のPRです。
- [ feat(translate): Command line crash course の翻訳 #11745 ](https://github.com/mdn/translated-content/pull/11745)
still en-us only
tranlate japanese for LearnSidebar.ejs
please https://github.com/mdn/translated-content/pull/11745 will be merged after review and approve, this PR merge.
still en-us only
add tranlate japanese for LearnSidebar.ejs
> chore(macros/LearnSidebar): translate command_line in Japanese

- build/cli.ts
- build/extract-sidebar.ts
- client/src/document/organisms/sidebar/index.tsx
- client/src/telemetry/constants.ts
- client/src/telemetry/glean-context.tsx
- client/src/telemetry/sidebar-click.ts
- kumascript/macros/APIRef.ejs
- kumascript/macros/AddonSidebar.ejs
- kumascript/macros/AddonSidebarMain.ejs
- kumascript/macros/CSSRef.ejs
- kumascript/macros/DefaultAPISidebar.ejs
- kumascript/macros/FirefoxSidebar.ejs
- kumascript/macros/GamesSidebar.ejs
- kumascript/macros/HTMLSidebar.ejs
- kumascript/macros/HTTPSidebar.ejs
- kumascript/macros/JsSidebar.ejs
- kumascript/macros/LearnSidebar.ejs
- kumascript/macros/MDNSidebar.ejs
- kumascript/macros/MathMLRef.ejs
- kumascript/macros/QuickLinksWithSubpages.ejs
- kumascript/macros/WebAssemblySidebar.ejs
- kumascript/tests/macros/WebAssemblySidebar.test.ts
- libs/types/document.ts
This is a simpler version of https://github.com/mdn/yari/pull/8273 that doesn't require a data review.
We don't know how often users click on links on the sidebars, but knowing this allows us to observe the impact of upcoming improvements to the sidebar.
Record clicks on links in the sidebar as `sidebar_click: <MACRO> <HREF>`.
Examples:
- `sidebar_click: LearnSidebar /en-US/docs/Learn/CSS/First_steps`
- `sidebar_click: JsSidebar /en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer`
---
Set `REACT_APP_GLEAN_ENABLED=true` in my `.env` and clicked on sidebar links, then looked at the pings [here](https://debug-ping-preview.firebaseapp.com/pings/mdn-dev/) (note: there is a small processing delay).
> feat(telemetry): add sidebar_click measurement

- client/src/document/on-github.tsx
This is a follow up to fix the concern raised in the pull request https://github.com/mdn/yari/pull/7809#issuecomment-1398668433.
The links were on a partial set of phrases. This does not help with tab navigation on links and with screens readers.
All links in the footer box now span the entire text. This will help with accessibility.
> fix(on-github): include entire text in links

- kumascript/macros/Compat.ejs
- kumascript/macros/EmbedLiveSample.ejs
- kumascript/macros/Specifications.ejs
- kumascript/src/api/mdn.ts
- tool/macro-usage-report.ts
This PR introduces a new `mdn.deprecatedParams()` method for macros for when the parameters of a macro are deprecated.  This allows us to add comments to macro deprecation, such as to explain how to replace the macro.  Requested in https://github.com/mdn/yari/pull/8298#discussion_r1116735165.
> refactor(kumascript): add mdn.deprecatedParams() for deprecated macro parameters

- kumascript/macros/WebkitBug.ejs
- kumascript/macros/bug.ejs
This PR deprecates the `{{bug}}` and `{{WebKitBug}}` macros.  These two macros are simply wrappers to redirect to Firefox and WebKit bugs respectively, which can be replaced with a simple link.
These should both be replaceable by a simple regex call.
> refactor(macros): Deprecate {{bug}} and {{WebkitBug}} macros

- client/src/document/interactive-examples.scss
Fixes double grey border in HTML & CSS interactive examples. This border is now meant to be set by only BOB. This change was introduced by [#1004](https://github.com/mdn/bob/pull/1004), but it was published with BOB version 3 today.
---
> fix(style): Fix double border in HTML & CSS interactive examples

- kumascript/macros/JSRef.ejs
- kumascript/macros/SVGRef.ejs
https://github.com/mdn/yari/pull/8293 added a measurement for sidebar clicks by macro, but this requires every sidebar macro to add a `data-macro` attribute to the `#Quick_links`, and I missed two occurrences.
Add the two missing `data-macro` attributes, so clicks on those sidebars can be attributed properly.
---
Not tested.
> fix(macros): add data-macro to JSRef/SVGRef

- client/src/telemetry/sidebar-click.ts
https://github.com/mdn/yari/pull/8293 added a measurement for sidebar clicks, but it didn't consider that - on mobile - the TOC is inside `#sidebar-quicklinks`, and so those clicks are also measured.
Check if we're inside `.document-toc`.
---
- Added `REACT_APP_GLEAN_ENABLED=true` to my `.env`.
- Clicked in the mobile TOC and verified (via the JS console and https://debug-ping-preview.firebaseapp.com/pings/mdn-dev) that it doesn't cause a measurement (action ping).
- Clicked in the sidebar and verified that it still causes a measurement.
> fix(telemetry/sidebar-click): ignore mobile TOC clicks

- client/src/document/organisms/toc/placement.tsx
When we count fetches, we don't distinguish between failed and successful fetches, which makes it hard to understand why there are comparatively few views.
Add the HTTP status code (e.g. 200, 204) to the fetched event.
---
- Enabled `REACT_APP_GLEAN_ENABLED=true` in `.env`.
- Ran `yarn dev`.
- Opened http://localhost:3000/en-US/docs/Web/HTML locally.
- Checked debug ping preview: https://debug-ping-preview.firebaseapp.com/pings/mdn-dev/78ec40b3-b0f3-49ac-97ca-2ce2ac2ab321
> chore(placement): record HTTP status with fetched event

- tool/sync-translated-content.ts
The `mdOrHtmlExists` function would treat the param as a regular file, so we can't get the correct status for orphaned document. I didn't get notice this before (see: https://github.com/mdn/yari/pull/7886/files#diff-a7e07f3cdd78c4694f3af5102aa12cf9db651315ad11b1e4ac10518129492ff7R173). Really sorry about this.
treat the param as a file dir.
---
Be moved to orphaned folder ):
---
run `yarn tool sync-translated-content zh-cn`
> fix(tool/sync-translated-content): find document by dir only

- client/src/flaws/index.scss
- client/src/flaws/index.tsx
This improves the flaws display page (/[locale]/_flaws) in many ways, including: utilizing a grid layout instead of floats, utilizing theme variables for colors, standardizing element display, and more.  This helps improve contrast in both dark and light theme; ensures uniform appearance with recognizable UI elements; and provides a better layout on smaller screens (ex. half-width of a laptop screen, smartphones...).
Before:
After:
> fix(flaws): Improve flaws display page

- kumascript/macros/MathMLRef.ejs
This PR rewrites the current MathML sidebar, [MathMLRef.ejs](https://github.com/mdn/yari/blob/main/kumascript/macros/MathMLRef.ejs).
The immediate reason for this is that the current sidebar uses tags, and we want to stop using tags.
But the current sidebar is also not very useful: it only lists elements, not attributes or any guide/tutorial content.
This sidebar is pretty much cloned from the [PR to rewrite the SVG sidebar](https://github.com/mdn/yari/pull/8289), but the content is a little different:
* **Guides**
* **Reference**
* **Elements**
* **Global attributes**
* **Attributes reference**
* **Examples**
Some notes and things.
* There's definitely scope to have a similar organization and ordering at the top level for many of our sidebars (i.e Tutorials/Guides/Reference or something) …
> feat(macros): Rewrite MathML sidebar

- .env-dist
- client/src/document/organisms/metadata/index.tsx
- Fixes: https://github.com/mdn/yari/issues/8272
Client renders different day as per their timezone:
As per the common practice simply use `suppressHydrationWarning` on timestamps.
I set `TZ="US/Eastern"` in `.env` file as there is >2hr difference in time from here. In local dev environment there was hydration error before fix and after fix it got resolved.
***
**Note:** These errors are very hard to diagnose. I couldn't reproduce the error on the same page as the person who reported it on MDN Matrix room. After some back and forth they shared more links and luckily I could reproduce it on `https://developer.mozilla.org/en-US/docs/Glossary/Attribute` page.\
There are some more `<time dateTime={..}>` tags in MDN Plus and translations code. We should preemptively test and mark them with …
> fix(organisms/metadata): suppress hydration error in last modified timestamp

- build/cli.ts
- content/document.test.ts
- content/document.ts
- content/translations.ts
- markdown/m2h/cli.ts
- server/translations.ts
- testing/tests/destructive.test.ts
- tool/cli.ts
This changes the `findAll()` function to an asynchronous function to help improve performance.
> refactor(build): Make Document.findAll() asynchronous

- kumascript/macros/LearnSidebar.ejs
- kumascript/macros/MathMLRef.ejs
- kumascript/macros/SVGRef.ejs
Fixes https://github.com/mdn/yari/issues/8369, fixes https://github.com/mdn/yari/issues/8370.
Page titles used as link text were not properly escaped, so page titles containing HTML elements (such as [`<object> 로부터 <iframe>까지 — 기타 임베딩 기술`](http://localhost:3000/ko/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies])) broke the sidebar.
Use `htmlEscape` to escape the `page.title`.
---
---
Ran `yarn dev` and opened http://localhost:3000/ko/docs/Learn/Getting_started_with_the_web locally.
> fix(macros): escape page.title in sidebars

- .github/workflows/stage-build.yml
- libs/constants/index.js
Updates where we the stage deployment of interactive-examples is hosted.
Previously, the stage deployment of interactive-examples was hosted at `https://interactive-examples.stage.mdn.mozilla.net`, but now it will be at `https://interactive-examples.mdn.allizom.net`.
Updates both the `stage-build` workflow and the CSP headers.
---
Not tested, but used Search+Replace to avoid human errors.
> ci(stage-build): switch to interactive-examples.mdn.allizom.net

- client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
Fixes #8328
* The text is missing a space between "the" and the preference name
* "preferences" should be singular when only one flag needs to be enabled
* Add a space between "the" and the preference name
---
---
> fix(bcd): add space before the preference name

- build/spas.ts
On https://developer.mozilla.org/en-US/, the menu links point to `en-us`, e.g. `https://developer.mozilla.org/en-us/docs/Web` instead of `https://developer.mozilla.org/en-US/docs/Web`. This causes an unnecessary redirect.
Build the homepage using the properly cased locale (`en-US`).
(While at it, this also makes use of `DEFAULT_LOCALE` where possible.)
---
1. On `main`, I ran `yarn build:prepare`.
2. Ran `git add -f client/build`.
3. Switched to this branch.
4. Ran `yarn build:prepare` again.
5. Looked at `git diff --word-diff client/build` and saw the following:
> fix(spas): use cased locale for homepage, not lowercase

- client/src/settings/newsletter.tsx
https://mozilla-hub.atlassian.net/browse/MP-249
Newsletter opt-in was only shown to subscribed users.
Show opt-in to all users.
---
---
Logged in with subscribed and core users.
Requires setting `REACT_APP_NEWSLETTER_ENABLED=true` in `.env` for toggle to show up.
> feat(plus): show newsletter opt-in to core users

- build/document-utils.ts
- build/index.ts
- kumascript/macros/APIRef.ejs
- kumascript/src/info.ts
- libs/types/document.ts
Partially reverts d6e44563d836b4534a09f0b3d3e93fb7799ba1e5.
In https://github.com/mdn/yari/pull/7825, the `short_title` property of `Doc` was renamed to `shortTitle`, and this broke the deployment of the Updates feature, as [Rumba expects the `short_title` property](https://github.com/search?q=repo%3Amdn%2Frumba%20short_title&type=code).
Rename the property back to `short_title`
---
Full-text search for `shortTitle` showed no remaining occurrence.
> fix(types/document): rename shortTitle back to short_title

- .github/workflows/pr-commit-signatures.yml
We require all commits to be signed, we verify this with a workflow, and we point to documentation about signing commits, **but we don't explain how to sign existing unsigned commits**.
Explain how to sign existing commits and then force-push the branch.
---
Pushed an unsigned commit to this branch, causing [the workflow to fail](https://github.com/mdn/yari/actions/runs/4378439251/jobs/7663182846):
> ci(pr-commit-signatures): explain how to sign existing commits

- kumascript/src/api/web.ts
The macro helper function `web.smartlink()` is used to create clever links, especially following redirects and providing a fallback in `en-US` if the page doesn't exist in the specified locale.
Usually, `smartlink()` emits flaws when it follows redirects or provides a `en-US` fallback.
However, as a lot of pages are not available in all locales, this would cause a lot of flaws (one for each missing page on every page using the sidebar macro), so a parameter `ignoreFlawMacro` exists to emit console warnings once for each distinct warning.
For smartlinks where the page does not exist in the current locale but exists in `en-US`, it is too verbose and not useful to emit a console warning.
Omit neither a console warning nor a flaw for fallback links if `ignoreFlawMacro` is set.
---
```
% yarn …
```
> fix(kumascript): ignore smartlink warning for links with fallback

- client/src/document/hooks.ts
- client/src/document/index.tsx
- client/src/telemetry/interactive-examples.ts
Measures how users interact with interactive-examples.
1. [bob] https://github.com/mdn/bob/pull/1145
2. [**yari**] https://github.com/mdn/yari/pull/8337
We don't know how many users interact with interactive-examples, and how.
Handle interaction events that bob posts, and forward them with Glean.
---
1. In bob, checked out the PR (`gh pr checkout 1145`) and ran the build (`npm ci && npm run start`).
3. In yari, added the following environment variables to `.env`:
```
BUILD_INTERACTIVE_EXAMPLES_BASE_URL=http://localhost:4444
REACT_APP_INTERACTIVE_EXAMPLES_BASE_URL=http://localhost:4444
```
4. In yari, checked out this PR (`gh pr checkout 8337`) and ran the dev-build (`yarn && yarn dev`).
5. Opened http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat#try_it …
> feat(interactive-examples): measure actions

- build/build-options.ts
- client/config/env.js
- deployer/aws-lambda/content-origin-request/build.js
- libs/env/index.js
- ssr/index.ts
We currently `import dotenv from "dotenv";`, but the recommended way is to `import * as dotenv from "dotenv";`. In https://github.com/mdn/yari/pull/8366, this caused the following error:
```
TypeError: Cannot read properties of undefined (reading 'config')
4 | import { cwd } from "node:process";
5 |
> 6 | dotenv.config({
|        ^
7 |   path: path.join(cwd(), process.env["ENV_FILE"] || ".env"),
8 | });
9 |
```
Update the imports accordingly.
---
Ran `yarn && yarn dev` without any issues.
> fix(dotenv): import * as dotenv

- deployer/aws-lambda/kevel/env.js
- deployer/aws-lambda/kevel/index.js
- deployer/aws-lambda/kevel/package.json
- deployer/aws-lambda/kevel/yarn.lock
Kevel sends us encoded stings. Since we do not use `innerHTML` but only `textContent` we must decode these in the lambda.
> fix(lambda): decode html entities via he

- client/src/ui/organisms/placement/index.tsx
- deployer/aws-lambda/kevel/index.js
Previously we relied on the status code only. Using the body allows use differentiate between geo restrictions and no inventory.
---
The lambda is already deployed on stage so once can run it locally.
> enhance(placement): use body for placement status

- .github/workflows/prod-build.yml
- client/src/document/lazy-bcd-table.tsx
- client/src/env.ts
- client/src/plus/updates/api.ts
- docs/envvars.md
- server/index.ts
Fetches BCD data from the separate `bcd.developer.mozilla/allizom.org` host.
We have moved the BCD data off to a separate subdomain as part of our (ongoing) migration from AWS to GCP, but we're still fetching BCD data for BCD tables from `/bcd/*`.
- Introduce an environment variable `REACT_APP_BCD_BASE_URL`, defaulting to stage (`https://bcd.developer.allizom.org`).
- Use it for fetching the data for the BCD table.
- Use `bcd.developer.mozilla.org` for the prod build.
---
---
Ran `yarn dev`, then opened http://localhost:3000/en-US/docs/Web/CSS/background#browser_compatibility locally, verified that the BCD data is fetched from `bcd.developer.allizom.org` and properly displayed, then blocked the URL in the DevTools and verified that the BCD data is no longer displayed.
> feat(bcd): fetch compat data from bcd.developer.mozilla/allizom.org

- tool/cli.ts
- Fixes https://github.com/mdn/yari/issues/8372
The changes report all the files referring to the deleted docs so that the contributor will update them manually and there won't be any broken links left behind.
\* Ignore the missing space between the two sentences.
When no references:
/cc @teoli2003
> feature(tool/delete): list files pointing to the deleted document

- client/src/ui/organisms/top-navigation/index.tsx
1. Remove the repeated extra class name, and keep the code tight and clean.
2. Avoid a severe bug that causes the website to crash (seems incredible, let me explain further).
Just remove the class name.
---
Before the deletion, both the `div` and `header` have a `main-document-header-container` class name. Stylesheets attached to the class are:
```css
// client/src/document/index.scss
.main-document-header-container {
position: sticky;
top: 0;
z-index: var(--z-index-top);
}
```
One of them should be deleted, but the real fatal problem is this one:
Follow these steps:
1. Browser MDN pages such as [this one](https://developer.mozilla.org/en-US/docs/Web/HTML) using Chrome.
2. Open Chrome DevTools.
3. Switch to the Layers panel.
See? Chrome crashed.
After some attempts, I created [this …
> fix: remove repeated extra class name

- libs/constants/index.js
Follow-up to https://github.com/mdn/yari/pull/8470.
We changed where BCD data is fetched from, but didn't update our Content-Security-Policy accordingly.
Add `bcd.developer.mozilla/allizom.org` as `connect-src`.
---
Noticed the issue on https://developer.allizom.xyz/en-US/docs/Web/CSS/background#browser_compatibility.
> fix(csp): add bcd.developer.mozilla/allizom.org as connect-src

- client/src/document/index.scss
- client/src/document/index.tsx
- client/src/document/organisms/sidebar/index.scss
- client/src/document/organisms/sidebar/index.tsx
- client/src/document/organisms/toc/index.tsx
- client/src/ui/molecules/grids/_document-page.scss
- client/src/ui/organisms/placement/index.tsx
The sidebar scrolling was scrolling the placement our of view. This refactors the sidebar to have it shown sticky at the bottom if there's enough vertical space.
This also starts to remove duplication of elements and should be continued.
---
---
Deploying it to stage nowish.
> enhance(placement): show placement in split screen

- client/src/document/index.scss
- client/src/document/organisms/sidebar/index.scss
- client/src/ui/_vars.scss
Fixes #8494
Several issues. 
- On a view port 1400x700 overflow was shown for the left sidebar and it wasn't scroll-able.
- Unnecessary scroll bars were shown on the right sidebar (ToC).
Set overflow correct.
---
> fix(sidebar): fix scrolling behavior

- server/index.ts
We make a whoami request on each page, which is served from rumba. When developing locally, we usually set `REACT_APP_KUMA_HOST=localhost:8000`. However, if rumba is then not running, this produces multiple failed requests in the DevTools' network tab.
If the whoami request fails during development, return an empty response.
---
1. Set `REACT_APP_KUMA_HOST=localhost:8000` in `.env`.
2. Run `yari dev`.
3. Make sure rumba is **not** running at localhost:8000.
4. Open http://localhost:3000/en-US/docs/Web and verify in DevTools' network tab that the `/api/v1/whoami` request succeeds anyways.
> feat(server): return whoami fallback if rumba is not running

- client/src/document/index.scss
Fixes #7727.
This PR fixes the problem that icons in good/bad code examples could overlap with the code content.
This PR sets the icons as floated `::before` pseudo-elements to make the content wrap around them.
---
> fix(client): make icons in good/bad examples float

- .github/workflows/stage-build.yml
The GCP deployment is still slow, and copying `client/build` takes longer than it used to take in AWS.
Accelerate the storage copy using the `-j` option:
> _Applies gzip transport encoding to any file upload whose extension matches the -j extension list. This is useful when uploading files with compressible content (such as .js, .css, or .html files) because it saves network bandwidth while also leaving the data uncompressed in Cloud Storage._ ([Source](https://cloud.google.com/storage/docs/gsutil/commands/rsync#options))
Note: `json`, `html` and `txt` are by far the most frequent text formats in the build.
```
% find . -type f | sed -e 's/.*\.//' | sort | uniq -c | sort -nr
81115 json
52112 html
40502 txt
2146 png
276 jpg
218 svg
85 gif
32 map
21 js
12 css
9 gz
2 xml
2 woff2
1 jpeg
1 ico …
```
> ci(stage-build): rsync with -j html,json,txt

- client/src/document/index.scss
Fixes #6647.
This PR places the hash in front of section headings to make it stay on the same line.
This PR uses absolutely-positioned `::before` pseudo-elements to generate the hash, and `align-items: center` to center it.
Alternative:
Put the hash in `::marker`. (It's less optimal in that `::marker` inherits `text-decoration` from its parent, which cannot be nullified.)
---
> fix(client): place hash before headings

- kumascript/macros/LearnSidebar.ejs
Fixes https://github.com/mdn/yari/issues/8552. The lesson pages were duplicated and the assessment page was missing.
The sidebar had the main set of lessons twice, and no assessment.
This is the simplest solution, in which we just move the assessment page into the module. This is in line with the other modules. It might be nice to split assessments into a different subsection, but that should be a change to all the modules (and might end up with some edge cases).
The accessibility section of the sidebar, expanded. Note the duplicated pages.
The sidebar when the user is on the accessibility assessment (the sidebar is not scrolled to the page, because the page isn't in the sidebar):
The accessibility section of the sidebar, expanded. Only one subsection, no duplicated pages:
The sidebar …
> fix(macros/LearnSidebar): remove duplicated accessibility section

- libs/constants/index.js
We no longer host `mdn.mozillademos.org`/`interactive-examples.prod.mdn.mozilla.net`, but they are still included in our CSP.
Remove them.
---
Didn't test, but we have disabled those hosts in CloudFront, so requests no longer come through. Removing the hosts from CSP means requests (e.g. from references in mdn/translated-content) will show up as CSP errors in the console rather than just as failed requests.
> chore(csp): remove legacy hosts

- kumascript/macros/htmlattrdef.ejs
- kumascript/macros/htmlattrxref.ejs
- testing/content/files/en-us/web/bar/index.html
- testing/content/files/en-us/web/fixable_flaws/index.html
- testing/tests/destructive.test.ts
- testing/tests/index.test.ts
chore: deprecate htmlattrdef and htmlattrxref macro
As a part of: https://github.com/orgs/mdn/discussions/347
~blocked by: mdn/content#25823.~
> chore(macros): deprecate htmlattrdef + htmlattrxref macros

- .github/workflows/stage-build.yml
The existing deploy-cloud-functions GHA is limited to only running CloudFunction V1. This attempts to run the deploy command directly from gcloud instead and deploys the function in multiple regions
Github Issue:
https://github.com/google-github-actions/deploy-cloud-functions/issues/304
> ci(stage-build): deploy Cloud Function in multiple regions

- client/src/banners/active-banner.tsx
- client/src/banners/index.tsx
Resolves MP-321.
The MDN Plus launch announcement banner is outdated and links to an outdated blog post.
Remove the banner.
---
---
Ran `yarn dev` and opened http://localhost:3000/en-US/_homepage locally.
> chore(client): remove MDN Plus launch banner

- client/src/app.tsx
- client/src/ui/organisms/top-navigation/index.tsx
Make the top navigation sticky again.
#8326 made the top navigation non sticky on non document pages.
This is just a quick and dirty fix by adding the class name again. 
---
> fix(top-nav): top navigation not sticky

- deployer/src/deployer/upload.py
Fixes: #8497
The content-encoding of sitemap files, such as: https://developer.mozilla.org/sitemaps/en-us/sitemap.xml.gz is not set.
Add content-encoding when mimetypes could infer this.
Some refs:
- kjvarga/sitemap_generator#338
- https://docs.python.org/3.10/library/mimetypes.html#mimetypes.guess_type
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/upload_file.html
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/customizations/s3.html#boto3.s3.transfer.S3Transfer
---
None.
---
The content-encoding and content-type inferred by mimetypes.
> fix(deployer): add content-encoding if mimetypes infers one

- .github/workflows/prod-build.yml
Like https://github.com/mdn/yari/pull/8456, but for prod.
We're migrating to GCP, but right now we sync our prod build only to S3.
Sync our build to GCS as well.
---
I copied the steps from `stage-build` and replaced "stage" with" build, so as long as IAM permissions etc are set up the same way as for stage, this should work. But even if it doesn't right away, this doesn't have a negative impact on the current deployment in AWS, because the GCP steps come after the AWS steps.
> ci(prod-build): sync build with GCS

- kumascript/macros/MathMLRef.ejs
Add the "MathML Attribute Values" to the nav.
The [MathML Attribute Values](https://developer.mozilla.org/en-US/docs/Web/MathML/Attribute/Values) is not visible in the nav.
Add it to the MathMLRef macro. Note that this points to the new location of the page (after https://github.com/mdn/content/pull/26093).
Also note that if we supported [weight](https://github.com/orgs/mdn/discussions/124), then we would not have to update sidebars manually in cases like this.
> Add "attribute values" guide to MathML sidebar

- client/src/document/index.scss
- client/src/ui/molecules/grids/_document-page.scss
fixes https://github.com/mdn/yari/issues/8610
also fixes a z-index issue with the mobile sidebar
---
> fix(sidebar): end of toc cut off

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
Our builds are regularly slow, because we have been limited to 2core runners with varying CPU performance.
1. Use a 4core runner (large runner).
2. Build all locales (9) concurrently.
---
The xyz environment (in https://github.com/mdn/yari/pull/8366) has been built like this for about 2 weeks already.
> ci(stage,prod): build all locales concurrently on 4core runner

- client/src/plus/offer-overview/offer-overview-subscribe/index.tsx
- client/src/ui/atoms/avatar/index.tsx
- client/src/user-context.tsx
- client/src/utils.ts
- server/index.ts
When we migrate to GCP, the API might be temporarily unavailable for a few minutes, but our users won't notice this unless they execute any actions involving the API.
Show a maintenance message if the whoami request fails.
---
---
Blocked the `/api/v1/whoami` request using DevTools.
> feat(user-context): show maintenance message if whoami failed

- libs/pong/cc2ip.d.ts
- libs/pong/click.d.ts
- libs/pong/coding.d.ts
- libs/pong/fallback.d.ts
- libs/pong/get.d.ts
- libs/pong/image.d.ts
- libs/pong/index.d.ts
- libs/pong/viewed.d.ts
Extracted from https://github.com/mdn/yari/pull/8366.
The `libs/pong` cannot be used in our Cloud Function, because it doesn't have any TypeScript definitions.
Add the TypeScript definitions.
---
Just extracted, so it shouldn't break anything.
> chore(libs/pong): add TypeScript definitions

- kumascript/macros/AddonSidebar.ejs
This goes hand in hand with mdn/content#26242
mdn/content#26242 removes an article. An existing KS sidebar has a ref to said article.
Update sidebar
I did not apart from running `yarn dev` and checking the corresponding pages.
> KS Macros: Remove fx differentiators from sidebar as a companion of mdn/content#26242

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
(MP-360)
We migrated stage and prod to GCP, but we're also still deploying to AWS.
Remove the deployment to AWS.
**Note**: The "dev" environment (also used by the PR Review Companion) is still in AWS.
---
I would trigger a stage-build later.
> ci(stage,prod): stop deploying to AWS

- cloud-function/src/app.ts
Fix 404 for fxa webhooks
We are proxying `/events/fxa/*` but the path is `/events/fxa`.
Proxy `/events/fxa`
> fix(cloud-function): fix fxa webhooks

- .github/workflows/pr-kumascript.yml
- jest.config.json
- package.json
(MP-363)
The kumascript unit tests are failing since April, because they're reaching the maximum heap size.
1. Combine `node --expose-gc` with `jest --logHeapUsage` to regularly collect garbage.
1. Enable ts-jest's `isolateModules` option.
1. (Make sure that the kumascript unit test runs if `jest.config.json` or `package.json` change.)
---
- Before: https://github.com/mdn/yari/actions/runs/4862602408/jobs/8669188317
- After: https://github.com/mdn/yari/actions/runs/4876600693/jobs/8700289580
> fix(jest): reduce memory usage

- content/document.ts
- Addresses https://github.com/mdn/content/pull/26132#issuecomment-1504575810
We prefer double quotes in front-matter YAML to wrap title attributes with special characters.\
At the moment in content repo we have ~5514 double double quotes and only ~147 single quotes.
But the `yarn content move` converts double quotes to singe quotes:
```
title: "AbortSignal: abort() static method"
to
title: 'AbortSignal: abort() static method'
```
This pushes unnecessory changes to the content repo and confuses reviewers.
Configure `js-yaml.dump()` method to use double quotes:
```js
yaml.dump(saveMetadata, {quotingType: '"'})}
```
Tested `yarn content move` locally with and without the changes.
> fix: prevent `yarn content move` from converting double quotes to single quotes

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
CDN invalidation takes 10 minutes in GCP, and our build is waiting for it to finish.
Trigger CDN invalidation asynchronously with `--async`.
(Also merges the separate `invalidate` job back into the `build` job to have a single deployment job.)
---
Not yet tested, but could trigger a stage build.
> ci(stage,prod): invalidate CDN asynchronously

- client/public/index.html
- client/src/app.scss
- client/src/document/hooks.ts
- client/src/document/index.scss
- client/src/homepage/static-page/index.tsx
- client/src/plus/index.tsx
- client/src/plus/plus-docs/index.tsx
- client/src/ui/molecules/grids/_document-page.scss
- client/src/ui/organisms/article-actions-container/index.scss
- client/src/ui/organisms/article-actions/index.scss
use `--sticky-header-height` everywhere
On prod when scrolling on an article page the toc is moving by 2px because the offset was wrong. This is worse on staging with the top banner.
Consolidate the offset to use `-sticky-header-height`. This should fix the issue at hand without touching to much of our fragile CSS.
---
> fix(layout): consolidate sticky header

- tool/cli.ts
Sometimes `yarn tool spas` fails with an error message that is not very helpful:
```
$ ts-node tool/cli.ts spas
(node:13884) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13884) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
error: 
```
This happens when the `Error` has an empty `message`.
(Note: That `yarn tool spas --verbose` always prints the Error stack before the message.)
Print the Error stack if the Error message is empty.
---
---
Ran `yarn tool spas` while it was …
> chore(tool): print error.stack if error.message is empty

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
- client/src/blog/index.scss
- Fix sync step (stop rsyncing `static` / fix -y option)
- Fix img width of blog index in safari
> fix(sync): skip rsync for static

- build/utils.ts
- package.json
- yarn.lock
The package [`vscode-ripgrep`](https://www.npmjs.com/package/vscode-ripgrep) is renamed to [`@vscode/ripgrep
`](https://www.npmjs.com/package/@vscode/ripgrep).
This PR just renamed this package and bump the version to `1.15.2`.
> chore(deps): rename package `vscode-ripgrep` to `@vscode/ripgrep`

- tool/popularities.ts
(MP-366)
Previously, popularities were derived from CloudFront logs, and hosted in an S3 bucket.
Now, we derive popularities from Glean data (page events) and host them at `popularities.mdn.mozilla.net`.
Update where we download popularities from.
**Note**: This might change the order of some items in the in-page search (quicksearch)!
---
Ran `yarn tool popularities` and verified that the `popularities.json` is generated correctly.
> chore(popularities): use Glean popularities

- package.json
- yarn.lock
(It seems like Dependabot omits this major version bump.)
> chore(deps-dev): bump @types/node from 16.18.25 to 18.16.6

- .github/dependabot.yml
Dependabot doesn't currently update dependencies in all folders.
Enable it also for these folders:
- `/cloud-function` (MP-361)
- `/lib/locale-utils`
- `/lib/pong`
---
Hard to test, but I just duplicated and adjusted the config from `/lib/slug-utils`.
> ci(dependabot): enable for /cloud-function + /lib/{locale-utils,pong}

- kumascript/macros/PWASidebar.ejs
Adds "What's a PWA" to the PWA sidebar.
"What's a PWA", added in https://github.com/mdn/content/pull/26569, isn't in the sidebar.
Add "What's a PWA", to the sidebar.
Ran yarn dev, looked at pages.
> Add 'Whats a PWA' to PWA sidebar

- .github/workflows/npm-publish.yml
(MP-385)
The [mikeal/merge-release](https://github.com/mikeal/merge-release) no longer works.
Migrate to the [release-please-action](https://github.com/google-github-actions/release-please-action).
**Note**: This means we no longer create a tag/release on every merge to main.
---
Hard to test, but we have done this before for Rumba in https://github.com/mdn/rumba/pull/186.
> ci(npm-publish): migrate from merge-release to release-please

- .github/workflows/npm-publish.yml
(MP-385)
The npm-publish workflow is now creating releases with release-please, but the npm publish fails, because I renamed an environment variable by mistake.
Revert the rename.
Also:
- Removes the (unnecessary) dry run step.
- Renames the build steps.
---
We'll see if this works as soon as the next release is cut.
> fix(npm-publish): revert renaming of NPM_AUTH_TOKEN

- lint-staged.config.js
(MP-410)
YAML files were not automatically formatted with prettier as part of `lint-staged`, because the negative pattern for other files (introduced in 6184affef801d9425d60a667579d17a2135a16f0) is not correct. (Negative patterns must start with the `!`, not contain it.)
Fix the negative pattern.
---
---
Tested by updating a YAML file to use single quotes (`'`), staging the changes, and running `yarn lint-staged` thereafter.
> fix(lint-staged): use negative pattern correctly

- .github/workflows/npm-publish.yml
(MP-385)
The "npm publish" workflow is failing, and the real reason (after 3 unsuccessful tries) seems to be that npm doesn't actually use `NPM_AUTH_TOKEN` or `NODE_AUTH_TOKEN`, unless these are referenced in an `.npmrc` file.
Call the `setup-node` action with the `registry-url` input, which causes it to create an `.npmrc` file that references the `NODE_AUTH_TOKEN` environment file.
Also:
- Reverts the env rename revert.
- Reverts the `--access` revert (this is not necessary for scoped packages that are already published and public).
---
🤞
> fix(npm-publish): setup node with registry url

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
- build/cli.ts
- build/sentry.ts
- libs/env/index.d.ts
- libs/env/index.js
- package.json
- yarn.lock
We emit a lot of warnings and errors during our yari builds, but we don't actively track them.
Adds and configures [Sentry Node](https://docs.sentry.io/platforms/node/) to track `console.warn/error/assert()` calls during our builds.
*Note*: This does **not** enable Sentry for the website.
---
Set `SENTRY_DSN_BUILD` in my `.env` file and ran `yarn build:prepare && yarn build --locale en-us --nohtml web/html`, verifying that some warnings and errors appear in our (internal) [Sentry project](https://mozilla.sentry.io/projects/mdn-yari-build/?project=4504955643428864).
> feat(build): collect errors + warnings with @sentry/node

- .github/workflows/xyz-build.yml
- libs/constants/index.js
(Extracted from https://github.com/mdn/yari/pull/8366.)
Previously, we only had one test environment (`stage`), but this means we often have to wait for each other to "test on stage".
Add another environment `xyz` and a `xyz-build` workflow similar to `stage-build`.
**Note**: The `xyz` environment does not have a dedicated rumba, so it doesn't currently support logging in.
---
Will run another xyz build now.
> feat(ci): add xyz-build

- client/src/contributor-spotlight/index.tsx
- client/src/document/hooks.ts
- client/src/document/index.tsx
- client/src/document/toolbar/edit-actions.tsx
- client/src/flaws/index.tsx
- client/src/page-not-found/fallback-link.tsx
- client/src/plus/plus-docs/index.tsx
- client/src/search.tsx
- client/src/translations/dashboard/index.tsx
- client/src/translations/differences/index.tsx
- client/src/translations/index.tsx
- client/src/translations/missing/index.tsx
- client/src/ui/organisms/article-actions/language-menu/index.tsx
- cloud-function/src/middlewares/redirect-leading-slash.ts
1. When getting the `locale` via `useParams()`, we may get an invalid (unsanitized) locale.
2. When normalizing multiple leading trailing slashes in our Cloud Function, we don't take encoded slashes into consideration.
1. Always use `useLocale()` to ensure we get a valid locale.
2. Remove encoded leading slashes by redirecting.
---
https://developer.allizom.xyz/%2fexample.com redirects to https://developer.allizom.xyz/example.com.
> fix: avoid leading double slash

- client/src/document/index.scss
This PR adds a CSS rule to strip the bottom margin from last elements inside blockquotes.
See:
* https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide
* https://developer.mozilla.org/en-US/blog/aria-accessibility-html-landmark-roles/
The styles for blockquotes looks a little wobbly and difficult to read.
Add a rule like the following:
```css
.main-page-content .section-content blockquote > :last-child {
margin-bottom: 0;
}
```
---
Running on localhost.
> fix(CSS): last elements inside blockquotes do not need bottom margin

- client/src/app.scss
- client/src/document/index.scss
- client/src/document/organisms/sidebar/index.scss
- client/src/ui/_vars.scss
- client/src/ui/atoms/modal/index.scss
- client/src/ui/organisms/article-actions/index.scss
- client/src/ui/organisms/placement/index.scss
- client/src/ui/organisms/top-navigation/index.scss
fixes https://github.com/mdn/yari/issues/8646
fixes https://github.com/mdn/yari/issues/8702
remove --z-index-top variable, and split into per-element variables -
not everything can be on top!
remove some unnecessary z-indexes due to relative positioning
I intend to follow up with another PR removing the rest of the
reused/unnecessary z-indexes later - but don't want to block fixing this
issue with that
- sidebar offset is wrong on mobile - in the past this seemed to cause part of the sidebar to be cut off, now it causes a gap between the header and sidebar
- some content shows through the sidebar
- correct offset
- correct z-index
---
> fix(sidebar): incorrect offset and z-index on mobile

- client/src/ui/organisms/placement/index.scss
reset width to prevent scrolling on small screen sizes
---
Click in the image to see a white space on the right.
> fix(top-banner): adjust width

- .github/workflows/dev-build.yml
- .github/workflows/developing.yml
- .github/workflows/npm-publish.yml
- .github/workflows/npm-published-simulation.yml
- .github/workflows/performance.yml
- .github/workflows/pr-kumascript.yml
- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
- .github/workflows/testing.yml
- .github/workflows/xyz-build.yml
We hit a rate limit when installing yarn packages in CI, and the job fails as a result, requiring manual intervention.
Setting the `GITHUB_TOKEN` environment variable should use a per-token rate limit, rather than a public one: https://github.com/microsoft/vscode-ripgrep#github-api-limit-note
Testing in this draft PR.
> fix(workflows): rate limit downloading ripgrep

- build/syntax-highlight.ts
This PR supports `apacheconf` syntax highlighting.
We reference `apache` in some code blocks in `mdn/content` but the correct key is `apacheconf`. Neither language is explicitly loaded, so neither currently work.
Add `apacheconf` to list of Prism loaded languages.
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Apache_Configuration_htaccess
on localhost whith code block using `apacheconf`:
on localhost.
__Related issues and pull requests:__
> feat: Add Prism key for syntax highlighting apache code as 'apacheconf'

- client/src/blog/post.tsx
SSR renders an en-US format date, client side renders in the user's locale
---
- `yarn dev`
- once that finishes run `yarn build:blog` in a separate terminal
- once that finishes, load http://localhost:5042/en-US/blog/ with JS disabled
- observe date in US format, e.g. "May 10, 2023"
- enable JS, reload page
- observe date in (in my case) GB format, e.g. "10 May 2023"
- observe no hydration errors in console
> fix(blog): hydration error on date

- README.md
I notice that the `engine` field in `package.json` requires Node.js version `>= 18.0.0`, but the README content has not been updated to reflect this.
> docs(README): sync require nodejs version

- client/src/ui/molecules/theme-switcher/index.scss
- client/src/ui/organisms/article-actions/bookmark-menu/index.scss
Header jumps around when opening the menu in tablet mode, exposing a 1px gap at the top of the page.
Icons in the article actions menu also appear cropped, due to half-pixel offset.
Make header and article actions band full-pixel heights, rather than half pixel.
---
Observe the whole page seem to shift down 1px, including the header (look at the logo), and a gap at the top you can see some text peeking through, when the menu opens. Also observe the icons in article actions be cropped at the bottom when the menu opens:
[Screencast from 2023-05-18 11-11-11.webm](https://github.com/mdn/yari/assets/755354/7d324567-2e55-4c54-9de3-ecd59c219d1d)
[Screencast from 2023-05-18 11-13-37.webm](https://github.com/mdn/yari/assets/755354/e72f6904-6041-4b20-b921-473a1e37e603)
> fix(ui): gap at top of page in tablet mode

- build/cli.ts
- content/translations.ts
- server/index.ts
Trying to fix and as a part of #8301
Gather all translation would slow down the static document build in translated-content. Only gather the translations of the incoming slug might be a better idea.
After we migrating to ESM, the PR-test ci in translated-content would spend more than 25 seconds to build a single document (as in most of PRs, the number of changed documents is only `1`). The most of time during a build is spent on
`gathering all translations` (as metioned in #8301).
Try to gather the translations of a required slug only, this should save most of the time for build a single document.
---
Using a locale build of `yari` to check the build time.
Run `yarn build files/en-us/learn/common_questions/web_mechanics/what_is_a_web_server/index.md`
and `node …
> fix(content): only collect required translations

- libs/constants/index.js
- libs/fundamental-redirects/index.js
(Part of MP-354)
Related:
- https://github.com/mdn/content/pull/26809
- https://github.com/mdn/translated-content/pull/13291
We migrated to GCP and archived the legacy media files (including samples) under https://mdn.dev/archives/media/, but we're still redirecting to the old host.
Update the redirect, and the CSP header.
---
Ran `npm start` in `cloud-function` and checked with curl:
```
% curl localhost:5100/samples/foo
Found. Redirecting to https://mdn.dev/archives/media/samples/foo
```
> fix(csp,fundamental-redirects): replace media.*.mdn.mozit.cloud with mdn.dev

- build/syntax-highlight.ts
The `webidl` language is disabled in Prism syntax highlighting and we have build warnings because of this. It looks like we use it in the content repo, so I would propose enabling it here.
See https://github.com/mdn/yari/commit/def733d5f803f274d0db9bbe339f7a311b9e57f2
> chore: activate webidl language definition

- client/src/search.tsx
- client/src/ui/molecules/search/index.tsx
- testing/tests/headless.search.spec.ts
https://mozilla-hub.atlassian.net/browse/MP-400
- page doesn't scroll to top when using quicksearch
- when using keyboard to open a result, key modifiers aren't recognised, so pages can't be opened in e.g. a new tab
- use proper links
- dispatch a `MouseEvent` when using the keyboard - unfortunately, browser support for passing modifiers is inconsistent, I presume this is some kind of clickjacking protection
---
- clicked on quicksearch results with mouse, using various modifier keys (or none)
- interacted with quicksearch results with keyboard, using various modifier keys (or none) across Firefox/Chromium/Epiphany (with inconsistent/consistent/no support for modifier keys respectively)
> fix(quicksearch): opened pages don't scroll to top

- build/syntax-highlight.ts
We have build errors that `vue` is not a detected language. There is no support for `vue` in Prism, an alternative is to use `markup` which is supported without additional Yari dependencies. Adding an alias will allow us to highlight the language and preserve Prettier linting in content.
Prism does not support `vue` as a language, see:
* https://github.com/mdn/content/blob/218df89024b21bc4d1896ec4b3be727213704cca/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/vue_computed_properties/index.md?plain=1#L75-L85
* https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_computed_properties
Add an alias for `markup` so that the language will be highlighted and Prettier can still format the examples.
On …
> chore: add alias vue -> markup to enable syntax highlighting

- .stylelintrc.json
- client/src/newsletter/index.scss
- client/src/ui/organisms/placement/index.scss
- package.json
- yarn.lock
- we stopped sorting css properties after https://github.com/mdn/yari/commit/ec6822ffd8e477168b924ee6a5a5ae82cf22edef and started slowly descending into css anarchy :scream: 
- add the rules removed upstream back: https://github.com/bjankord/stylelint-config-sass-guidelines/pull/278
---
Ran `yarn stylelint --fix`
> chore(lint): re-add stylelint-order

- kumascript/index.ts
- kumascript/src/templates.ts
When a macro fails, the console error message mentions only the macro name and the error message, making it hard to identify which page the macro failed on.
Add the document path to the error message.
---
```
specifications macro failed: Error: /path/to/yari/kumascript/macros/Specifications.ejs:1
...
```
```
The specifications macro in /Users/claas/github/mdn/content/files/en-us/mdn/writing_guidelines/page_structures/page_types/aria_page_template/index.md failed to render. Error: /path/to/yari/kumascript/macros/Specifications.ejs:1
...
```
---
Ran `yarn build --locale en-us` in a VSCode Debug Console, setting a breakpoint in the catch block.
> fix(kumascript): mention path in render error message

- build/spas.ts
https://mozilla-hub.atlassian.net/browse/MP-445
- we want to add blog posts to featured articles, but can't
- change the featuredArticles logic to accept either docs or blog posts
- opted to not add a "Blog" tag as it would make the boxes a bit long
---
---
Clicked the links to make sure they work.
> chore(homepage): add blog posts to featured articles

- build/blog.ts
- kumascript/index.ts
- kumascript/src/templates.ts
Same as https://github.com/mdn/yari/pull/8936, but incorporating fixes for the build errors it caused.
---
Ran `yarn tool spas` and `yarn build --locale en-us`.
> fix(kumascript): mention path in render error message (v2)

- kumascript/macros/SeeCompatTable.ejs
This PR add localization support for the title of `{{SeeCompatTable}}` macro (the translation is copied from [ExperimentalBadge](https://github.com/mdn/yari/blob/089697015fdfa521d14e3816cc02fe1f3a364889/kumascript/macros/ExperimentalBadge.ejs#L19-L29)), and also update the zh-CN translation and the `href`s of zh-TW str.
---
See:
- `http://localhost:5042/zh-TW/docs/Web/API/AbortController`
- `http://localhost:5042/zh-CN/docs/Web/API/AmbientLightSensor`
- zh-TW
- zh-CN
---
run `yarn start` and see rendered pages.
> chore(macros/SeeCompatTable): localize "Experimental" title

- client/src/document/toolbar/index.tsx
On Preview URLs, the toolbar is unnecessarily high, because it contains a `<p>`, which has `margin: 1rem 0 2rem;`.
Turn the `<p>` into a `<div>`.
---
---
Applied the changes directly [here](https://pr26985.content.dev.mdn.mozit.cloud/en-US/docs/Glossary/Firefox_OS).
> fix(toolbar): reduce height if read-only

- kumascript/index.ts
- kumascript/src/templates.ts
The path is so long that it cuts in Sentry, making it harder to export a list of errors programatically.
Use the url instead.
---
---
> chore(kumascript): use url in render error

- kumascript/macros/GlossarySidebar.ejs
- kumascript/macros/ListSubpagesForSidebar.ejs
This PR adds a dedicated `{{GlossarySidebar}}` macro.
We do not have a sidebar in any Glossary sub-page. This PR introduces a macro that lists all pages under `glossary/*/index.md`
A macro `{{GlossarySidebar}}` that will list all Glossary pages for discovery.
locally with `yarn && yarn dev`
- Do we need tests for this?
> feat(macros): add GlossarySidebar macro

- .gitattributes
Currently, when [searching for yari files on GitHub](https://github.com/mdn/yari?search=1), files from the `build/` directory are excluded as per [the GitHub docs](https://docs.github.com/en/search-github/searching-on-github/finding-files-on-github#customizing-excluded-files).
Set the `linguist-generated=false` for those files in a `.gitattributes` file.
---
We'll see!
> fix(github): include build/** in search results

- .stylelintrc.json
- client/src/document/organisms/sidebar/index.scss
- client/src/document/organisms/toc/index.scss
- client/src/document/toolbar/index.scss
- client/src/plus/icon-card/index.scss
- client/src/plus/updates/index.scss
- client/src/ui/atoms/avatar/index.scss
- client/src/ui/atoms/toast/index.scss
- client/src/ui/molecules/dropdown/index.scss
- client/src/ui/molecules/pagination/index.scss
- client/src/ui/organisms/article-actions/index.scss
- client/src/ui/organisms/footer/index.scss
Selectors can be concatenated in Sass, but this prevents those selectors from being found via the search.
Disallow selector concatenating, as [described here](https://stackoverflow.com/questions/74598779/how-to-disallow-concatenated-selectors).
---
Ran `yarn stylelint` and manually reviewed the changes once more in this PR to make sure I used the correct replacement in each case.
> style(sass): disallow concatenated selectors

- kumascript/macros/AddonSidebar.ejs
- kumascript/tests/macros/addonsidebar.test.ts
Renders items programmatically using `page.{short_title,title}` (where possible).
Removes unused translations, obsolete details expansion and the "toggle" class.
The `AddonSidebar` macro includes page titles and their translations, increasing maintenance cost, e.g. when new translated pages are added.
Derive page titles directly from the page's frontmatter.
---
See: https://www.diffchecker.com/AmrMSA7i/
---
Ran `yarn && yarn dev` locally and:
1. Looked at http://localhost:3000/en-US/docs/Mozilla/Add-ons/WebExtensions
2. Compared the `innerHTML` of the sidebar with that of https://developer.allizom.org/en-US/docs/Mozilla/Add-ons/WebExtensions using DiffChecker (see above).
> refactor(macros/AddonSidebar): use page titles + cleanup

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
- .github/workflows/xyz-build.yml
- cloud-function/src/headers.ts
disable cdn invalidation by default in the build - it doesn't really
work in gcp: even after waiting the ~20 minutes it takes to "finish",
content is still cached for certain users in certain geos - but keep
the option for manual use in exceptional circumstances
https://mozilla-hub.atlassian.net/browse/MP-440
- cdn invalidation doesn't work well (or at all) in gcp
- stop using invalidation, set caching header to 1h on volatile content (i.e. content which doesn't have a hash in its path)
---
I haven't yet, and I need help learning how :)
@caugner we'll peer review/test this tomorrow
> fix(gcp): cache volatile content for 1h

- client/src/telemetry/glean-context.tsx
this causes any useEffects depending on it to fire on every render
should fix the underlying problem in https://github.com/mdn/yari/pull/9106 (MP-482)
---
Set:
```
REACT_APP_GLEAN_ENABLED=true
REACT_APP_GLEAN_DEBUG=true
```
and observed glean events in console not being sent for every keypress in the sidebar filter.
> fix(glean): gleanClick changes between re-renders

- kumascript/macros/LiveSampleURL.ejs
- kumascript/tests/macros/EmbedLiveSample.test.ts
- kumascript/tests/macros/LiveSampleURL.test.ts
We did not use the legacy URL in LiveSampleURL.ejs
Live samples translated from another page (deprecated), resulted in to 404 iframe. 
Use the legacy url in LiveSampleURL.ejs to point to the legacy live sample.
---
---
https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_build_custom_form_controls
With:
```
BUILD_LIVE_SAMPLES_BASE_URL=https://live.mdnplay.dev
BUILD_LEGACY_LIVE_SAMPLES_BASE_URL=https://live-samples.mdn.mozilla.net
```
Use a `yarn build files/en-us/learn/forms/how_to_build_custom_form_controls/index.md` and check that the iframes in the resulting html file have `live-samples.mdn.mozilla.net` as domain if they are not using the `runner.html`.
> fix(livesamples): use correct legacy url

- client/public/runner.html
Navigating back and forth can try to initialized the runner multiple times. Let's not do that.
> fix(playground): only initialize once

- client/src/document/hooks.ts
fixes #9177
We were passing an raw class into querySelectorAll
use getElementsByClassName
> fix(live-sample): use getElementsByClassName

- client/src/blog/index.scss
- client/src/blog/index.tsx
- client/src/blog/post.scss
https://mozilla-hub.atlassian.net/browse/MP-469
also progressively enhance with subgrid to align elements of the article cards with different lengths of titles/content
---
---
Set `sponsored: true` to frontmatter in a blog article.
`yarn && yarn dev`
> chore(blog): stylise sponsored content indicator

- client/src/plus/ai-help/index.scss
- client/src/plus/ai-help/index.tsx
Currently, there is no way for users of AI Help to give qualitative feedback about an answer of low quality.
Add a "Report issue with this answer on GitHub" link that pre-fills a GitHub issue template on a dedicated feedback repo.
---
| Step 1 | Step 2 | Step 3 |
| ------ | ------- | ------ |
| <img width="814" alt="image" src="https://github.com/mdn/yari/assets/495429/b47f783f-02d2-4e42-83e6-04787e70dd90"> | ![image](https://github.com/mdn/yari/assets/495429/1213326f-d5c4-472f-9d25-dad4e2c40d44) | ![image](https://github.com/mdn/yari/assets/495429/43c5d776-1883-4b8d-ba76-8e7983028eca) |
---
Asked a question locally and clicked on the new link.
> feat(ai-help): add "Report issue with this answer on GitHub" link

- kumascript/macros/AddonSidebar.ejs
Fixes #9211.
Correct wrong AddonSidebar item.
Replace incorrect address with correct address。
---
1. git clone `yari`, `content`, `translated-content`. and configure them normally.
2. apply change.
3. `yarn dev` to check if it works.
> fix(macros/AddonSidebar): inline "Using_the_JavaScript_APIs" redirect

- client/src/plus/ai-help/index.tsx
Changes the copy for the "thumbs up" button, as requested internally (MP-513).
---
---
Ran `yarn && yarn dev` with rumba running locally.
> chore(ai-help): update thumbs copy

- client/src/document/code/playground.ts
https://mozilla-hub.atlassian.net/browse/MP-515
fixes https://github.com/mdn/yari/issues/9190
inline bits of css get a `css` class applied to them, so our extraction logic was treating them as "normal" css - which of course it isn't, since it doesn't have any kind of selector
specifically target `pre.${language_name}` rather than just `.${language_name}` - I'm going to wait for your review @fiji-flo here, because I imagine there was a reason you chose *not* to specifically target pre tags, so I want to make sure I'm not breaking anything else
---
---
http://localhost:3000/en-US/docs/Web/CSS/flex-grow
> fix(playground): don't extract inline css

- client/src/plus/ai-help/index.scss
- client/src/plus/ai-help/index.tsx
(MP-532)
We already have a disclaimer below the question input field, but we don't want to leave any doubt that this feature is still beta, and that it occasionally generates incorrect answers.
Add a disclaimer that communicates the beta status, informs about the answers being occasionally incorrect (reuses the wording from ChatGPT), and asks users to verify information independently.
---
---
Ran `yarn && yarn dev` and opened http://localhost:3000/en-US/plus/ai-help/ locally (with Rumba running).
> fix(ai-help): add beta disclaimer banner

- client/src/plus/ai-help/index.tsx
There were two problems with issue reporting:
1. The first question was used as the issue title, not the last.
2. Multiple questions were separated with "---" (no line breaks).
1. Use the last question.
2. Put the questions in an enumerated list instead.
---
Ran `yarn && yarn dev`, opened http://localhost:3000/en-US/plus/ai-help locally, answered multiple questions, and clicked on the "Report an issue with this answer" link.
> fix(ai-help): enhance issue reporting

- client/src/ui/organisms/footer/index.tsx
The Community Discord Server has been operational for a while now. People are wondering why we do not have invite link in the footer where other communication channels are mentioned.
Add the invite to the list.
Using `yarn dev` in local.
> chore(footer): Add Discord server to footer

- build/document-utils.ts
See for example:
Changed the regex to only match HTML tags at the start of the text (which matches the editorial conventions). Also did some minor refactoring.
---
---
> fix(build): avoid breadcrumbs over-shortening

- kumascript/macros/cssxref.ejs
Fixes #8883.
On non-en-US pages, `{{CSSXref}}` doesn't add parentheses in the displayed link texts for CSS functions.
As the `page-type` front matter key is absent from l10n contents, this PR uses en-US links to fetch the key instead.
---
> fix(macros/cssxref): use en-US page to fetch front matter key

- kumascript/macros/xref_cssvisual.ejs
This macro is not used in en-US, and it does point to the redirected page (`/en-US/docs/CSS/Media/Visual -> /en-US/docs/Web/CSS/@media`). Maybe it's time to deprecate this macro.
/cc @mdn/yari-content-css @bsmth
---
None.
> chore(macros): deprecate {{xref_cssvisual}} macro

- build/blog.ts
Hidden code blocks were being included in the read time calculation for blog posts, which leads to https://developer.mozilla.org/en-US/blog/scroll-progress-animations-in-css/ for instance having a 25 minute read time, because of lots of lorem ipsum being included in the examples.
Ignore hidden code blocks when doing this calculation: the above article now has a 7 minute read time.
---
- `yarn dev`, visited article locally
- also pasted source of article into https://regex101.com/ and checked my regex matched the intended blocks (and nothing else - I needed that non-greedy match `?`)
> fix(blog): ignore hidden code blocks when calculating read time

- .prettierrc
- build/blog.ts
- build/cli.ts
- build/flaws/index.ts
- build/index.ts
- client/public/index.html
- client/public/runner.html
- client/src/document/mathml-polyfill/mathml-font.scss
- client/src/document/organisms/sidebar/filter.scss
- client/src/document/organisms/sidebar/index.tsx
- client/src/playground/index.tsx
- client/src/playground/loader.scss
- client/src/plus/ai-help/index.scss
- client/src/plus/index.scss
- client/src/search.tsx
- client/src/site-search/search-results.tsx
- client/src/ui/base/_typography.scss
- client/src/ui/molecules/search/index.scss
- content/document.ts
- content/utils.ts
- package.json
- server/document.ts
- tool/cli.ts
- tool/sync-translated-content.ts
- yarn.lock
This PR bumps Prettier from 2.8.8 to 3.0.0, and then fixes issues with the content commands caused by changes to the Prettier API.  In Prettier v3.0, the `format()` command became asynchronous, so we were returning a Promise every so often, which caused errors when running commands.  This PR aims to fix this by adding an `await`, and making the rest of the function chain asynchronous.
**Note:** because the content repositories use Prettier 3.0.0, these commands are **broken** regardless of the Prettier version Yari is requesting.
**Note:** because Prettier has changed its defaults, the formatting output has also changed.  TO pass linting, all files had to be formatted, which unfortunately means a greater risk of merge conflicts.  Since this is a critical bug fix, it should be merged …
> Bump Prettier from 2.8.8 to 3.0.0

- kumascript/macros/CSSRef.ejs
This fixes the "In CSSRef the smartLink to ... is broken" warnings when running `yarn tool spas`.
By building the docs and ensuring that the relevant sidebar links still work.
> fix(macros/CSSRef): Update links to the pages they redirect to

- build/flaws/broken-links.ts
We have a flaw that reports absolute MDN links, to ensure content uses relative links, so that they work on all environments (locally, stage and prod), and another flaw that reports relative MDN links that don't exist.
When we added relative links to MDN blog articles, this has been causing a flaw, because external contributors don't have the mdn/mdn-studio repository checked out, and even if they would, the flaw doesn't take the blog articles into consideration.
That's why relative links to MDN blog articles were replaced with absolute links, but that caused the other flaw.
Do not consider absolute links to MDN blog articles broken.
---
Ran `yarn && yarn dev` (with `REACT_APP_WRITER_MODE=true` in my `.env`) and opened http://localhost:3000/en-US/docs/Web/CSS/:not#_flaws locally.
> fix(flaws): stop reporting absolute MDN blog links as broken

- client/src/document/organisms/sidebar/filter.scss
- client/src/document/organisms/sidebar/filter.tsx
- client/src/document/organisms/sidebar/index.scss
The sidebar filter experiment has ended (with success), but we're still requesting users to give feedback.
Remove the feedback button.
---
---
Ran `yarn && yarn dev` and opened http://localhost:3000/en-US/docs/Web/CSS locally, then clicked into the sidebar filter field.
> chore(sidebar-filter): remove feedback footer

- package.json
- yarn.lock
`@types/hast` was added in #3843 in the context of HTML-to-Markdown conversion, but we no longer need it.
Remove the dependency.
---
Ran `yarn check:tsc`.
> chore(deps-dev): remove @types/hast

- package.json
- yarn.lock
This PR adds `@babel/plugin-proposal-private-property-in-object` as a dev. dependency.
When running `yarn dev`, the following error message is shown:
```
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.
babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.
``` …
> fix(deps-dev): add @babel/plugin-proposal-private-property-in-object

- build/utils.ts
Addresses https://github.com/mdn/yari/pull/8950#issuecomment-1641335798
The blogs repo is not public so `BLOG_ROOT` environment variable has not been advertised. If the variable is not set then `yarn tool spas` command throws an error which doesn't make sense at all.
If the variable is not set then don't run ripgrep command.
Tested the code with the variable set and unset in the `.env` file. Also set the variable to unrelated dir to test match not found message.
> chore(tools): better error handling for `yarn tool spas` command

- client/src/ui/molecules/document-survey/index.scss
- client/src/ui/molecules/document-survey/index.tsx
In the document survey box, the teaser and questions aren't separated with space, and the `<details>` content isn't indented.
Adjust margins and widths to resolve these issues.
---
| --- | --- |
| <img width="790" alt="image" src="https://github.com/mdn/yari/assets/495429/1c882a00-5eea-4cab-9991-a0b19c97a43f"> | <img width="782" alt="image" src="https://github.com/mdn/yari/assets/495429/f169b122-0932-4a16-bd90-71bb313cb717"> |
| <img width="782" alt="image" src="https://github.com/mdn/yari/assets/495429/487e996d-8d29-497b-a44a-67daf175c8f6"> | <img width="782" alt="image" src="https://github.com/mdn/yari/assets/495429/8c0df8ad-a9f2-4579-9f6c-82d6584e4832"> |
---
Ran `yarn && yarn dev`, temporarily re-opened the Blog survey, and visited …
> enhance(document-survey): adjust margins and widths

- build/syntax-highlight.ts
This PR enables LaTeX syntax highlighting in Yari, which will be used in https://developer.mozilla.org/en-US/docs/Learn/MathML/First_steps/Three_famous_mathematical_formulas.
> feat(docs): add LaTeX syntax highlighting

- package.json
some versions prior to 18.16 were causing ts-node to raise an error: `RangeError: Maximum call stack size exceeded`
bump minimum engine version in `package.json`
---
I've been using node 18.16 for months locally with no problems
> chore: update minimum node version from 18.0 to 18.16

- client/src/ui/atoms/signup-link/index.tsx
- clicking "Sign up for free" button leads to a 404
- set `target="_self"` on link to force it to be a "true" `<a>` tag
- we should make this default in future, and "opt-in" to internal links in various plus features, but this is a hotfix for now
> fix(signup-link): clicking led to 404

- build/syntax-highlight.ts
Enables `nginx` syntax highlighting. This language is used in content already, generates some build errs:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin
---
`yarn && yarn dev`
> feat(prism): enable Nginx syntax highlighting

- build/build-blog.ts
- package.json
Building yari in the blog CI takes time.
Expose the `build:blog` command so we can make use of the pre-built npm package.
---
```bash
git clone yari yari-npm-test # so it's easy to clean up the js files which get generated from typescript compilation
cd yari-npm-test
yarn
export REACT_APP_WRITER_MODE=true
export REACT_APP_DISABLE_AUTH=true
export CONTENT_ROOT=testing/content/files
yarn build:prepare
npm pack
cd ../content
yarn add ../yari-npm-test/mdn-yari-2.28.4.tgz
npx yari-build-blog
```
> feat(npm): add yari-build-blog command

- client/src/ui/atoms/avatar/index.tsx
- client/src/ui/molecules/user-menu/index.tsx
often when highlighting text to copy from ai help, something like this gets prepended:
```
Avatar
9901f5c4d49546998c4138f6d7759b46
```
the avatar component was defining pretty meaningless alt text, I've removed that, and added more meaningful alt text to the user menu
---
- copied before/after
- checked the user menu button still got text in Firefox's accessibility devtools
> fix(ai-help): nonsense prepended when copying message

- client/src/telemetry/glean-context.tsx
- package.json
- yarn.lock
Updating Glean to 2.0.1 [Changelog](https://github.com/mozilla/glean.js/releases/tag/v2.0.0)
This migrates from IndexDB to LocalStorage.
Deployed to stage and checked for migrated data.
> chore(deps): upgrade to glean 2.x

- .github/workflows/prod-build.yml
- client/src/env.ts
- client/src/plus/ai-help/index.tsx
- docs/envvars.md
We already gather issue reports about AI Help answers from our users in a public repository, and now we would also like to collect internal feedback in the same way, but without mixing them with user reports.
Introduce an environment variable for the repository, and use a private repository for internal feedback on all nonprod builds.
---
Ran `yarn && yarn dev` with rumba running, opened http://localhost:3000/en-US/plus/ai-help/, clicked on "Report an issue with this answer on GitHub", and verified that it opens an issue in the private feedback repository.
> chore(ai-help): use private repo for internal feedback

- client/src/plus/ai-help/index.scss
- client/src/plus/ai-help/index.tsx
Syntax highlighting for AI-Help answers.
Code examples looked different than anywhere else.
Use prism to style code samples in AI-Help answers.
---
> feat(ai-help): use prism for syntax highlighting

- client/src/telemetry/glean-context.tsx
URL metrics did not get sent after upgrading to Glean 2.0
[`set`](https://github.com/mozilla/glean.js/blob/a4560183c9e332ef6eac0d05e93bb0bf17e9edfa/glean/src/core/metrics/types/url.ts#L106) seems to be async and should be sync.
See https://github.com/mozilla/glean.js/issues/1753
Use `setUrl` for now
---
Locally with GLEAN Debug enabled
> fix(glean): fix url metrics

- client/src/ui/organisms/article-actions/language-menu/index.tsx
https://github.com/orgs/mdn/discussions/365
The buttons in the dropdown language switcher menu, being buttons, couldn't be middle clicked to open in another tab.
Make them `<a>` tags, also remove another use of client side nav
---
- `yarn && yarn dev`
- tested on a few pages on localhost:3000
- manually looked at cookies in devtools to verify that they updated
- didn't test GA, do we want to migrate this to glean, or remove the measurement entirely?
> chore(language-menu): use proper <a> tags

- client/src/document/code/ai-explain.ts
- client/src/document/code/playground.ts
- client/src/telemetry/glean-context.tsx
- client/src/ui/organisms/placement/index.tsx
We were using a few different dataset properties to send glean pings.
Migrate to using one `data-glean`.
Also make it take priority over external links.
---
- `yarn && yarn dev`
- Breaking out from playground appears to send a well-formed ping: https://debug-ping-preview.firebaseapp.com/pings/mdn-dev/75a2dea1-428a-4af2-94ff-1e87eb793416
- Wasn't able to test ads, as I get a `geo_unsupported` error locally
- Wasn't able to test ai explain, as we've disabled that feature
> chore(glean): migrate to using data-glean everywhere

- .eslintrc.cjs
also add some jsdoc type hinting
Trying to commit locally I was getting this error:
```
Oops! Something went wrong! :(
ESLint: 8.48.0
Error: Cannot read config file: /workspace/yari/.eslintrc.cjs
Error: ENOTDIR: not a directory, lstat '/workspace/yari/.git/info/exclude'
```
I've been running yari from a git submodule as an easier way of transferring my dev environment state between devices. I'm not sure it's a setup we want to explicitly support, but it should fail more gracefully than an error message and no commit.
> fix(eslint): support running in git submodule

- client/src/telemetry/metrics.yaml
Move core metrics to `never`. Everything else we still need for next 12 months.
> chore(glean): renew metrics

- .github/dependabot.yml
We update deployer/test dependencies individually, but we don't need to update those minor/patch updates separately.
Configure grouped dependency updates for `/deployer/` and `/testing/integration` for minor/patch updates.
---
Hard to test, but once merged, we will (hopefully) see grouped Dependabot PRs for these directories.
> chore(dependabot): group pip minor/patch updates

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
- client/src/env.ts
- client/src/settings/manage.tsx
Preparing our accounts rebranding
> chore(plus): prepare account rebranding

- client/src/ui/organisms/top-navigation-main/index.scss
See: #9350
Firefox shows the following CSS warning in the DevTools when opening https://developer.mozilla.org/en-US/docs/Web/CSS/mask-type:
> Unexpected token ‘-1’ in media list.
Add the missing space between `-` and `1`.
---
TBD
> fix(client): avoid CSS warning in Firefox

- client/src/document/index.scss
Fixes #9130 
The alt text of images is not visible due to the way the background color is set
I made set the background color to `transparent` for the dark theme. This will make the alt text appear in dark mode. 
---
> fix(client): make alt text on images appear in dark mode

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
- kumascript/macros/LiveSampleLink.ejs
Fix `LiveSampleLink` macro for now and consolidate live samples domains.
`LiveSampleLink` pointing to an empty page.
Enforce fallback to prebuild samples.
---
Deploying to stage now.
> fix(macros/LiveSampleLink): add fallback to prebuilt samples

- libs/constants/index.js
Fixes https://github.com/mdn/yari/issues/9463.
fixes live sample in https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#example_using_object_urls_to_display_images
We do not allow blob urls in the playground
Add according CSP and also allow `data:`.
---
Locally running the cloud function.
> feat(playground): allow img from blob and data

- client/src/blog/post.scss
- client/src/blog/post.tsx
- client/src/document/index.scss
Move the blog ToC to the left on large screens.
---
---
Locally
> fix(blog): move toc to left on large screens

- .github/labeler.yml
We use the [actions/labeler](https://github.com/actions/labeler) action to automatically add labels to PRs based on the files they change, but the mapping of labels to file path patterns was not comprehensive.
Add more labels to the mapping.
---
Not really testable, we'll see when it's merged.
> chore(labeler): add more labels

- client/src/document/index.scss
- kumascript/src/api/util.ts
Fixes #9810.
https://github.com/mdn/yari/pull/8413 introduced a regression, making it unable to identify description terms (`<dt>`) that link to another page.
Restore the style of those links, excluding anchor links.
Also makes the hashtag of the anchor links interactive.
---
---
Ran `yarn dev` and opened http://localhost:3000/en-US/docs/Web/CSS/border#values locally.
> fix(docs): restore behavior of description term links

- client/src/ui/molecules/search/index.scss
Fixes tabbing across the search box.
When tabbing through the header reaching the search input and pressing tab again will reset the focus to the html document.
This happened because the next item would be the cancel input button. Which will be removed via display one and then we start from the the beginning.
Keep the search box expanding when the parent has focus within.
---
Locally.
> fix(a11y): fix tab order reset in the header

- client/src/document/index.scss
- fixes https://github.com/mdn/content/issues/29755
- related to https://github.com/mdn/content/pull/29698
The PR https://github.com/mdn/yari/pull/9250 caused a regression. It changed background color of all the images from `white` to `transparent`. Now all the transparent images in `mdn/content` are facing issues in dark mode: black lines, black text, and black boxes are appearing invisible.
Set page in dark mode.
Before the regression: https://web.archive.org/web/20230601124043/https://developer.mozilla.org/en-US/docs/Web/Performance/Animation_performance_and_frame_rate#the_rendering_waterfall
After the regression: https://developer.mozilla.org/en-US/docs/Web/Performance/Animation_performance_and_frame_rate#the_rendering_waterfall
Before regression:
After regression:
It is not feasible …
> fix(css): transparent images in dark mode issue

- client/src/ui-context.tsx
- client/src/ui/molecules/theme-switcher/index.tsx
- client/src/utils.ts
Fixes #7884.
(copied from the issue title)
> the color of status bar remains white even if dark mode is on. Because of `<meta name="theme-color" content="#ffffff" />`
Set "theme-color" to the background color of the page(`<body>`) on
- page load
- user changes theme
---
|Before|After|
|-|-|
|![screenshot before](https://github.com/mdn/yari/assets/59327276/a37b8d53-4d23-4c10-ac01-be6dbef6a45f)|![screenshot after](https://github.com/mdn/yari/assets/59327276/0cb22b12-edae-48d2-9690-b0263a9448e4)|
---
Tested by running `yarn dev` and
- visiting on PC
- Tried when dark mode on/off and checked that 
- the class of `<html>` is set correctly
- the "theme-color" meta tag's `content` (color)
- is correct on first visiting the site and
- changes on changing theme
- on Vivaldi browser 6.1.3035.111 …
> feat(theme): sync body background-color with theme-color meta tag

- package.json
- yarn.lock
We no longer use `use-debounce`.
Remove this dependency.
---
Tests are passing, and a [full-text search for `use-debounce`](https://github.com/search?q=repo%3Amdn%2Fyari%20use-debounce&type=code) did not yield any results (apart from `package.json` and `yarn.lock`).
> chore(deps-dev): remove use-debounce

- yarn.lock
Bumps the indirect dependency `fast-xml-parser`.
See checks.
> chore(deps): bump fast-xml-parser from 4.1.3 to 4.3.4

- yarn.lock
Bumps indirect dependencies of `react-dev-utils`, especially `recursive-readdir` and `minimatch`.
See checks.
> chore(deps-dev): bump dependencies of react-dev-utils

- package.json
- yarn.lock
Bumps the indirect dependency `http-cache-semantics` by defining a resolution `>=4.1.1`, since `imagemin-{gifsicle,mozjpeg,pngquant}` depend on `http-cache-semantics@3.8.1` via `cacheable-request@2.1.4`.
_Note_: The only breaking change of `http-cache-semantics` v4 is the drop of Node.js 4 support, see: https://github.com/kornelski/http-cache-semantics/compare/v3.8.1...v4.0.0 
See checks.
> chore(deps): resolve http-cache-semantics to >=4.1.1

- package.json
- yarn.lock
Bumps the indirect dependency `semver-regex` by defining a resolution `^3.1.4`, since `imagemin-{gifsicle,mozjpeg,pngquant}` depend on `semver-regex@^2.0.0` via `find-versions@3.2.0`.
_Note_: The only breaking change in v3 is the drop of Node.js 8 support: https://github.com/sindresorhus/semver-regex/releases/tag/v3.0.0
However, we cannot upgrade to v4, because [it is pure ESM](https://github.com/sindresorhus/semver-regex/releases/tag/v4.0.0).
See checks.
> chore(deps): resolve semver-regex to ^3.1.4

- yarn.lock
Bumps `is-svg` v4 (required by `imagemin-svgo`) from 4.3.2 to 4.4.0.
_Note_: This, in turn, removes a dependency on `fast-xml-parser@^3.19.0`.
See checks.
> chore(deps): bump is-svg v4 from 4.3.2 to 4.4.0

- yarn.lock
Bumps `semver` v5 (required by `bin-version`, `bin-version-check`, `imagemin-gifsicle`, `read-pkg` and `semver-truncate`) from 5.7.1 to 5.7.2.
_Note_: I had to manually update the `yarn.lock` file as `yarn upgrade semver` etc wouldn't work.
See checks.
> chore(deps): bump semver v5 from 5.7.1 to 5.7.2

- package.json
Related to: https://github.com/mdn/yari/issues/10653#issuecomment-2003374829
`yarn start` fails on a fresh checkout, with the following error:
```
error: ENOENT: no such file or directory, open '/path/to/yari/popularities.json'
```
Run `yarn tool popularities` as part of `yarn start`, if the `popularities.json` doesn't exist.
---
Ran `yarn start` on a fresh checkout, and I was able open http://localhost:3000/ afterwards.
> fix(cli): add popularities to "yarn start" script

- package.json
We're using `cross-env` for most scripts that set environment variables, except for `tool`.
Use `cross-env` for `tool` as well.
---
Didn't test, but this just aligns the script with other scripts.
> fix(scripts): use cross-env for tool

- package.json
- yarn.lock
Fixes #11619.
The issue occurred where the type of the `js-yaml` package used for parsing YAML in `front-matter_utils.js` and `document.ts` was not being inferred.
`@types/js-yaml` package will be added to devdependencies list.
---
---
Tested on my local machine, with node 18.
> chore(deps-dev): add @types/js-yaml 4.0.9

- yarn.lock
We're using some outdated versions of indirect dependencies.
Ran `yarn upgrade`, which updates these indirect dependencies.
---
Relying on semantic versioning of all involved dependencies, and on our tests catching issues.
> chore(deps): run yarn upgrade

- package.json
- yarn.lock
Supersedes https://github.com/mdn/yari/pull/11997.
We no longer use `bfj` since 5e6edb0728bdc80ea7eacee2dc7df7e17671b05a.
Remove the dependency.
n/a
> chore(deps-dev): remove bfj

- package.json
- yarn.lock
The `lint-staged` depedency is outdated and depends on a vulnerable version of `micromatch`.
Bump it to the latest major version.
Note: The breaking changes are the bump to Node.js 16 (lint-staged v14) and Node.js 18 (lint-staged v16) respectively.
---
Committing worked, so `lint-staged` seems to do its job.
> chore(deps-dev): bump lint-staged from 13.2.3 to 15.2.10

- package.json
Correct the filename of the `ssr` cli, see: https://github.com/mdn/yari/blob/main/build/ssr-cli.ts
The wrong path prevented `yarn` from creating the symbol-link `yari-render-html` in `node_modules/.bin`
Correct the file path.
No test has been done to this PR. It's a simple fix.
> fix(release): correct the filename of the `ssr` cli

- package.json
- yarn.lock
Noticed in https://github.com/mdn/yari/pull/12261.
We depend on `react-is`, although we don't use it.
Remove the dependency.
---
Searched for `react-is` and `ReactIs`.
> chore(deps-dev): remove react-is

- package.json
- yarn.lock
Dependabot didn't pick up the BCD v6 release.
Bump BCD manually to v6.
---
Relying mainly on `yarn check:tsc`, which still passes.
Also ran `yarn dev` and checked http://localhost:3000/en-US/docs/Web/API/Window.
> chore(deps): bump @mdn/browser-compat-data from 5.7.6 to 6.0.0

- package.json
- yarn.lock
When updating `@mdn/yari` in mdn/content, Dependabot may choose a newer version of `@mdn/rari`, which hasn't been tested with yari yet.
Migrate from a version range to an exact version.
_Note_: Dependabot should still update the dependency.
---
Trivial change, didn't test.
> enhance(deps): require exact rari version

- package.json
- yarn.lock
Our `@types/node` version doesn't match our Node version.
Bump `@types/node` from v18 to 20.
---
Trivial dependency change, tests will tell.
> chore(deps-dev): bump @types/node from 18.19.115 to 20.19.4
