- Makefile
- README.md
- bin/yarn-audit-all.sh
- client/package.json
- client/yarn.lock
- server/package.json
- server/yarn.lock
> yarn audit all

- client/src/App.js
- client/src/mdn.scss
As suggested in https://github.com/peterbe/mdn2/pull/10#discussion_r290932900.
> Remove superflous div

- client/src/App.js
Fixes #29
PS. We need to fix our Prettier tooling because a lot of files weren't prettier and my editor fixed it. Sorry.
> Locale redirects are busted

- README.md
- cli/index.js
- cli/package.json
- cli/yarn.lock
- client/package.json
- client/src/app.js
- client/src/app.test.js
- client/src/document.js
- client/src/homepage.js
- client/src/index.js
- client/yarn.lock
> @reach/router instead of react-router

- cli/package.json
- cli/render.js
- cli/yarn.lock
> use cheerio in ssr rendering

- Makefile
- cli/index.js
- cli/package.json
- cli/yarn.lock
> cli needs to be able to read N directories

- Makefile
- README.md
> makefile with $STUMPTOWN_CONTENT_ROOT

- client/src/document.js
What do you think @joedarc
I got this idea from your BCD branch. This feels a lot neater.
> use React.createElement to get variable header tags

- cli/index.js
- client/src/document.js
- client/src/ingredients/attributes.js
- client/src/ingredients/examples.js
- client/src/ingredients/interactive-example.js
Fixes #65
I thought this would be weirder/harder but I'm quite pleased with how it worked out. 
One thing I like is that the various "ingredient components" got a little simpler now that they only get the props they need instead of a whole document. 
I've only tested it with the HTML Element reference pages. Haven't even started trying it on guide docs which are now in stumptown-content. One thing at a time I suppose.
> Render list of sections

- client/package.json
- client/src/search.test.js
- client/src/setupTests.js
- client/yarn.lock
> Initial Jest tests for Search Component

- client/src/document.js
- client/src/ingredients/interactive-example.js
GitHub is cryptic when it comes to displaying submodule updates. 
But https://github.com/mdn/stumptown-content/commit/d8ec3b03626711fefd0d7e941b9881345a17894c is currently the latest and greatest of `master` on `stumptown-content`.
> upgrade to stumptown-content d8ec3b0362

- client/src/document.js
- client/src/index.js
- client/src/ingredients/browser-compatibility-table/index.js
> Refactored the variable name 'document'

- README.md
- package.json
> Specify minimum node version

- cli/index.js
- cli/render.js
- client/src/document.js
> cli generated index.html files had no HTML in them

- cli/index.js
This simplifies things. I noticed that there isn't a single `mdn_url` that doesn't start with `/` and now the renderer has no intention of messing with that. If that's what it *was* called on MDN, we should totally respect that in the renderer or else migration would be hard.
> simplify how we deal with 'mdn_url'

- .travis.yml
- package.json
- scripts/end-to-end-test.js
Part of #146
The intention is that this file will be a place where we can put in various simple sanity checks. 
It mustn't get too crowded in there but the before this we just ran `yarn deployment-build` and simply running it makes the CI test that it doesn't exit with non-zero.
> integration test should verify full HTML generated

- client/src/document.js
- client/src/ingredients/prose.js
As mentioned in https://github.com/mdn/stumptown-renderer/pull/172#issuecomment-538010513, I'm moving Prose and ProseWithHeading into ingredients folder
> Move Prose and ProseWithHeading into ingredients

- .prettierignore
- client/public/index.html
- client/public/manifest.json
- client/src/ingredients/browser-compatibility-table/bcd.scss
- client/src/mdn.scss
- package.json
By whitelisting them in the .prettierignore
Fixes #170
And I run prettier in a separate commit
> Make prettier work in css/scss/html files

- client/src/ingredients/browser-compatibility-table/rows.js
Fixes #181
Proof that it worked:
> BCD renderer should handle omitted mdn_url

- cli/syntax-highlighter.js
- client/src/document.js
- client/src/ingredients/browser-compatibility-table/index.js
- client/src/ingredients/examples.js
- package.json
This'll only make sense once https://github.com/mdn/stumptown-content/pull/178 is merged and once it's merged the git submodule needs to upgrade.
> support multiple bcd tables and examples

- client/src/document.js
- client/src/ingredients/specifications.js
Next task item in https://github.com/mdn/stumptown-content/issues/126
Fixes https://github.com/mdn/stumptown-renderer/issues/191
This is my first PR here and my first attempt to do anything with React, so everything might be wrong :-)
> Add rendering for specification section

- client/package.json
Reverts mdn/stumptown-renderer#199
> Revert "Bump node-sass from 4.12.0 to 4.13.0 in /client"

- client/src/ingredients/browser-compatibility-table/bcd.scss
- client/src/ingredients/browser-compatibility-table/index.js
- client/src/ingredients/browser-compatibility-table/utils/browser-name.js
> Get BCD category from query

- cli/index.js
- cli/package.json
- cli/syntax-highlighter.js
- client/src/document.js
- yarn.lock
This code was originally meant for the Project Milton prototype in Nov 2019. The core gist is that it's able to cope with .json files that might not have a `related_content` but instead have a `sidebar_html` instead. 
The rest is arguably fluffy noise just to make it possible to use this in Project Milton. However, I quite like the new progress bar which, although possibly buggy, is better than what we have today.
> sidebar html

- client/src/homepage.js
I keep having to figure out what these were when testing. Just making it easier to get this for now.
> more sample links from home page

- cli/index.js
Fixes #236
There were actually two problems:
1. the `buildHtmlAndJson()` function expects a parameter called `filePath` but it wasn't given that. Destructuring can be buggy in JS!
2. The `buildHtmlAndJson()` [was changed](https://github.com/mdn/stumptown-renderer/pull/183/files) to only return `null` or `true` to avoid out-of-memory when you run the cli for tens of thousands of files. 
To test:
1. Check the output of `yarn deployment-build`
2. Start `yarn start` and edit some `stumptown/content/**/*.md` file and make sure you get the right output in the terminal and that the thin headers on the web app displays the right information. E.g.
> fix watcher in cli

- client/src/document.js
- client/src/mdn.scss
Based on styles applied by @Gregoor at https://github.com/mdn/kuma/pull/6189 :wink: 
Fixes #230
Tested on both client and server
> Highlight current page in the side bar

- content/index.js
- content/scripts/build.js
- content/scripts/importer.js
- content/scripts/utils.js
> avoid dupes in importer

- content/scripts/importer.js
> Some redirects lack locale in the destination

- content/scripts/importer.js
* add tags
* use "translation_of" rather than "translationof"
* ~~remove use of "rendered_html"~~
* remove query for translations
> more importer adjustments

- content/index.js
- content/scripts/importer.js
Fixes #383
As mentioned in Slack `7,644 redirects that redirected to an archived URL.`
> Redirects whose destination should be archived

- content/scripts/build.js
This PR extracts some changes from https://github.com/mdn/stumptown-renderer/pull/402 that are really separate from the asynchronicity/KS changes needed for KS rendering. The changes are simple changes intended for readability, specifically getting rid of some levels of nesting.
> adding some iterators and changes for readability

- content/scripts/importer.js
> exclude translations of docs with excluded prefixes

- content/scripts/build.js
Fixes #446 
It all started so innocently. I noticed that we still did `doc.last_modified = metadata.modified;` but `metadata.modified` is no longer a thing. (at the moment we're relying on `wikihistory.json` instead but we'll need to supplement that with git logs)
Then I noticed, that when you run a build from the `server/index.js` the `ensureAllPopularities` hasn't been run. Well, then I realized it's much better to put it ALL in the `this.allTitles`. Which we actually already do. So instead of having to remember to first run `this.ensureAllPopularites` **and** `this.ensureAllTitles`, how about `ensureAllTitles()` can own it all under one roof. 
So that's what it does this:
```javascript
// This is what ensureAllTitles does in principle
ensureAllTitles() {
const allPopularities = …
```
> get some stuff from allTitles inside build

- server/index.js
Fixes #460
Here's how to test it; first run `yarn start` which cleans out anything in `client/build/`. And it starts the server on `localhost:5000`
1. `curl -I http://localhost:5000/en-US/docs/HTML/Global_attributes/index.json` should 301 redirect to `http://localhost:5000/en-US/docs/Web/HTML/Global_attributes/index.json` (note the extra `/Web`) because `content/files/en-us/_redirects.txt
2. `curl -I http://localhost:5000/en-US/docs/HTML/Global_attributes` should 301 redirect to `curl -I http://localhost:5000/en-US/docs/Web/HTML/Global_attributes`
3. `curl -I http://localhost:5000/en-US/docs/Web/HTML/Global_attributes/index.json` should build the document and respond with the JSON file. 
4. Stop the server by killing the `yarn start` and start it up again`
5. `curl -I …
> Fix dev server redirecting

- client/src/document/index.js
**tl;dr; this is blocking me from going to react-router v6**
I have a 99.9% ready branch to switch from `@reach/router` to `react-router@next`. 
The 0.1% remaining turns out to be a biggie. At the moment, when you first mount `<Document/>` it gets the routing props automatically thanks to `@reach/router`. And then it uses `componentDidUpdate` (when the location changes) to figure out it's time to trigger `this.fetchDocument()` again. Well, in react-router v6 you don't get any probs passed on from the routing. To find out the current pushState URL in react-router v6 you do something like this:
```javascript
import { useParams } from "react-router-dom";
function Document() {
const { slug } = useParams();
useEffect(() => {
// Slug has changed, time to XHR!
}, [slug])
...
```
Well, you can't …
> Document hook

- content/scripts/build.js
- server/index.js
This PR adds `allRedirects` to the builder. It was extracted from the KS rendering work.
> add allRedirects

- client/src/document/index.js
> ssr rendering and fetching the json regression

- content/scripts/build.js
- ssr/index.js
> Use a Map for this.allTitles

- kumascript/macros/InterfaceData.json
- kumascript/macros/LearnSidebar.ejs
- kumascript/macros/SpecData.json
- kumascript/macros/bug.ejs
Let's update the Kumascript macros with the most-recent changes copied from https://github.com/mdn/kumascript. By the way, @peterbe, was we suspected, this was really easy.
> add updates from the in-use kumascript/macros

- client/src/document/ingredients/browser-compatibility-table/error-boundary.test.js
> control error boundary console error

- client/search-experimentation.js
- client/src/search.js
> Searching for 'arra' doesn't find "Array..."

- content/package.json
- yarn.lock
Remove `html-differ` npm package from `content` workspace.
> remove html-differ npm package from content

- content/scripts/build.js
Fixes #547
Turned out to be a lot simpler than I thought.
> ensureAllTitles will append duplidate `translations`

- .travis.yml
- scripts/ci-kumascript.sh
> add kumascript tests to CI

- content/scripts/build.js
- content/scripts/constants.js
- content/scripts/sources.js
- server/index.js
> re-use 'source' when rendering macros

- docs/envvars.md
Part of #575
It's a start. 
It doesn't close the issue because there are probably things I've forgotten. 
Also, the `BUILD_FLAWS` one is deliberately omitted because it's due to change pretty soon.
> Document all important env vars

- client/src/document/index.tsx
- client/src/flaws/index.tsx
> scroll flaws into view on mount when hash is present

- content/scripts/document.js
- content/scripts/importer.js
> Extract content document creation

- client/src/flaws/index.tsx
Fixes #651
Now...
* http://localhost:3000/en-US/_flaws?flaws=macros 
* http://localhost:3000/en-US/_flaws?mdn_url=things&flaws=broken_links&flaws=macros
* http://localhost:3000/en-US/_flaws
...all work as expected.
> Warning about "flaws" keyword in filters of Flaws dashboard

- client/src/flaws/index.scss
- client/src/flaws/index.tsx
- server/index.js
No bug. This was an experiment that started when I needed to help myself review the [live samples PR](https://github.com/mdn/yari/pull/592) and I thought it'd be worth keeping. 
It doesn't have to be perfect but it'd be nice if it worked and isn' too horrible on your TypeScript eyes.
> ability to search flaws

- client/src/document/edit.tsx
@peterbe just tagging you here, so that you see it. This basically reverts something I've reverted, where you were already doing the right thing, and my misunderstanding lead me to revert that.
Fortunately the author of the useDebouncedCallback lib helped me get a better understanding:
https://github.com/xnimorz/use-debounce/issues/53
Will just merge once green.
> Add parameters back to putDocument

- .github/workflows/functional.yml
We can and will optimize this later but I just wanted to get started with this. 
The idea is that we have a GHA (GitHub Actions) workflow for all functional tests which is the word I use that means unit tests, functional tests, headless browser testing, etc. What it does not mean is actually building real content.
> basic functional GitHub Action

- .github/workflows/testing.yml
- content/scripts/constants.js
- docs/envvars.md
- server/index.js
- server/package.json
- testing/README.md
- testing/jest-puppeteer.config.js
- testing/package.json
- testing/scripts/functional-test.sh
- testing/tests/headless.test.js
- yarn.lock
Fixes #511
~~This is NOT ready until I've documented all the useful tips and tricks for how to do development on the tests.~~
> functional tests with jest-puppeteer

- content/scripts/build.js
- content/scripts/document-extractor.js
- content/scripts/importer.js
I couldn't figure out how to set up `eslint` for node but I hacked on something and ran it. A problem is that we're using yarn workspaces. Yada yada. 
Anyway I got a bunch of errors. A lot of them I know we can ignore but a bunch were good tips. So I just did those.
> eslint content code

- content/package.json
> got is not needed in content

- content/scripts/build.js
- content/scripts/progress-bar.js
- content/scripts/utils.js
> Record max head memory

- content/package.json
- content/scripts/build.js
- yarn.lock
I could have just replaced the guts of `function ppMilliseconds` but I realized I didn't like the name.
> use ms to format milliseconds

- testing/README.md
The mistake I made when I started playing your branch was that I opened the README and jumped straight to the code snippets which I pasted in. That's why I missed running the bash script. Hopefully this helps. 
I would be tempted to say something like "To run all the functional tests, open .github/workflows/testing.yml and do what it does." But that's not quite good enough :)
> note about getting started with local dev on test suite

- client/public/contribute.json
Fixes #732
[It validates](https://www.contributejson.org/)
> /contribute.json

- content/files/en-us/glossary/jpeg 2000/index.html
- content/files/en-us/glossary/jpeg 2000/wikihistory.json
- content/files/en-us/glossary/png/index.html
- content/files/en-us/web/html/element/video/index.html
Just wanted to try out the PR builds now that it's in `master`.
> undo sample changes to content

- .github/workflows/pr-build.yml
> don't even bother with cache if no content changes

- server/document.js
Fixes #795 
I basically just followed your suggestion Peter, because it made sense to me and it seems to do the trick.
> reuse content's DEFAULT_BUILD_ROOT

- content/scripts/build.js
- kumascript/index.js
- kumascript/src/errors.js
- kumascript/src/live-sample.js
- kumascript/src/render.js
- testing/content/files/en-us/learn/css/css_layout/introduction/grid/stuff/index.html
- testing/tests/index.test.js
Fixes #810 
This PR does more than fix #810 (sorry!). It tests for the fix, and also creates full-fledged source-code flaws with line numbers and the source context for cases (like a prerequisite URI that doesn't exist) that prior were only creating Javascript `Error` objects.
> kumascript rendering fix and improvements

- client/src/mdn.scss
Meant to address that earlier but just now noticed it again. The layout on master is a bit overlappy for me. Also there's a scrollbar for sidebars that don't need one. I just made it extend to whatever height it needs.
Just a small cosmetic thing ✨
> Fix overlapping sidebar

- kumascript/src/api/web.js
- kumascript/src/render.js
- kumascript/tests/renderer.test.js
- testing/content/files/en-us/web/bar/index.html
- testing/tests/index.test.js
> fix result memoization for macros

- client/src/footer/index.tsx
Fixes #948
You can't argue with the results :)
> SVG icons in footer has wrong color

- client/package.json
- client/src/document/index.tsx
- content/package.json
- yarn.lock
Fixes #927
Pretty sure this is solving all our worldly problems, but it's late and perhaps my brain is a bit fried.
> back button and document state working

- .github/workflows/production-build.yml
- README.md
What I'm still trying to figure out is how to manually trigger a build on these cron-job-based workflows. This can/will be super useful if you have an urgent fix in `master` and you can't wait till the next time-tick.
> production build updates

- build/cli.js
- build/flaws.js
- build/index.js
- client/src/document/forms/form.tsx
- content/document.js
- content/index.js
- content/utils.js
- docs/conventions.md
- kumascript/index.js
- kumascript/tests/index.test.js
- server/document.js
> Renames & Conventions

- client/src/document/index.tsx
> cope with 0-length TOCs

- client/public/index.html
- ssr/render.js
- testing/tests/index.test.js
> Canonical URL and robots meta tags

- build/index.js
Fixes #1028
@Gregoor Now it makes perfect sense why it was slow on my machine and not yours. I had checked out your branch with `git checkout Gregoor/drop-workspaces` and that puts me into a detached HEAD. I.e. *not* in a branch. 
Either way, I think all of these changes are better and safer.
> optimize getGitHubURL

- client/src/document/index.scss
- client/src/document/ingredients/prose.tsx
Fixes #1004
Just like docs.github.com does it.
> Make headlines permalink-able

- client/src/index.tsx
Fixes #45
Before:
After:
It's the same useful hack that we're currently using in Kuma and that I use on https://songsear.ch
> Google translate needs to work

- build/check-images.js
- testing/content/files/en-us/web/images/index.html
- testing/tests/index.test.js
> fix fixable image reference flaws

- kumascript/src/api/util.js
Part of #1189
Now, with this patch you get:
It other words, it solves all the world hunger.
> Box-shadow generator

- content/files/en-us/web/api/document/querycommandstate/index.html
- content/files/en-us/web/api/geolocationcoordinates/longitude/index.html
- content/files/en-us/web/api/htmlelement/change_event/index.html
- content/files/en-us/web/api/window/pageshow_event/index.html
- content/files/en-us/web/css/@media/prefers-contrast/index.html
- content/files/en-us/web/css/@media/prefers-reduced-data/index.html
- content/files/en-us/web/css/@media/prefers-reduced-transparency/index.html
- content/files/en-us/web/css/_doublecolon_-webkit-meter-optimum-value/index.html
- content/files/en-us/web/css/appearance/index.html
- content/files/en-us/web/css/css_grid_layout/layout_using_named_grid_lines/index.html
- content/files/en-us/web/css/css_grid_layout/relationship_of_grid_layout/index.html
- content/files/en-us/web/html/element/optgroup/index.html
- content/files/en-us/web/html/element/rtc/index.html
- content/files/en-us/web/html/element/s/index.html
These changes have already been made in the Wiki, but I'm updating the docs in Yari just so we no longer see these live-sample errors until we update the Yari content from the Wiki content.
> temp fix live-samples in docs

- .github/workflows/auto-merge.yml
> auto-merge minor Dependabot PRs

- import/README.md
- import/cli.js
- import/popularities.js
> A fresh popularities.json export

- .stylelintignore
- .stylelintrc
- client/src/app.tsx
- client/src/document/index.tsx
- client/src/ui/molecules/toc.scss
- client/src/ui/molecules/toc.tsx
Add styling for the new table of contents aka "jump to section"
@peterbe Do not worry too much about testing this in a browser. Something is seriously 💩 up with the responsiveness of the site/page in general so, if the code looks good, let's merge so I can take a step back and see what is going on there.
fix #1142
> add toc styling

- build/cli.js
If you patiently wait, eventually it will say (on my macbook):
```
Built 11,135 in 8.7 minutes, at a rate of 21.3 documents per second.
Peak heap memory usage: 2.33 GB
✨  Done in 523.54s.
```
That's pretty intense by the way!
> record peak heap memory usage

- .github/workflows/production-build.yml
> Debug production build workflow

- client/src/app.tsx
- client/src/banners/banner.scss
- client/src/document/index.tsx
- client/src/ui/atoms/logo.scss
- client/src/ui/molecules/breadcrumbs.scss
- client/src/ui/molecules/interactive-example.scss
- client/src/ui/molecules/interactive-example.tsx
- client/src/ui/molecules/main-menu.scss
- client/src/ui/molecules/search-header.scss
- client/src/ui/molecules/titlebar.tsx
- client/src/ui/molecules/toc.scss
- client/src/ui/organisms/footer.scss
- client/src/ui/organisms/header.scss
- package.json
- yarn.lock
Add code for code examples and interactive examples.
This also addresses the problems with responsiveness.
fix #1260
fix #1176
> code examples and interactive examples with fiori

- server/index.js
> Serving images through server and relative URLs

- import/import.js
> Dumper should dump _wikihistory.json for archived and translated content

- content/document.js
- import/import.js
> translated content should dump the rendered HTML

- .gitignore
Forgot to clean-up `.gitignore`.
> remove cruft from .gitignore

- deployer/src/deployer/upload.py
Not changing any functionality, just reorganizing some of the display code.
> better organization

- README.md
Fix README to reflect latest content license.
> update README with content license info

- kumascript/macros/Index.ejs
Fixes #1338
Definitely solves the problem, but it's a rushed job so would really appreciate your review.
> Unable to build /web/api due to OOM

- .stylelintrc.json
- client/src/stories/atoms/forms.stories.js
- package.json
- yarn.lock
Documents our form styles in Storybook aka Fiori :)
fix #1121
@peterbe All this does is document our form styles in Storybook so, not going to ask for a review. Please feel free to fire up Storybook locally and let me know if you disagree with any of the style choices or if I missed something. Thanks!
> docs: forms

- build/cli.js
- build/index.js
- client/src/document/index.tsx
- content/document.js
- server/index.js
Fixes #1329
Scroll to the bottom and you'll see this:
> contributors.txt for each document

- kumascript/src/info.js
Fixes #1347
See full explanation here: https://github.com/mdn/yari/pull/1349#issuecomment-701100010
> don't follow redirects when listing sub-pages

- import/import.js
Fixes #1355
Fixes #1348
With this, I managed to make this change: https://github.com/mdn/content/commit/67ce17d8cdb233e369246a058e65a44a4d23bb58 (ignore everything except the new _redirects.txt)
Now every line in the `_redirects.txt` is URL encoded both in the "from" and in the "to" (before it was only in the "to")
It also discards about 30 redirects (of nearly 20k) whose slug was either weird or when post-processed ends up being "from === to".
> From-URLs in dumper redirects should be escaped

- client/.storybook/preview.scss
- client/src/stories/components/color-item.jsx
- client/src/stories/docs/color-palette.stories.js
- package.json
- yarn.lock
Our color palette is now defined and documented. In both Figma and Storybook you can also see the appropriate foreground and background color combinations to use to ensure we meet at least an AA color contrast ratio.
fix #1171
@peterbe This is all documentation i.e. Storybook so going to merge. Please do have a look and let me know if anything is unclear or if you would recommend changes or improvements. Thank you.
https://www.figma.com/file/YYVJ8uqG8UFBBvQhdI7fxR/MDN-Web-Docs?node-id=1%3A7
> color palette

- client/src/stories/atoms/tables.stories.js
- package.json
- yarn.lock
The initial set of table styles. There may be some that I have missed, will work with Chris to find these. This is a good first pass and covers most use cases.
fix #1172
@peterbe This is again all minimalist and design system so, merging.
> table styles

- .github/workflows/production-build.yml
This builds all of github.com/mdn/archived-content if you manually trigger it in Actions.
> build archived content in production-build

- client/src/stories/atoms/typography.stories.js
- client/src/stories/docs/color-palette.stories.js
- package.json
- yarn.lock
Update and document typography style
fix #1170
@peterbe This is again a minimalist and Storybook only change. Merging 🌮
> typography

- .github/workflows/production-build.yml
Fixes #1370 
It's hard to test this before landing it.
> ability to build any branch and prefix in production build

- import/constants.js
> More weird prefixes to discard in the importer

- .github/workflows/testing.yml
- deployer/src/deployer/constants.py
> Some basic CI for the deployer

- .github/workflows/developing.yml
- .github/workflows/testing.yml
- testing/tests/developing.test.js
> Run and open the development server in CI

- kumascript/src/live-sample.js
> drop token.args line

- testing/.env
> fix name of live-samples-url env var

- build/flaws.js
> make sure the <code>'s parent really is a <pre>

- deployer/aws-lambda/content-origin-request/index.js
Fixes #1474 
This code is already running in the Yari `stage` environment: https://yari.stage.mdn.mozit.cloud.
> lambda only adjusts for custom s3 origins

- client/.storybook/preview.scss
- client/src/document/index.scss
- client/src/document/index.tsx
- client/src/document/organisms/sidebar/index.scss
- client/src/stories/atoms/tables.stories.js
- client/src/stories/grid/reference-page-grid.stories.mdx
- client/src/stories/mocks/breadcrumbs.js
- client/src/stories/molecules/breadcrumb.stories.js
- client/src/stories/organisms/page-header.stories.js
- client/src/ui/molecules/language-menu/index.scss
- client/src/ui/molecules/main-menu/index.scss
- client/src/ui/molecules/titlebar/index.scss
- client/src/ui/molecules/toc/index.scss
- client/src/ui/organisms/footer/index.scss
- package.json
- yarn.lock
Ensure that content always aligns properly at all viewports.
For now, until we have come to a conclusion on https://github.com/mdn/yari/issues/1486, test this without translated content so that the language switcher does not show up in the UI.
fix #1441
> correct content alignment on all viewports

- .github/workflows/production-build.yml
- deployer/README.md
- deployer/src/deployer/constants.py
- deployer/src/deployer/upload.py
> Make deployer less noisy about successful uploads by default

- kumascript/src/api/wiki.js
> support depth for wiki.tree

- package.json
let's see if this let's us use yari in the content repo again
> bundle internal libs

- client/src/stories/docs/browser-support-matrix.stories.mdx
Add document to Storybook detailing our commitment to browser support and out support matrix.
fix #1120
> docs: document browser support

- deployer/src/deployer/upload.py
Fixes #1527
Tested when using my personal AWS account.
> don't cache-control _whatsdeployed urls

- client/src/ui/molecules/breadcrumbs/index.scss
- client/src/ui/molecules/breadcrumbs/index.tsx
~This was mentioned in my PR review but I guess we decided to break it out to a separate follow-up or something. Either way, I suspect it's faster to just do it than the time it takes to find the relevant issue.~
Fixes #1589
> refactor Breadcumb DRY

- client/src/document/index.tsx
Part of #1587
I really like this effect. It doesn't necessarily solve it for full a11y compliance but I'm confident it's better for everyone and anyone because now your eyes see that the browser tab is reacting immediately to your click.
> update document.title that document is loading

- content/document.js
> fix tool move for top level slugs

- build/flaws.js
- fix to stop fixing flaws from crashing
> warn on 404 for an extenal image

- client/src/app.tsx
- client/src/document/forms/create.scss
- client/src/document/forms/create.tsx
- client/src/document/forms/edit.scss
- client/src/document/forms/edit.tsx
- client/src/document/forms/form.tsx
- client/src/document/forms/manage.scss
- client/src/document/forms/manage.tsx
- client/src/document/index.test.tsx
- client/src/document/index.tsx
- client/src/document/toolbar/edit-actions.scss
- client/src/document/toolbar/edit-actions.tsx
- client/src/document/toolbar/index.scss
- client/src/ui/molecules/titlebar/index.tsx
- server/document.js
> hacky improvment for the toolbar

- package.json
- yarn.lock
Cuz we get it from `@mdn/minimalist` now.
> remove typeface-zilla-slab dependency

- .github/workflows/developing.yml
Trying to figure out why CI is failing on "Developing"
> why is CI breaking

- content/document.js
- import/import.js
@escattone This is what I used to create https://github.com/mdn/content/pull/94
> import and show diff when not using startClean

- client/src/homepage/index.tsx
- client/src/search.tsx
- client/src/ui/molecules/search/index.tsx
- client/src/ui/organisms/header/index.tsx
> hide main menu after picked search result

- client/src/app.tsx
> Refactor layout definitions on the <App>

- client/src/app.tsx
- client/src/document/index.tsx
- client/src/ui/molecules/a11y-nav/index.scss
- client/src/ui/molecules/a11y-nav/index.tsx
- client/src/ui/organisms/header/index.scss
Add a11y nav with skip to content and skip to search links
fix #1513
> fix: add a11y nav

- import/import.js
> make sure archived content has the new notecard classes

- import/import.js
> Importer replaces an empty string with an empty string

- kumascript/macros/PreviousNext.ejs
Part of #1730
This is not the whole solution. Just makes it look a bit better.
> PreviousNext macro and button class

- import/import.js
> inject class=button on div.prevnext a

- content/document.js
fixes #1709
Nasty to debug. We mutated a memoized object.
> do not mutate the doc.url

- deployer/src/deployer/upload.py
This is another little thing that came up while testing.
> add charset when appropriate

- .gitignore
- client/.storybook/main.js
- client/src/document/index.scss
- client/src/stories/atoms/button.stories.js
- client/src/stories/atoms/forms.stories.js
- client/src/stories/atoms/links.stories.js
- client/src/stories/atoms/logo.stories.js
- client/src/stories/atoms/tables.stories.js
- client/src/stories/atoms/typography.stories.js
- client/src/stories/docs/color-palette.stories.js
- client/src/stories/molecules/auth.stories.js
- client/src/stories/molecules/breadcrumb.stories.js
- client/src/stories/molecules/dropdown.stories.js
- client/src/stories/molecules/language-menu.stories.js
- client/src/stories/molecules/titlebar.stories.js
- client/src/stories/organisms/footer.stories.js
- client/src/stories/organisms/header.stories.js
- client/src/stories/organisms/main-menu.stories.js
- client/src/stories/organisms/page-header.stories.js
- client/src/stories/organisms/sidebar.stories.js
- package.json
Clean up and fix article-specific link styles
fix #1173
> fix: link styles

- client/src/document/index.scss
- client/tsconfig.json
Move `pre` element styling to minimalist
> NOTE: The `tsconfig` change was made by react-scripts
```
The following changes are being made to your tsconfig.json file:
- compilerOptions.noFallthroughCasesInSwitch to be suggested value: true (this can be changed)
```
> remove pre styling

- .gitignore
Based on https://github.com/mdn/yari/pull/1848/files#r532633121
> remove tabnine ignore file

- deployer/aws-lambda/content-origin-request/index.js
Fixes #1891 
This fix is already "live" on stage (https://developer.allizom.org) for testing purposes, and fixed a large number of integration tests (PR coming soon that adds the integration tests to Yari).
> URI encode the redirect location

- client/src/document/index.tsx
> No archived banner for translated content

- client/src/ui/organisms/footer/index.scss
> Fix multiple CSS issues in footer

- client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
> Let's not use <Link> in the BCD table

- ssr/render.js
> analytics.js isn't loaded async

- testing/integration/README.md
- testing/integration/conftest.py
- testing/integration/headless/__init__.py
- testing/integration/headless/map_301.py
- testing/integration/headless/test_cdn.py
- testing/integration/headless/test_endpoints.py
- testing/integration/headless/test_redirects.py
- testing/integration/headless/test_robots.py
- testing/integration/poetry.lock
- testing/integration/pyproject.toml
- testing/integration/utils/urls.py
I added these integration tests (pulled over from Kuma and substantially modifed) to help me test my AWS work, so this is part pf #1107. They have been really helpful in discovering some bugs in our AWS CloudFront configuration and Lambda@Edge origin-request handler (for example, PR's #1892, #1894, and #1765).
Here's the latest run:
```sh
rjohnson-44864:integration rjohnson$ poetry run pytest --base-url https://developer.allizom.org
The currently activated Python version 2.7.16 is not supported by the project (^3.7).
Trying to find and use a compatible version.
Using python3 (3.8.0)
============================================ test session starts =============================================
platform darwin -- Python 3.8.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
baseurl: …
```
> initial set of yari integration tests

- package.json
- yarn.lock
> Revert "build(deps-dev): bump husky from 4.3.4 to 5.0.4"

- .eslintrc.js
- package.json
- yarn.lock
> package.json is not sorted correctly

- client/src/ui/organisms/header/index.scss
> Moving the search down to show the logo

- build/check-images.js
- testing/content/files/en-us/web/empty_image/index.html
- testing/tests/index.test.js
> don't crash on empty <img> tags

- client/src/ui/molecules/main-menu/index.tsx
- client/src/ui/organisms/header/index.tsx
Fixes #1435
It looks horribly big and complicated but the reason the diff is so big is the indentation when now the menu is no longer needed to be a `useMemo` callback.
> report a problem link in header

- client/src/document/on-github.tsx
> use README.md instead of CONTRIBUTING.md

- content/document.js
- tool/cli.js
> disallow moving to slug with the # character

- client/src/ui/molecules/main-menu/index.tsx
> Remove non-feedback related links in "Feedback" menu

- .github/workflows/dev-build.yml
- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
- content/document.js
- import/import.js
> dump translated-content twice

- import/import.js
> improvements to importer

- kumascript/macros/GroupData.json
- kumascript/macros/InterfaceData.json
- kumascript/macros/SpecData.json
- kumascript/macros/secureContextGeneric.ejs
Per our launch plan, updating the `kumascript` macros with changes since my last update on Nov. 11th.
> update with changes since last update on nov 11

- kumascript/macros/CSP.ejs
- kumascript/macros/CSSInfo.ejs
- kumascript/macros/CSSSyntax.ejs
- kumascript/macros/CSS_Ref.ejs
- kumascript/macros/HTMLElement.ejs
- kumascript/macros/HTTPMethod.ejs
- kumascript/macros/HTTPStatus.ejs
- kumascript/macros/SVGElement.ejs
- kumascript/macros/httpheader.ejs
> remove unused localStrings and commonLocalStrings

- build/cli.js
I never know whether to call it "URLs" or "documents" or "pages" but anything is better than saying "Built 1,234 in 3.2 minutes"
> fix build cli output

- client/src/ui/molecules/login/index.tsx
> view profile in menu

- kumascript/macros/secureContextGeneric.ejs
Reverts a small part of #2049.
> partial revert

- build/index.js
- import/import.js
Fixes #2081
E.g.
Also, compare:
https://developer.allizom.org/en-US/docs/Web/API/AnalyserNode and http://localhost:5000/en-US/docs/Web/API/AnalyserNode/
I haven't run the importer yet but will later after this is merged.
> Have to handle <div class="note"> too

- client/src/document/index.scss
- kumascript/macros/PreviousMenuNext.ejs
- kumascript/macros/PreviousNext.ejs
Add minimal class to next-prev buttons on learn area
fix #2089
> fix: add minimal to learn pagination

- testing/integration/headless/test_endpoints.py
> add integration tests for preferredlocale cookie

- client/src/search.tsx
- client/src/ui/molecules/search/basic-search-widget.scss
- client/src/ui/molecules/search/index.scss
- client/src/ui/molecules/search/index.tsx
- fix: add submit button and icon to search field
- ensure search button input is also present for CRUD mode
fix #1982 
Fix #2104
> 1982 submit button in header search

- testing/integration/headless/map_301.py
Fix the `learn` zone integration tests.
> fix learn integration tests

- kumascript/macros/GroupData.json
- kumascript/macros/SpecData.json
Adding the File System Access API changes by @rumyra from https://github.com/mdn/kumascript/commit/749837f88f7d48dee8ba76b0db0fbb335aca0d36
> add file-system-access api from old ks repo

- kumascript/macros/SpecData.json
Another new WebGL extension specification. Docs to follow over in mdn/content soon.
I think this commit should be signed now.
> Add WEBGL_multi_draw spec

- deployer/poetry.lock
> poetry packages needs updating

- server/index.js
- testing/tests/developing.test.js
Part of #350
I need to write a test too. Clearly, we failed to have that.
> wrong redirect in local server

- kumascript/tests/macros/utils.js
- kumascript/tests/macros/utils.test.js
- package.json
- yarn.lock
Seems to work. No more dependency on `java` (JDK) to be able to local development on Yari. 
Also, much faster tests.
> replace vnu-har with html-validate

- client/src/ui/atoms/logo/index.tsx
> logo link to /$locale/

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
- deployer/src/deployer/main.py
- deployer/src/deployer/speedcurve.py
Fixes #2208
Based on https://github.community/t/using-github-action-environment-variables-in-shell-script/18330/2?u=peterbe
> fix Speedcuve deployment ping

- package.json
> restart server on .ejs edits

- kumascript/tests/index.test.js
> fx ks unit tests

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
Fixes #2323
I've tested this manually by commenting out all the stuff that takes time. 
But I've also now kicked off a full build and if that works (in about 45 min), I think that's good enough.
> manual run of stage & prod build is broken

- kumascript/src/templates.js
- kumascript/tests/templates.test.js
- package.json
> Disable EJS caching for local server

- .npmignore
Most of dev stuff is already masked out, just found a few other minor ones.
> chore: Ignore more files from NPM pack

- kumascript/macros/CompatVersionUnknown.ejs
- kumascript/macros/ObsoleteBadge.ejs
fixed incorrect translation.
The old string means:
"Please update to the latest support status."
> fix: Japanese translation in CompatVersionUnknown.ejs

- kumascript/macros/CSS_key_concepts.ejs
> Update Japanese translations in CSS_key_concepts.ejs

- kumascript/tests/macros/spec2.test.js
> fix spec2.test.js

- package.json
- yarn.lock
Only hard reference is in a test file
https://github.com/mdn/yari/blob/982ca032abf3fd6421a78399254e990f9cc38798/testing/tests/redirects.test.js#L2
> chore: Move braces to devDependecy

- kumascript/macros/anch.ejs
> avoid kumascript's string.toLower()

- filecheck/checker.js
> Help with running yarn filecheck save compression

- kumascript/macros/L10n-Common.json
Removed a pt-BR element which has been duplicated.
> Remove a duplicated pt-BR element

- kumascript/macros/L10n-SVG.json
Add and update Japanese translations in L10n-SVG.json
> Add and update Japanese translations in L10n-SVG.json

- .eslintrc.js
- .prettierrc
- client/package.json
- deployer/aws-lambda/content-origin-request/package.json
- libs/constants/package.json
- libs/fundamental-redirects/package.json
- libs/get-locale/package.json
- package.json
- yarn.lock
Found the ESLint one wasn't working properly on ESLint v7 anymore
> chore: Use prettier plugin for package.json

- kumascript/macros/GroupData.json
> fix: Incorrect URL for HTML Drag and Drop API Events

- kumascript/macros/SpecData.json
I am currently documenting Portals, this PR adds the spec.
re: https://github.com/mdn/content/issues/1209
> adding portals spec

- client/src/document/index.tsx
> DOMException on using anchor links that can't be used as selectors

- .github/workflows/pr-deployer.yml
- deployer/README.md
- deployer/poetry.lock
- deployer/pyproject.toml
- deployer/src/deployer/constants.py
- deployer/src/deployer/main.py
- deployer/src/deployer/search/__init__.py
- deployer/src/deployer/search/models.py
- deployer/src/deployer/search/test_search.py
Part of #2410
To test; make a complete build. You'll also need an elasticsearch instance URL. 
@escattone We can discuss this in more detail on Monday.
> Publish to Elasticsearch in deployer

- package.json
Only used in client/src/document/forms/form.tsx
> chore: Push down use-debounce

- .github/workflows/dev-build.yml
- .github/workflows/stage-build.yml
- deployer/README.md
- deployer/src/deployer/constants.py
- deployer/src/deployer/main.py
> actually call 'deployer search-index' in dev and stage

- kumascript/macros/InterfaceData.json
Working on https://github.com/mdn/content/issues/1209
PR to add the inheritance info for HTMLPortalElement so the InheritanceDiagram will be correct.
> adding HTMLPortalElement

- client/src/ui/molecules/main-menu/index.tsx
- kumascript/macros/MDNSidebar.ejs
> Change the "Join the MDN Community" link in the global nav

- testing/integration/headless/test_cdn.py
- testing/integration/headless/test_endpoints.py
> Fix integration tests 2463

- kumascript/macros/LearnSidebar.ejs
Continuation of #2533 since GitHub hickuped and closed it on a force push that I cancelled.
> fix: Duplicate How_the_web_works in Learn

- build/flaws.js
- filecheck/checker.js
- testing/content/files/en-us/web/images/index.html
> Links to local images is considered broken

- deployer/src/deployer/search/__init__.py
- testing/integration/headless/test_cdn.py
- testing/integration/headless/test_endpoints.py
- testing/integration/utils/urls.py
Ran `find . -name "*.py" -exec pyupgrade --py37 {} \;`
> chore: Run pyupgrade for 3.7

- package.json
Matched version used by react-script pack
> chore: Add missing webpack peerDep

- deployer/src/deployer/search/__init__.py
#2622 broke the deployer. This PR fixes it.
> fix incomplete change from pull request 2622

- build/document-extractor.js
Fixes #2632
Now, both http://localhost:3000/en-US/docs/Web/Accessibility/ARIA/Roles/Search_role and http://localhost:3000/en-US/docs/Web/CSS/minmax() and working fine.
> Quick_Links or Quick_links, both are OK

- .github/workflows/developing.yml
- README.md
> override file descriptors setting for linux

- content/document.js
- content/redirect.js
* remove cylces like A -> A
* remove filter when invoking add
> fix short cuts

- content/constants.js
> Help when the CONTENT_ROOT lacks the "files" ending

- client/src/ui/molecules/search/index.tsx
Adds the search role to our header search component.
Part of #2613
> fix: add search role to header search

- .github/workflows/prod-build.yml
Emergency fix for production search index.
> add missing DEPLOYER_ELASTICSEARCH_URL to prod deploy

- build/flaws.js
> fix: Mark as warning when image host not resolved

- client/src/document/index.tsx
- client/src/document/toolbar/flaws.tsx
- client/src/document/toolbar/index.tsx
> reload page after fixing fixable flaws

- deployer/src/deployer/search/__init__.py
> index document summary in ES

- yarn.lock
The result of `npx browserslist@latest --update-db`
> upgrade caniuse-lite

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
> make the speedcurve ping the last step

- deployer/src/deployer/search/models.py
> add summary to Document class too

- build/document-extractor.js
Fixes #1722
I just took the implementation we worked so hard on in `kumascript/src/info.js` and copied the best bits over to the Yari builder.
> extract summary better

- build/index.js
A solution to https://github.com/mdn/mdn-minimalist/issues/458
Examples:
> Make external links have classexternal

- tool/cli.js
I think an effort like this started somewhere but it stalled. I so dearly need/want it that I decided to just bite the bullet and implement it. Now you can do:
```
yarn tool preview Web/XPath -p 3000
...or...
yarn tool preview https://developer.mozilla.org/en-US/docs/Web/XPath
...or... (best of all)
yarn tool preview files/en-us/web/xpath/index.html
```
the last one is most important because often run `rg` in the content repo and it lists the files like that. Then I can just copy that file path and go straight to it.
> make 'yarn tool preview' more friendly

- client/src/document/on-github.tsx
> hint harder in the new issue template

- docs/unarchiving.md
Adding a guide on how to unarchive things to the docs.
> adding unarchiving guide

- content/redirect.js
- content/redirect.test.js
- package.json
Something like this? I'll add some more but first wanna get in the basics and add as I work on unslugging.
> add some unit tests for redirect.js

- build/flaws.js
> Anchor links casing should always be corrected in build-time

- content/redirect.js
Fixes #2787 
I'm sad that `eslint` didn't capture this. I could say that I'm sad that code review didn't catch it, but this is the kind of stuff `eslint` should be able to help with.
> "Cannot access 'url' before initialization" in add-redirect

- package.json
- yarn.lock
> Revert "build(deps-dev): bump react-scripts from 4.0.1 to 4.0.2"

- deployer/src/deployer/search/__init__.py
> 'p.hidden' get included in search text

- kumascript/tests/macros/svginfo.test.js
Rename function since it wasn't really a class constructor
> fix: ESlint new-cap

- kumascript/macros/XsltRef.ejs
> fix links in xsltref macro

- deployer/src/deployer/search/__init__.py
Context: https://github.com/mdn/kuma/pull/7778#issuecomment-775330408
> store 'slug' in lowercase in ES

- build/document-extractor.js
- content/redirect.js
- kumascript/src/api/string.js
- kumascript/src/api/wiki.js
- kumascript/src/live-sample.js
- kumascript/tests/macros/apiref.test.js
- server/flaws.js
- server/index.js
This is an auto-fix from ESLint. Kind of neutral on the change, as maybe the originals have better readability
> fix: ESLint no-else-return

- libs/fundamental-redirects/index.js
> /<locale>/DOM -> /<locale>/docs/DOM

- kumascript/macros/SpecData.json
I'm documenting the Cookie Store API, this adds the spec.
> Adds Cookie Store API spec

- kumascript/macros/EmbedLiveSample.ejs
This is an idea for addressing https://github.com/mdn/translated-content/issues/23.
> improve EmbedLiveSample macro for non-English locales

- build/index.js
> data-flaw attribute is set in production HTML

- deployer/src/deployer/upload.py
> woff2 fonts served with the wrong content-type

- deployer/src/deployer/search/__init__.py
> Don't Elasticsearch index noIndexing documents

- build/index.js
- kumascript/index.js
This cache grew to big if rendering all locales.
> use LRU for kumasript cache

- build/check-images.js
- testing/content/files/en-us/web/images/srcless/.#index.html
- testing/content/files/en-us/web/images/srcless/index.html
- testing/tests/index.test.js
>  img without a src will crash the flaw checker

- client/src/document/index.tsx
- client/src/document/interactive-examples.scss
> interactive-examples.scss in main CSS bundle

- tool/cli.js
> Remove disk-based caching for gather-git-history CLI tool

- kumascript/macros/SpecData.json
https://www.chromestatus.com/feature/6577673212002304
> Adds Web Serial API to SpecData.json.

- kumascript/macros/SpecData.json
I'm going to document this spec, adding it to the specdata.
Also, have set up signed commits so testing if this works.
> Adding Local Font Access API

- .github/workflows/dev-build.yml
- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
Fixes #3010
Now, translated content is *always* built. It's not a choice anymore.
> always build translated content

- build/flaws.js
- build/matches-in-text.js
and we know there's exactly one result anyhow
> don't crash on long needle

- client/src/user-context.tsx
Fixes #2994
This switches from a plain `fetch()` to using the `useSWR` hook. The advantages are that `useSWR` "caches" the response and can revalidate when the page visibility event triggers. That means if you have 2 MDN windows open and you sign in or sign out in the other window, when you go back to the first window it retriggers the fetch and can now notice that your authentication state has changed. 
Also `useSWR` has built-in support for retries on errors. This is really helpful if your network connection fails after the initial load. 
I also took the liberty of removing `wikiContributions: number` from the `UserData` struct since it's something the `/api/v1/whoami` have ceased to send.
> use useSWR for /api/v1/whoami

- build/flaws.js
Fixes #3072
[The results speak for themselves](https://github.com/mdn/content/pull/2727) :)
> Unable to download .svg external images because invalid file type

- client/src/site-search/index.scss
- client/src/site-search/search-results.scss
- client/src/site-search/search-results.tsx
Second iteration of the search results page UI updates
Part of #2889
> enhancement: next iteration of search result UI updates

- client/src/site-search/index.scss
Fix unintentional Prettier fail
> fix: prettier fail

- tool/cli.js
I've wanted/needed this for so long and sick of having to manually figure out the slug first. 
I also snook in a nifty check if you try to do this and `CONTENT_TRANSLATED_ROOT` isn't set.
> ability to preview based on absolute file path

- kumascript/macros/SpecData.json
Adding the Trusted Types spec as I'm documenting it: https://w3c.github.io/webappsec-trusted-types/dist/spec/
> adds Trusted Types spec

- content/document.js
> fix tool delete

- docs/npm-packaging.md
https://github.com/github/renaming#creating-a-seamless-move-for-existing-repositories-
> chore: master -> main branch

- build/check-images.js
- testing/content/files/en-us/web/empty_image/index.html
- testing/tests/index.test.js
> don't crash on <img src="#x">

- .github/workflows/performance.yml
anything to save some wasteful electricity
> disable lighthouse PR check unless relevant changes

- .github/workflows/auto-merge.yml
Part of #3217
Supposedly, this is all you need to do.
> Fix our auto-merge workflow

- .github/workflows/dev-build.yml
- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
Part of #3219
Once this lands, we'll need to create a new shortcode on whatsdeployed and mention its URL in the right places.
> create a whatsdeployed.json for translated-content too

- deployer/aws-lambda/content-origin-request/index.js
[Here](https://github.com/mdn/yari/pull/3222/files#r593396722) you made a good suggestion but I think you merged it before you committed the suggestion. It's worth correcting it.
> correct code comment

- content/constants.js
> convert *_ROOT env to absolute paths

- build/flaws.js
> Don't choke on iframes without a src

- build/cli.js
- content/document.js
> Ability to build by specific locale(s)

- .github/workflows/prod-build.yml
Part of #2224 (will manually close after verification).
> start pruning prod builds

- kumascript/macros/cssxref.ejs
- kumascript/tests/macros/cssxref.test.js
From comment in https://github.com/mdn/content/pull/3243#discussion_r596531023
> fix: Don't double brace some CSS refs

- client/src/document/index.scss
Fixes #3031
See http://localhost:3000/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers
> .page-not-create can appear outside article and .main-content

- deployer/src/deployer/upload.py
> Deployer needs to upload static assets first

- .github/workflows/dev-build.yml
- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
> temporarily disable pruning

- server/search-index.js
> use sync fs to populate search index

- kumascript/macros/HTMLSidebar.ejs
- kumascript/macros/ServiceWorkerSidebar.ejs
- kumascript/macros/WebGLSidebar.ejs
- kumascript/macros/WebRTCSidebar.ejs
Fixes https://github.com/mdn/content/issues/3602
> Drop all “Doc status” links from sidebars

- ssr/render.js
- testing/tests/index.test.js
> Alternate lang link tags are broken

- kumascript/macros/CanvasSidebar.ejs
- kumascript/macros/HTMLSidebar.ejs
- kumascript/macros/ServiceWorkerSidebar.ejs
- kumascript/macros/WebGLSidebar.ejs
- kumascript/macros/WebRTCSidebar.ejs
Fixes https://github.com/mdn/content/issues/3557
> Drop all “Pages tagged Foo” stuff from sidebars

- kumascript/macros/GroupData.json
Fixes https://github.com/mdn/content/issues/3549
> Specify overview for XMLHttpRequest in GroupData

- client/src/constants.ts
- client/src/document/toolbar/edit-actions.tsx
- client/src/document/toolbar/flaws.tsx
- client/src/document/toolbar/index.tsx
- client/src/sitemap/index.tsx
- docs/envvars.md
Fixes #3334
Not my best work but it works.
> Toolbar but read-only mode

- kumascript/macros/SpecData.json
I'll be documenting Compression Streams soon, added the spec in preparation for that https://wicg.github.io/compression/
> Adding Compression Streams spec

- kumascript/macros/GroupData.json
Fixes https://github.com/mdn/content/issues/3627
> Specify overview for Web Speech API in GroupData

- client/src/document/ingredients/browser-compatibility-table/index.tsx
Fixes #3410
Yes
(Still) No
(Still) Yes
> compat tables to include Node for web APIs

- kumascript/macros/SpecData.json
I'm documenting a couple of methods of this API, adding the spec https://w3c.github.io/badging/
> Add the Badging API

- client/src/ui/molecules/main-menu/index.tsx
Fixes #3299
I feel lighter already!
> remove 'Wiki' GA event code

- client/src/document/organisms/toc/index.tsx
- client/src/ui/molecules/dropdown/index.tsx
> remove 'MozMenu' event collection

- kumascript/macros/ref.ejs
> Ref macro injects unsafe_html HTML

- kumascript/tests/macros/svginfo.test.js
Fixes Kumascript tests for https://github.com/mdn/yari/pull/3456
> fix kumascript test svginfo.test.js

- client/src/ui/molecules/language-menu/index.tsx
- docs/experiments/0002_language-preferredcookie-before.md
> include preferredlocale in 'Change language' event

- kumascript/macros/GroupData.json
Fixes https://github.com/mdn/content/issues/4091
> Add the Sensor API to GroupData.json

- client/src/document/toolbar/flaws.tsx
> Apple emoji in heading_links Flaw UI after diffs

- kumascript/macros/EmbedInteractiveExample.ejs
- kumascript/tests/macros/EmbedInteractiveExample.test.js
> Remove <p class="hidden"> from the interactive examples

- build/index.js
> Remove injectInPageCallout()

- libs/constants/index.js
We now have an active Korean localization team, so I'm activating the `ko` locale!
> activate Korean locale

- client/src/ui/molecules/dropdown/index.scss
Small overrides for the user menu and user menu dropdown
Fix #3415
> fix: user menu ui bug fixes

- docs/REVIEWING.md
I fixed the **Yari quickstart** link in docs/REVIEWING.md
> fix link in REVIEWING.md

- kumascript/macros/SpecData.json
Working on https://github.com/mdn/content/issues/4298 and so adding the Level 5 Fonts spec which this feature is part of.
> adds level 5 CSS fonts spec

- build/cli.js
- build/index.js
> EmbedLiveSample errors should probably be fatal

- kumascript/macros/SpecData.json
Adding the WebHID spec.
Ref: https://github.com/mdn/content/pull/4234
> adds WebHID spec

- build/flaws/broken-links.js
- testing/content/files/en-us/web/brokenlinks/index.html
> contributors URL's are incorrectly considered broken

- deployer/src/deployer/analyze_pr.py
- deployer/src/deployer/test_analyze_pr.py
Part of #3499
It'll make the whole comment a bit smaller if there are docs with 0 flaws. E.g.
> don't list documents with 0 flaws

- build/spas.js
- client/src/app.tsx
- client/src/mdnplusplus/app.tsx
- client/src/mdnplusplus/index.scss
- client/src/mdnplusplus/index.tsx
Now you'll be able to go to http://localhost:3000/en-US/mdn++ and play.
> mdn++ landing page

- client/src/mdnplusplus/app.tsx
[My bad](https://github.com/mdn/yari/pull/3608).
> fix alchemer survey iframe

- content/document.js
Part of #3605
The reason this PR isn't marked to fix the issue is because once this lands I'd like to manually correct all existing `_wikihistory.json` files in mdn/content and mdn/translated-content. 
And I can't do that just yet because I don't want to conflict any existing open PRs. 
I ran [my test script](https://gist.github.com/peterbe/3195822bd4f0f85f5ed4f104f96fbf2b) and it produced this:
https://gist.github.com/peterbe/cff128fdf2fb26019ed2fa966f98c4b3
> Make updates to the _wikihistory.json file deterministic

- client/src/flaws/index.tsx
- server/flaws.js
I need a quick way to find out which pages, that have flaws, have some fixable ones.
> refactor Flaws dashboard to include count fixable

- deployer/src/deployer/analyze_pr.py
> It says that there are no flaws twice

- client/src/document/interactive-examples.scss
- kumascript/macros/EmbedInteractiveExample.ejs
- kumascript/tests/macros/EmbedInteractiveExample.test.js
> move interactive height CSS into KS macro

- client/src/mdnplusplus/app.tsx
Now we can display different content depending on a random 25% chance.
> experimental variants for the mdn++ landing page

- .github/dependabot.yml
- package.json
- yarn.lock
Fixes #3694
This seems to be making things better.
> Weird test failures related to puppeteer

- .github/dependabot.yml
> increase npm dependabot open PRs and ignore storybook

- client/src/ui/organisms/footer/index.tsx
> wrong twitter icon

- client/src/document/molecules/localized-content-note/index.tsx
Refactor ko localized content note naturally
It was a little unnatural, so I fixed it more naturally.
> Refactor ko localized content note naturally

- deployer/src/deployer/analyze_pr.py
It still doesn't read great. But it covers the confusion a bit.
> better phrasing in external URLs caught in diffs

- content/translation.js
This new macro was added last week.
> add 'Specifications' as an important macro for translations

- client/public/index.html
> add twitter:card HTML meta tag

- client/src/document/index.scss
> Set max-width to 100% for iframes in content

- kumascript/macros/cssxref.ejs
> cssxref - fix example so it doesn't generate flaw

- kumascript/macros/GroupData.json
Fixes #3824
Now it works. No more "Page not found".
> HTMLMediaElement, not HMTLMediaElement

- client/src/plus/app.tsx
- client/src/plus/landing-page-survey/index.tsx
> plus page copy changes

- libs/constants/index.js
We now have an active pt-BR localization team! This PR activates that locale in the Yari system.
> activate pt-BR locale

- client/src/plus/app.tsx
- client/src/plus/landing-page-survey/index.tsx
> "Join the waitlist" button cta disappears after submitting in survey

- deployer/src/deployer/analyze_pr.py
- deployer/src/deployer/test_analyze_pr.py
> empty href might be None

- .gitignore
> git ignore client .env file

- client/src/app.tsx
I hate leaving code commented out, but I hate digging through git logs a little bit more. Especially for something I think is only a matter of time to come back.
> disable banners

- build/flaws/broken-links.js
- client/src/document/index.scss
- testing/tests/index.test.js
Undoing a messed up rebase in https://github.com/mdn/yari/pull/3914
> follow-up for self-link styling (part 2)

- libs/constants/index.js
Looks like I missed some GA CSP values, I think that should be all (from testing it locally and reading some blogs about it).
> GA CSP values

- kumascript/macros/InterfaceData.json
- kumascript/macros/SpecData.json
Adds the WebOTP API to SpecData: https://wicg.github.io/web-otp/
> Adds the WebOTP API

- client/src/document/hooks.ts
Fixes #3980
This solves the problem. I don't know if there's a better way.
> ignore pre.hidden for copy-to-clipboard button

- client/src/banners/active-banner.tsx
- client/src/banners/index.tsx
- client/src/user-context.tsx
- docs/proxying.md
- server/static.js
Follow-up from https://github.com/mdn/kuma/issues/7882
> no more waffle flags from whoami

- client/src/document/ingredients/browser-compatibility-table/atoms/_bc-browsers.scss
> Fix vertical alignment for pseudo element browser icon in BC tables

- kumascript/macros/SpecData.json
https://www.w3.org/blog/news/archives/9093
> Update Web Audio API Status

- build/spas.js
- build/subscriptionconfig.js
I just wanted to increase the patience of that `got` and I copied the same config we have in `feedparser.js`. Then I decided to refactor it so that this new file and `feedparser` are more "identical", so I rearrange the stuff a little. I hope it helps.
> retries and timeont on getting subscription config

- markdown/cli.ts
- markdown/utils/index.js
> use yaml.dump when dumping makdown file

- build/flaws/broken-links.js
- testing/content/files/en-us/web/brokenlinks/index.html
> fix for decodeURI in broken-links flaw check

- kumascript/macros/GroupData.json
The sidebar was completely wrong.
See it in action at http://localhost:3000/en-US/docs/Web/API/Accelerometer
(On MDN: https://developer.mozilla.org/en-US/docs/Web/API/Accelerometer )
> Update SensorAPI sidebar

- testing/tests/headless.auth.test.js
See lengthy code comment that justifies commenting out as opposed to deleting the code.
> comment out fragile google auth headless test

- client/src/document/on-github.tsx
Similarly as done for content labels
> Pre-set localization labels on issues raised from MDN content

- kumascript/macros/GroupData.json
Long removed.
Fixes mdn/content#6649
@rachelandrew, are you allowed to approve this PR?
> Remove AudioStreamTrack from sidebar

- kumascript/macros/GroupData.json
Companion PR of mdn/content#6669
@sideshowbarker, since you reviewed the content PR, can you review this?
> Remove MediaPositionState from sidebar

- kumascript/macros/GroupData.json
Companion PR of mdn/content#6640
@sideshowbarker, since you reviewed the content PR, can you review this?
> Remove PaymentDetailsBase from sidebars

- README.md
Hello
The smallest pull request that is ..
Thanks
> Typo on yari repo link

- kumascript/macros/HTTPSidebar.ejs
Fixes https://github.com/mdn/content/issues/6956
> Make HTTPSidebar have “Incomplete list of MIME types” (not “Complete”)

- .gitignore
As I'm now fiddling a bit more concretely with the conversion tool in https://github.com/mdn/translated-content/pull/1574, I'm getting a few reports in my yari repo which are a bit annoying when it comes to git + fiddling with yari itself.
I hope this minor PR will help.
> Marking conversion reports in gitignore

- libs/fundamental-redirects/index.js
- testing/integration/headless/map_301.py
- testing/integration/headless/test_cdn.py
- testing/integration/headless/test_endpoints.py
- testing/tests/redirects.test.js
Companion for https://github.com/mdn/kuma/pull/7932
> fix integration tests for butcher-axe

- .github/workflows/dev-build.yml
- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
As soon as this lands in `main`, let's build a complete Stage build to make sure it works as expected.
> disable auth on prod, stage, dev

- client/src/auth/sign-in.tsx
- client/src/auth/sign-up.tsx
- client/src/settings/app.tsx
- client/src/ui/atoms/auth-disabled/index.tsx
It doesn't look perfectly the same/sane on all three pages but I don't think it's worth worrying over. The chances of someone ending up on the sign-up page are minuscule.
> say Auth Disabled on sign in/up too

- deployer/aws-lambda/content-origin-request/index.js
- deployer/aws-lambda/tests/server.test.js
> inject locale to /plus request

- kumascript/macros/GroupData.json
Removed deleted mixin from Fetch API sidebar
cc/ @elchi3 for review from the content side.
Fix mdn/content#7163
> Fix Fetch API sidebar

- client/src/plus/deep-dives/sample-articles.tsx
Based on https://mozilla.slack.com/archives/CLTBV3W9X/p1627045414347000
> less latin, more taglines

- client/src/plus/app.tsx
- client/src/plus/deep-dives/article.tsx
- client/src/plus/deep-dives/feature/index.scss
- client/src/plus/deep-dives/index.scss
- client/src/plus/deep-dives/sample-articles.tsx
- client/src/plus/deep-dives/survey/index.tsx
- client/src/plus/index.scss
- client/src/ui/organisms/hero/index.scss
- client/src/ui/organisms/product-features/index.scss
- client/src/ui/theme/buttons/index.scss
- client/src/ui/theme/index.scss
- client/src/ui/theme/links/index.scss
- client/src/ui/theme/typography/fonts.scss
- client/src/ui/theme/typography/index.scss
The first iteration of UI updates to market research pages.
fix #4292
> fix: ui updates for market research pages

- client/src/plus/app.tsx
- client/src/plus/deep-dives/feature/index.scss
- client/src/plus/index.scss
- client/src/ui/molecules/card/index.scss
- client/src/ui/organisms/hero/index.scss
- client/src/ui/organisms/hero/index.tsx
- client/src/ui/organisms/product-features/index.scss
- client/src/ui/theme/buttons/index.scss
- client/src/ui/theme/typography/index.scss
- client/src/ui/theme/utils/index.scss
Second phase of UI updates to plus landing page.
fix #4294
> fix: phase 2: ui updates to plus landing page

- client/src/plus/deep-dives/survey/index.tsx
To test this you'll need https://github.com/mdn/kuma/pull/7943 on kuma first. 
Also, the error messaging looks pretty bad. Left as an exercise to the reviewer ;)
*When it can't even pre-flight connect to the server*
*Any error when submission fails*
> market research survey implementation

- kumascript/macros/APIListAlpha.ejs
> list all web api sub-pages

- .github/workflows/dev-build.yml
- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
Part of #4297
Reverts mdn/yari#4295
> Revert "unbreak redirects"

- client/src/plus/deep-dives/overview/index.scss
> fix spacing on in this series overview

- client/src/plus/deep-dives/article-meta/index.scss
- client/src/plus/deep-dives/article.tsx
- client/src/plus/deep-dives/byline/index.scss
- client/src/plus/deep-dives/index.scss
- client/src/plus/deep-dives/overview/index.scss
- client/src/plus/deep-dives/series-card/index.tsx
> style updates for market research pages

- build/spas.js
- client/src/app.tsx
- client/src/plus/deep-dives/byline/index.tsx
- client/src/plus/deep-dives/index.tsx
- client/src/plus/deep-dives/overview/index.tsx
- client/src/plus/deep-dives/sample-articles.tsx
Now http://localhost:5000/en-US/plus/deep-dives/ will work.
> unbreak the deep-dives overview page

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
This is a continuation of (Dev) https://github.com/mdn/yari/pull/4324/files but for Stage and Prod.
> building by locales in parallel (stage, prod)

- client/src/plus/deep-dives/overview/index.scss
Set background image for hero on overview to 100% on mobile as well
> fix: hero header on mobile

- client/src/plus/deep-dives/article.tsx
- client/src/plus/deep-dives/series-card/index.tsx
- client/src/plus/deep-dives/survey/index.tsx
Here's how I tested it. 
Filled in the first page (and "Continue"), reloaded the page. Button still there. 
Filled in the second page (and "Submit"), say the "Thank you" message, reloaded the page. Button gone. 
Reload the page again. Button gone. 
Copy the URL to a new tab. Button back.
> hide "Take our survey" button if taken

- client/src/plus/deep-dives/byline/index.tsx
- client/src/plus/deep-dives/sample-articles.tsx
> fix React warning in Byline

- client/src/plus/deep-dives/survey/index.scss
Set a min height on survey success message
> fix: min height on survey success

- kumascript/macros/InterfaceData.json
See https://html.spec.whatwg.org/multipage/window-object.html#the-window-object
Fixes mdn/content#7411
cc/ @Elchi3 for the review from the content side.
> Fix inheritance of Window object

- client/src/plus-v1/index.tsx
- client/src/plus/deep-dives/homepage/index.tsx
- client/src/plus/deep-dives/index.tsx
- client/src/plus/deep-dives/overview/index.tsx
- client/src/plus/index.tsx
Fixes #4355
See 
https://user-images.githubusercontent.com/26739/127383056-8b466df1-b3d3-47ac-9b72-0d320b3ea964.mov
Compare that with the issue. 
It's not great but it's better (because the Deep-dives use different background color and different main menu fonts). And more importantly, this is something we should always do going forwards when Deep-dives aren't hard-coded.
> <Loading> in isServer too

- client/src/document/index.scss
- kumascript/macros/EmbedInteractiveExample.ejs
- kumascript/macros/InheritanceDiagram.ejs
- kumascript/macros/JSFiddleEmbed.ejs
- kumascript/tests/macros/EmbedInteractiveExample.test.js
> remove inline `width` attribute from `iframe` 

- kumascript/macros/SVGRef.ejs
Fixes https://github.com/mdn/content/issues/7503
> Don’t lowercase SVG doc titles (element names) in sidebar

- kumascript/macros/JSFiddleEmbed.ejs
Fixes https://github.com/mdn/content/issues/7571
Fixes https://github.com/mdn/content/issues/7632
> Fix missing-quotation mark error in JSFiddleEmbed; fix width

- kumascript/macros/GroupData.json
- kumascript/macros/InterfaceData.json
IDL: https://immersive-web.github.io/depth-sensing/#idl-index
r? @teoli2003 We discussed this one on Monday :-)
> Update inheritance and group data for WebXR Depth Sensing

- kumascript/src/parser.pegjs
pegjs docs are at https://pegjs.org/documentation
> Update pegjs docs link

- client/src/plus/deep-dives/article.tsx
- client/src/plus/deep-dives/byline/index.scss
- client/src/plus/deep-dives/byline/index.tsx
- client/src/plus/deep-dives/index.scss
- client/src/plus/deep-dives/sample-articles.tsx
- client/src/plus/deep-dives/series-card/index.tsx
- client/src/plus/deep-dives/survey/index.tsx
Updates to deep dive article pages for market research v3
fix #4460
> fix: updates to deep dive article pages

- client/src/plus/deep-dives/index.scss
- client/src/plus/deep-dives/overview/app.tsx
- client/src/plus/deep-dives/overview/index.scss
- client/src/plus/deep-dives/sample-articles.tsx
- client/src/plus/deep-dives/survey/index.scss
Updates to overview and deep dive article pages for market research v3
fix #4480
> fix: changes to ready next version of market research pages

- client/src/plus/deep-dives/index.scss
- client/src/plus/deep-dives/overview/app.tsx
- client/src/plus/deep-dives/overview/index.scss
- client/src/plus/deep-dives/sample-articles.tsx
> fix: updates to deep dive landing page

- client/src/plus/deep-dives/overview/index.scss
> fix: z-index

- client/src/plus/deep-dives/overview/app.tsx
- client/src/plus/deep-dives/sample-articles.tsx
Change the see more button text to Read more.
https://github.com/mdn/yari/issues/4494#issuecomment-900620175
> fix: change see more to read more

- testing/tests/developing.spec.js
> wait for kitchensink rendering

- build/document-extractor.js
> skip empty prose sections

- kumascript/macros/CanvasSidebar.ejs
Fixes mdn/content#8400
This removes a dead link in the sidebar for the canvas element, and guides,…
cc/ @wbamberg for a review from the content side.
> Remove dead snippets link from CanvasSidebar.ejs

- .github/workflows/dev-build.yml
- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
> reflect exit status of jobs we're waiting-on

- deployer/aws-lambda/tests/server.test.js
- libs/fundamental-redirects/index.js
- testing/integration/headless/map_301.py
Per decisions in meeting with @HerminaC, @dalexsy, @schalkneethling, and @escattone.
> temporarily redirect plus URLs to the home page

- kumascript/src/live-sample.js
> make live-sample build check lowercase

- client/public/index.html
- client/public/opensearch.xml
> Add OpenSearch description xml file

- deployer/src/deployer/upload.py
Companion PR for https://github.com/mdn/yari/pull/4568. Sets the proper header when uploading the `opensearch.xml` files.
> add proper content-type for opensearch

- kumascript/macros/AddonSidebar.ejs
This article wasn't present in the sidebar
> Interact with clipboard article to add-on sidebar

- package.json
- yarn.lock
Make it easy to keep track of our bundle sizes:
https://create-react-app.dev/docs/analyzing-the-bundle-size/
> chore: add source map explorer

- markdown/localizations/zh-CN.json
- markdown/localizations/zh-TW.json
> add zh-* markdown card labels

- .github/dependabot.yml
- package.json
- yarn.lock
Rollback to older version of Dinocons
> fix: rollback dinocons

- libs/fundamental-redirects/index.js
- testing/tests/redirects.test.js
> Fix redirext loop

- .github/ISSUE_TEMPLATE/issue-and-pr-triage-task-list.md
Add issue template for the weekly issue and pr triage
> Update issue templates

- client/src/document/ingredients/browser-compatibility-table/headers.tsx
> feat(client/browser_compat_table): show tooltip on hover

- kumascript/macros/JSRef.ejs
Companion for https://github.com/mdn/content/pull/8402/
> Add Intl.Segmenter in JSRef sidebar

- kumascript/macros/CSSRef.ejs
> Fix a link in CSSRef.ejs

- README.md
Update the README to include information detailing our requirements for pull requests.
fix #4653
> (fix:docs) update README with info on pull request requirements

- content/document.js
- content/translations.js
yarn build -l zh-cn web/api/datatransfer/cleardata/index.html
was failing
> support building individial translated pages

- package.json
- yarn.lock
- (chore:deps) pin webpack version
- yarn lock
> pin webpack version in package json

- kumascript/macros/LearnSidebar.ejs
Part of https://github.com/mdn/content/issues/10337.
This updates the Learn sidebar to reflect the changes to the "Objects" module of the JS section, made in https://github.com/mdn/content/pull/11373.
> Update Learn sidebar for updates to JS objects module

- README.md
> Reword Readme to indicate Node 17 is incompatible

- client/src/document/organisms/sidebar/index.scss
> Change word-wrap to ensure sidebar links don't overflow into post content

- kumascript/macros/DeprecatedGeneric.ejs
Translate deprecation message to Spanish
> Translate deprecation message to spanish

- yarn.lock
Update browserlist using `npx browserslist@latest --update-db`
> (chore:browserlist) update browserlist

- markdown/localizations/es.json
> Add Markdown Localizations ES

- build/document-extractor.js
- client/src/document/ingredients/spec-section.tsx
See discussion in https://github.com/w3c/browser-specs/pull/517#issuecomment-1038876922
> Make the Specifications macro not append the spec shortTitle

- kumascript/macros/EmbedLiveSample.ejs
> fix: #5287 by typechecking before calling string methods

- .github/ISSUE_TEMPLATE/new-issue-template.md
Add a basic new issue template
> (chore:issues) add new issue template

- client/src/document/organisms/sidebar/index.scss
> fix side bar list style type

- client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
- client/src/document/ingredients/browser-compatibility-table/index.scss
- client/src/document/ingredients/browser-compatibility-table/index.tsx
- client/src/ui/base/_themes.scss
For new screenshots scroll down.
> Add browser versions to BCD tables

- client/src/app.tsx
- client/src/banners/README.md
- client/src/banners/active-banner.tsx
- client/src/banners/banner-utils.ts
- client/src/banners/ids.ts
- client/src/banners/index.tsx
- client/src/document/ingredients/browser-compatibility-table/index.scss
- chore:banners - disable hacks post banner
- use flex-end as opposed to end for better cross browser support
Fixes #5528.
> chore(banners): disable hacks post & refactor

- client/src/document/interactive-examples.scss
Before:
https://i.elijahpepe.com/v8zUE90.png
After:
https://i.elijahpepe.com/c3bIXNF.png
> chore(interactive-examples): add border radius

- .github/PULL_REQUEST_TEMPLATE.md
Loosely based on: https://github.com/facebook/react/blob/581f0c42ed4baa07309dbda296dc93a101bd922b/.github/PULL_REQUEST_TEMPLATE.md?plain=1
> chore(github): add PR template

- client/src/plus/search-filter/index.tsx
- client/src/ui/atoms/search/index.tsx
Fixes https://github.com/mdn/yari-private/issues/921.
> Make search only submit on enter (& blur) in collections/notifications

- client/src/ui/molecules/submenu/index.scss
- client/src/ui/molecules/submenu/index.tsx
The submenu component is really really broken. I hope nothing breaks.
This was done to add the external icon to links in the user menu.
I removed the gap as it was to my knowledge only used for the top level nav menus.
---
---
> add external class to submenu links

- .husky/pre-commit
- .lintstagedrc
- README.md
- package.json
- yarn.lock
> build(lint): use lint-staged to run prettier and eslint when comitting

- client/src/plus/offer-overview/offer-overview-subscribe/index.scss
- client/src/plus/offer-overview/offer-overview-subscribe/index.tsx
- client/src/ui/base/_themes.scss
> add support for offer upgrades

- client/src/document/molecules/localized-content-note/index.tsx
Add `zh-CN` translation for the NoteBanner.
> chore(l10n): add `zh-CN` translation for `NoteBanner`

- kumascript/macros/FirefoxSidebar.ejs
part of https://github.com/mdn/translated-content/discussions/4706
zh-cn translated by @yin1999 at https://github.com/mdn/translated-content/issues/4707#issuecomment-1073442381
> zh-tw / zh-cn of Firefox sidebar macro

- kumascript/macros/FirefoxSidebar.ejs
Adds remaining French translations for the new Firefox sidebar (part of/related to mdn/translated-content#4706)
(pinging @schalkneethling and @SphinxKnight for reviews)
> French translations for Firefox sidebar

- client/src/ui/organisms/footer/index.tsx
Updates the product help link in the footer
> fix:link : update product help link

- client/src/constants.ts
- client/src/plus/offer-overview/index.tsx
- client/src/plus/offer-overview/offer-hero/index.tsx
- client/src/ui/organisms/top-navigation-main/index.tsx
- client/src/utils.ts
> Revert "allow list for mdn plus"

- client/src/ui/molecules/user-menu/index.tsx
Updates SUMO link in the user menu
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/51.
> fix:link : fix sumo link

- client/src/ui/atoms/limit-banner/index.tsx
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/67.
> chore(limit-banner): replace MDN {Supporter => Plus subscriber}

- copy/plus/features/notifications.md
Correct "Collections" to "Notifications"
fix https://github.com/mdn/foxfooding-mdn-plus/issues/60
> fix:content ~ change collections to notifications

- client/src/plus/offer-overview/offer-overview-feature/index.tsx
Fixes links on product overview page
> fix:links ~ fixes feature links on feature overview

- client/src/plus/collections/collections-tab.tsx
- client/src/plus/collections/frequently-viewed-tab.tsx
- client/src/plus/notifications/notification-card.tsx
- client/src/plus/notifications/notifications-tab.tsx
Updates the copy for the toast component in collections and notifications.
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/68
> fix:copy ~ update toast copy for collections and notifications

- client/src/offline-settings/clear.tsx
- client/src/offline-settings/update.tsx
Adds button class to buttons on the offline settings page.
Fixes https://github.com/mdn/foxfooding-mdn-plus/issues/79
> fix:buttons ~ adds button class to buttons on offline settings page

- client/src/about/index.tsx
The MDN links on https://developer.mozilla.org/en-US/about did not have a locale. This makes them depend our redirect and not work while being offline.
Add the locale to the links so they work offline.
---
---
> add locale to about-links

- copy/plus/features/offline.md
Adds a note to the offline docs about offline and private/incognito modes
Fix https://github.com/mdn/foxfooding-mdn-plus/issues/82
> fix:docs ~ update offline docs to mention usage is private mode

- copy/plus/features/collections.md
Replace visited with viewed in collections docs
Fix https://github.com/mdn/foxfooding-mdn-plus/issues/81
> fix:docs ~ replace visited with viewed

- .github/workflows/prod-build.yml
- client/src/constants.ts
- client/src/ui/molecules/user-menu/index.tsx
Updated manage subscription link in user menu. 
Manage subscriptions link in user menu was linking to staging.
---
---
Added to .env , tested locally.
> Fix:Manage subscriptions prod url

- .github/workflows/prod-build.yml
- client/src/constants.ts
Enables plus
Plus wasn't enabled
Enable it.
---
---
> Enable plus

- client/src/offline-settings/index.tsx
Update the copy on the offline settings page for non-subscribers
Fix https://github.com/mdn/foxfooding-mdn-plus/issues/87
> fix:copy ~ update copy on offline settings

- libs/constants/index.js
Add https://firefoxusercontent.com/ to CSP for avatars
> fix:csp ~ add https://firefoxusercontent.com/

- copy/plus/faq.md
It's a bit more North American friendly format now, although it still might need future tweaks (for example, adding a currency would probably be good; "$5 USD/month or $50 USD/year" to be a bit more clear).
---
---
> Tweak pricing text on /plus/faq page

- copy/plus/features/notifications.md
Switch from `->` to `→`
---
---
> Use consistent arrows on /plus/features/notifications page

- copy/plus/features/offline.md
> Convert -> to →

- client/src/plus/offer-overview/offer-overview-subscribe/index.scss
- client/src/plus/offer-overview/offer-overview-subscribe/index.tsx
Inlcude link to MDN Plus for companies form.
Fix https://github.com/mdn/foxfooding-mdn-plus/issues/91
> fix:plus ~ update to product overview

- README.md
Mention document files for mdn/content can be in .md.
It only says there are `index.html` files.
Mention document files for mdn/content can be in .md.
---
---
> Mention document files for mdn/content can be in .md

- client/src/ui/atoms/avatar/index.tsx
Change avatar alt text to 'Avatar'
Related to https://github.com/mdn/foxfooding-mdn-plus/issues/92
User ID was being displayed as Avatar alt. 
If Avatar failed to load this looked strange and confusing.
Also not good for accesibility. 
---
---
> Fix:92 Adjust Avatar alt

- deployer/src/deployer/upload.py
- deployer/src/deployer/utils.py
fixes #5780
Redirect URLs have not been escaped. (what slugToFolder does during build time).
---
---
> implement slug to folder for redirects

- client/src/plus/notifications/notification-card-list-item.tsx
Creates dynamic links in notifications text with PR. 
---
---
> Make PR links dynamic

- kumascript/macros/EmbedInteractiveExample.ejs
> Add Japanese translation

- client/pwa/src/caches.ts
- client/pwa/src/service-worker.ts
- client/src/offline-settings/mdn-worker.tsx
Send periodic keep alive messages while updating to keep the service worker alive.
---
---
> Serviceworker keepalive

- client/src/plus/common/api.tsx
- client/src/plus/notifications/notifications-tab.tsx
- 'Star' button wasn't working on multi select. Corrected camel case **csrfMiddlewareToken** to **csrfmiddlewaretoken**
- Fixed isLoading check to prevent Notifications empty state displaying briefly on input changes
---
---
> Fix loading state. Fix CSRF Token

- kumascript/macros/ServiceWorkerSidebar.ejs
Added Japanese translation
There isn't Japanese translations in this macro
---
---
> Added Japanese translation for ServiceWorkerSidebar

- kumascript/macros/ServiceWorkerSidebar.ejs
Remove obsoleted interfaces.
---
---
> Remove obsoleted interfaces

- client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
- client/src/document/ingredients/browser-compatibility-table/index.scss
- client/src/document/ingredients/browser-compatibility-table/utils.ts
Fixes #6009 and some other issues requiring immediate attention.
...
...
---
---
> fix(bcd): fix some regressions

- client/public/index.html
- libs/constants/index.js
Fixes: `Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). Source: const c={light:"#ffffff",dark:"#1b1b1b"};if(window&&document.body){const o=window.localStorage.getItem("theme");o&&(document.body.className=o,document.body.style.backgroundColor=c[o])}.`
---
---
> update csp headers for allow updated inline script

- client/src/banners/active-banner.tsx
- client/src/utils.ts
Enable Plus anywhere when launching in Europe and update our banner.
---
---
> feature(Plus): enable plus worldwide and update banner

- client/src/plus/offer-overview/offer-overview-subscribe/index.tsx
Previously we defaulted to show the US plans. But when visiting from an unsupported region it would flicker and then only show _Core_
---
and then
and then
---
> fix(Plus) hide plans while loading

- deployer/aws-lambda/mdn-stripe-price-ids/index.js
- deployer/aws-lambda/mdn-stripe-price-ids/tests/__mocks__/plans-prod-lookup-test.json
- deployer/aws-lambda/mdn-stripe-price-ids/tests/handler.test.js
Incorrect header value being used for stage/prod switch.
Make default always to prod. 
Update test
> Update test to fail if not prod. Correct header lookup

- client/src/document/ingredients/browser-compatibility-table/index-mobile.scss
Tables on mobile devices are not scrollable.
Allow horizontal scrolling for tables on mobiles
---
---
1. Use https://developer.mozilla.org/en-US/docs/Web/Performance/Navigation_and_resource_timings as test page
> fix: make tables scrollable on mobiles

- client/src/plus/offer-overview/offer-overview-subscribe/index.tsx
> fix(plus): fix yearly plans

- .github/workflows/prod-build.yml
Enables EU users to access MDN plus.
> Set enable EU flag for prod build

- client/src/plus/offer-overview/index.tsx
- client/src/plus/offer-overview/offer-hero/index.scss
- client/src/plus/offer-overview/offer-hero/index.tsx
- client/src/plus/offer-overview/offer-overview-subscribe/index.tsx
Added currency spinner on currency loading in Offer hero. 
---
---
> Added loading state for currency on offer-overview

- client/src/ui/molecules/auth-container/index.scss
- client/src/ui/molecules/guides-menu/index.scss
- client/src/ui/molecules/language-menu/index.scss
- client/src/ui/molecules/main-menu/index.scss
- client/src/ui/molecules/menu/index.tsx
- client/src/ui/molecules/plus-menu/index.scss
- client/src/ui/molecules/reference-menu/index.scss
- client/src/ui/molecules/search/index.scss
- client/src/ui/molecules/submenu/index.scss
- client/src/ui/molecules/submenu/index.tsx
- client/src/ui/molecules/theme-switcher/index.scss
- client/src/ui/molecules/theme-switcher/index.tsx
- client/src/ui/molecules/user-menu/index.scss
- client/src/ui/organisms/top-navigation-main/index.scss
- client/src/ui/organisms/top-navigation/index.scss
> fix(top-navigation): avoid header wrap

- client/src/plus/offer-overview/index.tsx
- client/src/plus/offer-overview/offer-hero/index.scss
- client/src/plus/offer-overview/offer-hero/index.tsx
- client/src/plus/offer-overview/offer-overview-subscribe/index.tsx
> fix(plus): No price line

- kumascript/src/live-sample.js
Was running some validation on the generated files in content and VNU validator was emmiting `The “type” 
attribute for the “style” element is not needed and should be omitted.` since it's not required anymore in HTML5
---
---
> chore(live-samples): remove unnecessary <style> type

- client/src/plus/offer-overview/offer-overview-subscribe/index.scss
Fix a style that looks strange
See: https://developer.mozilla.org/en-US/plus#subscribe
Add border radius style to H3 label
---
---
> fix(offer-overview): copy border-radius from wrapper to header

- testing/tests/developing.spec.js
This ain't great. The kitchensind page contains macros that depend on
other pages. This may introduce flaws. They are fixed for now.
We must make this more resilient.
---
---
> fix(tests): fix developing.spec.js

- client/src/app.scss
- client/src/ui/organisms/article-actions/index.scss
Signed-off-by: zhouhaoyu <67226385+zhouhaoyiu@users.noreply.github.com>
Fixes #6125 .
change the top value and add a margin
---
> fix(article-actions-header): change article actions position

- client/src/index.tsx
- ssr/render.js
this probably escapes far too much, but works as an initial fix
> fix: escape hydration data

- build/spas.js
- client/src/homepage/recent-contributions/index.tsx
- testing/tests/index.test.js
hide whole recent contributions section if data is missing
> fix(build): only add necessary github data to hyData

- client/src/ui/base/_themes.scss
Signed-off-by: zhouhaoyu <67226385+zhouhaoyiu@users.noreply.github.com>
Fix #6135
---
localhost:3000
> fix(theme): avoid :not() with selector list

- content/document.js
fixes [#6226](https://github.com/mdn/yari/issues/6226) and enhances https://github.com/mdn/yari/pull/6228
---
---
> Fix find children

- .github/workflows/pr-rebase-needed.yml
Adds a workflow that adds this comment to PRs with merge conflicts:
> This pull request has merge conflicts that must be resolved before we can merge this.
**Example**: https://github.com/mdn/browser-compat-data/pull/15775#issuecomment-1120428855
> build(workflows): add "PR Needs Rebase" check

- deployer/aws-lambda/content-origin-request/yarn.lock
- deployer/aws-lambda/mdn-stripe-price-ids/yarn.lock
- deployer/aws-lambda/tests/yarn.lock
- markdown/h2m/h.ts
- markdown/h2m/handlers/cards.ts
- markdown/h2m/handlers/dl.ts
- markdown/h2m/handlers/index.ts
- markdown/h2m/handlers/tables.ts
- yarn.lock
Fixes #6276.
It looks as if #5970 somehow regressed our `yarn.lock` file, causing errors for some users.
Someone [mentioned on StackOverflow](https://stackoverflow.com/a/71543416) that recreating `yarn.lock` helped after upgrading to react-scripts v5, and indeed this resolved the issue for me locally. 🤔 
---
(Generated with [yarn-lock-diff](https://github.com/tychota/yarn-lock-diff).)
```
┌──────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
│ package name                 │ old version(s)                                   │ new version(s)                                   │
├──────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
│ …
```
> build(deps): recreate yarn.lock files

- .github/workflows/prod-build.yml
> feature(deployer): auto deploy lamdbas on prod

- build/build-options.js
- build/constants.js
- build/flaws/index.js
- build/matches-in-text.js
- client/src/document/toolbar/flaws.tsx
- docs/envvars.md
- tool/cli.js
This adds the `yarn tool fix-flaws` command.
Previously, we didn't enable flaws in markdown files being fixed.
For now only fixing broken links works fully.
Fixing broken macros kinda works but needs review.
---
---
> feature(build): enable flaws fixing in markdown

- content/document-paths.js
- content/document.js
This will improve our build time. We spend quite some time
finding "children". This is invoked in many macros.
Therefore, we start to cache it upfront.
---
---
> feature(build): cache directories for prod build

- build/spas.js
https://github.com/mdn/yari/issues/6329
> chore(featured-articles): color-scheme -> cascade

- deployer/aws-lambda/mdn-stripe-price-ids/plans-stage-lookup.json
> feature(plus): update plans for stage

- .github/workflows/new-issues.yml
Add required `target-repo` input and rename workflow name.
Update required as a result of https://github.com/mdn/workflows/pull/55
> chore: update new-issues workflow

- .github/workflows/pr-rebase-needed.yml
Add required `target-repo` input and rename workflow name.
Update required as a result of https://github.com/mdn/workflows/pull/55
> chore: update pr-rebase-needed workflow

- docs/popularities.md
Just updating the docs
---
---
> chore(builder): add a history to popularities

- deployer/aws-lambda/mdn-stripe-price-ids/plans-prod-lookup.json
> feature(plus): add more plans

- ssr/index.ts
- ssr/render.ts
- ssr/webpack.config.js
Converts `ssr/` to TypeScript.
Extracted from #6307.
---
_No changes._
---
1. Ran `yarn build:ssr` locally.
> refactor(ssr): convert to typescript

- client/src/plus/offer-overview/offer-overview-subscribe/index.scss
- client/src/plus/offer-overview/offer-overview-subscribe/index.tsx
Fixes #5792.
"Fanboy's Annoyance List" contains a rule [`##.subscribe-wrapper`](https://github.com/easylist/easylist/blob/2435db8e5df6ff9b5f3cbf0d5600764b27ea552a/fanboy-addon/fanboy_newsletter_general_hide.txt#L2085) which is blocking MDN Plus subscription form. Obviously, this is problematic for Plus onboarding.
This solution: Rename one CSS class from `subscribe-wrapper` to anything else not present in the list. I used `plus-subscribe-wrapper`.
Alternative solution: ask "Fanboy's Annoyance List" maintainers to add an exclusion, as was suggested [here](https://github.com/mdn/yari/issues/5792#issuecomment-1079159725). This is much harder than just renaming a CSS class within Yari itself.
---
I tested this by hard-coding `plusAvailable`  to be `true` and validating that with uBlock Origin …
> fix(offer-overview): rename subscribe wrapper to avoid Fanboy's Annoyance filter

- deployer/aws-lambda/mdn-stripe-price-ids/plans-prod-lookup.json
This reverts commit 2c88a15ef8327cbdec19b01eee3b8a5999fb04e4.
---
---
> Revert "feature(plus): add more plans (#6400)"

- client/pwa/src/service-worker.ts
- client/src/offline-settings/mdn-worker.tsx
Phases:
1. https://github.com/mdn/yari/pull/5980
2. https://github.com/mdn/yari/pull/5955
3. https://github.com/mdn/yari/pull/6381
> chore(pwa): remove backward-compatible update handling (Phase 3 of 3)

- client/src/homepage/homepage-hero/index.tsx
- client/src/ui/molecules/mandala/index.scss
- client/src/ui/molecules/mandala/index.tsx
Changes the Mandala colors to match the rainbow flag (and adds a 6th inner circle for that matter).
---
---
> chore(mandala): update colors to show rainbow flag

- markdown/cli.ts
Fixes #6181
1. Windows is using `\` as path separator. So the `Document.findAll` will not math any folder with `folderSearch` arguement like this `web\javascript` (with `\` in this string).
2. The `saveProblemsReport()` won't work on windows either. Because of using `:` in file path, which is not allowed on windows.
1. To let the `Document.findAll` works on windows, I replace the `\` in filepath with `\\`.
2. Replace `\` in `args.folder` with `/` to match the slug.
3. replace the `:` in `reportFileName` with `_` to create file on windows.
With file count: `0`.
With file count: `809`.
> fix(markdown): support h2m cli for windows

- client/src/banners/index.tsx
> Revert "chore(banner): disable current banner (#6510)"

- client/src/banners/active-banner.tsx
- client/src/banners/banner.scss
- client/src/banners/ids.ts
- client/src/banners/index.tsx
- client/src/homepage/homepage-hero/index.tsx
- client/src/ui/molecules/mandala/index.scss
- client/src/ui/molecules/mandala/index.tsx
> chore(pride): pride month is over

- client/pwa/src/db.ts
- client/pwa/src/service-worker.ts
- client/src/index.tsx
- client/src/offline-settings/db.ts
- client/src/offline-settings/mdn-worker.tsx
- client/src/ui/atoms/signout/index.tsx
- client/src/user-context.tsx
Enable caching the API in IndexDB for all MDN Plus users.
> feature(plus): enable api caching for all plus users

- client/src/ui/molecules/user-menu/index.tsx
> fix: breakpoint for user menu was wrong

- ssr/render.ts
> fix(SSR): use .replace with arrow functions

- kumascript/macros/JsSidebar.ejs
In accordance with https://github.com/mdn/content/pull/18542
---
---
> Replace Details of the object model with Using classes in JS sidebar

- kumascript/macros/JsSidebar.ejs
Follow-up of #6745. Forgot to update the slug...
> fix: update slug for Using Classes in JS sidebar

- kumascript/macros/Interwiki.ejs
Depreciate the Interwiki macro.
See mdn/community#165
Depreciate the macro.
---
---
> Depreciate the Interwiki macro

- client/src/plus/collections/v2/api.ts
- client/src/plus/collections/v2/collection.tsx
- client/src/plus/collections/v2/index.tsx
- client/src/plus/collections/v2/new-collection-modal.tsx
- client/src/plus/index.tsx
- client/src/ui/molecules/collection/index.tsx
- client/src/ui/molecules/collection/menu-v2.tsx
- client/src/ui/molecules/dropdown/index.tsx
- client/src/ui/molecules/notifications-watch-menu/index.scss
- current code in `api.ts` is entirely throwaway and just there to ease development - awaiting the api
- unstyled, that'll come in future PRs - awaiting medium fidelity prototypes
- no logic for toggling between collections v1 and v2 yet, I've just commented the collections v1 components out - awaiting designs for how users will opt-in/toggle/etc.
> MP-15 initial frontend logic for multiple collections

- kumascript/macros/Link.ejs
Depreciate the link macro.
---
---
> Depreciate the link macro

- client/src/ui/organisms/article-actions/index.scss
From this:
Back to this:
But keeping this:
> fix(article-actions): fix mobile button style

- content/document.test.js
- kumascript/tests/environment.test.js
- kumascript/tests/index.test.js
- kumascript/tests/macros/addonsidebar.test.js
- kumascript/tests/render.test.js
- kumascript/tests/templates.test.js
- testing/tests/destructive.test.ts
- testing/tests/index.test.ts
Extracted from #6683.
The idea is to get more helpful error messages if the length does not match.
---
If the checks pass, all should be good.
> test: use toHaveLength check

- client/src/app.scss
> fix: 'sans-sans' should be 'sans-serif'

- client/src/plus/collections/collections-tab.tsx
- client/src/plus/collections/types.ts
- client/src/plus/common/api.tsx
- client/src/plus/notifications/notification-card.tsx
- client/src/plus/notifications/notifications-tab.tsx
- client/src/plus/notifications/utils.ts
- client/src/plus/notifications/watched-items-tab.tsx
- client/src/types/notifications.tsx
- client/src/ui/organisms/article-actions/bookmark-menu/index.tsx
- client/src/ui/organisms/article-actions/bookmark-menu/menu.tsx
- server/static.ts
Follow up of #6895, removes CSRF parts that are no longer relevant for our new rumba backend.
---
Tested except for notifications.
> chore(client): remove CSRF remainders

- client/src/hooks.ts
- client/src/plus/collections/v2/api.ts
- client/src/plus/collections/v2/collection.tsx
- client/src/plus/collections/v2/index.scss
- client/src/plus/collections/v2/index.tsx
- client/src/plus/collections/v2/rust-types.ts
- client/src/plus/index.tsx
- client/src/utils.ts
it looks like this:
https://user-images.githubusercontent.com/755354/186120976-b39fed96-b9c1-4c67-9921-1aa90ea3ec6b.mp4
> MP-16: style collections v2

- client/src/plus/collections/v2/new-edit-collection-modal.tsx
https://mozilla-hub.atlassian.net/browse/MP-96
> MP-96 fix stale data in collection edit modal

- kumascript/macros/SectionOnPage.ejs
I added ja translation to the SectionOnPage macro.
The SectionOnPage macro don't have  Japanese translation.
I added ja translation to the SectionOnPage macro.
> feat(macros): add ja translation to SectionOnPage

- kumascript/macros/JsSidebar.ejs
Follow-up of https://github.com/mdn/content/pull/18303
---
---
> Replace re-introduction to JS with language overview in JS sidebar

- client/src/banners/active-banner.tsx
- client/src/banners/ids.ts
- client/src/banners/index.tsx
- client/src/plus/collections/v2/index.scss
> feature(plus) add preview banner

- kumascript/macros/JsSidebar.ejs
This page is not well linked to. Placing it in the sidebar will increase visibility.
---
---
> chore(macros/JsSidebar): add "Trailing commas" page

- .github/workflows/prod-build.yml
> Enable glean for production env

- client/src/plus/collections/v2/api.ts
- client/src/ui/organisms/article-actions/bookmark-menu/menu-v2.tsx
Allow to add an article to multiple collections.
> MP-116: support adding an item to multiple collections

- client/src/ui/atoms/modal/index.scss
https://mozilla-hub.atlassian.net/browse/MP-86
> MP-86 update modal styling to match designs

- client/src/banners/active-banner.tsx
- client/src/banners/ids.ts
- client/src/banners/index.tsx
- client/src/plus/collections/v2/collection.tsx
- client/src/plus/collections/v2/index.scss
- client/src/plus/collections/v2/index.tsx
- client/src/plus/offer-overview/offer-overview-subscribe/index.tsx
- client/src/telemetry/constants.ts
- client/src/ui/base/_themes.scss
- no more hero border
- banner for multiple collections
- article count links to collection
- updated default collection copy
- updated core plan
> enhance(plus): finishing touches for collectionsV2

- client/src/plus/collections/new-edit-collection-modal.tsx
- client/src/telemetry/constants.ts
- client/src/ui/atoms/modal/index.scss
- client/src/ui/atoms/subscribe-link/index.tsx
- client/src/ui/molecules/auth-container/index.tsx
I'd highly recommend reviewing with "hide whitespace changes" turned on
> MP-122: add collections limit for free users in the frontend

- client/src/plus/collections/collection.tsx
- client/src/plus/collections/index.scss
- client/src/plus/collections/index.tsx
- client/src/utils.ts
> MP-106 Fix collection card spill 

- client/src/ui/atoms/button/index.scss
https://mozilla-hub.atlassian.net/browse/MP-101
no longer disappears on hover
> MP-101: fix(button): disabled styling

- kumascript/macros/FirefoxSidebar.ejs
Issue by https://github.com/mdn/translated-content/issues/4707
---
---
> chore(macros/FirefoxSidebar): add Japanese translation

- .github/workflows/dev-build.yml
- .github/workflows/pr-deployer.yml
- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
The other dependencies are already setup this way to reduce the Dependabot noise
---
---
> ci(deps): pin snok/install-poetry and setup-python to major version

- server/translations.ts
This fixes the localization dashboard on Windows by correctly converting the separator used in the slug into the corresponding filesystem separator.
The localization dashboard (ex. http://localhost:3000/fr/_translations/dashboard?section=/Web/JavaScript ) was not working on Windows and displayed progress bars in an undefined state.
Fix calls to `document.findAll()` to make sure the `folderSearch` was a folder path as expected on the OS filesystem.
N.B. 
Ran it locally on a Windows (and on a Linux) machine (ex. opening http://localhost:3000/fr/_translations/dashboard?section=/Web/CSS after a `yarn dev`)
cc @mdn/localization-team-leads
> fix(server/translations): convert path segment separators on Windows

- .stylelintrc.json
- client/src/banners/banner.scss
- client/src/document/index.scss
- client/src/document/toolbar/flaws.scss
- client/src/plus/offer-overview/offer-hero/index.scss
- client/src/plus/offer-overview/offer-overview-subscribe/index.scss
- client/src/translations/differences/index.scss
- client/src/ui/atoms/logo/index.scss
- client/src/ui/atoms/notification/index.scss
- client/src/ui/molecules/card/index.scss
- client/src/writers-homepage/viewed-documents.scss
Used VSCode colour picker to swap to hex values
---
---
> fix(stylelint): color-named

- .stylelintrc.json
- client/src/ui/molecules/document-survey/index.scss
Disabled during upgrade, but quotes used everywhere else
---
---
> fix(stylelint): function-url-quotes

- .github/workflows/aws-lambda.yml
- .github/workflows/dev-build.yml
- .github/workflows/developing.yml
- .github/workflows/npm-publish.yml
- .github/workflows/npm-published-simulation.yml
- .github/workflows/performance.yml
- .github/workflows/pr-kumascript.yml
- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
- .github/workflows/testing.yml
setup-node now includes built-in caching with the actions/cache so the custom setup shouldn't be required anymore
---
---
> ci: use built-in setup-node caching

- .stylelintrc.json
- client/src/homepage/homepage-hero/index.scss
> fix: stylelint declaration-block-no-duplicate-properties

- .eslintrc.js
- build/cli.ts
- build/spas.ts
- content/utils.ts
- deployer/aws-lambda/content-origin-request/build.js
- deployer/aws-lambda/content-origin-request/index.js
- deployer/aws-lambda/content-origin-response/index.js
- deployer/aws-lambda/tests/server.js
- deployer/aws-lambda/tests/server.test.js
- package.json
- sd-config.js
- server/dev.ts
- yarn.lock
`eslint-plugin-n` is the maintained fork of the old `node` plugin. Turned on `reportUnusedDirectives` so unnessary disable statements are flagged/autofixed
---
---
> fix: replace eslint-plugin-node with n

- .stylelintrc.json
- client/src/plus/offer-overview/offer-overview-subscribe/index.scss
Flatten down the selector to do the same as the bare selector
---
---
> fix: stylelint scss/at-extend-no-missing-placeholder

- .stylelintrc.json
- client/src/document/ingredients/browser-compatibility-table/index.scss
- client/src/document/organisms/sidebar/index.scss
- client/src/flaws/index.scss
- client/src/plus/offer-overview/offer-overview-subscribe/index.scss
- client/src/ui/atoms/icon/index.scss
- client/src/ui/molecules/mandala/index.scss
- client/src/ui/molecules/search/index.scss
- client/src/ui/organisms/article-actions/index.scss
- client/src/ui/organisms/footer/index.scss
- client/src/ui/organisms/top-navigation-main/index.scss
> fix: stylelint no-duplicate-selectors

- build/bcd-urls.ts
- build/document-extractor.ts
- client/src/banners/README.md
- client/src/utils.ts
- deployer/aws-lambda/content-origin-response/index.js
- docs/envvars.md
- docs/npm-packaging.md
- kumascript/src/templates.ts
- testing/translated-content/files/fr/web/embeddable/index.html
Removes a bunch of duplicate words picked up by Vale. No functional changes
---
---
> chore: remove duplicate words

- client/src/plus/collections/index.scss
- client/src/plus/collections/new-edit-collection-modal.tsx
- client/src/ui/atoms/form/expanding-textarea.tsx
- client/src/ui/atoms/form/index.scss
- client/src/ui/atoms/form/limited-input.tsx
- client/src/ui/atoms/modal/index.scss
- client/src/ui/base/_themes.scss
- client/src/utils.ts
- update collections card styling
- clamp displayed lines
- update collection create/edit modal
- change description input to textarea
- add auto-expanding textarea component
- add character limited input/textarea component
> MP-138 Collection card and modal updates

- docs/what-yari-does.md
Moves Yari page from content. See mdn/content#22078.
See mdn/mdn#142
Move the page.
---
---
> Move Yari Page from Content

- .stylelintrc.json
- client/src/plus/collections/index.scss
- client/src/plus/icon-card/index.scss
- client/src/plus/notifications/index.scss
- client/src/ui/molecules/notecards/index.scss
- client/src/ui/molecules/search/index.scss
- client/src/ui/organisms/article-actions/index.scss
Remove unnessessary `&` nesting selector
---
---
> chore: Stylelint scss/selector-no-redundant-nesting-selector

- .stylelintrc.json
- client/src/about/index.scss
- client/src/document/index.scss
- client/src/document/ingredients/browser-compatibility-table/index.scss
- client/src/document/organisms/sidebar/index.scss
- client/src/document/organisms/toc/index.scss
- client/src/document/toolbar/index.scss
- client/src/plus/offer-overview/offer-hero/index.scss
- client/src/ui/molecules/submenu/index.scss
- client/src/ui/organisms/footer/index.scss
Current way may read better, but leaves redundant values that are already covered by the autofixed shorthands
---
---
> chore: Stylelint shorthand-property-no-redundant-values

- client/src/plus/collections/collection.tsx
- client/src/ui/atoms/form/expanding-textarea.tsx
- client/src/ui/organisms/article-actions/bookmark-menu/index.scss
- client/src/ui/organisms/article-actions/bookmark-menu/index.tsx
- client/src/ui/organisms/article-actions/index.scss
- add separate delete and cancel buttons
- update note field to expanding textarea
- also update collection item edit modal note field
- reorder buttons
> MP-141 update bookmark menu to reflect new designs

- client/src/ui/atoms/page-content/index.tsx
- ssr/render.ts
I notices most pages had some HTML checker warnings/errors in common so I fixed it.
There were warnings/errors.
Fix the warnings/errors.
---
---
> Fix the Causes of some Nu HTML Checker Warnings/Errors

- client/src/ui/organisms/footer/index.tsx
Recently the site has removed the old sections of these links without any replacement (as far as I'm aware); temporarily replacing them with direct github links for now until we get a reliable replacement
Recently the site has removed the old sections of these links without any replacement (as far as I'm aware)
This pull request would temporarily replace them with direct github links for now until we get a reliable replacement
> chore(footer): replace outdated "Report issue" links

- client/src/document/organisms/toc/index.tsx
Remove unnecessary id. This fixes #7537
It’s unused.
Delete it.
---
---
> Fix: #7537

- client/src/app.scss
- client/src/document/organisms/metadata/index.tsx
- client/src/plus/collections/collection.scss
- client/src/plus/collections/collection.tsx
- client/src/plus/collections/index.scss
- client/src/plus/collections/index.tsx
- client/src/ui/atoms/button/index.scss
- client/src/ui/atoms/button/index.tsx
- client/src/ui/base/_themes.scss
- client/src/ui/organisms/article-actions-container/index.scss
- client/src/ui/organisms/article-actions-container/index.tsx
- client/src/ui/organisms/article-actions/bookmark-menu/index.tsx
- client/src/ui/organisms/article-actions/index.scss
- client/src/ui/organisms/article-actions/index.tsx
- client/src/ui/organisms/article-actions/notifications-watch-menu/index.tsx
- client/src/utils.ts
Dependent on https://github.com/mdn/yari/pull/7487 (so this won't build, checkout `next` instead).
Just the collections changes from `next`, so this can be code reviewed separately/properly.
> MP-140 Collection + collections redesign

- client/src/community/index.tsx
Fix some links and grammar. Fix: #6619
Some stuff is outdated.
Update it.
---
---
> chore(community): update links + wordings

- client/src/document/ingredients/utils.tsx
Remove useless title attribute. Fix #4567
The title attribute is bad for screen readers.
Delete it.
---
---
> fix(permalink): remove unnecessary title

- kumascript/tests/macros/fixtures/apiref/commonl10n.json
Continues with https://github.com/mdn/yari/pull/7335 for `es`
Improve `es` strings in commonl10n.json
Add strings with a more complete l10n
---
---
> chore(macros/APIRef): update Spanish fixtures

- .eslintrc.js
- build/cli.ts
- server/index.ts
Fixes and ignores some ESLint warnings that appear in every test workflow run.
There are some outstanding ESLint warnings:
Fix the obvious one and ignore the ones that don't have a straight-forward solution.
---
n/a
---
There should be no more warnings in the "Changes" tab of this PR.
> style(eslint): resolve current warnings

- package.json
- tsconfig.json
Fixes: #7560
use transorm instead, see: <https://jestjs.io/docs/code-transformation#defaults>
---
None
---
run `yarn test`.
> test: remove jest `globals` config

- build/index.ts
- client/src/telemetry/glean-context.tsx
- testing/tests/index.test.ts
Start opening external link in a new tab (`target="_blank"`) and add metrics.
> open ext links in _blank and metrics

- .github/workflows/glean-probe-scraper.yml
See https://mozilla.github.io/glean/book/user/adding-glean-to-your-project/enable-data-ingestion.html#validate-and-publish-metrics
---
---
> fix(metrics): add glean probe scraper workflow

- client/src/plus/collections/collection.tsx
- client/src/plus/collections/frequently-viewed.tsx
- client/src/plus/collections/index.tsx
- client/src/plus/index.tsx
Fix a rendering issue.
frequently visited articles scroll to top after editing an item
🤷‍♂️
> fix(rendering): less re-rendering

- kumascript/macros/languages.ejs
Last instance is being removed in https://github.com/mdn/translated-content/pull/10099, but draft till then
---
---
> fix: remove Languages macro

- package.json
- yarn.lock
Doesn't appear to be required anymore. There was a little bit of a diff for the `lodash` one, so I left it
---
---
> chore: remove @types/react resolution

- client/src/document/index.tsx
- client/src/document/organisms/sidebar/index.tsx
- client/src/document/organisms/toc/index.tsx
- client/src/homepage/static-page/index.tsx
Fixes https://github.com/mdn/yari/issues/6852.
- Chore for https://github.com/mdn/yari/issues/6852
- I think I followed the guidelines for making this PR, but if I did anything wrong, then I'll try to correct it right away (as this is my first ever PR to any open source project).
- The problem deals with semantics, rather than functionality. In [this page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside#examples), there is a table of contents component that contains navigation links as children. The parent of such components should be a `nav` by convention, but is currently an `aside` tag instead.
- I followed the suggestion as suggested by caugner: https://github.com/mdn/yari/issues/6852#issuecomment-1219815019
- The suggestion ensures that the nav tag doesn't become …
> fix(nav): use <aside> and un-nested <nav>s for better semantics

- .github/ISSUE_TEMPLATE/bug-report.yml
Beacuse of https://github.com/mdn/yari/discussions/6285
> fix(issue-template): update link to GitHub Discussions

- kumascript/macros/HTTPSidebar.ejs
- kumascript/tests/macros/fixtures/documentData2.json
MDN content has updated `Feature-Policy` to `Permissions-Policy`. This PR updates the `HTTPSidebar` macro to point to the correctly-named docs.
This is part of the work specified at https://github.com/mdn/content/issues/22347.
Updated incorrect links in HTTPSidebar.
Updates link strings and URLs.
---
Confirmed — tested in local yari install, sidebar works fine.
> chore(HTTPSidebar): update Feature-Policy to Permissions-Policy

- build/spas.ts
Update featured articles to those mentioned in https://github.com/mdn/yari/issues/7815
fix #7815
> chore(spas): update featured articles

- client/src/plus/offer-overview/offer-overview-subscribe/index.tsx
- client/src/telemetry/constants.ts
Fixes MP-220. Before the launch of BCD Updates we'd like to see how this affects conversion. 
There was no click telemetry on our CTAs 
Put click telemetry on our CTAs. 
---
---
I enabled debug mode for glean and clicked on the CTAs
> chore(plus/updates): add click event on offer overview clicks (MP-220)

- build/spas.ts
Updates the performance API article on the landing page.
> chore: update performance api featured article

- client/pwa/src/fetch-interceptors.ts
- client/pwa/src/service-worker.ts
We were checking only for `/api/v1` now we look for `/api/`.
Collections and updates are broken when MDN offline is enabled.
> fix(offline): don't intercept api/v? requests

- .github/workflows/stage-build.yml
- client/src/banners/active-banner.tsx
- client/src/banners/ids.ts
- client/src/banners/index.tsx
- client/src/constants.ts
- client/src/env.ts
- client/src/plus/common/api.tsx
- client/src/settings/index.tsx
- client/src/settings/newsletter.tsx
- client/src/telemetry/constants.ts
- client/src/ui/molecules/user-menu/index.scss
- client/src/ui/molecules/user-menu/index.tsx
- client/src/user-context.tsx
Adding support for an MDN Plus newsletter.
> Newsletter

- client/src/app.tsx
- client/src/hooks.ts
- client/src/user-context.tsx
https://mozilla-hub.atlassian.net/browse/MP-233
Companion to https://github.com/mdn/rumba/pull/126.
The `offlineSettings` property on `userData` is very inconsistent - as it gets set in its own `useEffect` it doesn't appear to always be properly set on `userData`. Rather than delay this further trying to fix that, I've just fetched the data from local storage, which I believe should always be correct and up to date.
> MP-233: send daily ping about offline feature status

- client/src/plus/search-filter/index.tsx
- client/src/plus/updates/api.ts
- client/src/plus/updates/index.tsx
We want to deprecate notifications in favour of filtering by collections.
Add new endpoint to backend updates/collections . 
Pull variants from API for filtering. 
---
Multiple collections selected
No collections available. Disabled state.
---
> MP-223 Add filtering on collections.

- client/src/banners/active-banner.tsx
- client/src/settings/newsletter.tsx
- client/src/ui/molecules/user-menu/index.tsx
- client/src/user-context.tsx
change newsletter copy and guard settings
> fix(plus): change newsletter copy and unbreak it

- client/src/hooks.ts
- client/src/plus/search-filter/index.tsx
- client/src/plus/updates/api.ts
- client/src/settings/newsletter.tsx
- client/src/ui/molecules/paginator/index.tsx
- client/tsconfig.json
No strict null/undefined checks in the client (it's bitten us a few times).
Turn it on, fix the small number of errors.
---
`cd client && tsc --noEmit`
> chore(client): turn on typescript strict null checking

- client/src/settings/newsletter.tsx
> fix(plus): update newsletter copy

- .lintstagedrc.json
This PR makes `.ts` files automatically verified by eslint on git commit.
> Use precommit hooks also for `.ts` files

- package.json
Speeds up `yarn check:tsc` by running the tasks in parallel.
The `check:tsc` is script is slow, partly because it runs the tasks (one per directory with a `tsconfig.json` file) sequentially, not parallel.
Run it in parallel, according to the number of processors.
---
```
% yarn check:tsc
yarn run v1.22.19
$ find . -mindepth 2 -name 'tsconfig.json' ! -wholename '**/node_modules/**' -print0 | xargs -n1 -0 bash -c 'cd `dirname $0` && pwd && npx tsc --noEmit || exit 255'
/Users/claas/github/mdn/yari/kumascript
/Users/claas/github/mdn/yari/markdown
/Users/claas/github/mdn/yari/filecheck
/Users/claas/github/mdn/yari/content
/Users/claas/github/mdn/yari/server
/Users/claas/github/mdn/yari/libs/types
/Users/claas/github/mdn/yari/testing
/Users/claas/github/mdn/yari/ssr …
```
> chore(lint): run check:tsc in parallel

- client/src/document/on-github.tsx
Fixes #8026
Spells `GitHub` according to https://github.com/logos
Capitalize the `H`
---
> fix: use proper brand for GitHub

- kumascript/macros/SectionOnPage.ejs
It’s been removed from mdn/content
It’s not needed
Remove it
---
---
> chore(macros): deprecate SectionOnPage

- client/src/site-search/search-results.scss
Removes the horizontal scrollbar in the search results page, which might be shown on mobile devices when some long titles are found.
Fixes #4104 
---
---
> fix(search-results): avoid horizontal scrollbar

- kumascript/macros/APIListAlpha.ejs
- kumascript/macros/APIRef.ejs
- kumascript/macros/CSSRef.ejs
- kumascript/macros/JSRef.ejs
- kumascript/macros/ListGroups.ejs
- kumascript/macros/ListSubpagesForSidebar.ejs
- kumascript/macros/WebExtAPISidebar.ejs
- kumascript/src/api/page.ts
- kumascript/src/environment.ts
- kumascript/src/lib/badges.ts
I have moved Experimental/Deprecated/Obsolete/Non-Standard badges to the right side of the links in the sidebar. I have also extracted the logic of creating those badges to page.ts, so multiple different macros can use it.
- In APIListAlpha & ListGroups, argument `1` was passed to the badge templates. It didn't do anything, so I have removed it
- CSSRef now supports Obsolete & Non-Standard badges, although I don't think they are used anywhere.
Fixes #8051 
---
I have checked every type of sidebar in dev mode.
> chore(sidebars): move status badges to the right side of links

- package.json
Fixed #7965.
https://github.com/mdn/yari/blob/main/package.json#L28
```json
"md": "echo 'The HTML to Markdown conversion command has been moved to https://github.com/mdn/markdown!' && exit 1",
```
URL `https://github.com/mdn/markdown` and exclamation mark `!` in message is not separated.
Sorry for reporting very small issue.
```json
"md": "echo 'The HTML to Markdown conversion command has been moved to https://github.com/mdn/markdown !' && exit 1",
```
URL and `!` was separated.
> chore(scripts): remove "md" script

- client/src/ui/organisms/article-actions/bookmark-menu/index.tsx
Fixes small issues that prevented 'saved' state from being updated on updates article actions bar. 
BEFORE : Removing from all collections would still show as 'saved'
AFTER: Saved state is cleared.
> MP-202 Fix update state on removal

- .github/workflows/stage-build.yml
- deployer/src/deployer/constants.py
- deployer/src/deployer/update_lambda_functions.py
prefix our Lambda@Edge for stage
> enhance(deployer): prefix lambda for stage

- client/src/settings/manage.tsx
Enable should be disable: Boolean(b ^ 1)
> fix: off by one

- .github/workflows/stage-build.yml
Syncing Yari content to GCS using `gsutil`.
> ci: Sync Yari content with GCS

- client/src/document/organisms/toc/index.tsx
- client/src/site-search/index.scss
- client/src/site-search/index.tsx
- client/src/ui/organisms/placement/index.scss
- client/src/ui/organisms/placement/index.tsx
It shouldn't have been tied to the toc in the first place. This also adds a placement on the site search result page.
> chore(placement): move out of toc

- client/src/document/index.scss
> hofix(sidebar): safari had issues with z-index

- client/src/index.tsx
- client/src/placement-context.tsx
- client/src/ui/organisms/placement/index.tsx
Previously the logic for fetching lived within the component. By refactoring this we start to enable more complex queries for future enhancements.
Resolves MP-268.
---
Nothing changes visually.
> refactor(placement): introduce PlacementContext + mutate on pathname change

- .github/workflows/prod-build.yml
Adds parts that were missing in https://github.com/mdn/yari/pull/8630.
(MP-337)
https://github.com/mdn/yari/pull/8630 added additional steps to the prod-build for deployment to GCP, but was missing some required parts to make those steps work.
Add the missing parts.
---
Did not test, but used a diff between `stage-build.yml` and `prod-build.yml` to rule out that there are other parts I have been missing.
> fix(prod-build): add required secrets, environment and permissions

- libs/pong/get.js
Use an allow list to filter keywords.
Garbage ending up in our keyword metrics.
Add an allow list filter.
> fix(libs/pong): add keyword allow list to pong

- client/src/app.scss
- client/src/app.tsx
- client/src/document/index.scss
- client/src/document/index.tsx
- client/src/document/organisms/sidebar/index.tsx
- client/src/placement-context.tsx
- client/src/site-search/index.tsx
- client/src/ui/organisms/placement/index.scss
- client/src/ui/organisms/placement/index.tsx
- libs/pong/get.d.ts
- libs/pong/get.js
Initial support for another placement.
---
---
Deploying to stage.
> feat(placement): add top banner support

- client/src/community/index.tsx
Update OWD info on the community page http://localhost:3000/en-US/community
Community page contains outdated info about OWD.
Update to current info.
Renders fine locally for me.
> Update OWD info on community page

- build/blog.ts
Compare timestamps instead of stings.
> improve(blog): make sorting more resilient

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
> fix(sync): don't deploy to static/static

- client/src/placement-context.tsx
- client/src/ui/organisms/placement/index.scss
- client/src/ui/organisms/placement/index.tsx
Support dark mode to top banner.
> enhance(placement): top banner dark mode

- client/src/ui/organisms/placement/index.scss
Updated design for the top banner
> Top banner xx

- client/src/app.scss
- client/src/document/index.scss
- client/src/ui/organisms/placement/index.scss
We'll monitor our CTR and decide afterwards which way to go.
> experiment(top-banner): make it non-sticky

- build/spas.ts
https://mozilla-hub.atlassian.net/browse/MP-426
- latest news isn't very latest
- add baseline blog post
> chore(homepage): add to and update latest news

- client/src/app.scss
- client/src/plus/offer-overview/offer-overview-subscribe/index.scss
- client/src/plus/offer-overview/offer-overview-subscribe/index.tsx
- client/src/ui/molecules/main-menu/index.tsx
- client/src/ui/organisms/top-navigation-main/index.scss
https://mozilla-hub.atlassian.net/browse/MP-397
- we don't promote the blog enough
- add "new" tag to blog link in menu
- design was a collaborative effort on slack with Hermina
- also update plus offer page new tag to match
---
---
Tested across Firefox/Chrome/Epiphany on Linux (Wayland - not sure if that makes a different for font rendering).
> chore(blog): add new tag next to blog link in menu

- kumascript/index.ts
- kumascript/src/templates.ts
Reverts mdn/yari#8936
Breaking or build. Reverting for now.
> Revert "fix(kumascript): mention path in render error message"

- client/src/homepage/index.scss
- client/src/homepage/index.tsx
- client/src/placement-context.tsx
- client/src/ui/organisms/placement/index.scss
- client/src/ui/organisms/placement/index.tsx
- libs/pong/get.js
Support HP Takeover Placements.
> feat(placement): hp takeover

- .stylelintrc.json
- client/src/document/organisms/sidebar/index.scss
- client/src/document/organisms/toc/index.scss
- client/src/document/toolbar/index.scss
- client/src/plus/icon-card/index.scss
- client/src/plus/updates/index.scss
- client/src/ui/atoms/avatar/index.scss
- client/src/ui/atoms/toast/index.scss
- client/src/ui/molecules/dropdown/index.scss
- client/src/ui/molecules/pagination/index.scss
- client/src/ui/organisms/article-actions/index.scss
- client/src/ui/organisms/footer/index.scss
> Revert "style(sass): disallow concatenated selectors"

- client/src/assets/icons/feed.svg
- client/src/ui/atoms/icon/index.scss
- client/src/ui/organisms/footer/index.tsx
https://mozilla-hub.atlassian.net/browse/MP-468
- there is no clickable link to our feed (just the `<link>` in the header)
- add a clickable link to our feed in the site footer
---
---
- `yarn dev`
- `yarn build:blog`
- visited localhost:5042
- scrolled to footer
- clicked the link
> feat(blog): add feed icon to footer

- .github/workflows/prod-build.yml
> fix(prod): set ORIGIN_PLAY for cloud function

- client/src/app.scss
- client/src/ui/molecules/main-menu/index.tsx
- client/src/ui/organisms/top-navigation-main/index.scss
Per Hermina's request.
Difficult to distinguish between new and beta tags.
Give them different, fixed, colours.
---
---
Received approval from Hermina on slack.
> chore(ai-help): distinguish beta tag from new tag

- client/src/playground/console.tsx
Autoscroll the consoles in Playground.
> fix(playground): console scroll to bottom

- client/src/document/hooks.ts
Make code detection more like the legacy version.
We were only looking for code samples withing the preceding `hX` for an iframe within and `hX`. 
Now we directly look into the `h(X-1)`. 
---
---
locally for http://localhost:3000/ja/docs/Web/API/Canvas_API/Tutorial/Basic_animations
> enhance(livesamples): improve live samples w/o id

- build/spas.ts
Hermina approved.
New tag is less than 7 days old, so should disappear tomorrow for the playground post.
> chore(homepage): add ai help and playground posts to latest news

- .github/workflows/prod-build.yml
- .github/workflows/stage-build.yml
- build/syntax-highlight.ts
- client/src/blog/post.tsx
- client/src/document/code/ai-explain.ts
- client/src/document/code/copy.ts
- client/src/document/code/playground.ts
- client/src/document/code/render-md.ts
- client/src/document/hooks.ts
- client/src/document/index.scss
- client/src/document/index.tsx
- client/src/telemetry/constants.ts
- client/src/telemetry/glean-context.tsx
- libs/env/index.d.ts
- libs/env/index.js
- package.json
- yarn.lock
Allows users to get an explanation of code / parts of code.
---
> feat(ai-explain): add ai-explain to code blocks

- kumascript/macros/PWASidebar.ejs
This PR updates the PWA sidebar with new content that's been written as part of https://github.com/mdn/mdn/issues/280.
Add missing pages (and remove one page that was deleted).
It adds the missing pages!
---
---
Ran yarn dev
> Update PWA sidebar

- README.md
As discussed a few weeks back, when reviewing open PRs.
> chore(readme): add section about supported platforms

- client/src/ui/organisms/footer/index.tsx
Changing the link as per the internal discussion.
/cc @LeoMcA @Rumyra
> chore(footer): update Discord invite link in the footer

- cloud-function/src/headers.ts
Fixes #9239.
The X-XSS-Protection response header is no longer recommended for use in production websites but is in use by yari.
Removing the header removes non-standard code.
> fix(cloud-function): remove X-XSS-Protection header

- package.json
- yarn.lock
The `html-react-parser` was used for Notifications (MDN Plus), a feature that has since been removed in d83e7760570f5a5aee2520c996d8386638328ad7. So we no longer need this dependency.
Remove the dependency.
---
Compared local builds of `main` against this branch, and only found the usual suspects to differ:
```
% diff -q -r build-v3 build                                                                                             ✭
Files build-v3/allBrowserCompat.txt and build/allBrowserCompat.txt differ
Files build-v3/en-us/docs/mdn/at_ten/index.html and build/en-us/docs/mdn/at_ten/index.html differ
Files build-v3/en-us/docs/mdn/at_ten/index.json and build/en-us/docs/mdn/at_ten/index.json differ
Files build-v3/en-us/docs/mdn/at_ten/metadata.json and …
```
> chore(deps): remove html-react-parser

- .github/workflows/npm-publish.yml
Replicates the changes from https://github.com/mdn/rumba/pull/282 to yari.
We use `enhance:` and `chore:` prefixes for commits, but these don't trigger release-please PRs and don't appear in the changelog.
Configure release-please to include these commit prefixes.
---
We'll see! 🤞
> enhance(release-please): include chore/enhance commits

- client/src/playground/index.tsx
Fix a bug where the cursor jumps around in the playground.
When coming to playground in a fresh session the fist time the code is run the cursor jumped back to the start.
Clean up the state. This still needs some more cleanup but it resolves the bug for now.
> fix(play): fix cursor jump on first edit

- client/src/plus/ai-help/index.tsx
Mark the feedback link as external.
---
> chore(ai-help): make feedback link external

- client/src/ui/molecules/main-menu/index.tsx
As requested by Hermina on slack
- Playground isn't new any more
- Remove the new tag
---
---
`yarn dev`, localhost:3000
> chore(menu): remove playground new tag

- client/src/hooks.ts
- client/src/ui/organisms/placement/index.tsx
See: https://github.com/mdn/yari/pull/9631#discussion_r1321700849
> Fix placement ping: add intersection observer hook, simplify logic

- client/src/document/index.test.tsx
- client/src/document/index.tsx
- client/src/hooks.ts
- client/src/placement-context.tsx
- client/src/ui/organisms/placement/index.scss
- client/src/ui/organisms/placement/index.tsx
Unify `sendViewed` and empty placement.
We did not cancel our timer properly.
Use an unified `sendViewed` function.
---
Locally
> fix(placement): fix firing multiple impressions

- kumascript/macros/WebExtExamples.ejs
> fix(macros/WebExtExamples): update branch name

- package.json
- yarn.lock
Pin the `web-features` package so an npm release doesn't trigger an update (and with it a whole load of new Baseline statuses in a different form). We'll bump this manually when we're ready to release.
---
Trivial change, no testing done.
> chore(web-features): pin package version
